// Career simulator: whole careers from a 14-year-old freshman to retirement, played with Sim and sensible choices
// (headless, in the page). Usage: node tests/careersim.js [careers=40] [seed=1] [engineGames=0] [--each] [--json]
// [--set career.proMean=80 ...] (--set overrides a CONFIG value for a tuning run) [--trait=<id>|none] (R3: every career's
// signature trait is <id> and it has no hidden one; the trait balance test runs this for each trait; V3: none = no traits at all, its baseline) [--press=team|confident|
// trash|nocomment] (R8: every press answer) [--hype=chase|quiet] (R8: trash talk after a win and Confident after a loss, or
// No comment after a win and Team first after a loss) [--fa=stars|money|yours|best|starter] [--trade=up|never] (F7: free agency
// takes the most stars, the most money or one kind of offer ("big" is the old name for best); trade requests go a star up, or
// never) [--spend=smart|none] (R7; V10: smart hires the best agent who isn't shady, then skills coach, mental coach,
// nutritionist, physio and strength trainer, each the best tier inside --staffBudget=0.5 of the salary; none hires nobody)
// [--staff=only:<role>] (V10: that role alone) [--gear=buy|none] (F8: buy gear once the money covers it twice over, four times in the pros)
// Reports medians at ages 17/21/25, peak OVR, the franchises reached, titles, the Hall of Fame rate and any stuck states
// against the spec's targets.
const { launch, openPage } = require('./lib');
(async () => {
  const argv = process.argv.slice(2), sets = []; for (let i = 0; i < argv.length; i++) if (argv[i] === '--set') { sets.push(argv[i + 1]); argv.splice(i, 2); i--; }
  const args = argv.filter(a => !a.startsWith('--')); const N = +(args[0] || 40), seed0 = +(args[1] || 1), engineGames = +(args[2] || 0); const forceTrait = ((argv.find(a => a.startsWith('--trait=')) || '').split('=')[1]) || null; const forceSummer = ((argv.find(a => a.startsWith('--summer=')) || '').split('=')[1]) || null; // R5: --summer=aau|camp|rest|job (every summer); default: a job, a camp, then AAU
  const pressPolicy = ((argv.find(a => a.startsWith('--press=')) || '').split('=')[1]) || null, hypePolicy = ((argv.find(a => a.startsWith('--hype=')) || '').split('=')[1]) || null, pressAm = ((argv.find(a => a.startsWith('--pressAm=')) || '').split('=')[1]) || null; // R8 (--pressAm=: the amateur years' answer, for diagnostics)
  const faPolicy = ((argv.find(a => a.startsWith('--fa=')) || '').split('=')[1]) || 'stars', tradePolicy = ((argv.find(a => a.startsWith('--trade=')) || '').split('=')[1]) || 'up', spend = ((argv.find(a => a.startsWith('--spend=')) || '').split('=')[1]) || 'smart', gearPolicy = ((argv.find(a => a.startsWith('--gear=')) || '').split('=')[1]) || 'buy'; /* F8: --gear=buy|none */ // R7/F7: --fa=stars|money|best|starter|yours (free agency; stars: the best franchise, the goal) · --trade=up|none (F7: ask for a trade when a better franchise would take you) · --spend=smart|none (the trainer, coach, nutrition, the shoe line, lifestyle)
  const storyPolicy = ((argv.find(a => a.startsWith('--story=')) || '').split('=')[1]) || 'default', schoolPolicy = ((argv.find(a => a.startsWith('--school=')) || '').split('=')[1]) || 'auto', staffOnly = (((argv.find(a => a.startsWith('--staff=only:')) || '').split(':')[1]) || null), staffBudget = +(((argv.find(a => a.startsWith('--staffBudget=')) || '').split('=')[1]) || 0.5); // V9: --school=student crams every exam and studies under 3.6 (the default: AUTO's Study weeks under 2.3, Balanced exams) // V8: --story=random answers every story card at random (seeded), to reach every ending; the default takes each card's default
  const seasonsOut = argv.includes('--seasons'), policy = ((argv.find(a => a.startsWith('--policy=')) || '').split('=')[1]) || 'typical', edge = +(((argv.find(a => a.startsWith('--edge=')) || '').split('=')[1]) || 2.5); // V6 (Part 2 §1.1): typical (sensible choices, mostly simmed) or great (plays every game well: simmed games count as played, with an OVR edge)
  const browser = await launch(); const P = await openPage(browser); const page = P.page; const errors = P.errors;
  if (sets.length) console.log('overrides: ' + (await page.evaluate(sets => sets.map(kv => { const [path, v] = kv.split('='); const keys = path.split('.'); let o = CONFIG; for (const k of keys.slice(0, -1)) o = o[k]; o[keys[keys.length - 1]] = JSON.parse(v); return path + ' = ' + v; }).join(', '), sets)));
  const out = await page.evaluate(({ N, seed0, engineGames, forceTrait, forceSummer, faPolicy, tradePolicy, spend, pressPolicy, hypePolicy, pressAm, gearPolicy, policy, edge, seasonsOut, storyPolicy, schoolPolicy, staffOnly, staffBudget }) => { const great = policy === 'great', student = schoolPolicy === 'student'; const storyPick = (c, e) => { if (student && e.exam && e.choice) return stChoose(c, e, 0); /* V9: Cram */ if (storyPolicy !== 'random' || !e.choice || !e.choice.length) return stAutoChoose(c, e); return stChoose(c, e, (hashString(String(c.seed || 1) + ':' + e.id + ':' + c.season) >>> 0) % e.choice.length); };
    const styles = Object.keys(AM_STYLES); const results = [];
    // V11 (Part 2 §5): smart spending in the shop: a stock item for an empty slot or a better one (a rarer item) while the
    // money covers it keep times over, then the cheapest next level of what you wear; an ice bath when tired, and a drink
    // and a film session for the playoffs and the rival.
    const gearAuto = (c, rec, keep, big) => { if (gearPolicy === 'none') return; const B = holderOf(c), G = gearOf(B), S = gearStock(c), rank = it => GEAR_RARITY.indexOf(it.rarity);
      for (const id of S.ids) { const it = gearItem(id); if (G.owned[id] || S.sold[id]) continue; const slots = it.slot === 'train' ? ['train1', 'train2'] : [it.slot], free = slots.find(s => !G.eq[s]), worst = slots.map(s => G.eq[s]).filter(Boolean).map(gearItem).sort((a, b) => rank(a) - rank(b))[0];
        if (!free && !(worst && rank(it) > rank(worst))) continue; const p = gearStockPrice(c, id); if (gearWallet(c) < p * keep) continue; if (!gearBuy(c, id)) continue; if (!free) gearEquip(B, id, slots.find(s => G.eq[s] === worst.id)); rec.gear.spent += p; rec.gear.buys++; }
      for (let k = 0; k < 8; k++) { let best = null; for (const [it] of gearWorn(B)) { const p = gearNextPrice(c, it.id); if (p != null && (!best || p < best.p)) best = { id: it.id, p }; } if (!best || gearWallet(c) < best.p * keep) break; if (!gearUpgrade(c, best.id)) break; rec.gear.spent += best.p; rec.gear.ups++; }
      const cp = gearConsumePrice(c); if (gearWallet(c) >= cp * keep * 4) { const f = B.fatigue || 0; for (const k of (f >= 25 ? ['ice'] : []).concat(big ? ['drink', 'film'] : [])) if (gearConsume(c, k)) { rec.gear.uses++; rec.gear.spent += cp; } }
    };
    const gearLevels = c => gearWorn(holderOf(c)).reduce((n, [it, lv]) => n + lv, 0);
    const answer = (c, e, rec) => { const won = !!(e.x && e.x.won); const k = (pressAm && !isPro(c) ? pressAm : null) || pressPolicy || (hypePolicy === 'chase' ? (won ? 'trash' : 'confident') : hypePolicy === 'quiet' ? (won ? 'nocomment' : 'team') : null); const r = pressAuto(c, e, k); rec.press++; const st = isPro(c) ? 'pro' : c.stage; rec.pressBy[st] = (rec.pressBy[st] || 0) + 1; if (r.fine != null) rec.fines++; }; // R8: the press policy (and where the questions come)
    const fakeBox = (c, g) => { const rng = careerRng(c); const E = great ? edge : 0, me0 = c.players[c.meId], r0 = me0.r; if (E) me0.r = Object.fromEntries(Object.entries(r0).map(([k, v]) => [k, Math.min(CR.ratingMax, v + E)])); let r; try { r = simBox(c, g.h, g.a, rng); } finally { me0.r = r0; } /* V6: the great policy plays with an edge */ const toP = id => { const s = r.box[id]; return Object.assign({ name: c.players[id].name }, makeStats(), { pts: s.pts, fgm: s.fgm, fga: s.fga, tpm: s.tpm, tpa: s.tpa, reb: s.reb, stl: s.stl, blk: s.blk, to: s.to, dunkM: s.dunk, dunkA: s.dunk, layM: Math.max(0, Math.round((s.fgm - s.tpm - s.dunk) * 0.5)), layA: Math.max(0, Math.round((s.fga - s.tpa - s.dunk) * 0.5)), ankles: s.ank, moves: 20 }); }; const meH = g.h === c.meId; const opp = meH ? g.a : g.h; return { teams: [{ score: meH ? r.hs : r.as, players: [toP(c.meId)] }, { score: meH ? r.as : r.hs, players: [toP(opp)] }], overtime: r.ot }; };
    for (let n = 0; n < N; n++) {
      const save = defaultSave(); const style = styles[n % styles.length]; const inv = []; const ages = {}; let guard = 0, engineUsed = 0;
      const a = amCreate(save, { name: 'Sim Player', look: PRESET_LOOKS[n % 16], number: 7, style, seed: (seed0 * 7919 + n * 104729) >>> 0, seasonLength: 11, gameLength: 120, traits: forceTrait && forceTrait !== 'none' ? [forceTrait] : null }); if (forceTrait === 'none') { a.tr = null; a.caps = capsFrom(a.genes, a, a.r); } // V3: --trait=none: a career without traits (the trait balance test's baseline)
      if (great) a.simEdge = edge; // V6: the great policy
      const rec = { style, heightFinal: a.heightFinal, bloom: a.bloom, ovr: {}, pick: null, draftAge: null, college: null, tier: null, proSeasons: 0, titles: 0, mvps: 0, legacy: 0, hof: false, peak: 0, peakAge: 0, retireAge: null, amTitles: 0, h14: a.height, stuck: false, injuries: 0, plans: {}, fat: [], press: 0, beats: {}, choices: 0, pressBy: {}, grudgeBy: {}, fines: 0, hypeSum: 0, hypeN: 0, hype60: 0, hype70: 0, benchAm: 0, benchPro: 0, benchBy: {}, challenges: 0, trustDraft: 0, hs: { jv: 0, fresh: 0, callups: 0, districts: 0, state: 0, study: 0, inel: 0, gpaMin: 4, stars: 0, nat: 0, top: -1, summers: {} }, col: { seasons: 0, nat: 0, natW: 0, ff: 0, champ: 0, confT: 0, missed: 0, nilOffers: 0, nilDeals: 0, nil: 0, portal: 0, transfer: 0, agent: false, mock: [], study: 0, inel: 0 } }; rec.gear = { spent: 0, buys: 0, ups: 0, uses: 0, atPro: 0, end: 0 }; rec.cash = { hsEnd: null, colEnd: null, at25: null, at30: null, retire: null, left: null, earned: 0, upkeep: 0, life: 0 }; // F8
      const note = (age, ovr) => { if (ages[age] == null) ages[age] = ovr; if (ovr > rec.peak) { rec.peak = ovr; rec.peakAge = age; } };
      // amateur years
      while (!a.handedOff && guard++ < 400) {
        for (const e of a.events) { if (e.kind === 'traitpick') { trPickAuto(a); rec.third = (a.tr && a.tr.third) || null; continue; } /* V3: the third trait (the rarest offer) */ if (e.kind === 'dialog' || e.kind === 'rival') { const k = 'a' + a.stage + a.season; rec.beats[k] = (rec.beats[k] || 0) + 1; if (e.kind === 'dialog') { storyPick(a, e); if (e.choice) rec.choices++; } } if (e.kind === 'press') answer(a, e, rec); else if (e.kind === 'nil') { rec.col.nilOffers++; colNilAnswer(a, e, (e.apps || 0) <= 1); if (e.accepted) rec.col.nilDeals++; } else if (e.kind === 'agent') { colAgentAnswer(a, e, true); rec.col.agent = !!a.agent; } } a.events.length = 0; note(a.age, amOvr(a)); // R6: NIL deals with at most one appearance; always an agent
        if (a.stage === 'combine') { { const Sg = a.saga || {}, pr = (Sg.arcs || {}).probation; rec.sch = { sch: a.scholarship || 'none', tuition: a.tuitionPaid || 0, loan: a.loan || 0, academic: !!(a.program && a.program.academic), major: (a.degree && a.degree.major) || null, years: (a.degree && a.degree.years) || 0, gpa: a.gpa, probation: !!(pr && pr.st !== 'skip'), col: !!a.college, commitAcademic: !!rec.commitAcademic }; } /* V9 */ rec.col.nil = a.nilEarned || 0; rec.trustDraft = trustOf(a); rec.hype = a.hype || 0; rec.dscore = +amDraftScore(a).toFixed(1); rec.draftAge = a.age; rec.college = a.college || '(none)'; rec.tier = a.collegeTier; rec.amTitles = a.titles; try { rec.offer = Math.max(...proEntryOffers(a).offers.map(o => o.stars || 1)); } catch (e) { rec.offer = null; } /* V6: the best first pro offer */ createCareerFromAmateur(save, a); if (great && save.career) save.career.me.simEdge = edge; if (forceTrait === 'none' && save.career) { save.career.me.tr = null; const me0 = meOf(save.career); me0.caps = capsFrom(save.career.me.genes, save.career.me, me0.r); } break; }
        if (a.decision) { const d = a.decision; if (d.kind === 'portal') { rec.col.portal++; const o = d.offers.find(x => x.tier < (a.collegeTier || 0)) || null; if (o) rec.col.transfer++; colPortalChoose(a, o); continue; } /* R6: the portal: a step down that starts you, else stay */ if (d.kind === 'college') { const skip = d.offers.find(o => o.draft); const proj = amPickFrom(amDraftScore(a)); const byTier = d.offers.filter(o => !o.draft).sort((x, y) => (y.tier - x.tier) || ((y.academic ? 1 : 0) - (x.academic ? 1 : 0))); /* V9: an elite academic program over its tier's others */ const play = great ? byTier.filter(o => o.tier <= 2)[0] : null; /* V6: the great policy goes where it plays (a power program over a blue blood's bench) */ const pick = skip && proj <= 10 ? skip : play || byTier[0] || d.offers[0]; rec.commitAcademic = !!pick.academic; amChooseCollege(a, pick); } else amDeclare(a, amPickFrom(amDraftScore(a)) <= 30 || a.stageYear >= 3); continue; }
        if (a.summer && a.summer.pending) { const k = forceSummer || ['job', 'camp', 'aau'][(a.summer.year || 1) - 1] || 'rest'; const got = hsSummerChoose(a, k); if (got) rec.hs.summers[got.kind] = (rec.hs.summers[got.kind] || 0) + 1; continue; } // R5: the summer
        if (a.tryout && a.tryout.step !== 'done') { const y = a.stageYear; hsSimTryout(a); if (y === 1 && a.squad === 'varsity') rec.hs.fresh++; if (a.squad === 'varsity' && rec.varsityYear == null) rec.varsityYear = y; continue; } // R5: tryouts (simmed); V6: the year you made varsity
        if (a.stage === 'hs') { rec.hs.gpaMin = Math.min(rec.hs.gpaMin, a.gpa); if (a.squad === 'varsity' && rec.varsityYear == null) rec.varsityYear = a.stageYear; } // V6: the year you first played varsity (a tryout, a call-up or a junior's place)
        { const g0 = amNext(a); gearAuto(a, rec, 2, !!(g0 && (g0.playoff || (g0.opp && g0.opp.id === a.rivalId)))); } /* F8; V11 */ if (a.stage !== rec.cash.stage0) { if (rec.cash.stage0 === 'hs') rec.cash.hsEnd = a.cash || 0; rec.cash.stage0 = a.stage; } /* V11: cash by stage */ { const g = amNext(a); if (g && g.opp && !(a.wk && a.wk.done)) { ladderSettlePending(a); if (a.fatigue >= 40 || a.injury) amRest(a); else if ((a.stage === 'hs' || a.stage === 'college') && a.gpa < (student ? 3.6 : HS.autoStudyAt)) { wkStudy(a); if (a.stage === 'hs') rec.hs.study++; else rec.col.study++; } /* V9: AUTO's Study weeks, both levels */ else if (!isStarter(a) && ladderChallengeId(a)) { ladderSimChallenge(a, ladderChallengeId(a), 'you'); amPractice(a, a.focus, 'normal', amSessionXp(a, 'normal')); rec.challenges++; } else if (g.opp.rival || g.playoff || hasTrait(a, 'filmjunkie')) amFilm(a); /* V3: a Film Junkie films every week (it pays XP too) */ else amPractice(a, a.focus, 'normal', amSessionXp(a, 'normal')); } } // the week: rest when tired, a depth-chart challenge when benched (R4), film for big games, else practice
        const wasHs = a.stage === 'hs', sq = a.squad, colL = a.stage === 'college' ? a.league : null; { const g = amNext(a); if (g && g.opp && a.grudge && a.grudge[g.opp.id] && isStarter(a)) rec.grudgeBy[a.stage + (g.playoff ? '-po' : '')] = (rec.grudgeBy[a.stage + (g.playoff ? '-po' : '')] || 0) + 1; } const stg0 = a.stage, yr0 = a.stageYear, top0 = !!a.team && isStarter(a); const r = amSimGame(a); if (!r) { inv.push('amateur: no game and no decision, stage ' + a.stage + ' year ' + a.stageYear); break; } if (stg0 === 'college' && top0 && !r.bench && rec.colStart == null) rec.colStart = yr0; /* V6: the college year you first held the starting spot (not a spot start) */ if (forceTrait && forceTrait !== 'none' && traitsOf(a)) { const Lv = trLvOf(a, forceTrait); if (Lv >= 2 && rec.ageS == null) rec.ageS = a.age; if (Lv >= 3 && rec.ageG == null) rec.ageG = a.age; } /* V3: when the trait levelled up */ if (r.bench) rec.benchAm++; if (r.ineligible) { if (stg0 === 'college') rec.col.inel++; else rec.hs.inel++; } /* V9: by level */; if (r.note === 'Called up to varsity!') rec.hs.callups++;
        if (wasHs && a.decision && a.decision.kind === 'college' && !rec.hs.nat) { rec.hs.stars = a.recruit ? a.recruit.stars : 0; rec.hs.nat = a.recruit ? a.recruit.nat : 0; rec.hs.top = Math.max(...a.decision.offers.filter(o => !o.draft).map(o => o.tier)); rec.hs.districts = a.districts || 0; rec.hs.state = a.titles; rec.hs.jv = a.log.filter(e => e.squad === 'jv').length; }
        if (colL && colL.done && colL.format === 'conf' && !colL.counted) { colL.counted = true; const C = rec.col; C.seasons++; if (colL.inField) { C.nat++; C.natW += colL.games.filter(x => x.po >= 31 && x.won).length; } if (colL.finalFour) C.ff++; if (colL.missed) C.missed++; if (colL.confTourney) C.confT++; if (colL.playoffs && colL.playoffs.champion === 'me' && colL.inField) C.champ++; C.mock.push(amPickFrom(amDraftScore(a))); (C.log || (C.log = [])).push([a.collegeTier, colL.benchWeeks || 0, colL.all.w + colL.all.l, colL.inField ? 1 : 0, colL.natRank || 0, colL.all.w, colL.confTourney ? 1 : 0]); } // R6
        if (!(a.fatigue >= 0 && a.fatigue <= 100)) inv.push('amateur fatigue out of range ' + a.fatigue); if (r && r.wk) { if (r.wk.injury) rec.injuries++; rec.plans[r.wk.plan] = (rec.plans[r.wk.plan] || 0) + 1; }
      }
      const c = save.career; if (!c) { rec.stuck = true; rec.inv = inv.concat(['never reached the pros']); results.push(rec); continue; }
      rec.pro = { fa: {}, trades: 0, shoe: 0, trainerWeeks: 0, spent: 0, life: 0, worth: 0, foundation: 0, academy: false, stake: false };
      const moneyPolicy = () => { const S = staffOf(c); if (spend === 'none') { for (const r of STAFF_ROLES) S[r] = null; return; } const M = c.me, sal = (M.contract && M.contract.salary) || 0, cash = M.money, want = r => !staffOnly || staffOnly === r; if (staffOnly) for (const r of STAFF_ROLES) if (r !== staffOnly) S[r] = null; /* V10: the six roles; --staff=only:<role> hires that one alone (not even the agent from college) */
        if (want('agent')) { const pool = staffPool(c, 'agent'); let bi = -1; pool.forEach((a, i) => { if (a.pers !== 'shady' && a.tier > (S.agent ? S.agent.tier : 0) && (bi < 0 || a.tier > pool[bi].tier)) bi = i; }); if (bi >= 0) staffHire(c, 'agent', bi); } /* the agent pays for itself: the best one that isn't shady */
        const order = ['skills', 'mental', 'nutrition', 'physio', 'strength'].filter(want), budget = sal * staffBudget; let spent = 0; for (const r of order) if (S[r]) spent += S[r].salary; /* a budget: a share of the salary, roles in this order */
        for (const r of order) { const pool = staffPool(c, r), cur = S[r]; let bi = -1; pool.forEach((p, i) => { const extra = p.salary - (cur ? cur.salary : 0); if (p.tier > (cur ? cur.tier : 0) && spent + extra <= budget && M.money >= p.salary && (bi < 0 || p.tier > pool[bi].tier)) bi = i; }); if (bi >= 0) { spent += pool[bi].salary - (cur ? cur.salary : 0); staffHire(c, r, bi); } }
        if (proShoeOpen(c) && cash >= PR.shoeCost * 2 && proShoeLaunch(c)) rec.pro.shoe = 1; for (const [id, need] of [['car', 1e6], ['sportscar', 5e6], ['house', 1e7], ['mansion', 3e7]]) if (!(M.lifestyle || {})[id] && cash >= need && proBuy(c, id)) rec.pro.life++; }; /* V11: lifestyle pays every week (hype, confidence, fame) and costs upkeep: the sports car at $5M in the bank, the mansion at $30M (R7: $80M) */
      moneyPolicy();
      const me = meOf(c); rec.cash.colEnd = c.me.money || 0; /* V11: cash at the pro start */ rec.pick = me.draftPick; rec.fr = { first: frMine(c), best: frMine(c), age: {}, tradesUp: 0, seasons: [] }; rec.gear.atPro = gearLevels(c); for (let s2 = 1; s2 <= frMine(c); s2++) rec.fr.age[s2] = me.age; note(me.age, recOvr(me)); // F7
      while (c.phase !== 'retired' && guard++ < 4000) {
        if (c.phase === 'regular' || c.phase === 'playoffs') {
          const g = userGame(c); if (!g) { inv.push('no user game in phase ' + c.phase + ' week ' + c.week); break; }
          if (c.phase === 'regular' && c.week === 0 && !rec.fr.seasons[c.season]) { rec.fr.seasons[c.season] = frMine(c); if (tradePolicy === 'up' && proTradeOpen(c) && frCap(frValue(c)) > frMine(c)) { c.me.tradeSeason = c.season; proTrade(c); rec.fr.tradesUp++; } const s1 = frMine(c); if (s1 >= 5 && rec.fr.best < 5) rec.fr.via5 = rec.fr.lastClub === meOf(c).club ? 'rise' : 'move'; rec.fr.lastClub = meOf(c).club; rec.fr.best = Math.max(rec.fr.best, s1); if (seasonsOut) { const Sx = id => strengthOf(c.players[id], c) + LG.starEdge * simEdgeStars(c, id), arr = c.active.filter(id => c.players[id]).map(id => [id, Sx(id)]).sort((a, b) => b[1] - a[1]); (rec.sx || (rec.sx = {}))[c.season] = { sr: arr.findIndex(x => x[0] === c.meId) + 1, gap: +(Sx(c.meId) - arr.find(x => x[0] !== c.meId)[1]).toFixed(2), top: arr.map(x => +x[1].toFixed(1)) }; } /* V12: --seasons: your team's strength rank at the season's start */ for (let s2 = 1; s2 <= s1; s2++) if (rec.fr.age[s2] == null) rec.fr.age[s2] = meOf(c).age; { const cnt = {}; for (const id of c.active) cnt[c.players[id].club] = (cnt[c.players[id].club] || 0) + 1; if (Object.keys(cnt).length !== TEAMS.length || Object.values(cnt).some(v => v !== 1)) inv.push('franchises ' + JSON.stringify(cnt)); } } // F7: move up; one league player per franchise
          gearAuto(c, rec, 4, !!(g.playoff || opponentOf(c, g) === c.rivalId)); /* F8; V11 */ if (!(c.me.wk && c.me.wk.done)) { ladderSettlePending(c); if (c.me.fatigue >= 40 || c.me.injury) proRest(c); else if (!isStarter(c) && ladderChallengeId(c)) { ladderSimChallenge(c, ladderChallengeId(c), 'you'); proPractice(c, c.me.focus, 'normal', proSessionXp(c, c.me.focus, 'normal')); rec.challenges++; } else if (opponentOf(c, g) === c.rivalId || g.playoff || hasTrait(c.me, 'filmjunkie')) proFilm(c); else proPractice(c, c.me.focus, 'normal', proSessionXp(c, c.me.focus, 'normal')); } // the week: rest when tired, a depth-chart challenge when benched (R4), film for big games, else practice
          rec.plans[c.me.wk.done] = (rec.plans[c.me.wk.done] || 0) + 1; rec.fat.push(c.me.fatigue);
          if (c.allStar && c.allStar.invited && !c.allStar.done) finishAllStar(c, 12);
          { const o = opponentOf(c, g); if (playsThisWeek(c) && c.me.grudge && c.me.grudge[o]) rec.grudgeBy[g.playoff ? 'pro-po' : 'pro'] = (rec.grudgeBy[g.playoff ? 'pro-po' : 'pro'] || 0) + 1; } proStartGame(c); const res = !playsThisWeek(c) /* V5: a spot start plays */ ? (rec.benchPro++, (rec.benchBy[c.season] = (rec.benchBy[c.season] || 0) + 1), proSimBenchGame(c)) : engineUsed < engineGames ? (engineUsed++, simUserGame(save)) : careerAfterGame(save, fakeBox(c, g), 0, !great); /* V6: the great policy's games count as played */
          if (forceTrait && forceTrait !== 'none' && traitsOf(c.me)) { const Lv = trLvOf(c.me, forceTrait); if (Lv >= 2 && rec.ageS == null) rec.ageS = meOf(c).age; if (Lv >= 3 && rec.ageG == null) rec.ageG = meOf(c).age; } /* V3 */
          if (!res) { inv.push('careerAfterGame returned null'); break; } if (res.wk && res.wk.injury) rec.injuries++; { const h = c.me.hype || 0; rec.hypeSum += h; rec.hypeN++; if (h >= MD.keyedAt) rec.hype60++; if (h >= MD.distractAt) rec.hype70++; } for (const e of (c.events || []).slice()) { if (e.kind === 'traitpick') { trPickAuto(c.me); rec.third = (c.me.tr && c.me.tr.third) || null; continue; } if (e.kind === 'dialog' || e.kind === 'rival') { const k = 'p' + c.season; rec.beats[k] = (rec.beats[k] || 0) + 1; if (e.kind === 'dialog') { if (e.saga && e.saga.arc === 'trade' && e.saga.beat === 0) { const yes = proUnhappy(c) === 'bench'; stChoose(c, e, yes ? 1 : 2); if (yes) rec.pro.trades++; } /* V8: the saga's Trade Demand, answered like R7's card (quietly when benched) */ else storyPick(c, e); if (e.choice) rec.choices++; if (e.id === 'tour-ask') rec.tourAsk = (rec.tourAsk || 0) + 1; } } if (e.kind === 'press') answer(c, e, rec); else if (e.kind === 'trade') { const yes = e.why === 'bench'; proTradeAnswer(c, e, yes); if (yes) rec.pro.trades++; } else if (e.kind === 'shoe') { if (spend !== 'none' && c.me.money >= PR.shoeCost * 2) { proShoeAnswer(c, e, true); if (c.me.shoe) rec.pro.shoe = 1; } } } if (c.events) c.events.length = 0; while (c.me.offers && c.me.offers.length) acceptEndorsement(c, 0); /* R8: take every sponsor deal (the simulator never did: hype's endorsement money was invisible) */ rec.pro.spent += (res.staffCost || 0); rec.cash.upkeep += (res.upkeep || 0); /* V11: lifestyle's upkeep */ rec.pro.endorse = (rec.pro.endorse || 0) + (res.endorse || 0); /* R8: sponsor money */ if (STAFF_ROLES.some(r => r !== 'agent' && c.me.staff && c.me.staff[r])) rec.pro.trainerWeeks++ /* V10: weeks with a salaried staffer */; // R7: trade requests when benched, the shoe line
          for (const id of c.active) { const p = c.players[id]; for (const k of RATING_KEYS) if (!isFinite(p.r[k]) || p.r[k] < CR.ratingMin - 0.01 || p.r[k] > CR.ratingMax + 0.01) inv.push('rating out of range ' + p.name + ' ' + k + ' ' + p.r[k]); }
          if (c.active.length !== CR.leagueSize) inv.push('league size ' + c.active.length);
          if (!isFinite(c.me.money)) inv.push('money NaN');
        } else if (c.phase === 'offseason') {
          if (c.playoffs && c.playoffs.champion === c.meId && !rec['t' + c.season]) { rec['t' + c.season] = 1; if (isStarter(c)) rec.titleStart = (rec.titleStart || 0) + 1; else rec.titleBench = (rec.titleBench || 0) + 1; rec.titleStars = rec.titleStars || [0, 0, 0, 0, 0, 0]; rec.titleStars[frMine(c)]++; } // V6: a title as the starter or from the bench
          rec.proSeasons++; note(me.age, recOvr(me)); if (seasonsOut) (rec.ps || (rec.ps = [])).push({ a: me.age, o: recOvr(me), st: frMine(c), st0: rec.fr.seasons[c.season] || 0, rk: standingsSorted(c).indexOf(c.meId) + 1, po: c.me.playoffResult || null, t: c.playoffs && c.playoffs.champion === c.meId ? 1 : 0, sv: isStarter(c) ? 1 : 0, b: c.me.benchSeason || 0, cl: me.club, sx: rec.sx && rec.sx[c.season] }); /* V6: --seasons (a diagnostic): each pro season */ { const o = c.active.filter(id => id !== c.meId).map(id => recOvr(c.players[id])).sort((x, y) => y - x); (rec.lg || (rec.lg = [])).push([+(o.reduce((x, y) => x + y, 0) / o.length).toFixed(1), o[0], o[2]]); }
          offseasonProgression(c); offseasonMoves(c); for (const e of (c.events || []).slice()) if (e.kind === 'rebuild' && !e.answered) { proRebuildAnswer(c, e, true); rec.pro.rebuildTrades = (rec.pro.rebuildTrades || 0) + 1; } /* V12: a rebuilding owner's offer: go to the contender */ const offers = offseasonContract(c); if (offers) { const k = faPolicy === 'money' ? offers.findIndex(x => x.salary === Math.max(...offers.map(q => q.salary))) : faPolicy === 'stars' ? offers.reduce((bi, x, i) => ((x.stars || 0) > (offers[bi].stars || 0) || ((x.stars || 0) === (offers[bi].stars || 0) && x.salary > offers[bi].salary)) ? i : bi, 0) : Math.max(0, offers.findIndex(x => x.kind === (faPolicy === 'big' ? 'best' : faPolicy))); rec.pro.fa[offers[k].kind] = (rec.pro.fa[offers[k].kind] || 0) + 1; acceptContract(c, k, offers[k].maxYears >= 4 ? 4 : offers[k].maxYears, offers[k].kind === 'starter' || offers[k].promised); } // R7: the free-agency policy
          note(me.age, recOvr(me));
          if (mustRetire(c) || (canRetire(c) && me.age >= 34 && recOvr(me) < 68)) { rec.retireAge = me.age; { const Sg = c.me.saga; if (Sg) rec.saga = { order: Sg.order.slice(), beats: Sg.log.length, done: Sg.order.filter(id => Sg.arcs[id] && Sg.arcs[id].st === 'done').length, picks: Sg.log.filter(l => l.pick).length }; } /* V7: the saga */ rec.gear.end = gearLevels(c); retireCareer(save); rec.recBest = c.me.recBook ? c.me.recBook.best : null; /* V8: the records book's bests by level */ if (rec.saga) { const Sg = c.me.saga; rec.saga.epi = Sg.epilogue || null; rec.saga.beats = Sg.log.length; rec.saga.done = Sg.order.filter(id => Sg.arcs[id] && Sg.arcs[id].st === 'done').length; } /* V8: the epilogue (and the retirement's beats) */ rec.cash.retire = c.me.money || 0; rec.cash.earned = c.me.earned || 0; const worth = proNetWorth(c); const E = proEpilogue(save, { stake: worth >= PR.stakeCost * 1.2, academy: worth >= PR.academyCost * 3, foundation: PR.foundationMax, ending: 'coach' }); rec.pro.worth = E.worth; rec.cash.left = E.left; /* V11: what's left after the endings */ rec.pro.foundation = E.foundation; rec.pro.academy = E.academy; rec.pro.stake = E.stake; break; } // R7: the epilogue
          newSeason(c); moneyPolicy(); { const ag = meOf(c).age; if (ag === 25 && rec.cash.at25 == null) rec.cash.at25 = c.me.money || 0; if (ag === 30 && rec.cash.at30 == null) rec.cash.at30 = c.me.money || 0; } /* V11: cash by stage */ { const S = staffOf(c); rec.staffS = rec.staffS || { n: 0 }; rec.staffS.n++; for (const r of STAFF_ROLES) if (S[r]) { rec.staffS[r] = (rec.staffS[r] || 0) + 1; rec.staffS[r + 'T'] = (rec.staffS[r + 'T'] || 0) + S[r].tier; } } /* V10: who's on staff each season */
        } else { inv.push('unknown phase ' + c.phase); break; }
      }
      if (guard >= 4000) { rec.stuck = true; inv.push('guard hit'); }
      rec.goals = Object.assign({}, c.me.goals || {}); const L = c.legacy || legacyOf(c); rec.L = { titles: L.titles, mvps: L.mvps, allL: L.allL, seasons: L.seasons, pts: Math.round((L.ptsN != null ? L.ptsN : L.pts) / CR.legacy.ptsPer) /* F5: the legacy counts points per the old game length */, ppg: +(L.ppg || 0).toFixed(1) }; rec.titles = L.titles; rec.mvps = L.mvps; { const RD = roadOf(c); rec.v12 = { fmvp: L.fmvp || 0, run: c.me.titleBest || 0, jersey: (c.me.jerseys || []).length, franchise: !!(RD && RD.done && RD.done.franchise), rebuild: rec.pro.rebuildTrades || 0 }; } /* V12 */ rec.trLv = forceTrait && forceTrait !== 'none' && traitsOf(c.me) ? trLvOf(c.me, forceTrait) : 0; rec.lvAt = traitsOf(c.me) && c.me.tr.deeds ? Object.assign({}, c.me.tr.deeds) : null; rec.deedTot = forceTrait && TR.list[forceTrait] && TR.list[forceTrait].deed && rec.lvAt ? Math.round(rec.lvAt[TR.list[forceTrait].deed[0]] || 0) : null; /* V3: the trait's level at retirement */ rec.legacy = L.score; rec.hof = L.hof; rec.money = Math.round(c.me.money || 0); rec.social = (c.me.social || []).length; rec.arcLog = (a.arcLog || []).concat(c.me.arcLog || []); rec.earned = Math.round(c.me.earned || 0); rec.ovr = ages; rec.inv = inv.slice(0, 5); rec.hFinal = me.h;
      results.push(rec);
    }
    return results;
  }, { N, seed0, engineGames, forceTrait, forceSummer, faPolicy, tradePolicy, spend, pressPolicy, hypePolicy, pressAm, gearPolicy, policy, edge, seasonsOut, storyPolicy, schoolPolicy, staffOnly, staffBudget });
  const med = a => { const s = a.filter(x => x != null).sort((x, y) => x - y); return s.length ? s[Math.floor(s.length / 2)] : null; };
  const at = age => med(out.map(r => r.ovr[age]));
  console.log('careers', out.length, '· stuck', out.filter(r => r.stuck || (r.inv && r.inv.length)).length);
  console.log('median OVR at 14/17/21/25/29/33:', [14, 17, 21, 25, 29, 33].map(at).join(' / '));
  console.log('peak OVR median', med(out.map(r => r.peak)), '· peak age median', med(out.map(r => r.peakAge)), '· peak range', Math.min(...out.map(r => r.peak)) + '–' + Math.max(...out.map(r => r.peak)));
  { const F = out.filter(r => r.fr), n = Math.max(1, F.length), pc = k => Math.round(100 * F.filter(r => r.fr.best >= k).length / n), first = [1, 2, 3, 4, 5].map(k => F.filter(r => r.fr.first === k).length).join('/'), a5 = F.map(r => r.fr.age[5]).filter(x => x != null), gl = k => Math.round(100 * F.filter(r => r.goals && r.goals[k]).length / n); console.log('franchises (F7; --fa=' + faPolicy + ' --trade=' + tradePolicy + '): first team 1–5★ ' + first + ' · reached 3★ ' + pc(3) + '% · 4★ ' + pc(4) + '% · 5★ ' + pc(5) + '% (median age at the first 5★ ' + (a5.length ? med(a5) : '—') + '; by 29 ' + Math.round(100 * a5.filter(x => x <= 29).length / n) + '%, 2.0 §7) · started for a 5★ ' + gl('start5') + '% · a title with a 5★ ' + gl('title5') + '% · trades asked ' + (F.reduce((x, r) => x + r.fr.tradesUp, 0) / n).toFixed(2) + ' a career · the first 5★ by moving ' + F.filter(r => r.fr.via5 === 'move').length + ', by their team rising ' + F.filter(r => r.fr.via5 === 'rise').length); }
  console.log('pro start age median', med(out.map(r => r.draftAge)), '· skipped college', out.filter(r => r.college === '(none)').length);
  console.log('pro titles: mean ' + (out.reduce((a, r) => a + r.titles, 0) / out.length).toFixed(2) + ' · careers with a title ' + out.filter(r => r.titles > 0).length + ' · MVPs mean ' + (out.reduce((a, r) => a + r.mvps, 0) / out.length).toFixed(2));
  console.log('Hall of Fame: ' + out.filter(r => r.hof).length + ' of ' + out.length + ' (' + Math.round(100 * out.filter(r => r.hof).length / out.length) + '%) · legacy median ' + med(out.map(r => r.legacy)) + ' · pro seasons median ' + med(out.map(r => r.proSeasons)) + ' · retire age median ' + med(out.map(r => r.retireAge)));
  for (const sIdx of [0, 4, 9, 14]) { const rows = out.map(r => r.lg && r.lg[sIdx]).filter(Boolean); if (rows.length) console.log('league (others) after pro season ' + (sIdx + 1) + ': mean OVR ' + (rows.reduce((a, r) => a + r[0], 0) / rows.length).toFixed(1) + ' · best ' + (rows.reduce((a, r) => a + r[1], 0) / rows.length).toFixed(1) + ' · 3rd best ' + (rows.reduce((a, r) => a + r[2], 0) / rows.length).toFixed(1) + ' (n=' + rows.length + ')'); }
  console.log('pro score (the old draft score) median ' + med(out.map(r => r.dscore)) + ' · range ' + Math.min(...out.map(r => r.dscore || 0)).toFixed(0) + '–' + Math.max(...out.map(r => r.dscore || 0)).toFixed(0));
  console.log('heights: final median ' + med(out.map(r => r.hFinal)) + ' · at 14 median ' + med(out.map(r => r.h14)));
  { const P = { practice: 0, rest: 0, film: 0 }; for (const r of out) for (const k in r.plans) P[k] = (P[k] || 0) + r.plans[k]; const tot = P.practice + P.rest + P.film || 1; const fat = out.flatMap(r => r.fat); const mean = fat.length ? fat.reduce((x, y) => x + y, 0) / fat.length : 0; console.log('the week: practice ' + Math.round(100 * P.practice / tot) + '% · rest ' + Math.round(100 * P.rest / tot) + '% · film ' + Math.round(100 * P.film / tot) + '% · pro fatigue at tip-off: mean ' + mean.toFixed(1) + ', max ' + (fat.length ? fat.reduce((a, b) => Math.max(a, b), 0) : 0) + ' · injuries per career: mean ' + (out.reduce((x, r) => x + r.injuries, 0) / out.length).toFixed(1)); console.log('press questions per career: mean ' + (out.reduce((x, r) => x + r.press, 0) / out.length).toFixed(1) + ' · hype at the draft: median ' + med(out.map(r => r.hype))); }
  console.log('depth chart (R4): weeks on the bench per career: amateur ' + (out.reduce((x, r) => x + r.benchAm, 0) / out.length).toFixed(1) + ' · pro ' + (out.reduce((x, r) => x + r.benchPro, 0) / out.length).toFixed(1) + ' · challenges ' + (out.reduce((x, r) => x + r.challenges, 0) / out.length).toFixed(1) + ' · coach trust at the draft: median ' + med(out.map(r => r.trustDraft)) + ' · pro bench weeks by season 1–15: ' + Array.from({ length: 15 }, (_, i) => (out.reduce((x, r) => x + (r.benchBy[i + 1] || 0), 0) / out.length).toFixed(1)).join(' '));
  { const H = out.map(r => r.hs).filter(h => h && h.nat), avg = f => (H.reduce((x, h) => x + f(h), 0) / Math.max(1, H.length)).toFixed(2), mdn = f => { const v = H.map(f).sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; }, cnt = (f, vals) => vals.map(v => H.filter(h => f(h) === v).length).join('/'), sm = {}; for (const h of H) for (const k in h.summers) sm[k] = (sm[k] || 0) + h.summers[k];
    console.log('high school (R5): freshmen on varsity ' + Math.round(100 * H.filter(h => h.fresh).length / Math.max(1, H.length)) + '% · JV seasons ' + avg(h => h.jv) + ' · call-ups ' + avg(h => h.callups) + ' · district titles ' + avg(h => h.districts) + ' · state titles ' + avg(h => h.state) + ' · study weeks ' + avg(h => h.study) + ' · ineligible games ' + avg(h => h.inel) + ' · lowest GPA median ' + mdn(h => h.gpaMin).toFixed(2) + ' · stars at signing 5/4/3/2/1 ' + cnt(h => h.stars, [5, 4, 3, 2, 1]) + ' · national rank median ' + mdn(h => h.nat) + ' · best offer tier blue blood/power/mid/small ' + cnt(h => h.top, [3, 2, 1, 0]) + ' · summers ' + JSON.stringify(sm)); }
  { const C = out.map(r => r.col).filter(x => x && x.seasons), avg = f => (C.reduce((x, h) => x + f(h), 0) / Math.max(1, C.length)).toFixed(2), n = C.reduce((x, h) => x + h.seasons, 0) || 1, mk = C.flatMap(h => h.mock).sort((x, y) => x - y);
    console.log('college (R6): ' + C.length + ' careers, ' + avg(h => h.seasons) + ' seasons · national tournament ' + Math.round(100 * C.reduce((x, h) => x + h.nat, 0) / n) + '% of seasons (left out ' + Math.round(100 * C.reduce((x, h) => x + h.missed, 0) / n) + '%) · national wins per trip ' + (C.reduce((x, h) => x + h.natW, 0) / Math.max(1, C.reduce((x, h) => x + h.nat, 0))).toFixed(2) + ' · Final Fours ' + avg(h => h.ff) + ' · national titles ' + avg(h => h.champ) + ' · conference tournament titles ' + avg(h => h.confT) + ' · NIL offers ' + avg(h => h.nilOffers) + ', deals ' + avg(h => h.nilDeals) + ', money median $' + (C.map(h => h.nil).sort((x, y) => x - y)[Math.floor(C.length / 2)] || 0) + ' · portal ' + C.filter(h => h.portal).length + ' careers, transfers ' + C.filter(h => h.transfer).length + ' · agents ' + out.filter(r => r.col && r.col.agent).length + ' · season-end mock pick median ' + (mk.length ? mk[Math.floor(mk.length / 2)] : '–')); }
  { const T = [[], [], [], []]; for (const r of out) for (const e of (r.col && r.col.log) || []) { const [t, b, g, inf, rk, w, ct] = e; if (T[t]) T[t].push({ ws: g ? w / g : 0, bench: g ? b / g : 0, inf, ct }); } const f = (a, k) => a.length ? (a.reduce((x, y) => x + y[k], 0) / a.length) : 0;
    console.log('college by program tier (R6; seasons · win share · bench share · national tournament · conference tournament titles): ' + ['small', 'mid-major', 'power', 'blue blood'].map((nm, i) => nm + ' ' + T[i].length + ' · ' + f(T[i], 'ws').toFixed(2) + ' · ' + f(T[i], 'bench').toFixed(2) + ' · ' + Math.round(100 * f(T[i], 'inf')) + '% · ' + T[i].filter(x => x.ct).length).join(' | ')); }
  { const K = out.map(r => r.sch).filter(Boolean), col = K.filter(k => k.col), pct = (a, f) => Math.round(100 * a.filter(f).length / Math.max(1, a.length)) + '%', C = out.map(r => r.col).filter(x => x && x.seasons), avgC = f => (C.reduce((x, h) => x + f(h), 0) / Math.max(1, C.length)).toFixed(2), md = a => { const v = a.slice().sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; };
    console.log('school (V9): ' + col.length + ' went to college · full ride ' + pct(col, k => k.sch === 'full') + ', partial ' + pct(col, k => k.sch === 'partial') + ', lost ' + pct(col, k => k.sch === 'lost') + ' · elite academic: committed ' + pct(col, k => k.commitAcademic) + ', there at the draft ' + pct(col, k => k.academic) + ' · tuition paid: mean $' + Math.round(col.reduce((x, k) => x + k.tuition, 0) / Math.max(1, col.length)).toLocaleString('en-US') + ' · a loan at the draft ' + pct(col, k => k.loan > 0) + ' (median $' + md(col.filter(k => k.loan > 0).map(k => k.loan)).toLocaleString('en-US') + ') · college study weeks ' + avgC(h => h.study) + ' · college ineligible games ' + avgC(h => h.inel) + ' · probation ' + pct(col, k => k.probation) + ' · GPA at the draft: median ' + (+md(K.map(k => k.gpa))).toFixed(2) + ' · a degree (4 college years) ' + pct(col, k => k.years >= 4)); }
  { const R = out.map(r => r.pro).filter(Boolean), md = a => { const v = a.slice().sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; }, fa = {}; for (const r of R) for (const k in r.fa) fa[k] = (fa[k] || 0) + r.fa[k];
    { const Z = out.filter(r => r.staffS && r.staffS.n), sn = Z.reduce((a, r) => a + r.staffS.n, 0) || 1; console.log('staff (V10; --spend=' + spend + (staffOnly ? ' --staff=only:' + staffOnly : '') + ' --staffBudget=' + staffBudget + '): seasons with each role (mean tier) ' + ['agent', 'skills', 'strength', 'physio', 'nutrition', 'mental'].map(k => { const n = Z.reduce((a, r) => a + (r.staffS[k] || 0), 0); return k + ' ' + Math.round(100 * n / sn) + '%' + (n ? ' (' + (Z.reduce((a, r) => a + (r.staffS[k + 'T'] || 0), 0) / n).toFixed(1) + '★)' : ''); }).join(' · ')); }
    console.log('pro money (R7; --fa=' + faPolicy + ' --spend=' + spend + '): net worth median $' + (md(R.map(r => r.worth)) / 1e6).toFixed(1) + 'M · earned median $' + (md(out.map(r => r.earned || 0)) / 1e6).toFixed(1) + 'M · training spent median $' + (md(R.map(r => r.spent)) / 1e6).toFixed(1) + 'M · trainer weeks median ' + md(R.map(r => r.trainerWeeks)) + ' · shoe lines ' + R.filter(r => r.shoe).length + ' · lifestyle buys ' + R.reduce((x, r) => x + r.life, 0) + ' · trade requests ' + R.reduce((x, r) => x + r.trades, 0) + ' · free agency picks ' + JSON.stringify(fa) + ' · epilogue: foundation median +' + md(R.map(r => r.foundation)) + ', academies ' + R.filter(r => r.academy).length + ', stakes ' + R.filter(r => r.stake).length); }
  { const G = out.filter(r => r.gear), mean = k => G.reduce((a, r) => a + (r.gear[k] || 0), 0) / Math.max(1, G.length); console.log('gear (V11; --gear=' + gearPolicy + '): levels worn at the pro start mean ' + mean('atPro').toFixed(1) + ' · at retirement ' + mean('end').toFixed(1) + ' · spent median $' + Math.round((med(G.map(r => r.gear.spent)) || 0) / 1e3) + 'K · buys ' + mean('buys').toFixed(1) + ', upgrades ' + mean('ups').toFixed(1) + ', extras ' + mean('uses').toFixed(1) + ' a career'); }
  { const R = out.filter(r => r.cash && r.cash.earned > 0), M$ = v => v == null ? '–' : '$' + (v >= 1e6 ? (v / 1e6).toFixed(1) + 'M' : v >= 1e4 ? Math.round(v / 1e3) + 'K' : Math.round(v)), mdk = k => { const v = R.map(r => r.cash[k]).filter(x => x != null); return v.length ? med(v) : null; }, un = R.map(r => r.cash.retire / r.cash.earned), left = R.map(r => (r.cash.left || 0) / r.cash.earned), u = med(un) || 0;
    console.log('money (V11, Part 2 §5.3; --spend=' + spend + '): median cash at the end of high school ' + M$(mdk('hsEnd')) + ' · at the pro start ' + M$(mdk('colEnd')) + ' · at 25 ' + M$(mdk('at25')) + ' · at 30 ' + M$(mdk('at30')) + ' · at retirement ' + M$(mdk('retire')) + ' of ' + M$(mdk('earned')) + ' earned (unspent ' + Math.round(100 * u) + '%; after the endings ' + Math.round(100 * (med(left) || 0)) + '%) · lifestyle upkeep ' + M$(mdk('upkeep')) + (spend === 'smart' ? ' · target: unspent under 30% ' + (u < 0.3 ? '✓' : '✗') : '')); }
  { const g = out.reduce((x, r) => x + r.hypeN, 0) || 1; console.log('hype and press (R8; --press=' + (pressPolicy || 'auto') + ' --hype=' + (hypePolicy || '-') + '): pro hype mean ' + (out.reduce((x, r) => x + r.hypeSum, 0) / g).toFixed(1) + ' · pro games at 60+ ' + Math.round(100 * out.reduce((x, r) => x + r.hype60, 0) / g) + '%, 70+ ' + Math.round(100 * out.reduce((x, r) => x + r.hype70, 0) / g) + '% · press answers per career ' + (out.reduce((x, r) => x + r.press, 0) / out.length).toFixed(1) + ' · fines per career ' + (out.reduce((x, r) => x + r.fines, 0) / out.length).toFixed(2) + ' · questions per career by stage ' + JSON.stringify(['hs', 'college', 'pro'].reduce((o, k) => (o[k] = +(out.reduce((x, r) => x + (r.pressBy[k] || 0), 0) / out.length).toFixed(1), o), {})) + ' · grudge games per career ' + JSON.stringify(['hs', 'hs-po', 'college', 'college-po', 'pro', 'pro-po'].reduce((o, k) => (o[k] = +(out.reduce((x, r) => x + (r.grudgeBy[k] || 0), 0) / out.length).toFixed(2), o), {})) + ' · sponsor money mean $' + (out.reduce((x, r) => x + ((r.pro && r.pro.endorse) || 0), 0) / out.length / 1e6).toFixed(1) + 'M · shoe lines ' + out.filter(r => r.pro && r.pro.shoe).length + ' · hype at the draft: median ' + med(out.map(r => r.hype)) + ' · legacy mean ' + (out.reduce((x, r) => x + r.legacy, 0) / out.length).toFixed(1) + ' · earned mean $' + (out.reduce((x, r) => x + (r.earned || 0), 0) / out.length / 1e6).toFixed(1) + 'M · titles mean ' + (out.reduce((x, r) => x + r.titles, 0) / out.length).toFixed(2)); }
  { const all = out.map(r => (r.arcLog || []).map(e => e.n)).flat(), hist = {}; for (const v of all) hist[Math.min(v, 7)] = (hist[Math.min(v, 7)] || 0) + 1; const inRange = all.filter(v => v >= 3 && v <= 5).length; console.log('story (R9): beats a season (dialogue cards and the rival\'s moments): mean ' + (all.reduce((x, y) => x + y, 0) / Math.max(1, all.length)).toFixed(2) + ' · 3–5 in ' + (100 * inRange / Math.max(1, all.length)).toFixed(1) + '% of ' + all.length + ' seasons (' + all.filter(v => v < 3).length + ' under 3, ' + all.filter(v => v > 5).length + ' over 5: the beats that are always told) · histogram ' + JSON.stringify(hist) + ' · choices per career ' + (out.reduce((x, r) => x + r.choices, 0) / out.length).toFixed(1) + ' · social posts kept ' + Math.round(out.reduce((x, r) => x + (r.social || 0), 0) / out.length) + (process.argv.includes('--beats') ? ' · outside 3–5 in the first 12 careers: ' + JSON.stringify(out.slice(0, 12).map(r => (r.arcLog || []).filter(e => e.n < 3 || e.n > 5).map(e => e.st + e.s + ':' + e.n)).filter(l => l.length)) : '')); }
  if (process.argv.includes('--each')) for (const r of out) console.log(JSON.stringify({ style: r.style, h: r.hFinal, pick: r.pick, dAge: r.draftAge, col: r.college, ovr: r.ovr, peak: r.peak + '@' + r.peakAge, t: r.titles, mvp: r.mvps, leg: r.legacy, hof: r.hof, ret: r.retireAge, inv: r.inv, colLog: r.col && r.col.log }));
  { const R = out.filter(r => r.saga), n = Math.max(1, R.length), arcs = {}, epis = {}; for (const r of R) { for (const id of r.saga.order) arcs[id] = (arcs[id] || 0) + 1; if (r.saga.epi) epis[r.saga.epi] = (epis[r.saga.epi] || 0) + 1; } const per = R.map(r => r.saga.order.length), hist = {}; for (const v of per) hist[v] = (hist[v] || 0) + 1; const ids = Object.keys(arcs).sort((a, b) => arcs[b] - arcs[a]), in68 = per.filter(v => v >= 6 && v <= 8).length;
    console.log('saga (V7–V8): arcs per career mean ' + (per.reduce((a, b) => a + b, 0) / n).toFixed(2) + ' (6–8 in ' + Math.round(100 * in68 / n) + '% of careers) · histogram ' + JSON.stringify(hist) + ' · beats per career ' + (R.reduce((a, r) => a + r.saga.beats, 0) / n).toFixed(1) + ' · arcs finished ' + (R.reduce((a, r) => a + r.saga.done, 0) / n).toFixed(2) + ' (n=' + R.length + ')');
    console.log('  arc frequency (most → least common): ' + ids.map(id => id + ' ' + Math.round(100 * arcs[id] / n) + '%').join(', ') + (ids.length ? ' · above 70%: ' + (ids.filter(id => arcs[id] / n > 0.7).join(', ') || 'none') : ''));
    console.log('  epilogues: ' + (Object.keys(epis).sort((a, b) => epis[b] - epis[a]).map(id => id + ' ' + Math.round(100 * epis[id] / n) + '%').join(', ') || 'none')); }
  { const part = (rows, k) => rows.length ? (rows.reduce((a, r) => a + (r.L ? r.L[k] : 0), 0) / rows.length).toFixed(1) : '–'; const H = out.filter(r => r.hof), N = out.filter(r => !r.hof); console.log('legacy parts (Hall of Fame / the rest): titles ' + part(H, 'titles') + ' / ' + part(N, 'titles') + ' · MVPs ' + part(H, 'mvps') + ' / ' + part(N, 'mvps') + ' · All-League 1st ' + part(H, 'allL') + ' / ' + part(N, 'allL') + ' · seasons ' + part(H, 'seasons') + ' / ' + part(N, 'seasons') + ' · points/250 ' + part(H, 'pts') + ' / ' + part(N, 'pts') + ' · PPG ' + part(H, 'ppg') + ' / ' + part(N, 'ppg') + ' · peak ' + med(H.map(r => r.peak)) + ' / ' + med(N.map(r => r.peak))); const pk = out.map(r => r.peak).sort((x, y) => x - y); console.log('peak percentiles 10/25/50/75/90: ' + [0.1, 0.25, 0.5, 0.75, 0.9].map(q => pk[Math.floor(q * (pk.length - 1))]).join(' / ')); }
  { const V = out.filter(r => r.v12), n = Math.max(1, V.length), pc = f => Math.round(100 * V.filter(f).length / n); console.log('pro teams (V12, Part 2 §6): a ring ' + pc(r => r.titles > 0) + '% · Finals MVP ' + pc(r => r.v12.fmvp > 0) + '% (mean ' + (V.reduce((a, r) => a + r.v12.fmvp, 0) / n).toFixed(2) + ') · a franchise player ' + pc(r => r.v12.franchise) + '% · a jersey retired ' + pc(r => r.v12.jersey > 0) + '% · back-to-back ' + pc(r => r.v12.run >= 2) + '% · a three-peat ' + pc(r => r.v12.run >= 3) + '% · rebuild trades ' + (V.reduce((a, r) => a + r.v12.rebuild, 0) / n).toFixed(2) + ' a career'); }
  const invs = out.filter(r => r.inv && r.inv.length).slice(0, 5).map(r => r.inv); if (invs.length) console.log('invariants', JSON.stringify(invs));
  const pct = x => Math.round(100 * x);
  const hof = out.filter(r => r.hof).length / out.length, titles = out.reduce((a, r) => a + r.titles, 0) / out.length, stuck = out.filter(r => r.stuck || (r.inv && r.inv.length)).length;
  const inR = (v, lo, hi) => v != null && v >= lo && v <= hi ? '✓' : '✗';
  { const great5 = policy === 'great', b5 = pct(out.filter(r => r.fr && r.fr.best >= 5).length / out.length); /* V6: Part 2 §1.1 replaces F6's targets (the whole table: tests/difficulty.js, 600 careers) */
    console.log('TARGETS (Part 2 §1.1, ' + policy + '; 40 careers are a rough read): a 5★ team ' + b5 + '% (' + (great5 ? '52–68' : '15–25') + ') ' + (great5 ? inR(b5, 52, 68) : inR(b5, 15, 25)) + ' · titles/career ' + titles.toFixed(2) + ' (' + (great5 ? '1–3' : '0.2–0.4') + ') ' + (great5 ? inR(titles, 1, 3) : inR(titles, 0.2, 0.4)) + ' · HOF ' + pct(hof) + '% (' + (great5 ? '30–40' : '3–8') + '%) ' + (great5 ? inR(pct(hof), 30, 40) : inR(pct(hof), 3, 8)) + ' · peak ' + med(out.map(r => r.peak)) + ' · OVR@17/21/25 ' + at(17) + '/' + at(21) + '/' + at(25) + ' · stuck ' + stuck + ' (0) ' + (stuck ? '✗' : '✓')); }
  { const F = out.filter(r => !r.stuck), n = Math.max(1, F.length), P_ = x => Math.round(100 * x / n); // V6 (Part 2 §1.1): the difficulty table's numbers for this policy
    console.log('titles as the starter / from the bench: ' + (F.reduce((a, r) => a + (r.titleStart || 0), 0) / n).toFixed(2) + ' / ' + (F.reduce((a, r) => a + (r.titleBench || 0), 0) / n).toFixed(2) + ' · by the team\'s stars 1–5: ' + [1, 2, 3, 4, 5].map(k => (F.reduce((a, r) => a + ((r.titleStars || [])[k] || 0), 0) / n).toFixed(2)).join(' / ')); console.log('DIFFICULTY (' + policy + (policy === 'great' ? ', edge ' + edge : '') + '): varsity year 1/2/3/4/never ' + [1, 2, 3, 4].map(y => P_(F.filter(r => r.varsityYear === y).length)).join('/') + '/' + P_(F.filter(r => r.varsityYear == null).length) + '% · stars at signing 1–5 ' + [1, 2, 3, 4, 5].map(k => P_(F.filter(r => r.hs.stars === k).length)).join('/') + '% · college start year 1/2/3/4/never ' + [1, 2, 3, 4].map(y => P_(F.filter(r => r.colStart === y).length)).join('/') + '/' + P_(F.filter(r => r.colStart == null).length) + '% · first pro offer 1–5★ ' + [1, 2, 3, 4, 5].map(k => P_(F.filter(r => r.offer === k).length)).join('/') + '% · a 3★ team ' + P_(F.filter(r => r.fr && r.fr.age[3] != null).length) + '% (by 24 ' + P_(F.filter(r => r.fr && r.fr.age[3] != null && r.fr.age[3] <= 24).length) + '%, by 28 ' + P_(F.filter(r => r.fr && r.fr.age[3] != null && r.fr.age[3] <= 28).length) + '%, median age ' + med(F.map(r => r.fr && r.fr.age[3])) + ') · a 5★ team ' + P_(F.filter(r => r.fr && r.fr.best >= 5).length) + '% · titles ' + (F.reduce((a, r) => a + (r.titles || 0), 0) / n).toFixed(2) + ' · HoF ' + P_(F.filter(r => r.hof).length) + '%'); }
  if (process.argv.includes('--json')) console.log('JSON ' + JSON.stringify({ n: out.length, policy, edge, legParts: out.map(r => r.L || null), saga: out.map(r => r.saga || null), recBest: out.map(r => r.recBest || null), ps: seasonsOut ? out.map(r => r.ps || []) : undefined, diff: out.map(r => ({ v: r.varsityYear == null ? null : r.varsityYear, st: r.hs ? r.hs.stars : 0, cs: r.colStart == null ? null : r.colStart, of: r.offer == null ? null : r.offer, a3: r.fr && r.fr.age[3] != null ? r.fr.age[3] : null, b5: r.fr ? r.fr.best : 0, t: r.titles || 0, h: !!r.hof, pk: r.peak, stuck: !!r.stuck })), trait: forceTrait, lv: out.map(r => r.trLv || 0), ageS: out.map(r => r.ageS == null ? null : r.ageS), ageG: out.map(r => r.ageG == null ? null : r.ageG), deedTot: out.map(r => r.deedTot == null ? null : r.deedTot), third: out.filter(r => r.third).length, legacy: out.map(r => r.legacy), titles: out.map(r => r.titles), money: out.map(r => r.earned), cash: out.map(r => r.cash || null), gearRec: out.map(r => r.gear || null), worth: out.map(r => (r.pro && r.pro.worth) || 0), spent: out.map(r => (r.pro && r.pro.spent) || 0), inj: out.map(r => r.injuries || 0), hype: out.map(r => r.hypeN ? +(r.hypeSum / r.hypeN).toFixed(1) : 0), hof: out.filter(r => r.hof).length, stuck }));
  console.log('errors', errors.slice(0, 5)); await browser.close(); process.exitCode = errors.length || stuck ? 1 : 0;
})();
