// Career simulator: whole careers from a 14-year-old freshman to retirement, played with Sim and sensible choices
// (headless, in the page). Usage: node tests/careersim.js [careers=40] [seed=1] [engineGames=0] [--each] [--json]
// [--set career.proMean=80 ...] (--set overrides a CONFIG value for a tuning run) [--trait=<id>|none] (every career
// starts with badge <id> at Lv1; the badge balance test runs this for each badge; none: no badges at all, its baseline)
// [--fa=stars|money|yours|best|starter] [--trade=up|never] (F7: free agency takes the most stars, the most money or one
// kind of offer ("big" is the old name for best); trade requests go a star up, or never) [--spend=smart|none] (smart:
// an agent, the shoe line, lifestyle and big buys when the money covers them; none buys nothing) [--gear=buy|none]
// (F8: buy gear once the money covers it twice over, four times in the pros). 3.0 (§1): no press, hype, story or staff
// policies (those systems are gone).
// Reports medians at ages 17/21/25, peak OVR, the franchises reached, titles, the Hall of Fame rate and any stuck states
// against the spec's targets.
const { launch, openPage } = require('./lib');
// X9 (3.0 §8): the recruiting table by the national rank at signing (Top 50, 4★, 3★, 2★, 1★): offers received, none,
// 8+ and a top program for the Top 50 (a blue blood where the GPA meets its line), 2–4 for a 3★, the roads with none.
function rec8(out, blue) { blue = blue || 2.5; // (blue: the blue bloods' GPA line, CONFIG.school.gpaReq.blue; the page's arrays carry no extra fields)
  const H = out.map(r => r && (r.hs || r)).filter(h => h && h.nat), band = h => h.nat <= 50 ? 'Top 50' : h.stars + '★', pc = (a, f) => Math.round(100 * a.filter(f).length / Math.max(1, a.length)), roads = {}, roads1 = {}, why = {};
  const rows = ['Top 50', '4★', '3★', '2★', '1★'].map(b => { const G = H.filter(h => band(h) === b && h.offers != null), o = G.map(h => h.offers).sort((x, y) => x - y), bt = h => h.byTier || [0, 0, 0, 0, 0];
    return { band: b, n: G.length, mean: G.length ? o.reduce((x, y) => x + y, 0) / G.length : 0, med: o.length ? o[Math.floor(o.length / 2)] : 0, none: pc(G, h => !h.offers), eight: pc(G, h => h.offers >= 8), top: pc(G, h => bt(h)[2] + bt(h)[3] > 0), blue: pc(G.filter(h => h.gpa >= blue), h => bt(h)[3] > 0), nBlue: G.filter(h => h.gpa >= blue).length, twoFour: pc(G, h => h.offers >= 2 && h.offers <= 4) }; });
  for (const h of H) { if (!h.offers && h.road) { const k = String(h.road).split('+')[0]; roads[k] = (roads[k] || 0) + 1; if (h.stars === 1) roads1[k] = (roads1[k] || 0) + 1; } for (const w of (Array.isArray(h.pullWhy) ? h.pullWhy : Array.isArray(h.pulled) ? h.pulled : [])) why[w] = (why[w] || 0) + 1; }
  return { rows, roads, roads1, why, held: (H.reduce((x, h) => x + (h.held || 0), 0) / Math.max(1, H.length)).toFixed(2), pulled: (H.reduce((x, h) => x + (Array.isArray(h.pullWhy) ? h.pullWhy.length : Array.isArray(h.pulled) ? h.pulled.length : h.pulled || 0), 0) / Math.max(1, H.length)).toFixed(2) };
}
module.exports = { rec8 }; // (tests/recruit30.js reads the table; the simulator runs only from the command line)
if (require.main === module) (async () => {
  const argv = process.argv.slice(2), sets = []; if (argv.includes('--menus=never')) argv.unshift('--fa=default', '--trade=never', '--spend=none', '--gear=none'); /* 2.1 (§1.1): --menus=never: the player never opens a menu (no trade requests, no shop, no purchases); every card that comes takes its default button, free agency included */ for (let i = 0; i < argv.length; i++) if (argv[i] === '--set') { sets.push(argv[i + 1]); argv.splice(i, 2); i--; }
  const args = argv.filter(a => !a.startsWith('--')); const N = +(args[0] || 40), seed0 = +(args[1] || 1), engineGames = +(args[2] || 0); const forceTrait = ((argv.find(a => a.startsWith('--trait=')) || '').split('=')[1]) || null; const forceSummer = ((argv.find(a => a.startsWith('--summer=')) || '').split('=')[1]) || null; // R5: --summer=aau|camp|rest|job (every summer); default: a job, a camp, then AAU
  const faPolicy = ((argv.find(a => a.startsWith('--fa=')) || '').split('=')[1]) || 'stars', tradePolicy = ((argv.find(a => a.startsWith('--trade=')) || '').split('=')[1]) || 'up', spend = ((argv.find(a => a.startsWith('--spend=')) || '').split('=')[1]) || 'smart', gearPolicy = ((argv.find(a => a.startsWith('--gear=')) || '').split('=')[1]) || 'buy'; /* F8: --gear=buy|none */ // R7/F7: --fa=stars|money|best|starter|yours (free agency; stars: the best franchise, the goal) · --trade=up|none (F7: ask for a trade when a better franchise would take you) · --spend=smart|none (the agent, the shoe line, lifestyle)
  const schoolPolicy = ((argv.find(a => a.startsWith('--school=')) || '').split('=')[1]) || 'auto'; // V9: --school=student studies under 3.6 (the default: AUTO's Study weeks under 2.3)
  const seasonsOut = argv.includes('--seasons'), policy = ((argv.find(a => a.startsWith('--policy=')) || '').split('=')[1]) || 'typical', edge = +(((argv.find(a => a.startsWith('--edge=')) || '').split('=')[1]) || 2.5); // V6 (Part 2 §1.1): typical (sensible choices, mostly simmed) or great (plays every game well: simmed games count as played, with an OVR edge)
  const parityN = +(((argv.find(a => a.startsWith('--parity=')) || '').split('=')[1]) || 0), menusNever = argv.includes('--menus=never'), weekPolicy = ((argv.find(a => a.startsWith('--week=')) || '').split('=')[1]) || 'auto'; // 2.1 (§1.2): --week=rest: every week a Rest week (the lazy career; AUTO's Study weeks still come); 2.1 (§1.5): --week=nostudy: never a Study week (practice instead; the coach's rule still sends a player under 2.3 who made no plan to study hall) // 2.1 (§1.3): --parity=n plays your first n amateur and n pro games in the engine too
  const hsOnly = argv.includes('--hsOnly'), spread = +(((argv.find(a => a.startsWith('--spread=')) || '').split('=')[1]) || 0); // 2.1 (§2.7): --hsOnly stops every career at Signing Day (the recruiting tables only); --spread=k shifts each career's ratings and their limits by a seeded −k..+k (every star level sampled)
  const recPol = ((argv.find(a => a.startsWith('--rec=')) || '').split('=')[1]) || 'typical';
  const crewArg = ((argv.find(a => a.startsWith('--crew=')) || '').split('=')[1]) || 'auto', crewPol = crewArg.replace(/\+$/, ''), crewUp = crewPol === 'auto' || /\+$/.test(crewArg); // 3.0 (§7.6): --crew=auto (the typical crew: hired when the money covers it, credits spent on upgrades) | none (no crew, no agent) | full (every role open, each hired at Lv3) | <role> (that role alone, hired at Lv3); a + (full+, skills+) spends the credits on upgrades too (without: they stay at Lv3, a level more after two seasons) // 2.1 (§2.3–2.5): --rec=typical (the recruit's actions and commitment: recAuto below) | none (no actions, no commitment: Signing Day decides) | early (commits to the first offer) | late (commits in the senior year, warnings or not)
  const browser = await launch(); const P = await openPage(browser); const page = P.page; const errors = P.errors;
  if (sets.length) console.log('overrides: ' + (await page.evaluate(sets => sets.map(kv => { const [path, v] = kv.split('='); const keys = path.split('.'); let o = CONFIG; for (const k of keys.slice(0, -1)) o = o[k]; o[keys[keys.length - 1]] = JSON.parse(v); return path + ' = ' + v; }).join(', '), sets)));
  const out = await page.evaluate(({ N, seed0, engineGames, forceTrait, forceSummer, faPolicy, tradePolicy, spend, gearPolicy, policy, edge, seasonsOut, schoolPolicy, parityN, menusNever, weekPolicy, recPol, hsOnly, spread, crewPol, crewUp }) => { const great = policy === 'great', student = schoolPolicy === 'student';
    const styles = Object.keys(AM_STYLES); const results = [];
    // 2.1 (§2.3–2.5; 3.0 §1: no film, emails, coach calls or monthly points) the typical recruit: a camp at the best
    // program in reach in the summer, an official visit there from the junior year. The commitment: the #1 school (the
    // dream: the most prestigious program in offer range when the junior year starts) the week it offers, or the best
    // offer at the start of the senior year (sooner when a warning says its last spot is going: half the careers heed
    // it); the #1 offering later is worth a flip; a coach who leaves is followed.
    const recAuto = (a, rec) => { if (recPol === 'none' || a.stage !== 'hs' || a.decision || (a.stageYear || 1) < 2) return; const R = recOf(a), H = rec.hs, yr = a.stageYear || 1, clock = colRecruitClock(a);
      const sc = P => (colInterest(a, P.id) || 0) + 8 * P.stars, live = (a.offers || []).filter(o => !o.pulled && o.pid), has = id => live.some(o => o.pid === id);
      if (yr >= 3 && !H.top1) { const ok = P => (a.gpa || 0) >= recGpaFloor(P), dream = (p, q) => (q.stars - p.stars) || (q.tier - p.tier) || ((colInterest(a, q.id) || 0) - (colInterest(a, p.id) || 0)), T = COLLEGES.filter(P => ok(P) && (colInterest(a, P.id) || 0) >= COLG.stages[2]).sort(dream)[0] || COLLEGES.filter(P => ok(P) && (colInterest(a, P.id) || 0) >= COLG.stages[1]).sort(dream)[0]; if (T) { H.top1 = T.id; H.top1Stars = T.stars; } } /* the #1 school: the dream (the most prestigious program in offer range when the junior year starts) */
      if (!R.commit) { const T = COLLEGES.filter(P => !has(P.id) && (a.gpa || 0) >= recGpaFloor(P) && colSpots(a, P.id).left > 0 && (colInterest(a, P.id) || 0) >= COLG.stages[0]).sort((p, q) => sc(q) - sc(p)), t0 = T.length ? T[0].id : null;
        if (t0 && a.summer && a.summer.pending && (a.cash || 0) >= RCG.camp.cost + 300 && !recWhyNot(a, 'camp', t0) && recCamp(a, t0, amRng(a))) { H.camps = (H.camps || 0) + 1; H.acts = (H.acts || 0) + 1; }
        if (t0 && yr >= 3 && !recWhyNot(a, 'official', t0) && recOfficial(a, t0)) { H.off = (H.off || 0) + 1; H.acts = (H.acts || 0) + 1; } }
      if (yr < 3) return; const best = live.slice().sort((x, y) => (y.tier - x.tier) || (colProg(y.pid).stars - colProg(x.pid).stars) || ((colInterest(a, y.pid) || 0) - (colInterest(a, x.pid) || 0)))[0], heed = (hashString(String(a.seed) + ':heed') % 2) === 0;
      if (!R.commit && best) { const top1 = H.top1 ? live.find(o => o.pid === H.top1) : null, warned = o => recWarned(a, o, 'spot') != null, senior = clock >= 0.5;
        const pick = recPol === 'early' ? best : senior ? (top1 || best) : recPol === 'late' ? null : top1 || (heed && warned(best) ? best : null);
        if (pick && recCommit(a, pick.pid)) { H.commitAt = +clock.toFixed(2); H.commitPid = pick.pid; } }
      else if (R.commit && recPol === 'typical' && H.top1 && R.commit.pid !== H.top1 && has(H.top1)) { if (recCommit(a, H.top1)) H.flips = (H.flips || 0) + 1; }
    };
    // 2.1 (§1.3) --parity=n: the first n games you play in each part of a career (amateur, pro) are also played in the engine
    // with the AI at your controls (the career's own match options, finalized like a played game: Legends View), against the
    // sim's points for you in that matchup (40 draws); the career itself goes on simmed
    const engMine = o => { o = matchOptsFinal(HH.game, Object.assign({}, o), { kind: 'career' }); o.humanTeam = -1; o.headless = true; o.dev = true; const m = new Match(o); m.teams[0].tierShift = 0; let k = 0; while (!m.ended && k < 120 * 600) { simStep(m, STEP); k++; } const P0 = (m.players || []).find(p => p.team === 0), s0 = (P0 && P0.stats) || {}; return { me: m.teams[0].score, opp: m.teams[1].score, len: +(k / 120).toFixed(2), ot: m.overtime || 0, ln: { reb: s0.reb || 0, stl: s0.stl || 0, blk: s0.blk || 0, tpm: s0.tpm || 0 } }; }; /* 3.0 (§0.2): the game's length (s, the tip to the final whistle's beat) for tests/pace.js */ /* the line: your engine box (rebounds, steals, blocks, threes) */
    // 3.0 (§6.1): smart spending in the store: an item for each empty slot (in the store's order) while the money covers
    // it keep times over, then the cheapest next level of what you wear; an ice bath when tired, and a drink and a film
    // session for the playoffs.
    const gearAuto = (c, rec, keep, big) => { if (gearPolicy === 'none') return; const B = holderOf(c), G = gearOf(B);
      for (const id of GEAR_IDS) { const it = gearItem(id); if (G.owned[id] || !gearFreeSlot(G, it)) continue; const p = gearPrice(c, it, 1); if (gearWallet(c) < p * keep) continue; if (!gearBuy(c, id)) continue; rec.gear.spent += p; rec.gear.buys++; }
      for (let k = 0; k < 8; k++) { let best = null; for (const [it] of gearWorn(B)) { const p = gearNextPrice(c, it.id); if (p != null && (!best || p < best.p)) best = { id: it.id, p }; } if (!best || gearWallet(c) < best.p * keep) break; if (!gearUpgrade(c, best.id)) break; rec.gear.spent += best.p; rec.gear.ups++; }
      const cp = gearConsumePrice(c); if (gearWallet(c) >= cp * keep * 4) { const f = B.fatigue || 0; for (const k of (f >= 25 ? ['ice'] : []).concat(big ? ['drink', 'film'] : [])) if (gearConsume(c, k)) { rec.gear.uses++; rec.gear.spent += cp; } }
    };
    const gearLevels = c => gearWorn(holderOf(c)).reduce((n, [it, lv]) => n + lv, 0);
    // 3.0 (§7): the crew (--crew). Hiring in this order while slots last (high school: the skills coach; college: the
    // physio and the strength coach next; the pros: all six), the skills coach in the specialty you've trained most,
    // the best level of three; auto hires when the money covers two seasons of the salary and spends every credit on
    // the lowest level first; full and a single role keep each at Lv3 or more (the table's "at Lv3+"; paid like any crew:
    // one who walks unpaid is hired again). The messages: rest a tight hamstring, match a poacher
    // when the money covers three times the offer (always when forced), push a trade at even odds or better.
    const CREW_ORDER = ['skills', 'physio', 'strength', 'mental', 'scout', 'agent'], crewForce = crewPol !== 'auto' && crewPol !== 'none';
    const crewWants = role => crewPol === 'auto' || crewPol === 'full' || crewPol === role;
    const crewSpecPick = (c, L) => { const B = holderOf(c), N = (B && B.trainN) || {}, sc = M => (N[M.spec] || 0) * 10 + M.lv; return L.slice().sort((x, y) => sc(y) - sc(x))[0]; };
    const crewAuto = (c, rec) => { const B = holderOf(c); if (!B) return; const R = rec.crew;
      for (const M of crewList(B)) if (!crewWants(M.role)) crewLetGo(c, M.role); if (crewPol === 'none') return;
      for (const role of CREW_ORDER) { if (!crewWants(role) || !crewCanHire(c, role)) continue; const L = crewCandidates(c, role); if (!L.length) continue; const pick = role === 'skills' ? crewSpecPick(c, L) : L[L.length - 1];
        if (!crewForce && gearWallet(c) < crewPay(c, pick) * 2) continue; if (crewHire(c, pick)) { R.hires++; const M = crewMember(B, role); if (crewForce && M.lv < 3) { M.lv = 3; crewSync(c); } } }
      for (let k = 0; k < 12 && crewUp; k++) { const L = crewList(B).filter(M => crewUpCost(M) != null).sort((x, y) => x.lv - y.lv || CREW_ORDER.indexOf(x.role) - CREW_ORDER.indexOf(y.role)), M = L[0]; if (!M || crewCredits(c) < crewUpCost(M) || !crewUpgrade(c, M.role)) break; R.ups++; }
    };
    const crewMsg = (c, e, rec) => { const R = rec.crew; if (!e || !/^crew/.test(e.kind)) return false; R.msgs[e.kind] = (R.msgs[e.kind] || 0) + 1;
      if (e.kind === 'crewtight') crewTightAnswer(c, e, !(isPro(c) ? c.phase === 'playoffs' : !!(c.league && c.league.playoffs))); /* rest a regular-season week, play through it in the playoffs */ else if (e.kind === 'crewpoach') { const yes = crewForce || gearWallet(c) >= (e.offer || 0) * 3; crewPoachAnswer(c, e, yes); if (yes) R.matched++; else R.lost++; } else if (e.kind === 'crewtrade') { const yes = (e.odds || 0) >= 0.5; const r = crewTradeAnswer(c, e, yes); if (r) R.talkTrades++; }
      return true; };
    const crewEnd = (B, rec) => { const R = rec.crew, K = B && B.crew; if (!K) return; R.paid = K.paidAll || 0; R.levels = crewList(B).map(M => M.role + crewEffLv(M)).join(' '); R.n = crewCount(B); R.credits = { all: B.creditsEarned || 0, wins: B.creditsWins || 0, tn: B.creditsTn || 0 };
      const tot = k => (K.hist || []).reduce((s, h) => s + ((h.tot && h.tot[k]) || 0), 0) + Object.values(K.sea || {}).reduce((s, x) => s + ((x && x[k]) || 0), 0); R.inj = tot('inj'); R.days = tot('days'); R.agentMoney = (K.hist || []).filter(h => h.role === 'agent').reduce((s, h) => s + ((h.tot && h.tot.money) || 0), 0) + (((K.sea || {}).agent || {}).money || 0); R.xp = tot('xp'); R.grades = (K.hist || []).map(h => h.grade).join(''); };
    const fakeBox = (c, g) => { const rng = careerRng(c); const E = great ? edge : 0, me0 = c.players[c.meId], r0 = me0.r; if (E) me0.r = Object.fromEntries(Object.entries(r0).map(([k, v]) => [k, Math.min(CR.ratingMax, v + E)])); let r; try { r = simBox(c, g.h, g.a, rng); } finally { me0.r = r0; } /* V6: the great policy plays with an edge */ const toP = id => { const s = r.box[id]; return Object.assign({ name: c.players[id].name }, makeStats(), { pts: s.pts, fgm: s.fgm, fga: s.fga, tpm: s.tpm, tpa: s.tpa, reb: s.reb, stl: s.stl, blk: s.blk, to: s.to, dunkM: s.dunk, dunkA: s.dunk, layM: Math.max(0, Math.round((s.fgm - s.tpm - s.dunk) * 0.5)), layA: Math.max(0, Math.round((s.fga - s.tpa - s.dunk) * 0.5)), ankles: s.ank, moves: 20 }); }; const meH = g.h === c.meId; const opp = meH ? g.a : g.h; return { teams: [{ score: meH ? r.hs : r.as, players: [toP(c.meId)] }, { score: meH ? r.as : r.hs, players: [toP(opp)] }], overtime: r.ot }; };
    for (let n = 0; n < N; n++) {
      const save = defaultSave(); const style = styles[n % styles.length]; const inv = []; const ages = {}; let guard = 0, engineUsed = 0;
      const a = amCreate(save, { name: 'Sim Player', look: PRESET_LOOKS[n % 16], number: 7, style, seed: (seed0 * 7919 + n * 104729) >>> 0, seasonLength: 11, gameLength: 120, traits: forceTrait && forceTrait !== 'none' ? [forceTrait] : null }); if (forceTrait === 'none') { a.tr = null; a.caps = capsFrom(a.genes, a, a.r); } // V3: --trait=none: a career without traits (the trait balance test's baseline)
      if (spread) { const off = Math.round(((hashString(String(a.seed) + ':spread') % 2001) / 1000 - 1) * spread); for (const k of RATING_KEYS) { a.r[k] = clamp(a.r[k] + off, CR.ratingMin, CR.ratingMax); a.caps[k] = clamp(a.caps[k] + off, a.r[k], CR.ratingMax); } } /* 2.1: --spread */
      if (great) a.simEdge = edge; // V6: the great policy
      const rec = { crew: { hires: 0, ups: 0, topup: 0, matched: 0, lost: 0, talkTrades: 0, msgs: {}, proPay: [], proInc: [] }, parity: { am: [], pro: [] }, style, heightFinal: a.heightFinal, bloom: a.bloom, ovr: {}, pick: null, draftAge: null, college: null, tier: null, proSeasons: 0, titles: 0, mvps: 0, legacy: 0, hof: false, peak: 0, peakAge: 0, retireAge: null, amTitles: 0, h14: a.height, stuck: false, injuries: 0, plans: {}, fat: [], msgs: 0, fameSum: 0, fameN: 0, benchAm: 0, benchPro: 0, benchBy: {}, challenges: 0, trustDraft: 0, hs: { jv: 0, fresh: 0, callups: 0, districts: 0, state: 0, study: 0, inel: 0, gpaMin: 4, stars: 0, nat: 0, top: -1, summers: {} }, col: { seasons: 0, nat: 0, natW: 0, ff: 0, champ: 0, confT: 0, missed: 0, nilOffers: 0, nilDeals: 0, nil: 0, portal: 0, transfer: 0, agent: false, mock: [], study: 0, inel: 0 } }; rec.gear = { spent: 0, buys: 0, ups: 0, uses: 0, atPro: 0, end: 0 }; rec.cash = { hsEnd: null, colEnd: null, at25: null, at30: null, retire: null, left: null, earned: 0, upkeep: 0, life: 0 }; // F8
      const note = (age, ovr) => { if (ages[age] == null) ages[age] = ovr; if (ovr > rec.peak) { rec.peak = ovr; rec.peakAge = age; } };
      // amateur years
      while (!a.handedOff && guard++ < 400) { if (hsOnly && a.stage !== 'hs') break;
        for (const e of a.events) { if (e.kind === 'dialog') { const fi = e.rec && e.rec.carousel && recPol !== 'none' ? (e.choice || []).findIndex(x => x.rec && x.rec.car === 'follow') : -1; if (fi >= 0) msgChoose(a, e, fi); else msgAutoChoose(a, e); if (e.rec && e.rec.carousel) rec.hs.car = fi >= 0 ? 'follow' : 'stay'; rec.msgs++; } /* 2.1 (§2.5): the coaching carousel: follow the coach */ else if (e.kind === 'nil') { rec.col.nilOffers++; colNilAnswer(a, e, (e.apps || 0) <= 1); if (e.accepted) rec.col.nilDeals++; } else if (e.kind === 'agent') { colAgentAnswer(a, e, crewWants('agent') && (crewPol === 'agent' || crewCount(holderOf(a)) < crewSlots(a))); rec.col.agent = !!a.agent; } else crewMsg(a, e, rec); } a.events.length = 0; note(a.age, amOvr(a)); // R6: NIL deals with at most one appearance; always an agent
        if (a.stage === 'combine' && ovsNoOffers(a)) { rec.ovs = (rec.ovs || 0) + 1; ovsSign(a, ovsOffers(a)[0]); continue; } /* 3.0 (§4.3): no PBL offers: a season abroad */
        if (a.stage === 'combine') { rec.sch = { sch: a.scholarship || 'none', tuition: a.tuitionPaid || 0, loan: a.loan || 0, academic: !!(a.program && a.program.academic), years: (a.degree && a.degree.years) || 0, gpa: a.gpa, probation: a.scholarship === 'lost', col: !!a.college, commitAcademic: !!rec.commitAcademic }; /* V9 */ rec.col.nil = a.nilEarned || 0; rec.trustDraft = trustOf(a); rec.fame = a.fame || 0; rec.dscore = +amDraftScore(a).toFixed(1); rec.draftAge = a.age; rec.college = a.college || '(none)'; rec.tier = a.collegeTier; rec.amTitles = a.titles; try { rec.offer = Math.max(...proEntryOffers(a).offers.map(o => o.stars || 1)); } catch (e) { rec.offer = null; } /* V6: the best first pro offer */ createCareerFromAmateur(save, a); if (great && save.career) save.career.me.simEdge = edge; if (forceTrait === 'none' && save.career) { save.career.me.tr = null; const me0 = meOf(save.career); me0.caps = capsFrom(save.career.me.genes, save.career.me, me0.r); } break; }
        if (a.decision) { const d = a.decision; if (d.kind === 'portal') { rec.col.portal++; const o = d.offers.find(x => x.tier < (a.collegeTier || 0)) || null; if (o) rec.col.transfer++; colPortalChoose(a, o); continue; } /* R6: the portal: a step down that starts you, else stay */ if (d.kind === 'college') { const skip = d.offers.find(o => o.draft); const proj = amPickFrom(amDraftScore(a)); const byTier = d.offers.filter(o => !o.draft).sort((x, y) => (y.tier - x.tier) || ((y.academic ? 1 : 0) - (x.academic ? 1 : 0))); /* V9: an elite academic program over its tier's others */ const play = great ? byTier.filter(o => o.tier <= 2)[0] : null; /* V6: the great policy goes where it plays (a power program over a blue blood's bench) */ const cmO = d.signing && d.committed ? byTier.find(o => o.pid === d.committed) : null, pick = skip && proj <= 10 ? skip : play || cmO || byTier[0] || (d.signing ? null : d.offers[0]); if (a.prep && d.signing) rec.hs.prep = { bonus: !!a.prep.bonus, offers: byTier.length }; if (!pick) { const road = recSimSign(a); rec.hs.road = (rec.hs.road ? rec.hs.road + '+' : '') + (road || 'none'); if (!road) { rec.stuck = true; break; } continue; } rec.hs.road = rec.hs.road ? rec.hs.road + '+' + (pick.draft ? 'pro' : 'sign') : (pick.draft ? 'pro' : 'sign'); rec.commitAcademic = !!pick.academic; amChooseCollege(a, pick); } else amDeclare(a, amPickFrom(amDraftScore(a)) <= 30 || a.stageYear >= 3); continue; }
        if (a.summer && a.summer.pending) { recAuto(a, rec); const k = forceSummer || ['job', 'camp', 'aau'][(a.summer.year || 1) - 1] || 'rest'; const got = hsSummerChoose(a, k); if (got) rec.hs.summers[got.kind] = (rec.hs.summers[got.kind] || 0) + 1; continue; } // R5: the summer
        if (a.tryout && a.tryout.step !== 'done') { const y = a.stageYear; hsSimTryout(a); if (y === 1 && a.squad === 'varsity') rec.hs.fresh++; if (a.squad === 'varsity' && rec.varsityYear == null) rec.varsityYear = y; continue; } // R5: tryouts (simmed); V6: the year you made varsity
        if (a.stage === 'hs') { rec.hs.gpaMin = Math.min(rec.hs.gpaMin, a.gpa); if (a.squad === 'varsity' && rec.varsityYear == null) rec.varsityYear = a.stageYear; } // V6: the year you first played varsity (a tryout, a call-up or a junior's place)
        recAuto(a, rec); /* 2.1 (§2.3–2.5) */ crewAuto(a, rec); /* 3.0 (§7) */ { const g0 = amNext(a); gearAuto(a, rec, 2, !!(g0 && g0.playoff)); } /* F8; V11 */ if (a.stage !== rec.cash.stage0) { if (rec.cash.stage0 === 'hs') rec.cash.hsEnd = a.cash || 0; rec.cash.stage0 = a.stage; } /* V11: cash by stage */ { const g = amNext(a); if (g && g.opp && !(a.wk && a.wk.done)) { if (a.fatigue >= 40 || a.injury || weekPolicy === 'rest') amRest(a); else if ((a.stage === 'hs' || a.stage === 'college') && weekPolicy !== 'nostudy' && (a.gpa < (student ? 3.6 : HS.autoStudyAt) || (recPol !== 'none' && a.stage === 'hs' && (a.stageYear || 1) >= 2 && a.gpa < CONFIG.school.gpaReq.blue + 0.05 && hsStars(recProjRank(a)) >= 4))) { /* 2.1: a blue-chip recruit studies for the blue bloods' line */ wkStudy(a); if (a.stage === 'hs') rec.hs.study++; else rec.col.study++; } /* V9: AUTO's Study weeks, both levels */ else { if (g.playoff || amIsBoss(a, g.opp)) wkScouted(a, g.opp.id); /* 3.0: the scouting report before the playoffs and the Boss (Film Junkie's deed) */ amPractice(a, null, amSessionXp(a)); } } } // the week (3.0 §3: the standing plan, Auto): rest when tired, a depth-chart challenge when benched (R4), the report before big games, else the plan's training
        const wasHs = a.stage === 'hs', sq = a.squad, colL = a.stage === 'college' ? a.league : null; const stg0 = a.stage, yr0 = a.stageYear, top0 = !!a.team && isStarter(a); if (parityN && (a.stage === 'hs' || a.stage === 'college') && rec.parity.am.filter(x => x.st === a.stage).length < (a.stage === 'hs' ? Math.ceil(parityN / 2) : Math.floor(parityN / 2))) { const g = amNext(a); if (g && g.opp && playsThisWeek(a) && !(a.ineligible > 0)) { /* half of n in high school, half in college */ const SS = amSimSides(a, g), R2 = new RNG(4242 + rec.parity.am.length * 7 + n * 131); let sm = 0, so = 0, sw = 0; const sb = { reb: 0, stl: 0, blk: 0, tpm: 0 }; for (let k = 0; k < 40; k++) { const sc = amSimPts(R2, SS, a, g.opp); sm += sc[0]; so += sc[1]; if (sc[0] > sc[1]) sw++; const ln = amSimLine(a, R2, sc[0], SS.eff, gameScale(a.stage)); for (const q in sb) sb[q] += ln[q] / 40; } const e = engMine(amMatchOpts(HH.game, a, g.opp, !!g.playoff)); const len = gameScale('pro'), ea = attrsOfEff(SS.eff), eb = attrsOfEff(effRatings(g.opp.r, g.opp.height)); rec.parity.am.push({ len: e.len, ot: e.ot, st: a.stage, sty: style, eng: e.me, engOpp: e.opp, sim: sm / 40, simOpp: so / 40, simW: sw / 40, d: +(SS.a - SS.b).toFixed(1), mdl: linPtsAttr(ea, eb, a.height, g.opp.height) * len, mdlOpp: linPtsAttr(eb, ea, g.opp.height, a.height) * len, sa: SS.a, sb: SS.b, A: ea, B: eb, ha: a.height, hb: g.opp.height, bx: { e: e.ln, s: sb } }); } } /* 2.1 (§1.3) */ const r = amSimGame(a); if (!r) { inv.push('amateur: no game and no decision, stage ' + a.stage + ' year ' + a.stageYear); break; } if (stg0 === 'college' && top0 && !r.bench && rec.colStart == null) rec.colStart = yr0; /* V6: the college year you first held the starting spot (not a spot start) */ if (forceTrait && forceTrait !== 'none' && traitsOf(a)) { const Lv = trLvOf(a, forceTrait); if (Lv >= 2 && rec.ageS == null) rec.ageS = a.age; if (Lv >= 3 && rec.ageG == null) rec.ageG = a.age; } /* V3: when the trait levelled up */ if (r.bench) rec.benchAm++; if (r && r.ll) rec.llAm = (rec.llAm || 0) + 1; if (r.ineligible) { if (stg0 === 'college') rec.col.inel++; else rec.hs.inel++; } /* V9: by level */; if (r.note === 'Called up to varsity!') rec.hs.callups++;
        if (wasHs && a.decision && a.decision.kind === 'college' && !rec.hs.nat) { rec.hs.stars = a.recruit ? a.recruit.stars : 0; rec.hs.nat = a.recruit ? a.recruit.nat : 0; rec.hs.top = Math.max(...a.decision.offers.filter(o => !o.draft).map(o => o.tier)); rec.hs.districts = a.districts || 0; rec.hs.state = a.titles; rec.hs.jv = a.log.filter(e => e.squad === 'jv').length; /* 2.1 (§2.7): offers received (pulled ones too), live at Signing Day, conditional fallbacks */ rec.hs.offers = (a.offers || []).filter(o => o.pid || o.t != null || o.when).length; rec.hs.live = (a.offers || []).filter(o => !o.pulled).length; rec.hs.pulled = (a.offers || []).filter(o => o.pulled).length; rec.hs.pullWhy = (a.offers || []).filter(o => o.pulled).map(o => o.why || 'gpa'); rec.hs.gpa = a.gpa; rec.hs.acad = (a.offers || []).filter(o => o.cond).map(o => [!!o.pulled, a.gpa]); rec.hs.rk = a.rec && a.rec.rk ? JSON.parse(JSON.stringify(a.rec.rk)) : null; rec.hs.offT = (a.offers || []).map(o => o.t); { const R = a.rec || {}; rec.hs.lost1 = rec.hs.top1 ? !(a.offers || []).some(o => o.pid === rec.hs.top1 && !o.pulled) : null; if (rec.hs.top1) { const S1 = colSpots(a, rec.hs.top1, 1), o1 = (a.offers || []).find(o => o.pid === rec.hs.top1); rec.hs.dbg1 = { p: rec.hs.top1, tot: S1.total, rs: S1.recruits.map(x => x.at.toFixed(2) + x.status[0]), off: o1 ? [+(o1.at || 0).toFixed(2), o1.pulled ? o1.why + '@' + (+o1.pulledAt).toFixed(2) : 'live'] : 'none', cm: rec.hs.commitAt, cmP: rec.hs.commitPid, int: colInterest(a, rec.hs.top1) }; } rec.hs.committed = !!R.commit; rec.hs.rflips = R.flips || 0; rec.hs.offN = (R.off || []).length; rec.hs.carF = !!(R.carousel && R.carousel.fired) || !!rec.hs.car; rec.hs.testD = R.test ? R.test.d : null; rec.hs.byTier = [0, 1, 2, 3].map(t => (a.offers || []).filter(o => o.tier === t && !o.academic).length).concat([(a.offers || []).filter(o => o.academic).length]); rec.hs.held = Object.keys(R.hold || {}).filter(id => (a.offers || []).some(o => o.pid === id && !o.pulled)).length; /* X9 (3.0 §8): held through Signing Day */ try { const Pp = hsRecruitParts(a); rec.hs.parts = { rank: +Pp.rank.toFixed(2), rankV: Pp.rankV, ppg: +Pp.ppg.toFixed(2), exposure: Pp.exposure }; } catch (e) { rec.hs.parts = null; } } }
        if (colL && colL.done && colL.format === 'conf' && !colL.counted) { colL.counted = true; const C = rec.col; C.seasons++; if (colL.inField) { C.nat++; C.natW += colL.games.filter(x => x.po >= 31 && x.won).length; } if (colL.finalFour) C.ff++; if (colL.missed) C.missed++; if (colL.confTourney) C.confT++; if (colL.playoffs && colL.playoffs.champion === 'me' && colL.inField) C.champ++; C.mock.push(amPickFrom(amDraftScore(a))); (C.log || (C.log = [])).push([a.collegeTier, colL.benchWeeks || 0, colL.all.w + colL.all.l, colL.inField ? 1 : 0, colL.natRank || 0, colL.all.w, colL.confTourney ? 1 : 0]); } // R6
        if (!(a.fatigue >= 0 && a.fatigue <= 100)) inv.push('amateur fatigue out of range ' + a.fatigue); if (r && r.wk) { if (r.wk.injury) rec.injuries++; rec.plans[r.wk.plan] = (rec.plans[r.wk.plan] || 0) + 1; }
      }
      if (hsOnly) { results.push(rec); continue; } /* 2.1: --hsOnly */
      const c = save.career; if (!c) { rec.stuck = true; rec.inv = inv.concat(['never reached the pros']); results.push(rec); continue; }
      rec.pro = { fa: {}, trades: 0, shoe: 0, spent: 0, life: 0, worth: 0, foundation: 0, academy: false, stake: false };
      const moneyPolicy = () => { const M = c.me; if (spend === 'none') { if (M.agent) proFireAgent(c); return; } const cash = M.money; if (!M.agent && crewWants('agent') && crewPol !== 'none') proHireAgent(c); else if (M.agent && !crewWants('agent')) proFireAgent(c); /* 3.0 (§7): by the crew policy */ /* the agent pays for itself (3.0: no staff menu; your crew is §7) */
        if (proShoeOpen(c) && cash >= PR.shoeCost * 2 && proShoeLaunch(c)) rec.pro.shoe = 1; for (const [id, need] of [['car', 1e6], ['sportscar', 5e6], ['house', 1e7], ['mansion', 3e7]]) if (!(M.lifestyle || {})[id] && cash >= need && proBuy(c, id)) rec.pro.life++; for (const [id, keep] of [['family', 2], ['facility', 1.4], ['stake', 1.5], ['charity', 4], ['sneaker', 3], ['arena', 1.5]]) if ((M.money || 0) >= bigCost(c, id) * keep && bigBuy(c, id)) { rec.pro.big = rec.pro.big || {}; rec.pro.big[id] = (rec.pro.big[id] || 0) + 1; } }; /* V11: lifestyle pays every week (hype, confidence, fame) and costs upkeep: the sports car at $5M in the bank, the mansion at $30M (R7: $80M) */
      moneyPolicy();
      const me = meOf(c); rec.crew.p0 = { paid: (c.me.crew && c.me.crew.paidAll) || 0, earned: c.me.earned || 0 }; rec.cash.colEnd = c.me.money || 0; /* V11: cash at the pro start */ rec.pick = me.draftPick; rec.fr = { first: frMine(c), best: frMine(c), age: {}, tradesUp: 0, seasons: [] }; rec.gear.atPro = gearLevels(c); for (let s2 = 1; s2 <= frMine(c); s2++) rec.fr.age[s2] = me.age; note(me.age, recOvr(me)); // F7
      while (c.phase !== 'retired' && guard++ < 4000) {
        if (c.phase === 'regular' || c.phase === 'playoffs') {
          const g = userGame(c); if (!g) { inv.push('no user game in phase ' + c.phase + ' week ' + c.week); break; }
          if (c.phase === 'regular' && c.week === 0 && !rec.fr.seasons[c.season]) { rec.fr.seasons[c.season] = frMine(c); if (tradePolicy === 'up' && proTradeOpen(c) && frCap(frValue(c)) > frMine(c)) { c.me.tradeSeason = c.season; proTrade(c); rec.fr.tradesUp++; } const s1 = frMine(c); if (s1 >= 5 && rec.fr.best < 5) rec.fr.via5 = rec.fr.lastClub === meOf(c).club ? 'rise' : 'move'; rec.fr.lastClub = meOf(c).club; rec.fr.best = Math.max(rec.fr.best, s1); if (seasonsOut) { const Sx = id => strengthOf(c.players[id], c) + LG.starEdge * simEdgeStars(c, id), arr = c.active.filter(id => c.players[id]).map(id => [id, Sx(id)]).sort((a, b) => b[1] - a[1]); (rec.sx || (rec.sx = {}))[c.season] = { sr: arr.findIndex(x => x[0] === c.meId) + 1, gap: +(Sx(c.meId) - arr.find(x => x[0] !== c.meId)[1]).toFixed(2), top: arr.map(x => +x[1].toFixed(1)) }; } /* V12: --seasons: your team's strength rank at the season's start */ for (let s2 = 1; s2 <= s1; s2++) if (rec.fr.age[s2] == null) rec.fr.age[s2] = meOf(c).age; { const cnt = {}; for (const id of c.active) cnt[c.players[id].club] = (cnt[c.players[id].club] || 0) + 1; if (Object.keys(cnt).length !== TEAMS.length || Object.values(cnt).some(v => v !== 1)) inv.push('franchises ' + JSON.stringify(cnt)); } } // F7: move up; one league player per franchise
          crewAuto(c, rec); /* 3.0 (§7) */ gearAuto(c, rec, 4, !!g.playoff); /* F8; V11 */ if (!(c.me.wk && c.me.wk.done)) { if (c.me.fatigue >= 40 || c.me.injury || weekPolicy === 'rest') proRest(c); else { if (g.playoff || proIsBoss(c, opponentOf(c, g))) wkScouted(c.me, opponentOf(c, g)); /* 3.0: the report (Film Junkie's deed) */ proPractice(c, null); } } // the week (3.0 §3: the standing plan): rest when tired, a depth-chart challenge when benched (R4), the report before big games, else the plan's training
          rec.plans[c.me.wk.done] = (rec.plans[c.me.wk.done] || 0) + 1; rec.fat.push(c.me.fatigue);
          if (c.allStar && c.allStar.invited && !c.allStar.done) finishAllStar(c, 12);
          proStartGame(c); if (parityN && rec.parity.pro.length < parityN && playsThisWeek(c)) { const R2 = new RNG(9191 + rec.parity.pro.length * 7 + n * 131), oid = opponentOf(c, g); let sm = 0, so = 0, sw = 0; const sb = { reb: 0, stl: 0, blk: 0, tpm: 0 }; for (let k = 0; k < 40; k++) { const x = simBox(c, g.h, g.a, R2); sm += x.box[c.meId].pts; so += x.box[oid].pts; if (x.box[c.meId].pts > x.box[oid].pts) sw++; for (const q in sb) sb[q] += (x.box[c.meId][q] || 0) / 40; } const e = engMine(careerMatchOpts(c, save, g, true)); rec.parity.pro.push({ len: e.len, ot: e.ot, lg: +(linPts(meOf(c), c.players[oid], c, 0, 0) * gameScale('pro')).toFixed(3), lgOpp: +(linPts(c.players[oid], meOf(c), c, 0, 0) * gameScale('pro')).toFixed(3), st: 'pro', sty: style, eng: e.me, engOpp: e.opp, sim: sm / 40, simOpp: so / 40, simW: sw / 40, d: +(strengthOf(meOf(c), c) - strengthOf(c.players[oid], c)).toFixed(1), A: effAttrs(meOf(c), c), B: effAttrs(c.players[oid], c), ha: meOf(c).h, hb: c.players[oid].h, bx: { e: e.ln, s: sb } }); } /* 2.1 (§1.3) */ const res = !playsThisWeek(c) /* V5: a spot start plays */ ? (rec.benchPro++, (rec.benchBy[c.season] = (rec.benchBy[c.season] || 0) + 1), proSimBenchGame(c)) : engineUsed < engineGames ? (engineUsed++, simUserGame(save)) : careerAfterGame(save, fakeBox(c, g), 0, !great); /* V6: the great policy's games count as played */
          if (forceTrait && forceTrait !== 'none' && traitsOf(c.me)) { const Lv = trLvOf(c.me, forceTrait); if (Lv >= 2 && rec.ageS == null) rec.ageS = meOf(c).age; if (Lv >= 3 && rec.ageG == null) rec.ageG = meOf(c).age; } /* V3 */
          if (!res) { inv.push('careerAfterGame returned null'); break; } if (res.wk && res.wk.injury) rec.injuries++; rec.fameSum += c.me.fame || 0; rec.fameN++; for (const e of (c.events || []).slice()) { if (!(c.events || []).includes(e)) continue; /* (2.1: a story card that stepped back for a decision comes again later: the game shows it then) */ if (crewMsg(c, e, rec)) continue; if (e.kind === 'dialog') { msgAutoChoose(c, e); rec.msgs++; } else if (e.kind === 'tradeoffer') { proTradeOfferAnswer(c, e, true); rec.fr.calls = (rec.fr.calls || 0) + 1; } else if (e.kind === 'trade') { const yes = e.why === 'bench' || menusNever; /* (the card's default is the request) */ proTradeAnswer(c, e, yes); if (yes) rec.pro.trades++; } else if (e.kind === 'shoe') { if (spend !== 'none' && c.me.money >= PR.shoeCost * 2) { proShoeAnswer(c, e, true); if (c.me.shoe) rec.pro.shoe = 1; } } } if (c.events) c.events.length = 0; while (c.me.offers && c.me.offers.length) acceptEndorsement(c, 0); /* R8: take every sponsor deal (the simulator never did: hype's endorsement money was invisible) */ rec.pro.spent += (res.staffCost || 0); rec.cash.upkeep += (res.upkeep || 0); /* V11: lifestyle's upkeep */ rec.pro.endorse = (rec.pro.endorse || 0) + (res.endorse || 0); /* R8: sponsor money */ // R7: trade requests when benched, the shoe line
          for (const id of c.active) { const p = c.players[id]; for (const k of RATING_KEYS) if (!isFinite(p.r[k]) || p.r[k] < CR.ratingMin - 0.01 || p.r[k] > CR.ratingMax + 0.01) inv.push('rating out of range ' + p.name + ' ' + k + ' ' + p.r[k]); }
          if (c.active.length !== CR.leagueSize) inv.push('league size ' + c.active.length);
          if (!isFinite(c.me.money)) inv.push('money NaN');
        } else if (c.phase === 'offseason') {
          if (c.playoffs && c.playoffs.champion === c.meId && !rec['t' + c.season]) { rec['t' + c.season] = 1; if (isStarter(c)) rec.titleStart = (rec.titleStart || 0) + 1; else rec.titleBench = (rec.titleBench || 0) + 1; rec.titleStars = rec.titleStars || [0, 0, 0, 0, 0, 0]; rec.titleStars[frMine(c)]++; } // V6: a title as the starter or from the bench
          rec.proSeasons++; note(me.age, recOvr(me)); if (seasonsOut) (rec.ps || (rec.ps = [])).push({ a: me.age, o: recOvr(me), st: frMine(c), st0: rec.fr.seasons[c.season] || 0, rk: standingsSorted(c).indexOf(c.meId) + 1, po: c.me.playoffResult || null, t: c.playoffs && c.playoffs.champion === c.meId ? 1 : 0, sv: isStarter(c) ? 1 : 0, b: c.me.benchSeason || 0, cl: me.club, sx: rec.sx && rec.sx[c.season] }); /* V6: --seasons (a diagnostic): each pro season */ { const o = c.active.filter(id => id !== c.meId).map(id => recOvr(c.players[id])).sort((x, y) => y - x); (rec.lg || (rec.lg = [])).push([+(o.reduce((x, y) => x + y, 0) / o.length).toFixed(1), o[0], o[2]]); }
          if (c.offseason && c.offseason.v === 2) { /* 2.1 (§3.3, W6): the seven steps; free agency day by day: the policy's offer once nothing better is still coming (it waits for it) */
            const score = o => faPolicy === 'money' ? o.salary : faPolicy === 'stars' ? (o.stars || 0) * 1e9 + o.salary : faPolicy === 'default' ? 0 : (o.kind === (faPolicy === 'big' ? 'best' : faPolicy) ? 1e12 : 0) + o.salary;
            const pickFa = (live) => { if (faPolicy === 'default') return lgUserFaDefault(c); const all = c.offseason.fa.offers.filter(o => !o.gone && !o.signed); if (!live.length) return -1; const bi = live.reduce((b, o, i) => score(o) > score(live[b]) ? i : b, 0), best = Math.max(...all.map(score)); return score(live[bi]) >= best || live[bi].exp <= (c.offseason.day | 0) ? bi : -1; };
            const sv = c.me.contract && c.me.contract.salary; lgOffseasonAuto(c, { fa: pickFa, rebuild: true }); const Sg = c.offseason.fa && c.offseason.fa.signed; if (Sg) rec.pro.fa[Sg.kind] = (rec.pro.fa[Sg.kind] || 0) + 1; if (c.offseason.rebuild && c.offseason.rebuild.went) rec.pro.rebuildTrades = (rec.pro.rebuildTrades || 0) + 1; rec.pro.counters = (rec.pro.counters || 0) + ((c.offseason.fa && c.offseason.fa.counters) || 0); for (const e of (c.events || []).slice()) if (e.kind === 'rebuild' && !e.answered) proRebuildAnswer(c, e, true);
          } else {
          offseasonProgression(c); offseasonMoves(c); for (const e of (c.events || []).slice()) if (e.kind === 'rebuild' && !e.answered) { proRebuildAnswer(c, e, true); rec.pro.rebuildTrades = (rec.pro.rebuildTrades || 0) + 1; } /* V12: a rebuilding owner's offer: go to the contender */ const offers = offseasonContract(c); if (offers) { const k = faPolicy === 'default' ? faDefaultIdx(c, offers) : faPolicy === 'money' ? offers.findIndex(x => x.salary === Math.max(...offers.map(q => q.salary))) : faPolicy === 'stars' ? offers.reduce((bi, x, i) => ((x.stars || 0) > (offers[bi].stars || 0) || ((x.stars || 0) === (offers[bi].stars || 0) && x.salary > offers[bi].salary)) ? i : bi, 0) : Math.max(0, offers.findIndex(x => x.kind === (faPolicy === 'big' ? 'best' : faPolicy))); rec.pro.fa[offers[k].kind] = (rec.pro.fa[offers[k].kind] || 0) + 1; acceptContract(c, k, offers[k].maxYears >= 4 ? 4 : offers[k].maxYears, offers[k].kind === 'starter' || offers[k].promised); } // R7: the free-agency policy
          }
          note(me.age, recOvr(me));
          if (mustRetire(c) || (canRetire(c) && me.age >= 34 && recOvr(me) < 68)) { rec.retireAge = me.age; rec.gear.end = gearLevels(c); retireCareer(save);
            rec.recBest = c.me.recBook ? c.me.recBook.best : null; /* V8: the records book's bests by level */ rec.cash.retire = c.me.money || 0; rec.cash.earned = c.me.earned || 0; const worth = proNetWorth(c); const E = proEpilogue(save, { stake: worth >= PR.stakeCost * 1.2, academy: worth >= PR.academyCost * 3, foundation: PR.foundationMax }); rec.pro.worth = E.worth; rec.cash.left = E.left; /* V11: what's left after the endings */ rec.pro.foundation = E.foundation; rec.pro.academy = E.academy; rec.pro.stake = E.stake; break; } // R7: the epilogue
          { const K = c.me.crew || {}, R = rec.crew, p0 = R.p0 || { paid: 0, earned: 0 }; R.proPay.push((K.paidAll || 0) - p0.paid); R.proInc.push((c.me.earned || 0) - p0.earned); R.p0 = { paid: K.paidAll || 0, earned: c.me.earned || 0 }; } /* 3.0 (§7.6): the season's crew pay and income */
          newSeason(c); moneyPolicy(); { const ag = meOf(c).age; if (ag === 25 && rec.cash.at25 == null) rec.cash.at25 = c.me.money || 0; if (ag === 30 && rec.cash.at30 == null) rec.cash.at30 = c.me.money || 0; } /* V11: cash by stage */
        } else { inv.push('unknown phase ' + c.phase); break; }
      }
      if (guard >= 4000) { rec.stuck = true; inv.push('guard hit'); }
      { const best = (L0, st) => { const v = (L0 || []).filter(l => !st || l.stage === st).map(l => l.prk || 0).filter(r => r > 0); return v.length ? Math.min(...v) : 0; }, AL = (c.amateur && c.amateur.log) || a.log || []; rec.rk = { hs: best(AL, 'hs'), col: best(AL, 'college'), pro: best(c.me.seasonLog), top3: (c.me.seasonLog || []).filter(l => l.prk > 0 && l.prk <= 3).length }; } /* X4 (§4.1): your best ranks */
      crewEnd(c.me, rec); rec.goals = Object.assign({}, c.me.goals || {}); const L = c.legacy || legacyOf(c); rec.L = { titles: L.titles, mvps: L.mvps, allL: L.allL, seasons: L.seasons, pts: Math.round((L.ptsN != null ? L.ptsN : L.pts) / CR.legacy.ptsPer) /* F5: the legacy counts points per the old game length */, ppg: +(L.ppg || 0).toFixed(1) }; rec.titles = L.titles; rec.mvps = L.mvps; { const RD = roadOf(c); rec.v12 = { fmvp: L.fmvp || 0, run: c.me.titleBest || 0, jersey: (c.me.jerseys || []).length, franchise: !!(RD && RD.done && RD.done.franchise), rebuild: rec.pro.rebuildTrades || 0 }; } /* V12 */ rec.trLv = forceTrait && forceTrait !== 'none' && traitsOf(c.me) ? trLvOf(c.me, forceTrait) : 0; rec.lvAt = traitsOf(c.me) && c.me.tr.deeds ? Object.assign({}, c.me.tr.deeds) : null; rec.deedTot = forceTrait && TR.list[forceTrait] && TR.list[forceTrait].deed && rec.lvAt ? Math.round(rec.lvAt[TR.list[forceTrait].deed[0]] || 0) : null; /* V3: the trait's level at retirement */ rec.badges = traitsOf(c.me) ? trLevels(c.me) : {}; rec.badgeAm = traitsOf(a) ? trLevels(a) : {}; /* 3.0 (§6.3): the badges at the draft and at retirement */ rec.legacy = L.score; rec.hof = L.hof; rec.money = Math.round(c.me.money || 0); rec.earned = Math.round(c.me.earned || 0); rec.ovr = ages; rec.inv = inv.slice(0, 5); rec.hFinal = me.h;
      results.push(rec);
    }
    return results;
  }, { N, seed0, engineGames, forceTrait, forceSummer, faPolicy, tradePolicy, spend, gearPolicy, policy, edge, seasonsOut, schoolPolicy, parityN, menusNever, weekPolicy, recPol, hsOnly, spread, crewPol, crewUp });
  const med = a => { const s = a.filter(x => x != null).sort((x, y) => x - y); return s.length ? s[Math.floor(s.length / 2)] : null; };
  const at = age => med(out.map(r => r.ovr[age]));
  const printHs = () => {
  { const H = out.map(r => r.hs).filter(h => h && h.nat), avg = f => (H.reduce((x, h) => x + f(h), 0) / Math.max(1, H.length)).toFixed(2), mdn = f => { const v = H.map(f).sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; }, cnt = (f, vals) => vals.map(v => H.filter(h => f(h) === v).length).join('/'), sm = {}; for (const h of H) for (const k in h.summers) sm[k] = (sm[k] || 0) + h.summers[k];
    console.log('high school (R5): freshmen on varsity ' + Math.round(100 * H.filter(h => h.fresh).length / Math.max(1, H.length)) + '% · JV seasons ' + avg(h => h.jv) + ' · call-ups ' + avg(h => h.callups) + ' · district titles ' + avg(h => h.districts) + ' · state titles ' + avg(h => h.state) + ' · study weeks ' + avg(h => h.study) + ' · ineligible games ' + avg(h => h.inel) + ' · lowest GPA median ' + mdn(h => h.gpaMin).toFixed(2) + ' · stars at signing 5/4/3/2/1 ' + cnt(h => h.stars, [5, 4, 3, 2, 1]) + ' · national rank median ' + mdn(h => h.nat) + ' · best offer tier blue blood/power/mid/small ' + cnt(h => h.top, [3, 2, 1, 0]) + ' · summers ' + JSON.stringify(sm));
      { const byS = [5, 4, 3, 2, 1].map(st => { const G = H.filter(h => h.stars === st && h.offers != null); if (!G.length) return st + '★ –'; const o = G.map(h => h.offers).sort((x, y) => x - y); return st + '★ ' + (o.reduce((x, y) => x + y, 0) / G.length).toFixed(1) + ' (median ' + o[Math.floor(o.length / 2)] + ', none ' + Math.round(100 * G.filter(h => !h.offers).length / G.length) + '%, n ' + G.length + ')'; }); const pw = {}; for (const h of H) for (const w of h.pullWhy || []) pw[w] = (pw[w] || 0) + 1; const ac = H.flatMap(h => h.acad || []); if (process.env.RECDBG) for (const st of [4, 3, 2]) { const G = H.filter(h => h.stars === st && h.rk).slice(0, 6); for (const h of G) console.log('  dbg ' + st + '★ offers ' + h.offers + ' at t ' + JSON.stringify(h.offT) + ' rk ' + JSON.stringify(h.rk)); } console.log('recruiting (2.1 §2.7): offers received by stars ' + byS.join(' · ') + ' · pulled per career ' + avg(h => h.pulled || 0) + ' ' + JSON.stringify(pw) + ' · elite academic offers ' + ac.length + ', final below 3.3: ' + ac.filter(x => !x[0] && x[1] < 3.3).length);
      if (process.env.RECDBG1) for (const h of H.filter(h => h.stars >= +process.env.RECDBG1 && h.dbg1)) console.log('  #1 ' + h.stars + '★ ' + JSON.stringify(h.dbg1));
      if (process.env.RECDBG) console.log('  offers by program level (small/mid/power/blue blood/academic): ' + [5, 4, 3, 2, 1].map(st => { const G = H.filter(h => h.stars === st && h.byTier); return st + '★ ' + [0, 1, 2, 3, 4].map(t => (G.reduce((x, h) => x + h.byTier[t], 0) / Math.max(1, G.length)).toFixed(1)).join('/'); }).join(' · ') + ' · GPA under 2.5: ' + [5, 4].map(st => { const G = H.filter(h => h.stars === st); return st + '★ ' + Math.round(100 * G.filter(h => h.gpa < 2.5).length / Math.max(1, G.length)) + '%'; }).join(', '));
      { const F = H.filter(h => h.stars === 5 && h.lost1 != null), rd = {}; for (const h of H) if (h.road) rd[h.road] = (rd[h.road] || 0) + 1; const pp = H.filter(h => h.prep); console.log('recruiting (2.1 §2.3–2.6): a 5★ loses the #1 school ' + F.filter(h => h.lost1).length + ' of ' + F.length + ' (' + Math.round(100 * F.filter(h => h.lost1).length / Math.max(1, F.length)) + '%; 15–25) · #1 lost by stars 4★/3★/2★ ' + [4, 3, 2].map(st => { const G = H.filter(h => h.stars === st && h.lost1 != null); return Math.round(100 * G.filter(h => h.lost1).length / Math.max(1, G.length)) + '%'; }).join('/') + ' · committed by Signing Day ' + Math.round(100 * H.filter(h => h.committed).length / Math.max(1, H.length)) + '% (clock median ' + mdn(h => h.commitAt == null ? 9 : h.commitAt) + ') · flips ' + avg(h => h.rflips || 0) + ' · carousel ' + H.filter(h => h.car).length + ' (' + H.filter(h => h.car === 'follow').length + ' followed) · roads ' + JSON.stringify(rd) + (pp.length ? ' · prep years ' + pp.length + ' (dominated ' + pp.filter(h => h.prep.bonus).length + ', offers after ' + (pp.reduce((x, h) => x + h.prep.offers, 0) / pp.length).toFixed(1) + ')' : '') + ' · actions ' + avg(h => h.acts || 0) + ', film ' + avg(h => h.films || 0) + ', official visits ' + avg(h => h.offN || 0) + ', camps ' + avg(h => h.camps || 0) + ' · College test ' + JSON.stringify(H.reduce((m, h) => { if (h.testD != null) m[h.testD] = (m[h.testD] || 0) + 1; return m; }, {}))); } } }
    { const Q = out.map(r => r.hs).filter(h => h && h.nat && h.parts), md = a => { const v = a.slice().sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; }; if (Q.length) console.log('the play at signing (X9, 3.0 §8): ranked ' + Math.round(100 * Q.filter(h => h.parts.rankV).length / Q.length) + '% (median #' + md(Q.filter(h => h.parts.rankV).map(h => h.parts.rankV)) + ') · the ranking\'s points ' + (Q.reduce((x, h) => x + h.parts.rank, 0) / Q.length).toFixed(2) + ' · tournaments ' + (Q.reduce((x, h) => x + h.parts.exposure, 0) / Q.length).toFixed(2) + ' · PPG ' + (Q.reduce((x, h) => x + h.parts.ppg, 0) / Q.length).toFixed(2)); }
    { const T8 = rec8(out, out.gpaBlue); console.log('recruiting (3.0 §8, by the national rank at signing): ' + T8.rows.map(r => r.band + ' ' + r.mean.toFixed(1) + ' offers (median ' + r.med + ', none ' + r.none + '%' + (r.band === 'Top 50' ? ', 8+ ' + r.eight + '%, a power or blue blood ' + r.top + '%, a blue blood at GPA ' + (out.gpaBlue || 2.5).toFixed(1) + '+ ' + r.blue + '% of ' + r.nBlue : '') + (r.band === '3★' ? ', 2–4 ' + r.twoFour + '%' : '') + ', n ' + r.n + ')').join(' · ') + ' · 1★ with none: ' + JSON.stringify(T8.roads1) + ' · every road with none: ' + JSON.stringify(T8.roads) + ' · held through Signing Day ' + T8.held + ' a career · pulled ' + T8.pulled + ' a career ' + JSON.stringify(T8.why)); }
  };
  if (hsOnly) { console.log('careers', out.length, '· stuck', out.filter(r => r.stuck).length, '(high school only)'); printHs(); if (process.argv.includes('--json')) console.log('JSON ' + JSON.stringify({ n: out.length, gpaBlue: out.gpaBlue, hs: out.map(r => r.hs && r.hs.nat ? { nat: r.hs.nat, stars: r.hs.stars, offers: r.hs.offers, byTier: r.hs.byTier, gpa: r.hs.gpa, road: r.hs.road || null, held: r.hs.held || 0, pulled: r.hs.pullWhy || [] } : null) })); if (errors.length) console.log('ERRORS', errors.slice(0, 5)); await browser.close(); return; }
  console.log('careers', out.length, '· stuck', out.filter(r => r.stuck || (r.inv && r.inv.length)).length);
  console.log('median OVR at 14/17/21/25/29/33:', [14, 17, 21, 25, 29, 33].map(at).join(' / '));
  console.log('peak OVR median', med(out.map(r => r.peak)), '· peak age median', med(out.map(r => r.peakAge)), '· peak range', Math.min(...out.map(r => r.peak)) + '–' + Math.max(...out.map(r => r.peak)));
  { const F = out.filter(r => r.fr), n = Math.max(1, F.length), pc = k => Math.round(100 * F.filter(r => r.fr.best >= k).length / n), first = [1, 2, 3, 4, 5].map(k => F.filter(r => r.fr.first === k).length).join('/'), a5 = F.map(r => r.fr.age[5]).filter(x => x != null), gl = k => Math.round(100 * F.filter(r => r.goals && r.goals[k]).length / n); console.log('franchises (F7; --fa=' + faPolicy + ' --trade=' + tradePolicy + '): first team 1–5★ ' + first + ' · reached 3★ ' + pc(3) + '% · 4★ ' + pc(4) + '% · 5★ ' + pc(5) + '% (median age at the first 5★ ' + (a5.length ? med(a5) : '—') + '; by 29 ' + Math.round(100 * a5.filter(x => x <= 29).length / n) + '%, 2.0 §7) · started for a 5★ ' + gl('start5') + '% · a title with a 5★ ' + gl('title5') + '% · trades asked ' + (F.reduce((x, r) => x + r.fr.tradesUp, 0) / n).toFixed(2) + ' a career · the first 5★ by moving ' + F.filter(r => r.fr.via5 === 'move').length + ', by their team rising ' + F.filter(r => r.fr.via5 === 'rise').length); }
  console.log('pro start age median', med(out.map(r => r.draftAge)), '· skipped college', out.filter(r => r.college === '(none)').length);
  console.log('pro titles: mean ' + (out.reduce((a, r) => a + r.titles, 0) / out.length).toFixed(2) + ' · careers with a title ' + out.filter(r => r.titles > 0).length + ' · MVPs mean ' + (out.reduce((a, r) => a + r.mvps, 0) / out.length).toFixed(2));
  console.log('Hall of Fame: ' + out.filter(r => r.hof).length + ' of ' + out.length + ' (' + Math.round(100 * out.filter(r => r.hof).length / out.length) + '%) · legacy median ' + med(out.map(r => r.legacy)) + ' · pro seasons median ' + med(out.map(r => r.proSeasons)) + ' · retire age median ' + med(out.map(r => r.retireAge)));
  { const C = out.map(r => r.crew).filter(Boolean), n = Math.max(1, C.length), mean = f => (C.reduce((s, R) => s + (f(R) || 0), 0) / n), mid = C.map(R => { const p = R.proPay.slice(3, 8).reduce((s, v) => s + v, 0), i = R.proInc.slice(3, 8).reduce((s, v) => s + v, 0); return i > 0 ? p / i : null; }), cr = C.reduce((s, R) => { const x = R.credits || {}; s.all += x.all || 0; s.wins += x.wins || 0; s.tn += x.tn || 0; return s; }, { all: 0, wins: 0, tn: 0 }), msgs = {}; for (const R of C) for (const k in R.msgs) msgs[k] = (msgs[k] || 0) + R.msgs[k];
    const pc = v => Math.round(100 * v / Math.max(1, cr.all)) + '%'; console.log('crew (3.0 §7, --crew=' + crewPol + '): hires ' + mean(R => R.hires).toFixed(1) + ' · upgrades ' + mean(R => R.ups).toFixed(1) + ' · at the end ' + mean(R => R.n).toFixed(1) + ' staff · crew pay / income in pro seasons 4–8: median ' + (med(mid) == null ? '–' : Math.round(100 * med(mid)) + '%') + ' (target 15–30) · credits ' + Math.round(cr.all / n) + ' a career: wins ' + pc(cr.wins) + ', tournaments ' + pc(cr.tn) + ', goals ' + pc(cr.all - cr.wins - cr.tn) + ' · injuries avoided ' + mean(R => R.inj).toFixed(2) + ' (games back ' + mean(R => R.days).toFixed(1) + ') · injuries ' + (out.reduce((s, r) => s + (r.injuries || 0), 0) / out.length).toFixed(2) + ' · agent money ' + Math.round(mean(R => R.agentMoney) / 1e5) / 10 + 'M · topup ' + Math.round(mean(R => R.topup)) + ' · poach matched/lost ' + C.reduce((s, R) => s + R.matched, 0) + '/' + C.reduce((s, R) => s + R.lost, 0) + ' · trades from talk ' + C.reduce((s, R) => s + R.talkTrades, 0) + ' · messages ' + JSON.stringify(msgs)); }
  for (const sIdx of [0, 4, 9, 14]) { const rows = out.map(r => r.lg && r.lg[sIdx]).filter(Boolean); if (rows.length) console.log('league (others) after pro season ' + (sIdx + 1) + ': mean OVR ' + (rows.reduce((a, r) => a + r[0], 0) / rows.length).toFixed(1) + ' · best ' + (rows.reduce((a, r) => a + r[1], 0) / rows.length).toFixed(1) + ' · 3rd best ' + (rows.reduce((a, r) => a + r[2], 0) / rows.length).toFixed(1) + ' (n=' + rows.length + ')'); }
  console.log('pro score (the old draft score) median ' + med(out.map(r => r.dscore)) + ' · range ' + Math.min(...out.map(r => r.dscore || 0)).toFixed(0) + '–' + Math.max(...out.map(r => r.dscore || 0)).toFixed(0));
  console.log('heights: final median ' + med(out.map(r => r.hFinal)) + ' · at 14 median ' + med(out.map(r => r.h14)));
  { const R = out.filter(r => r.rk), med = v => { const x = v.filter(y => y > 0).sort((p, q) => p - q); return x.length ? x[Math.floor(x.length / 2)] : '–'; }, sh = f => R.length ? Math.round(100 * R.filter(f).length / R.length) + '%' : '–'; console.log('rankings (3.0 §4.1, your best a level): high school median ' + med(R.map(r => r.rk.hs)) + ' (ranked ' + sh(r => r.rk.hs > 0) + ', top 10 ' + sh(r => r.rk.hs > 0 && r.rk.hs <= 10) + ') · college median ' + med(R.map(r => r.rk.col)) + ' (ranked ' + sh(r => r.rk.col > 0) + ') · PBL median ' + med(R.map(r => r.rk.pro)) + ' (#1 ' + sh(r => r.rk.pro === 1) + ') · PBL seasons in the top 3: ' + (R.length ? (R.reduce((s2, r) => s2 + r.rk.top3, 0) / R.length).toFixed(1) : '–') + ' a career'); }
  { const P = { practice: 0, rest: 0, study: 0 }; for (const r of out) for (const k in r.plans) P[k] = (P[k] || 0) + r.plans[k]; const tot = P.practice + P.rest + P.study || 1; const fat = out.flatMap(r => r.fat); const mean = fat.length ? fat.reduce((x, y) => x + y, 0) / fat.length : 0; console.log('the week (3.0 §3: the plan, Auto): trained ' + Math.round(100 * P.practice / tot) + '% · rest ' + Math.round(100 * P.rest / tot) + '% · study ' + Math.round(100 * P.study / tot) + '% · pro fatigue at tip-off: mean ' + mean.toFixed(1) + ', max ' + (fat.length ? fat.reduce((a, b) => Math.max(a, b), 0) : 0) + ' · injuries per career: mean ' + (out.reduce((x, r) => x + r.injuries, 0) / out.length).toFixed(1)); console.log('press questions per career: mean ' + (out.reduce((x, r) => x + r.press, 0) / out.length).toFixed(1) + ' · hype at the draft: median ' + med(out.map(r => r.hype))); }
  console.log('depth chart (R4): weeks on the bench per career: amateur ' + (out.reduce((x, r) => x + r.benchAm, 0) / out.length).toFixed(1) + ' · pro ' + (out.reduce((x, r) => x + r.benchPro, 0) / out.length).toFixed(1) + ' · games in the league below ' + (out.reduce((x, r) => x + (r.llAm || 0), 0) / out.length).toFixed(1) + ' · abroad ' + Math.round(100 * out.filter(r => r.ovs).length / out.length) + '% of careers · coach trust at the draft: median ' + med(out.map(r => r.trustDraft)) + ' · pro bench weeks by season 1–15: ' + Array.from({ length: 15 }, (_, i) => (out.reduce((x, r) => x + (r.benchBy[i + 1] || 0), 0) / out.length).toFixed(1)).join(' '));
  printHs();
  { const C = out.map(r => r.col).filter(x => x && x.seasons), avg = f => (C.reduce((x, h) => x + f(h), 0) / Math.max(1, C.length)).toFixed(2), n = C.reduce((x, h) => x + h.seasons, 0) || 1, mk = C.flatMap(h => h.mock).sort((x, y) => x - y);
    console.log('college (R6): ' + C.length + ' careers, ' + avg(h => h.seasons) + ' seasons · national tournament ' + Math.round(100 * C.reduce((x, h) => x + h.nat, 0) / n) + '% of seasons (left out ' + Math.round(100 * C.reduce((x, h) => x + h.missed, 0) / n) + '%) · national wins per trip ' + (C.reduce((x, h) => x + h.natW, 0) / Math.max(1, C.reduce((x, h) => x + h.nat, 0))).toFixed(2) + ' · Final Fours ' + avg(h => h.ff) + ' · national titles ' + avg(h => h.champ) + ' · conference tournament titles ' + avg(h => h.confT) + ' · NIL offers ' + avg(h => h.nilOffers) + ', deals ' + avg(h => h.nilDeals) + ', money median $' + (C.map(h => h.nil).sort((x, y) => x - y)[Math.floor(C.length / 2)] || 0) + ' · portal ' + C.filter(h => h.portal).length + ' careers, transfers ' + C.filter(h => h.transfer).length + ' · agents ' + out.filter(r => r.col && r.col.agent).length + ' · season-end mock pick median ' + (mk.length ? mk[Math.floor(mk.length / 2)] : '–')); }
  { const T = [[], [], [], []]; for (const r of out) for (const e of (r.col && r.col.log) || []) { const [t, b, g, inf, rk, w, ct] = e; if (T[t]) T[t].push({ ws: g ? w / g : 0, bench: g ? b / g : 0, inf, ct }); } const f = (a, k) => a.length ? (a.reduce((x, y) => x + y[k], 0) / a.length) : 0;
    console.log('college by program tier (R6; seasons · win share · bench share · national tournament · conference tournament titles): ' + ['small', 'mid-major', 'power', 'blue blood'].map((nm, i) => nm + ' ' + T[i].length + ' · ' + f(T[i], 'ws').toFixed(2) + ' · ' + f(T[i], 'bench').toFixed(2) + ' · ' + Math.round(100 * f(T[i], 'inf')) + '% · ' + T[i].filter(x => x.ct).length).join(' | ')); }
  { const K = out.map(r => r.sch).filter(Boolean), col = K.filter(k => k.col), pct = (a, f) => Math.round(100 * a.filter(f).length / Math.max(1, a.length)) + '%', C = out.map(r => r.col).filter(x => x && x.seasons), avgC = f => (C.reduce((x, h) => x + f(h), 0) / Math.max(1, C.length)).toFixed(2), md = a => { const v = a.slice().sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; };
    console.log('school (V9): ' + col.length + ' went to college · full ride ' + pct(col, k => k.sch === 'full') + ', partial ' + pct(col, k => k.sch === 'partial') + ', lost ' + pct(col, k => k.sch === 'lost') + ' · elite academic: committed ' + pct(col, k => k.commitAcademic) + ', there at the draft ' + pct(col, k => k.academic) + ' · tuition paid: mean $' + Math.round(col.reduce((x, k) => x + k.tuition, 0) / Math.max(1, col.length)).toLocaleString('en-US') + ' · a loan at the draft ' + pct(col, k => k.loan > 0) + ' (median $' + md(col.filter(k => k.loan > 0).map(k => k.loan)).toLocaleString('en-US') + ') · college study weeks ' + avgC(h => h.study) + ' · college ineligible games ' + avgC(h => h.inel) + ' · probation ' + pct(col, k => k.probation) + ' · GPA at the draft: median ' + (+md(K.map(k => k.gpa))).toFixed(2) + ' · a degree (4 college years) ' + pct(col, k => k.years >= 4)); }
  { const R = out.map(r => r.pro).filter(Boolean), md = a => { const v = a.slice().sort((x, y) => x - y); return v.length ? v[Math.floor(v.length / 2)] : 0; }, fa = {}; for (const r of R) for (const k in r.fa) fa[k] = (fa[k] || 0) + r.fa[k];
    console.log('pro money (R7; --fa=' + faPolicy + ' --spend=' + spend + '): net worth median $' + (md(R.map(r => r.worth)) / 1e6).toFixed(1) + 'M · earned median $' + (md(out.map(r => r.earned || 0)) / 1e6).toFixed(1) + 'M · shoe lines ' + R.filter(r => r.shoe).length + ' · lifestyle buys ' + R.reduce((x, r) => x + r.life, 0) + ' · trade requests ' + R.reduce((x, r) => x + r.trades, 0) + ' · free agency picks ' + JSON.stringify(fa) + ' · epilogue: foundation median +' + md(R.map(r => r.foundation)) + ', academies ' + R.filter(r => r.academy).length + ', stakes ' + R.filter(r => r.stake).length); }
  { const G = out.filter(r => r.gear), mean = k => G.reduce((a, r) => a + (r.gear[k] || 0), 0) / Math.max(1, G.length); console.log('gear (V11; --gear=' + gearPolicy + '): levels worn at the pro start mean ' + mean('atPro').toFixed(1) + ' · at retirement ' + mean('end').toFixed(1) + ' · spent median $' + Math.round((med(G.map(r => r.gear.spent)) || 0) / 1e3) + 'K · buys ' + mean('buys').toFixed(1) + ', upgrades ' + mean('ups').toFixed(1) + ', extras ' + mean('uses').toFixed(1) + ' a career'); }
  { const R = out.filter(r => r.cash && r.cash.earned > 0), M$ = v => v == null ? '–' : '$' + (v >= 1e6 ? (v / 1e6).toFixed(1) + 'M' : v >= 1e4 ? Math.round(v / 1e3) + 'K' : Math.round(v)), mdk = k => { const v = R.map(r => r.cash[k]).filter(x => x != null); return v.length ? med(v) : null; }, un = R.map(r => r.cash.retire / r.cash.earned), left = R.map(r => (r.cash.left || 0) / r.cash.earned), u = med(un) || 0;
    console.log('money (V11, Part 2 §5.3; --spend=' + spend + '): median cash at the end of high school ' + M$(mdk('hsEnd')) + ' · at the pro start ' + M$(mdk('colEnd')) + ' · at 25 ' + M$(mdk('at25')) + ' · at 30 ' + M$(mdk('at30')) + ' · at retirement ' + M$(mdk('retire')) + ' of ' + M$(mdk('earned')) + ' earned (unspent ' + Math.round(100 * u) + '%; after the endings ' + Math.round(100 * (med(left) || 0)) + '%) · lifestyle upkeep ' + M$(mdk('upkeep')) + (spend === 'smart' ? ' · target: unspent under 30% ' + (u < 0.3 ? '✓' : '✗') : '')); { const BB = {}; for (const r of out) for (const [k, v] of Object.entries((r.pro && r.pro.big) || {})) BB[k] = (BB[k] || 0) + v; console.log('big buys (2.1 §1.4) per career: ' + (Object.keys(BB).length ? Object.entries(BB).map(([k, v]) => k + ' ' + (v / out.length).toFixed(2)).join(' · ') : 'none')); } }
  { const R = out.filter(r => r.badges), n = Math.max(1, R.length), cnt = r => Object.keys(r.badges).length, by = {}, am = {}; for (const r of R) { for (const id in r.badges) by[id] = (by[id] || 0) + 1; for (const id in (r.badgeAm || {})) am[id] = (am[id] || 0) + 1; } const lv = L => R.reduce((x, r) => x + Object.values(r.badges).filter(v => v >= L).length, 0) / n; console.log('badges (3.0 §6.3): per career at the draft ' + (R.reduce((x, r) => x + Object.keys(r.badgeAm || {}).length, 0) / n).toFixed(1) + ', at retirement ' + (R.reduce((x, r) => x + cnt(r), 0) / n).toFixed(1) + ' (Lv2+ ' + lv(2).toFixed(1) + ', Lv3 ' + lv(3).toFixed(1) + ') · earned (at retirement / by the draft): ' + Object.keys(by).sort((p, q) => by[q] - by[p]).map(id => id + ' ' + Math.round(100 * by[id] / n) + '%/' + Math.round(100 * (am[id] || 0) / n) + '%').join(', ')); const D = out.filter(r => r.lvAt), keys = [...new Set(D.flatMap(r => Object.keys(r.lvAt)))].sort(); if (D.length) console.log('  deeds at retirement (median; 10th–90th): ' + keys.map(k => { const v = D.map(r => r.lvAt[k] || 0).sort((x, y) => x - y), q = p => v[Math.min(v.length - 1, Math.floor(p * v.length))]; return k + ' ' + Math.round(q(0.5)) + ' (' + Math.round(q(0.1)) + '–' + Math.round(q(0.9)) + ')'; }).join(' · ')); }
  { const g = out.reduce((x, r) => x + r.fameN, 0) || 1; console.log('fame (3.0 §1: one meter, from performance): pro fame mean ' + (out.reduce((x, r) => x + r.fameSum, 0) / g).toFixed(1) + ' · fame at the draft: median ' + med(out.map(r => r.fame || 0)) + ' · sponsor money mean $' + (out.reduce((x, r) => x + ((r.pro && r.pro.endorse) || 0), 0) / out.length / 1e6).toFixed(1) + 'M · shoe lines ' + out.filter(r => r.pro && r.pro.shoe).length + ' · legacy mean ' + (out.reduce((x, r) => x + r.legacy, 0) / out.length).toFixed(1) + ' · earned mean $' + (out.reduce((x, r) => x + (r.earned || 0), 0) / out.length / 1e6).toFixed(1) + 'M · titles mean ' + (out.reduce((x, r) => x + r.titles, 0) / out.length).toFixed(2)); }
  if (process.argv.includes('--each')) for (const r of out) console.log(JSON.stringify({ style: r.style, h: r.hFinal, pick: r.pick, dAge: r.draftAge, col: r.college, ovr: r.ovr, peak: r.peak + '@' + r.peakAge, t: r.titles, mvp: r.mvps, leg: r.legacy, hof: r.hof, ret: r.retireAge, inv: r.inv, colLog: r.col && r.col.log }));
  { const part = (rows, k) => rows.length ? (rows.reduce((a, r) => a + (r.L ? r.L[k] : 0), 0) / rows.length).toFixed(1) : '–'; const H = out.filter(r => r.hof), N = out.filter(r => !r.hof); console.log('legacy parts (Hall of Fame / the rest): titles ' + part(H, 'titles') + ' / ' + part(N, 'titles') + ' · MVPs ' + part(H, 'mvps') + ' / ' + part(N, 'mvps') + ' · All-League 1st ' + part(H, 'allL') + ' / ' + part(N, 'allL') + ' · seasons ' + part(H, 'seasons') + ' / ' + part(N, 'seasons') + ' · points/250 ' + part(H, 'pts') + ' / ' + part(N, 'pts') + ' · PPG ' + part(H, 'ppg') + ' / ' + part(N, 'ppg') + ' · peak ' + med(H.map(r => r.peak)) + ' / ' + med(N.map(r => r.peak))); const pk = out.map(r => r.peak).sort((x, y) => x - y); console.log('peak percentiles 10/25/50/75/90: ' + [0.1, 0.25, 0.5, 0.75, 0.9].map(q => pk[Math.floor(q * (pk.length - 1))]).join(' / ')); }
  { const V = out.filter(r => r.v12), n = Math.max(1, V.length), pc = f => Math.round(100 * V.filter(f).length / n); console.log('pro teams (V12, Part 2 §6): a ring ' + pc(r => r.titles > 0) + '% · Finals MVP ' + pc(r => r.v12.fmvp > 0) + '% (mean ' + (V.reduce((a, r) => a + r.v12.fmvp, 0) / n).toFixed(2) + ') · a franchise player ' + pc(r => r.v12.franchise) + '% · a jersey retired ' + pc(r => r.v12.jersey > 0) + '% · back-to-back ' + pc(r => r.v12.run >= 2) + '% · a three-peat ' + pc(r => r.v12.run >= 3) + '% · rebuild trades ' + (V.reduce((a, r) => a + r.v12.rebuild, 0) / n).toFixed(2) + ' a career'); }
  const invs = out.filter(r => r.inv && r.inv.length).slice(0, 5).map(r => r.inv); if (invs.length) console.log('invariants', JSON.stringify(invs));
  const pct = x => Math.round(100 * x);
  const hof = out.filter(r => r.hof).length / out.length, titles = out.reduce((a, r) => a + r.titles, 0) / out.length, stuck = out.filter(r => r.stuck || (r.inv && r.inv.length)).length;
  const inR = (v, lo, hi) => v != null && v >= lo && v <= hi ? '✓' : '✗';
  { const great5 = policy === 'great', b5 = pct(out.filter(r => r.fr && r.fr.best >= 5).length / out.length); /* V6: Part 2 §1.1 replaces F6's targets (the whole table: tests/difficulty.js, 600 careers) */
    console.log('TARGETS (Part 2 §1.1; great: 2.1 §3.7, ' + policy + '; 40 careers are a rough read): a 5★ team ' + b5 + '% (' + (great5 ? '35–55' : '15–25') + ') ' + (great5 ? inR(b5, 35, 55) : inR(b5, 15, 25)) + ' · titles/career ' + titles.toFixed(2) + ' (' + (great5 ? '1–2' : '0.2–0.4') + ') ' + (great5 ? inR(titles, 1, 2) : inR(titles, 0.2, 0.4)) + ' · HOF ' + pct(hof) + '% (' + (great5 ? '30–40' : '3–8') + '%) ' + (great5 ? inR(pct(hof), 30, 40) : inR(pct(hof), 3, 8)) + ' · peak ' + med(out.map(r => r.peak)) + ' · OVR@17/21/25 ' + at(17) + '/' + at(21) + '/' + at(25) + ' · stuck ' + stuck + ' (0) ' + (stuck ? '✗' : '✓')); }
  if (policy === 'great') { const b3 = pct(out.filter(r => r.fr && r.fr.best >= 3).length / out.length), b5 = pct(out.filter(r => r.fr && r.fr.best >= 5).length / out.length); console.log('§3.7 (2.1, the plays-well policy): a 3★ team ' + b3 + '% (60%+) ' + inR(b3, 60, 100) + ' · a 5★ team ' + b5 + '% (35–55) ' + inR(b5, 35, 55) + ' · titles a career ' + titles.toFixed(2) + ' (1–2) ' + inR(titles, 1, 2)); }
  { const F = out.filter(r => !r.stuck), n = Math.max(1, F.length), P_ = x => Math.round(100 * x / n); // V6 (Part 2 §1.1): the difficulty table's numbers for this policy
    console.log('titles as the starter / from the bench: ' + (F.reduce((a, r) => a + (r.titleStart || 0), 0) / n).toFixed(2) + ' / ' + (F.reduce((a, r) => a + (r.titleBench || 0), 0) / n).toFixed(2) + ' · by the team\'s stars 1–5: ' + [1, 2, 3, 4, 5].map(k => (F.reduce((a, r) => a + ((r.titleStars || [])[k] || 0), 0) / n).toFixed(2)).join(' / ')); console.log('DIFFICULTY (' + policy + (policy === 'great' ? ', edge ' + edge : '') + '): varsity year 1/2/3/4/never ' + [1, 2, 3, 4].map(y => P_(F.filter(r => r.varsityYear === y).length)).join('/') + '/' + P_(F.filter(r => r.varsityYear == null).length) + '% · stars at signing 1–5 ' + [1, 2, 3, 4, 5].map(k => P_(F.filter(r => r.hs.stars === k).length)).join('/') + '% · college start year 1/2/3/4/never ' + [1, 2, 3, 4].map(y => P_(F.filter(r => r.colStart === y).length)).join('/') + '/' + P_(F.filter(r => r.colStart == null).length) + '% · first pro offer 1–5★ ' + [1, 2, 3, 4, 5].map(k => P_(F.filter(r => r.offer === k).length)).join('/') + '% · a 3★ team ' + P_(F.filter(r => r.fr && r.fr.age[3] != null).length) + '% (by 24 ' + P_(F.filter(r => r.fr && r.fr.age[3] != null && r.fr.age[3] <= 24).length) + '%, by 28 ' + P_(F.filter(r => r.fr && r.fr.age[3] != null && r.fr.age[3] <= 28).length) + '%, median age ' + med(F.map(r => r.fr && r.fr.age[3])) + ') · a 5★ team ' + P_(F.filter(r => r.fr && r.fr.best >= 5).length) + '% · titles ' + (F.reduce((a, r) => a + (r.titles || 0), 0) / n).toFixed(2) + ' · HoF ' + P_(F.filter(r => r.hof).length) + '%'); }
  if (parityN) { const all = { am: out.flatMap(r => r.parity.am), pro: out.flatMap(r => r.parity.pro) }, mean = (A, k) => A.length ? A.reduce((t, x) => t + x[k], 0) / A.length : 0; // 2.1 (§1.3): played (the engine, the AI at your controls) vs simmed
    for (const [k, A] of Object.entries(all)) { const parts = k === 'am' ? [['hs', A.filter(x => x.st === 'hs')], ['college', A.filter(x => x.st === 'college')], ['all', A]] : [['all', A]]; for (const [lb, B] of parts) { if (!B.length) continue; const pl = mean(B, 'eng'), sm = mean(B, 'sim'); console.log('PARITY ' + k + ' ' + lb + ': ' + B.length + ' games · played ' + pl.toFixed(2) + ' (opp ' + mean(B, 'engOpp').toFixed(2) + ') · simmed ' + sm.toFixed(2) + ' (opp ' + mean(B, 'simOpp').toFixed(2) + ') · simmed/played ' + (sm / Math.max(0.01, pl)).toFixed(3) + ' · gap ' + mean(B, 'd').toFixed(1)); } }
    for (const k of ['am', 'pro']) { const A = all[k]; if (!A.length) continue; const bins = [[-99, -6], [-6, -2], [-2, 2], [2, 6], [6, 99]]; console.log('PARITY ' + k + ' by the strength gap: ' + bins.map(([lo, hi]) => { const B = A.filter(x => x.d >= lo && x.d < hi); return B.length ? (lo === -99 ? '<' + hi : hi === 99 ? lo + '+' : lo + '..' + hi) + ' n' + B.length + ' ' + mean(B, 'eng').toFixed(1) + '/' + mean(B, 'sim').toFixed(1) : null; }).filter(Boolean).join(' · ') + ' (played/simmed)'); }
    console.log('PARITYJSON ' + JSON.stringify(all)); }
  if (process.argv.includes('--json')) console.log('JSON ' + JSON.stringify({ n: out.length, policy, edge, legParts: out.map(r => r.L || null), recBest: out.map(r => r.recBest || null), ps: seasonsOut ? out.map(r => r.ps || []) : undefined, diff: out.map(r => ({ o22: r.ovr[22] == null ? null : r.ovr[22], un: r.cash && r.cash.earned ? +(r.cash.retire / r.cash.earned).toFixed(3) : null, v: r.varsityYear == null ? null : r.varsityYear, st: r.hs ? r.hs.stars : 0, cs: r.colStart == null ? null : r.colStart, of: r.offer == null ? null : r.offer, a3: r.fr && r.fr.age[3] != null ? r.fr.age[3] : null, b5: r.fr ? r.fr.best : 0, t: r.titles || 0, h: !!r.hof, pk: r.peak, g: r.sch && r.sch.gpa != null ? +r.sch.gpa.toFixed(2) : null, gl: r.hs && r.hs.gpaMin < 4 ? +r.hs.gpaMin.toFixed(2) : null, stuck: !!r.stuck })), trait: forceTrait, lv: out.map(r => r.trLv || 0), ageS: out.map(r => r.ageS == null ? null : r.ageS), ageG: out.map(r => r.ageG == null ? null : r.ageG), deedTot: out.map(r => r.deedTot == null ? null : r.deedTot), legacy: out.map(r => r.legacy), titles: out.map(r => r.titles), money: out.map(r => r.earned), cash: out.map(r => r.cash || null), gearRec: out.map(r => r.gear || null), worth: out.map(r => (r.pro && r.pro.worth) || 0), spent: out.map(r => (r.pro && r.pro.spent) || 0), inj: out.map(r => r.injuries || 0), crew: out.map(r => r.crew || null), peak: out.map(r => r.peak), crewPol, fame: out.map(r => r.fameN ? +(r.fameSum / r.fameN).toFixed(1) : 0), hof: out.filter(r => r.hof).length, stuck }));
  console.log('errors', errors.slice(0, 5)); await browser.close(); process.exitCode = errors.length || stuck ? 1 : 0;
})();
