// 3.0 (§7, §11 "Crew"): your crew. The six roles open by stage and year (slots: high school 1, college 3, the pros 6);
// three candidates a role with a level, never rarity, and every effect in numbers; upgrades cost credits and raise the
// salary; two seasons together and they work a level higher; they follow you from high school to the pros; every
// role's work shows on HOME's crew report and the result screen's crew line; the crew's messages (the physio's
// hamstring call, a rival poaching, the agent's trade talk) and the one-a-week rule; the tournament prep and the scout's
// read on the bracket; the bench and the tip-off banner in a game; an old save's staff join the crew; and the §7.6 table
// (the career simulator: no crew, a full crew at Lv3, each role alone at Lv3): a full crew adds 25–40% legacy, every
// role at least +4%, the crew's salaries take 15–30% of a mid-career pro's income, and most credits come from wins and
// tournaments.
// Usage: node tests/crew.js   (the table: CREW_N careers a seed, default 200, over CREW_SEEDS, default 1–6: 1,200 careers a
// policy, four simulators at a time, about half an hour; the same careers in every policy, so each role's legacy is a
// paired difference, checked within its standard error of the target; ONLY=<regex> runs some steps)
const { spawn } = require('child_process');
const { launch, openPage, runner } = require('./lib');
(async () => {
  const browser = await launch(); const R = runner('crew'); const D = await openPage(browser); const { ev } = D; const step = (n, f) => R.step(n, f, D);
  await ev(() => {
    window.__hs = seed => { const g = HH.game; localStorage.clear(); g.save = new SaveSystem(); const a = amCreate(g.save.data, { name: 'Crew Test', look: PRESET_LOOKS[seed % 16], number: 9, style: 'slasher', seed }); g.save.data.c1 = a; hsTryoutDrill(a, 30); hsTryoutGame(a, true, 7, 0); a.events.length = 0; a.cash = 1e6; return a; };
    window.__pro = seed => { const g = HH.game; localStorage.clear(); g.save = new SaveSystem(); const c = testProLeague(seed, g.save.data); g.save.data.career = c; c.events.length = 0; c.me.money = 5e8; return c; };
    window.__full = c => { for (const role of CREW_ROLES) { const L = crewCandidates(c, role); crewHireForce(c, L[L.length - 1]); const M = crewMember(holderOf(c), role); if (M && M.lv < 3) M.lv = 3; } crewSync(c); return crewCount(holderOf(c)); };
    window.__texts = () => { const g = HH.game; g.ui.trans = null; g.ui.toastT = 0; RBF.boxes = []; let X = []; try { for (let k = 0; k < 3; k++) { RBF.boxes = []; g.drawUI(g.ctx, g.W, g.H); } } finally { X = RBF.boxes || []; RBF.boxes = null; } return X.map(b => b.t); };
  });

  await step('the roles, the slots and the levels (§7.1–7.2): a skills coach from the sophomore year, a scout from the junior year, the rest in college (the agent from the second season); slots 1/3/6; three candidates a role at the stage\'s levels, no rarity, every effect in numbers; the salary rises with the level; credits buy a level (6/12/20/30); two seasons together and they work a level higher', () => ev(() => {
    const bad = [], open = c => CREW_ROLES.filter(r => crewRoleOpen(c, r)).join(',');
    const a = __hs(41); const want = [[1, ''], [2, 'skills'], [3, 'skills,scout']]; for (const [y, w] of want) { a.stageYear = y; if (open(a) !== w) bad.push('high school year ' + y + ': ' + open(a)); } if (crewSlots(a) !== CREW.slots.hs) bad.push('high school slots ' + crewSlots(a));
    a.stage = 'college'; a.stageYear = 1; if (open(a) !== 'skills,scout,strength,physio,mental') bad.push('college year 1: ' + open(a)); a.stageYear = 2; if (open(a) !== CREW_ROLES.join(',')) bad.push('college year 2: ' + open(a)); if (crewSlots(a) !== CREW.slots.college) bad.push('college slots ' + crewSlots(a));
    const c = __pro(42); if (crewSlots(c) !== 6 || open(c) !== CREW_ROLES.join(',')) bad.push('pros: ' + crewSlots(c) + ' slots, ' + open(c));
    const RARE = /\b(common|uncommon|rare|epic|legendary|rarity|★)/i;
    for (const role of CREW_ROLES) { const L = crewCandidates(c, role); if (L.length !== 3) bad.push(role + ': ' + L.length + ' candidates');
      for (const M of L) { if (!(M.lv >= CREW.hireLv.pro[0] && M.lv <= CREW.hireLv.pro[1])) bad.push(role + ' Lv' + M.lv); if ('stars' in M || 'rarity' in M || 'tier' in M) bad.push(role + ': a star or rarity field'); const E = crewEffectLines(role, M.spec, M.lv), lines = E.week.concat(E.games); if (!lines.length || !lines.every(l => /\d/.test(l))) bad.push(role + ': an effect without its number: ' + lines.join(' | ')); if (lines.some(l => RARE.test(l))) bad.push(role + ': a rarity word'); }
      if (role === 'skills' && new Set(L.map(M => M.spec)).size !== 3) bad.push('the skills coaches share a specialty'); }
    for (let lv = 1; lv < CREW.maxLv; lv++) if (!(crewPay(c, { role: 'physio', lv: lv + 1 }) > crewPay(c, { role: 'physio', lv }))) bad.push('the salary doesn\'t rise at Lv' + (lv + 1));
    const cand = crewCandidates(c, 'skills')[0]; c.me.credits = 100; if (!crewHire(c, cand)) bad.push('can\'t hire'); const M = crewMember(c.me, 'skills'), costs = []; M.lv = 1;
    while (M.lv < CREW.maxLv) { const cr = c.me.credits, lv = M.lv; if (!crewUpgrade(c, 'skills')) { bad.push('no upgrade from Lv' + lv); break; } costs.push(cr - c.me.credits); }
    if (costs.join('/') !== '6/12/20/30') bad.push('upgrade costs ' + costs.join('/')); if (crewUpgrade(c, 'skills')) bad.push('upgraded past Lv' + CREW.maxLv);
    M.lv = 3; M.yrs = 0; const L0 = crewEffLv(M); c.events.length = 0; crewSeasonEnd(c, 10); crewSeasonEnd(c, 10); const L1 = crewEffLv(M); if (L0 !== 3 || L1 !== 4) bad.push('two seasons together: Lv' + L0 + ' → at work Lv' + L1); if (!c.events.some(e => e.kind === 'crewlevel' && /KNOWS YOUR GAME/.test(e.title))) bad.push('no "knows your game" news');
    if (crewValAt('skills', 'ceiling', 3) !== 1 || crewValAt('skills', 'ceiling', 5) !== 2) bad.push('the skills ceiling at Lv3/Lv5: ' + crewValAt('skills', 'ceiling', 3) + '/' + crewValAt('skills', 'ceiling', 5));
    if (bad.length) throw new Error(bad.slice(0, 10).join(' · ')); return 'upgrades ' + costs.join('/') + ' credits · Lv3 for two seasons works at Lv' + L1 + ' · pay Lv1–5 ' + [1, 2, 3, 4, 5].map(lv => crewMoney(crewPay(c, { role: 'physio', lv }))).join('/'); }));

  await step('they follow you (§7.2): a skills coach hired in high school is still yours in college and in the pros (the same person, the years together kept), and the slots grow', () => ev(() => {
    const bad = [], g = HH.game, a = __hs(43); a.stageYear = 2; const cand = crewCandidates(a, 'skills')[2]; if (!crewHire(a, cand)) throw new Error('no high school hire'); const id = cand.id; crewOf(a).staff.skills.yrs = 1;
    const r = devJumpToPro(g, 43); if (!g.save.data.career) createCareerFromAmateur(g.save.data, a); const c = careerOf(g); if (!c) throw new Error('no pro career: ' + JSON.stringify(r)); const M = crewMember(c.me, 'skills');
    if (!M || M.id !== id) bad.push('the coach didn\'t come: ' + JSON.stringify(crewList(c.me).map(x => x.id))); else if (!(M.yrs >= 1)) bad.push('the years together were lost: ' + M.yrs); if (crewSlots(c) !== 6) bad.push('pro slots ' + crewSlots(c));
    if (bad.length) throw new Error(bad.join(' · ')); return M.name + ' (' + CREW_SPEC_NAME[M.spec] + ', Lv' + M.lv + ') from high school to the pros, ' + M.yrs + ' seasons together'; }));

  await step('every role works and shows (§7.3, §11): a full crew in the pros: HOME\'s crew report has a line for each of the six; the result screen\'s crew line shows the coaches\' XP, the plan, the physio\'s fatigue, the agent\'s money and the mental coach (clutch or confidence held); the game\'s numbers (clutch, the plan, the timing edge, contact, the tired penalty)', () => ev(() => {
    const bad = [], g = HH.game, c = __pro(44); __full(c); const B = c.me, seen = {}; let lines = [], shown = false;
    for (let i = 0; i < 14 && Object.keys(seen).length < 6; i++) { c.events.length = 0; const r = simUserGame(g.save.data); if (!r) continue; const t = r.crew || ''; lines.push(t);
      if (/XP from your coaches/.test(t)) seen.coaches = 1; if (/plan/.test(t)) seen.scout = 1; if (/fatigue −/.test(t)) seen.physio = 1; if (/from your agent/.test(t)) seen.agent = 1; if (/clutch|confidence held/.test(t)) seen.mental = 1; if (/through contact/.test(t)) seen.contact = 1;
      if (!shown && t) { shown = true; g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); g.ui.push(gameResultScreen(g, c, r, null, 'result', () => g.ui.pop())); const T = __texts().join(' | '); if (!/Crew:/.test(T)) bad.push('the result screen has no crew line'); } }
    if (!seen.mental) { const W = { mental: { conf: 0.6 } }; if (!/confidence held/.test(crewGameLine(B, null, W, {}))) bad.push('the mental coach never shows'); else seen.mental = 1; } /* (a loss's confidence held: a week's note) */
    for (const k of ['coaches', 'scout', 'physio', 'agent', 'mental']) if (!seen[k]) bad.push('the result line never shows the ' + k + ': ' + lines.slice(0, 3).join(' / '));
    const parts = crewReportParts(c, c.players[opponentOf(c, userGame(c))]); if (parts.length !== 6) bad.push('HOME\'s crew report: ' + parts.length + ' lines: ' + parts.join(' / '));
    g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); const H = __texts().join(' | '); if (!parts.some(p => H.includes(p.slice(0, 12)))) bad.push('HOME doesn\'t draw the crew report');
    const opp = opponentOf(c, userGame(c)), d = crewDef(B, opp, c.players[opp]); for (const k of ['clutch', 'contact', 'tired']) if (!(d[k] > 0)) bad.push('the game def has no ' + k); if (!d.plan || !(d.plan.v > 0)) bad.push('no game plan'); if (!(d.win || d.rim || d.hand || d.dfn)) bad.push('no specialty edge'); if (!(crewStamMul(B) > 1)) bad.push('no stamina'); if (!(crewInjuryMul(B) < 1 && crewFatigueMul(B) < 1)) bad.push('no physio'); if (!(crewAgentRaise(B) > 0)) bad.push('no agent raise');
    if (bad.length) throw new Error(bad.slice(0, 8).join(' · ')); return 'HOME: ' + parts.join(' · ').slice(0, 150) + '… · a result: ' + (lines.find(t => t.length > 40) || lines[0]); }));

  await step('the crew\'s messages (§7.4): the physio\'s hamstring call is urgent (rest: no practice and no risk; play: +15% injury risk), without a physio the risk comes unwarned; a rival poaching a Lv3+ staff member is a message (match: their pay for good; let go: gone); the agent\'s trade talk shows its odds and trades on a yes; the counter\'s odds in words; one message a week', () => ev(() => {
    const bad = [], c = __pro(45); __full(c); const B = c.me, ct = CREW.msg.tight;
    // the hamstring
    c.events.length = 0; CREW.msg.tight = 100; delete wkOf(B).tight; crewTightCheck(c, B, careerRng(c)); CREW.msg.tight = ct; const h = c.events.find(e => e.kind === 'crewtight'); if (!h) bad.push('no hamstring call'); else { if (evClass(h, c) !== 'urgent') bad.push('the hamstring call is ' + evClass(h, c)); if (!/Rest a week \(no risk\) or play \(\+15% injury risk\)/.test(h.lines[0])) bad.push('the call: ' + h.lines[0]); B.fatigue = 40; crewTightAnswer(c, h, true); const w = wkOf(B); if (w.done !== 'rest' || w.tight !== 0 || !(B.fatigue < 40)) bad.push('resting: ' + JSON.stringify({ done: w.done, tight: w.tight, f: B.fatigue })); }
    const odds = t => { let n = 0; for (let i = 0; i < 600; i++) { B.injury = null; B.fatigue = 0; wkOf(B).tight = t; if (wkAfterGame(B, new RNG(500 + i), {}).injury) n++; } B.injury = null; return n / 600; }, o0 = odds(0), o1 = odds(CREW.msg.tightRisk); if (!(o1 - o0 > 0.1)) bad.push('playing through it: injury odds ' + o0 + ' → ' + o1);
    { const ph = B.crew.staff.physio; delete B.crew.staff.physio; c.events.length = 0; CREW.msg.tight = 100; delete wkOf(B).tight; crewTightCheck(c, B, careerRng(c)); CREW.msg.tight = ct; if (c.events.length || !(wkOf(B).tight > 0)) bad.push('no physio: ' + c.events.length + ' calls, risk ' + wkOf(B).tight); B.crew.staff.physio = ph; delete wkOf(B).tight; }
    // poaching
    const pp = CREW.msg.poach; CREW.msg.poach = 1; c.events.length = 0; for (let k = 0; k < 80 && !c.events.length; k++) { B.crew.poachS = null; crewPoachCheck(c, B, careerRng(c)); } CREW.msg.poach = pp; const p = c.events.find(e => e.kind === 'crewpoach'); if (!p) bad.push('no poaching'); else { if (evClass(p, c) !== 'message') bad.push('poaching is ' + evClass(p, c)); const M = crewMember(B, p.role); if (!(M.lv >= CREW.msg.poachLv)) bad.push('poached a Lv' + M.lv); crewPoachAnswer(c, p, true); if (crewPay(c, M) !== p.offer) bad.push('matched: pay ' + crewPay(c, M) + ' for ' + p.offer);
      const p2 = Object.assign({}, p, { answered: false }); crewPoachAnswer(c, p2, false); if (crewMember(B, p.role)) bad.push('let go: still there'); }
    // the agent's trade talk
    c.phase = 'regular'; const ci = CREW.msg.interest, cn = CREW.msg.near; CREW.msg.interest = 1; CREW.msg.near = 99; c.events.length = 0; for (let k = 0; k < 80 && !c.events.length; k++) { B.talkSeason = null; crewTalkCheck(c, careerRng(c)); } CREW.msg.interest = ci; CREW.msg.near = cn; const tt = c.events.find(e => e.kind === 'crewtrade');
    if (!tt) bad.push('no trade talk'); else { if (evClass(tt, c) !== 'message') bad.push('trade talk is ' + evClass(tt, c)); if (!new RegExp(Math.round(tt.odds * 100) + '% they say yes').test(tt.lines[0])) bad.push('the odds aren\'t shown: ' + tt.lines[0]); const club0 = meOf(c).club; tt.odds = 1; if (!crewTradeAnswer(c, tt, true) || meOf(c).club !== tt.dest || meOf(c).club === club0) bad.push('a yes didn\'t trade'); }
    if (!/% they accept, ' \+ Math\.round\(best\.risk \* 100\) \+ '% they walk/.test(String(lgAgentAdvice))) bad.push('the counter\'s advice has no odds in words'); /* (the words: a live free agency is life21's) */
    // one message a week
    c.inbox = [{ kind: 'crewpoach', title: 'A', lines: ['a'], inS: c.season }, { kind: 'crewpoach', title: 'B', lines: ['b'], inS: c.season }]; delete B.msgWk; const m1 = evNextMessage(c), m2 = evNextMessage(c); c.week++; const m3 = evNextMessage(c); if (!m1 || m2 || !m3) bad.push('one a week: ' + [m1, m2, m3].map(x => x ? x.title : '-').join(','));
    if (bad.length) throw new Error(bad.slice(0, 8).join(' · ')); return 'injury odds playing through it ' + Math.round(o0 * 100) + '% → ' + Math.round(o1 * 100) + '% · a poach offer ' + (p ? crewMoney(p.offer) : '-') + ' · trade talk at ' + (tt ? Math.round(tt.odds * 100) : '-') + '%'; }));

  await step('the tournament prep (§7.5): a tournament you play starts with a prep your crew can run, the Prep button cycles them until your first game, Recover\'s fresh legs come at that game, Lock in doubles the clutch, Study raises the plan, Sharpen doubles the specialty\'s XP; the scout reads the bracket; the prep ends with the tournament', () => ev(() => {
    const bad = [], c = __pro(46); __full(c); const B = c.me, T = tnCreate(c, 'oly', { mine: true, field: c.active.slice(0, 3).concat([c.meId]) }); tnQueue(c, T); const P = crewPrepOf(B);
    if (!P || P.tid !== T.id || !CREW.prep[P.id]) bad.push('no prep at the start: ' + JSON.stringify(P)); if (!T.tip || !/The best in the field/.test(T.tip.text)) bad.push('no read on the bracket');
    const b = crewPrepButton(c, T, null); if (b.hidden) bad.push('no Prep button'); const seen = new Set([crewPrepOf(B).id]); for (let k = 0; k < 4; k++) { crewPrepButton(c, T, null).onPress(); seen.add(crewPrepOf(B).id); } if (seen.size !== 4) bad.push('the button cycles ' + [...seen]);
    const S = crewMember(B, 'skills'), k = CREW_SPEC_K[S.spec], base = { clutch: crewDef(B, null, null).clutch, xp: crewXpMul(B, k) }, opp = c.players[c.active.find(id => id !== c.meId)];
    crewPrepSet(c, 'lockin', T.id); if (Math.abs(crewDef(B, null, null).clutch - 2 * crewVal(B, 'mental', 'clutch')) > 1e-9) bad.push('Lock in: clutch ' + crewDef(B, null, null).clutch);
    crewPrepSet(c, 'study', T.id); const pv = crewDef(B, null, opp).plan; if (!pv || Math.abs(pv.v - CREW.prep.study.plan * crewVal(B, 'scout', 'plan')) > 1e-9) bad.push('Study: plan ' + JSON.stringify(pv));
    const sh0 = crewSkillsShare(B, { spd: 10 }); crewPrepSet(c, 'sharpen', T.id); const sh1 = crewSkillsShare(B, { spd: 10 }); if (!(sh0 > 0) || Math.abs(sh1 - 2 * sh0) > 1e-9 || Math.abs(crewXpMul(B, k) - 2 * (1 + crewVal(B, 'skills', 'xp'))) > 1e-9) bad.push('Sharpen: the coach\'s share ' + sh0 + ' → ' + sh1 + ', the specialty ×' + crewXpMul(B, k));
    crewPrepSet(c, 'recover', T.id); B.fatigue = 40; if (B.fatigue !== 40) bad.push('Recover before the first game'); tnSimMine(c, T); if (B.fatigue > 15) bad.push('Recover: fatigue ' + B.fatigue + ' after the first game'); if (!crewPrepButton(c, T, null).hidden) bad.push('the Prep button after the first game');
    tnSimAll(c, T); if (!T.done) bad.push('the tournament didn\'t finish'); if (crewPrepOf(B)) bad.push('the prep outlived the tournament');
    if (bad.length) throw new Error(bad.slice(0, 8).join(' · ')); return 'preps ' + [...seen].join('/') + ' · the scout: ' + T.tip.text.slice(0, 90); }));

  await step('on the court (§7.3): a career game puts your crew on your bench (each of them), a big play of yours brings them up, and the scout\'s plan shows as a banner after the TIP-OFF stamp', () => ev(() => {
    const bad = [], g = HH.game, c = __pro(47); __full(c); crewPlanSet(c.me, 'shoot', null); const opts = careerMatchOpts(c, g.save.data, userGame(c), false); g.startMatch(opts, { kind: 'career' }); const m = g.match, C = crewCourtOf(m);
    if (!C || C.list.length !== 6) bad.push('the bench: ' + (C ? C.list.length : 'none')); else { const hs = opts.homeSide === 1 ? 1 : 0, me = m.players.find(p => p.isHuman); if (C.side !== (me.team === hs ? -1 : 1)) bad.push('the wrong bench'); if (!C.plan || C.plan.id !== 'shoot') bad.push('the plan: ' + JSON.stringify(C.plan)); }
    m.bus.emit('PHASE', { phase: 'tipoff' }); if (!(m.crewBannerAt > m.time)) bad.push('no banner after the stamp: ' + m.crewBannerAt + ' at ' + m.time); if (C && !crewBannerLines(C).some(L => /SHOOT OVER HIM/.test(L.texts[0]))) bad.push('the banner: ' + JSON.stringify(crewBannerLines(C)));
    const me = m.players.find(p => p.isHuman), them = m.players.find(p => !p.isHuman); m.crewCheer = null; m.bus.emit('BLOCK', { player: them, shooter: me }); if (m.crewCheer != null) bad.push('they cheered the other side'); m.bus.emit('STEAL', { player: me, victim: them }); if (m.crewCheer !== m.time) bad.push('no cheer for your steal');
    const cv = document.createElement('canvas'); cv.width = 640; cv.height = 360; try { crewCourtDraw(cv.getContext('2d'), g.cam, m, m.time); } catch (e) { bad.push('the bench draw throws: ' + e.message); }
    g.quitToMenu(); if (bad.length) throw new Error(bad.join(' · ')); return '6 on the bench, side ' + C.side + ' · the banner at +' + (m.crewBannerAt - m.time).toFixed(1) + ' s'; }));

  await step('an old save (§7): the 2.x staff join your crew at their tier (two seasons in: they know your game) and a signed agent at Lv3', () => ev(() => {
    const bad = [], c = __pro(48); c.me.crew = null; c.me.staff = { shooting: 3, trainer: 2, nutrition: 1 }; c.me.agent = 'Rosa Vance'; crewAgentLegacy(c); crewFromOld(c); /* (x30Migrate's order) */ const B = c.me, got = crewList(B).map(M => M.role + M.lv + (M.spec ? ':' + M.spec : '')).sort().join(' ');
    if (got !== 'agent3 physio1 skills3:shooting strength2') bad.push('the crew: ' + got); for (const M of crewList(B)) if (M.role !== 'agent' && crewEffLv(M) !== M.lv + 1) bad.push(M.role + ' doesn\'t know your game'); if (!crewMember(B, 'agent') || crewMember(B, 'agent').name !== 'Rosa Vance') bad.push('the agent');
    if (bad.length) throw new Error(bad.join(' · ')); return got; }));

  console.log(D.errors.length ? 'page errors: ' + D.errors.slice(0, 5).join(' | ') : 'no page errors');
  await browser.close();

  await step('the §7.6 crew table (the career simulator, the same careers each run): a full crew at Lv3 adds 25–40% legacy, every role alone at Lv3 at least +4%, the crew\'s salaries take 15–30% of a mid-career pro\'s income (the typical crew), most credits come from wins and tournaments', async () => {
    const N = process.env.CREW_N || '200', seeds = (process.env.CREW_SEEDS || '1,2,3,4,5,6').split(','), pols = ['none', 'full', 'auto', 'skills', 'scout', 'strength', 'physio', 'mental', 'agent'], J = {}, jobs = []; for (const p of pols) for (const s of seeds) jobs.push({ p, s });
    const run = j => new Promise(res => { let out = ''; const ch = spawn('node', [__dirname + '/careersim.js', N, j.s, '--crew=' + j.p, '--json']); ch.stdout.on('data', d => { out += d; }); ch.on('close', () => { const line = out.split('\n').find(l => l.startsWith('JSON ')); res(line ? JSON.parse(line.slice(5)) : null); }); });
    const got = {}; let k = 0; await Promise.all(Array.from({ length: Math.min(4, jobs.length) }, async () => { while (k < jobs.length) { const j = jobs[k++]; got[j.p + ':' + j.s] = await run(j); } })); /* (four at a time: the same careers in every run, seed by seed) */
    for (const p of pols) { const X = { legacy: [], peak: [], inj: [], crew: [], cash: [] }; for (const s of seeds) { const r = got[p + ':' + s]; if (!r) throw new Error('the simulator failed: ' + p + ' seed ' + s); for (const k2 in X) X[k2].push(...r[k2]); } J[p] = X; }
    const mean = a => a.reduce((s, v) => s + (v || 0), 0) / Math.max(1, a.length), med = a => { const s = a.filter(x => x != null).sort((x, y) => x - y); return s.length ? s[Math.floor(s.length / 2)] : null; }, base = J.none, bL = mean(base.legacy), bI = mean(base.inj), bE = med(base.cash.map(x => x && x.earned));
    const rows = [], bad = []; for (const p of pols) { const X = J[p], C = X.crew.filter(Boolean), d = X.legacy.map((v, i) => v - base.legacy[i]), dm = mean(d), se = Math.sqrt(d.reduce((s, v) => s + (v - dm) * (v - dm), 0) / Math.max(1, d.length - 1) / d.length), share = med(C.map(R => { const pp = R.proPay.slice(3, 8).reduce((s, v) => s + v, 0), ii = R.proInc.slice(3, 8).reduce((s, v) => s + v, 0); return ii > 0 ? pp / ii : null; })), cr = C.reduce((s, R) => { const x = R.credits || {}; s.all += x.all || 0; s.wt += (x.wins || 0) + (x.tn || 0); return s; }, { all: 0, wt: 0 });
      const r = { p, leg: 100 * dm / bL, se: 100 * se / bL, ovr: mean(X.peak) - mean(base.peak), inj: mean(X.inj) - bI, avoided: mean(C.map(R => R.inj || 0)), money: (med(X.cash.map(x => x && x.earned)) - bE) / 1e6, agent: mean(C.map(R => R.agentMoney || 0)) / 1e6, share, wt: cr.all ? cr.wt / cr.all : null }; rows.push(r);
      if (p === 'full' && !(r.leg >= 25 - r.se && r.leg <= 40 + r.se)) bad.push('a full crew: ' + r.leg.toFixed(1) + '% ±' + r.se.toFixed(1) + ' legacy (25–40)'); if (!['none', 'full', 'auto'].includes(p) && !(r.leg >= 4 - r.se)) bad.push(p + ' alone: ' + r.leg.toFixed(1) + '% ±' + r.se.toFixed(1) + ' legacy (at least 4)'); /* (a paired estimate: within its standard error of the target) */ if (p === 'auto' && !(share >= 0.15 && share <= 0.3)) bad.push('the typical crew\'s salaries: ' + Math.round(100 * share) + '% of income (15–30)'); if (p === 'auto' && !(r.wt >= 0.7)) bad.push('credits from wins and tournaments: ' + Math.round(100 * r.wt) + '%'); }
    console.log('  role      legacy        OVR    injuries  avoided  money    agent   pay/income  credits from wins+tournaments'); for (const r of rows) console.log('  ' + r.p.padEnd(9) + (r.p === 'none' ? '(' + bL.toFixed(1) + ')' : (r.leg >= 0 ? '+' : '') + r.leg.toFixed(1) + '% ±' + r.se.toFixed(1)).padEnd(14) + (r.ovr >= 0 ? '+' : '') + r.ovr.toFixed(2).padEnd(7) + (r.inj >= 0 ? '+' : '') + r.inj.toFixed(2).padEnd(10) + r.avoided.toFixed(2).padEnd(9) + ((r.money >= 0 ? '+' : '') + r.money.toFixed(1) + 'M').padEnd(9) + (r.agent.toFixed(1) + 'M').padEnd(8) + (r.share == null ? '–' : Math.round(100 * r.share) + '%').padEnd(12) + (r.wt == null ? '–' : Math.round(100 * r.wt) + '%'));
    if (bad.length) throw new Error(bad.join(' · ')); return N * seeds.length + ' careers a policy: full +' + rows[1].leg.toFixed(1) + '%, the weakest role +' + Math.min(...rows.slice(3).map(r => r.leg)).toFixed(1) + '%';
  });
  const f = R.done(); process.exit(f ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
