// 3.0 (§4.3–4.5, §11): teammates play, in the leagues below; transfers; the Overseas League; the PBL's teams. Every team
// has five; the four behind the starter play the league below (JV, the Reserve League, the PBL Development League) with
// real games, stat lines, standings and rankings; not starting, you play there (no lost seasons); the depth chart follows
// form (§11: a benched player who outplays the starter for 3 weeks takes the spot); the Transfers chart logs every move;
// high school's one transfer, the college portal, a pro buyout; a prospect no PBL franchise wants plays abroad and comes
// back; the Teams chart's cards; old saves keep their best four. Usage: node tests/lower.js
const { launch, openPage, runner } = require('./lib');
(async () => {
  const browser = await launch(); const P = await openPage(browser); const R = runner('lower'); const { ev } = P;
  await ev(() => {
    window.__adv = (a, n, until) => { let k = 0, g = 0; while (k++ < 2000 && g < n) { if (until && until(a)) break; a.events = []; a.inbox = []; if (a.summer && a.summer.pending) hsSummerChoose(a, 'rest'); else if (a.tryout && a.tryout.step !== 'done') hsSimTryout(a); else if (a.decision) { const d = a.decision; if (d.kind === 'portal') colPortalChoose(a, null); else if (d.kind === 'college' && d.signing) recSimSign(a); else if (d.kind === 'college') amChooseCollege(a, d.offers.find(o => !o.draft) || d.offers[0]); /* (college, not straight to the pros) */ else amDeclare(a, false); } else { amSimGame(a); g++; } } };
    window.__hs = (seed) => { const sv = defaultSave(); const a = amCreate(sv, { name: 'Lower Test', look: PRESET_LOOKS[seed % 6], number: 5, style: 'slasher', seed }); sv.c1 = a; __adv(a, 400, a => a.league && a.league.format === 'district'); return a; };
    window.__bench = (c, at) => { const L = ladderOf(c); L.splice(L.indexOf('me'), 1); L.splice(at || 2, 0, 'me'); if (!isPro(c)) hsSquadSync(c); };
  });
  await R.step('every team has five (high school, college, the pros): you and four teammates, five on the depth chart', () => ev(() => { const a = __hs(11), out = []; if (a.team.mates.length !== 4 || ladderOf(a).length !== 5) throw new Error('high school ' + a.team.mates.length); out.push('hs 5');
    __adv(a, 900, a => a.stage === 'college'); __adv(a, 1); if (a.team.mates.length !== 4 || ladderOf(a).length !== 5) throw new Error('college ' + a.team.mates.length); out.push('college 5');
    const c = testProLeague(12); if (c.team.mates.length !== 4 || ladderOf(c).length !== 5) throw new Error('pro ' + c.team.mates.length); for (const id of frIds()) if (id !== meOf(c).club && frBenchOf(c, id).length !== 4) throw new Error('a franchise bench of ' + frBenchOf(c, id).length); out.push('pro 5 · 16 benches of 4'); return out.join(' · '); }), P);
  await R.step('the leagues below play real games: standings, stat lines and rankings (JV, the Reserve League, the Development League)', () => ev(() => { const out = [];
    const a = __hs(21); __adv(a, 400, a => !a.league || a.league.playoffs); const W = a.lower; if (!W || W.lv !== 'hs') throw new Error('no JV'); const T = llStandRows(a), Pl = llPlayerRows(a); if (T.length !== 6 || T.some(t => t.w + t.l < 8)) throw new Error('JV teams ' + T.map(t => t.w + '-' + t.l)); if (Pl.length < 20 || Pl.some(p => !(p.ppg >= 0) || !(p.fg >= 0))) throw new Error('JV players ' + Pl.length); if (T.some(t => isNaN(t.diff))) throw new Error('margins'); out.push('JV ' + T.length + ' teams, ' + Pl.length + ' players · #1 ' + Pl[0].n + ' ' + Pl[0].ppg.toFixed(1));
    let b = null; for (const seed of [21, 22, 23, 24, 25, 26, 27, 28]) { const x = __hs(seed); __adv(x, 900, x => x.stage !== 'hs'); if (x.stage === 'college') { b = x; break; } } if (!b) throw new Error('no career went to college'); /* (a weak recruit turns pro instead) */
    __adv(b, 400, b => b.league && b.league.week >= 2); __adv(b, 400, b => !b.league || b.league.playoffs); const C = llStandRows(b), CP = llPlayerRows(b); if (b.lower.lv !== 'college' || C.length < 6 || CP.length < 20) throw new Error('Reserve ' + C.length + '/' + CP.length); out.push('Reserve ' + C.length + ' teams, ' + CP.length + ' players');
    const sv = defaultSave(), c = testProLeague(13, sv); sv.career = c; sv.c1.handedOff = true; let k = 0; while (c.phase === 'regular' && k++ < 40) simUserGame(sv); const D = llStandRowsOf(c.lower, null), DP = llPlayerRowsOf(c.lower, null); if (c.lower.lv !== 'pro' || D.length !== 16 || DP.length < 64 || DP.length > 64 + 4 || c.lower.wk !== c.schedule.length) /* 4.0 (§0.5): 64 slots, plus anyone who moved between the leagues (the fixture's OVR-43 player loses the start to teammates in the 60s now) */ throw new Error('Dev League ' + D.length + '/' + DP.length + ' wk ' + c.lower.wk); out.push('Dev League 16 teams, ' + DP.length + ' players, ' + c.lower.wk + ' weeks'); return out.join(' · '); }), P);
  await R.step('§11: a benched player who outplays the starter for 3 weeks takes the spot (and not after 2; not by a hair: the starter keeps ties within the edge)', () => ev(() => {
    const a = __hs(31); __bench(a, 3); const L = ladderOf(a), st = L[0], T = a.team; T.form = {}; T.hot = {}; for (const id of L) T.form[id] = [10, 10, 10];
    const week = (me, s) => { llForm(a, 'me', me); llForm(a, st, s); for (const id of L) if (id !== 'me' && id !== st) llForm(a, id, 5); return llDepthWeek(a); };
    if (week(30, 10) || week(30, 10)) throw new Error('swapped after 2 weeks'); if (ladderRank(a) === 1) throw new Error('starting after 2 weeks'); const r = week(30, 10); if (!r || r.up !== 'me' || ladderRank(a) !== 1 || a.squad !== 'varsity') throw new Error('no swap after 3 weeks: #' + ladderRank(a));
    if (!(a.events || []).some(e => e.kind === 'depth' && e.title === 'YOU START')) throw new Error('no YOU START news'); if (!(a.tx || []).some(t => t.kind === 'callup' && t.me)) throw new Error('no call-up in the Transfers log');
    const b = __hs(32); __bench(b, 2); const L2 = ladderOf(b), st2 = L2[0]; b.team.form = {}; b.team.hot = {}; b.team.trust = 50; for (let i = 0; i < 6; i++) { llForm(b, 'me', 11); llForm(b, st2, 10); llDepthWeek(b); } if (ladderRank(b) === 1) throw new Error('a point ahead (inside the edge ' + TM.depth.edge + ') took the spot');
    return 'swap on week 3 · ' + TM.depth.weeks + ' weeks, the last ' + TM.depth.games + ' games, edge ' + TM.depth.edge; }), P);
  await R.step('not starting, you play the league below every regular-season week (playable: its match; simmed: its result), and your team plays its game too', () => ev(() => {
    const a = __hs(41); __bench(a, 3); a.team.form = {}; a.team.hot = {}; const g = amNext(a); if (!g || !g.ll || !g.opp || !/JV/.test(g.opp.team)) throw new Error('no JV game: ' + JSON.stringify(g && g.opp && g.opp.team)); const o = amMatchOpts(HH.game, a, g.opp, 0); if (!o || o.teams[1].players[0].name !== g.opp.name) throw new Error('the match');
    const L = a.league, w0 = L.week, tg = L.games.length, r = amSimGame(a); if (!r || !r.ll || r.bench || L.week !== w0 + 1 || L.games.length !== tg + 1 || !L.games[tg].ll) throw new Error('the week: ' + JSON.stringify({ ll: r && !!r.ll, bench: r && r.bench, wk: L.week }));
    if (!a.lower.P.me || a.lower.P.me.g !== 1 || a.seasonStats.g !== (a.seasonStats.g | 0)) throw new Error('your JV line'); if (!(r.gains && (Array.isArray(r.gains) ? r.gains.length >= 0 : true))) throw new Error('XP');
    let weeks = 1, games = 1; while (a.league && !a.league.playoffs && a.league.week < a.league.schedule.length && weeks < 20) { if (isStarter(a)) __bench(a, 3); a.team.hot = {}; a.events = []; const q = amSimGame(a); weeks++; if (q && q.ll) games++; } if (games < weeks - (a.ineligible > 0 ? 2 : 0)) throw new Error('lost weeks: ' + games + ' of ' + weeks);
    const sv = defaultSave(), c = testProLeague(42, sv); sv.career = c; sv.c1.handedOff = true; __bench(c, 3); c.team.hot = {}; const G = llMyGameSafe(c); if (!G) throw new Error('no Dev League game'); const mo = devMatchOpts(HH.game, c, G); if (!mo || mo.teams[1].players[0].name !== G.sheet.n) throw new Error('the Dev League match'); const rec = simUserGame(sv); if (!rec || !rec.ll || rec.ll.lv !== 'pro' || !rec.ll.team) throw new Error('the Dev League week ' + JSON.stringify(rec && rec.ll));
    return 'JV: ' + games + ' games in ' + weeks + ' weeks · Dev League: ' + rec.ll.short + ' ' + rec.my + '-' + rec.their + ', the team ' + rec.ll.team.my + '-' + rec.ll.team.their; }), P);
  await R.step('the depth chart over whole careers: swaps happen, but a starter far better rarely loses the spot', () => ev(() => { let swaps = 0, bad = 0, seasons = 0;
    for (let i = 0; i < 8; i++) { const sv = defaultSave(); const a = amCreate(sv, { name: 'Depth ' + i, look: PRESET_LOOKS[i % 6], number: 5, style: ['slasher', 'sharpshooter', 'postscorer', 'playmaker'][i % 4], seed: 7000 + i }); sv.c1 = a; let k = 0, s0 = a.season;
      while (k++ < 700 && a.stage !== 'combine') { a.events = []; a.inbox = []; if ((a.summer && a.summer.pending) || (a.tryout && a.tryout.step !== 'done') || a.decision) { __adv(a, 0); __adv(a, 1); continue; } const T0 = a.team, L0 = T0 ? (ladderOf(a) || []).slice() : null; amSimGame(a); const L1 = a.team === T0 && a.team ? ladderOf(a) : null; if (L0 && L1 && L0[0] !== L1[0]) { swaps++; const o = id => (llPlayer(a, id) || { ovr: 0 }).ovr; if (o(L0[0]) - o(L1[0]) >= 8) bad++; } if (a.season !== s0) { seasons++; s0 = a.season; } } }
    if (!swaps) throw new Error('no swaps'); if (bad / swaps > 0.15) throw new Error('8+ OVR better starters benched: ' + bad + ' of ' + swaps); return swaps + ' swaps in ' + seasons + ' seasons · ' + bad + ' of the starter 8+ OVR better'; }), P);
  await R.step('transfers (§4.4): the PBL offseason logs trades, signings, free agents, call-ups and send-downs; the chart lists them; headlines for the big ones', () => ev(() => {
    const sv = defaultSave(), c = testProLeague(51, sv); sv.career = c; sv.c1.handedOff = true; let k = 0; while (c.phase !== 'offseason' && k++ < 80) { if (!simUserGame(sv) && c.phase === 'playoffs') simPlayoffsToEnd(c); c.events = []; } if (c.phase !== 'offseason') throw new Error('no offseason: ' + c.phase);
    lgOffseasonAuto(c, {}); const K = {}; for (const t of c.tx || []) K[t.kind] = (K[t.kind] || 0) + 1; for (const k2 of ['trade', 'signing', 'fa']) if (!K[k2]) throw new Error('no ' + k2 + ': ' + JSON.stringify(K)); const rows = txRows(c, 0).concat(txRows(c, 1)); if (rows.length < 10) throw new Error('chart rows ' + rows.length); if (!(c.tx || []).every(t => t.who && t.from && t.to && t.kind)) throw new Error('a row without its fields');
    return Object.keys(K).map(k2 => k2 + ' ' + K[k2]).join(', '); }), P);
  await R.step('high school\'s one transfer: a message after the season (up, down or stay); up: better teammates, the school changes, once', () => ev(() => {
    const a = __hs(61); __adv(a, 400, a => (a.events || []).some(e => e.kind === 'hstransfer') || a.stageYear >= 2 && a.league && a.league.week === 0); const ev = (a.events || []).find(e => e.kind === 'hstransfer') || hsTransferOffer(a); if (!ev || !ev.up || !ev.down) throw new Error('no message');
    if (evClass(ev, a) !== 'message') throw new Error('class ' + evClass(ev, a)); const from = a.school, me0 = ladderRank(a), r = hsTransferAnswer(a, ev, 'up'); if (!r || a.school === from || a.team.name !== a.school || ladderOf(a).length !== 5) throw new Error('the transfer');
    if (hsTransferOffer(a)) throw new Error('a second transfer offered'); if (!(a.tx || []).some(t => t.kind === 'transfer' && t.me)) throw new Error('the Transfers log'); return from + ' → ' + a.school + ' · #' + me0 + ' → #' + ladderRank(a); }), P);
  await R.step('the Overseas League: under the scouts\' bar no PBL franchise calls; a season abroad (eleven games and a final four); the PBL calls after a top-3 finish or a second season', () => ev(() => {
    const sv = defaultSave(); const a = amCreate(sv, { name: 'Abroad Test', look: PRESET_LOOKS[1], number: 5, style: 'slasher', seed: 71 }); sv.c1 = a; a.age = 22; a.stage = 'combine'; a.events = []; if (!ovsNoOffers(a)) throw new Error('score ' + amDraftScore(a) + ' had PBL offers');
    const O = ovsOffers(a); if (O.length !== 3 || O.some(o => !o.name || !o.ctry)) throw new Error('offers'); ovsSign(a, O[0]); if (a.stage !== 'overseas' || !a.league || a.league.opps.length !== 11 || a.league.schedule.length !== 11) throw new Error('the season ' + a.stage);
    for (const k of ['g', 'pts']) if (a.seasonStats[k] !== 0) throw new Error('a fresh line');
    for (const r of a.league.opps) if (!OVS.clubs.some(k => k.name === r.team)) throw new Error('an opponent from ' + r.team);
    let k = 0; while (k++ < 60 && a.stage === 'overseas') { a.events = []; amSimGame(a); } if (a.stage !== 'combine' || !(a.ovs && a.ovs.done) || ovsNoOffers(a)) throw new Error('back: ' + a.stage + ' ' + JSON.stringify(a.ovs));
    const P2 = proEntryOffers(a); if (!P2.offers.length) throw new Error('no PBL offers after'); const c = createCareerFromAmateur(sv, a, P2.offers[0]); if (!c || !(c.tx || []).some(t => t.kind === 'pro')) throw new Error('the pro entry'); return a.ovs.seasons + ' season(s) abroad · ' + (a.ovs.top ? 'top 3' : 'two seasons') + ' · ' + P2.offers.length + ' PBL offers'; }), P);
  await R.step('the pros\' Overseas League plays in the background; the best come back in free agency, players nobody signs go abroad', () => ev(() => {
    const sv = defaultSave(), c = testProLeague(81, sv); sv.career = c; sv.c1.handedOff = true; let k = 0; while (c.phase === 'regular' && k++ < 40) simUserGame(sv); const O = c.ovs; if (!O || Object.keys(O.T).length !== 12 || O.wk !== c.schedule.length) throw new Error('the league ' + (O && O.wk)); const rows = llPlayerRowsOf(O, null); if (rows.length !== 12) throw new Error('players ' + rows.length);
    const pool = []; ovsReturns(c, pool); const best = pool.filter(e => e.why === 'overseas'); for (const e of best) if (e.ovr < OVS.backOvr) throw new Error('a return under the bar'); const fa = [{ m: tmMakeMate(c, new RNG(5), 'pro', 79, 'fbx1', new Set(), 0), from: null, why: 'expired', ovr: 79, age: 27 }]; fa[0].ovr = tmMateOvr(fa[0].m); ovsTakeUnsigned(c, fa); if (!Object.values(c.ovs.T).some(T => T.star === fa[0].m)) throw new Error('the unsigned 79 did not go abroad');
    return '12 clubs, ' + O.wk + ' weeks · back: ' + best.length + ' · abroad: ' + fa[0].m.name; }), P);
  await R.step('a pro buyout: the trade message\'s third answer; paid out, and a free agent this offseason', () => ev(() => {
    const sv = defaultSave(), c = testProLeague(91, sv); sv.career = c; sv.c1.handedOff = true; for (let i = 0; i < 3; i++) simUserGame(sv); c.me.contract = Object.assign({}, c.me.contract, { years: 3, salary: 2e6 }); const m0 = c.me.money, ev = { kind: 'trade', title: 'UNHAPPY', why: 'bench', lines: ['x'] }; const B = proBuyoutAnswer(c, ev); if (!B || !(B.pay > 0) || c.me.money <= m0) throw new Error('the pay');
    let k = 0; while (c.phase !== 'offseason' && k++ < 80) { if (!simUserGame(sv) && c.phase === 'playoffs') simPlayoffsToEnd(c); c.events = []; } if (c.phase !== 'offseason') throw new Error('no offseason'); c.offseason.ticker = c.offseason.ticker || []; const F = lgUserFaOpen(c, careerRng(c)); if (!F.free) throw new Error('not a free agent'); return 'paid ' + fmtMoney(B.pay) + ' · free agency with ' + F.offers.length + ' offers'; }), P);
  await R.step('the PBL\'s teams (§4.5): sixteen cards with record, rank, stars, title odds, window and best players; dynasties', () => ev(() => {
    const sv = defaultSave(), c = testProLeague(101, sv); sv.career = c; sv.c1.handedOff = true; for (let i = 0; i < 5; i++) simUserGame(sv); const D = teamCards(c); if (D.length !== 16) throw new Error('cards ' + D.length);
    for (const d of D) { if (!(d.stars >= 1 && d.stars <= 5) || d.w + d.l !== 5 || !d.best.length || !d.window) throw new Error('a card ' + JSON.stringify(d)); } const O = frOdds(c); const sum = frIds().reduce((s, id) => s + (O.byClub[id] || 0), 0); if (Math.abs(sum - 1) > 0.02) throw new Error('odds sum ' + sum);
    const id = D[0].id, F = frx(c, id); F.titles.push({ s: c.season - 1, who: 'x' }, { s: c.season, who: 'x' }); F.streak = 2; if (frDynastyWord(c, id) !== 'BACK-TO-BACK') throw new Error('dynasty ' + frDynastyWord(c, id)); return D.slice(0, 3).map(d => d.n + ' ' + d.w + '-' + d.l).join(', '); }), P);
  await R.step('old saves: a longer roster keeps its best four; a pending challenge card goes; nothing pending on the team', () => ev(() => {
    const sv = defaultSave(); const a = amCreate(sv, { name: 'Old Roster', look: PRESET_LOOKS[3], number: 5, style: 'slasher', seed: 111 }); sv.c1 = a; __adv(a, 2); const T = a.team, rng = new RNG(9), used = new Set(T.mates.map(m => m.name)); for (let i = 0; i < 3; i++) T.mates.push(tmMakeMate(a, rng, 'hs', 70, 'old' + i, used, 2)); ladderRepair(a); T.pending = T.mates[0].id; a.events.push({ kind: 'ladder', mate: T.mates[0].id, title: 'CHALLENGE!' });
    const s2 = migrateSave(JSON.parse(JSON.stringify(sv))), b = s2.c1; if (b.team.mates.length !== 4 || ladderOf(b).length !== 5 || b.team.pending) throw new Error('roster ' + b.team.mates.length); if ((b.events || []).some(e => e.kind === 'ladder')) throw new Error('the challenge card'); return 'kept ' + b.team.mates.map(m => tmMateOvr(m)).join('/'); }), P);
  console.log('errors: ' + (P.errors.length ? P.errors.slice(0, 5).join(' | ') : 'none')); const fail = R.done(); await browser.close(); process.exit(fail ? 1 : 0);
})();
