// Phone audit (M9): opens about 130 screens at 844×390 with touch (or at a desktop size) and lists every tap target under
// 64 CSS px (width or height), widgets off the screen, overlapping widgets, overlapping text (F4), text cut short with "…"
// (F7), text a figure covers (F10) and the smallest text each screen draws. It plays a scripted career to reach the later screens.
// Usage: node tests/phoneaudit.js [shotsDir] [--desktop] [--size=WxH@dpr] [--text125]
const path = require('path'), fs = require('fs');
const { launch, openPage } = require('./lib');
(async () => {
  const sizeArg = (process.argv.find(a => a.startsWith('--size=')) || '').slice(7), sz = /^(\d+)x(\d+)(?:@([\d.]+))?$/.exec(sizeArg); /* F4: --size=WxH[@dpr] runs the desktop audit in any window */
  const desk = process.argv.includes('--desktop') || !!sz, big = process.argv.includes('--text125'); /* R10: --text125 runs every screen at the 1.25× text size */ const dir = process.argv.slice(2).find(a => !a.startsWith('--')); if (dir) fs.mkdirSync(dir, { recursive: true });
  const browser = await launch(); const P = await openPage(browser, sz ? { viewport: { width: +sz[1], height: +sz[2] }, dpr: +(sz[3] || 1) } : { phone: !desk }); /* --desktop: the same screens at 1280×720 (overflow, overlap and off-screen only) */ const { page, ev } = P; const wait = ms => page.waitForTimeout(ms);
  await ev(() => { const F = CanvasRenderingContext2D.prototype.fillText; window.__txt = []; CanvasRenderingContext2D.prototype.fillText = function (t, x, y, mw) { try { const m = /(\d+(?:\.\d+)?)px/.exec(this.font); if (m && window.__txtOn && String(t).trim()) { const a = this.getTransform().a / (window.devicePixelRatio || 1); window.__txt.push({ px: +m[1] * a, t: String(t).slice(0, 40) }); } } catch (e) {} return F.call(this, t, x, y, mw); }; });
  // text wider than the widget it is drawn in (a label running off its button)
  await ev(() => { const U = UI.prototype, D = U.drawWidget; window.__ovf = new Set(); U.drawWidget = function (ctx, w, f) { const F = ctx.fillText; ctx.fillText = function (t, x, y, mw) { try { if (window.__txtOn && w.kind !== 'text') { const m = Math.min(ctx.measureText(String(t)).width, mw > 0 ? mw : 1e9), al = ctx.textAlign; /* a maxWidth draws the text truncated to fit (the bitmap font adds …) */ const x0 = al === 'center' ? x - m / 2 : al === 'right' || al === 'end' ? x - m : x; if (x0 < w.x - 3 || x0 + m > w.x + w.w + 3) window.__ovf.add((w.label || w.kind) + ': "' + String(t).slice(0, 34) + '"'); } } catch (e) {} return F.call(this, t, x, y, mw); }; try { return D.call(this, ctx, w, f); } finally { delete ctx.fillText; } }; });
  // F4 (the user: "text overlaps, so we can't read other stuff"): every string's ink box from one synchronous UI draw;
  // two different strings whose boxes share more than a font pixel each way are flagged.
  await ev(() => { const U = UI.prototype, DS = U.drawScreen; U.drawScreen = function (ctx, s) { const on = RBF.boxes; if (!on || s === this.screen) return DS.call(this, ctx, s); const n0 = on.length; try { return DS.call(this, ctx, s); } finally { for (let i = n0; i < on.length; i++) on[i].under = s.name || '?'; } }; }); // V1: a screen under the top one: its strings are tagged (the two-screens check), the other checks skip them
  await ev(() => { const U = UI.prototype, DW = U.drawWidget; U.drawWidget = function (ctx, w, f) { const n0 = RBF.boxes ? RBF.boxes.length : 0; try { return DW.call(this, ctx, w, f); } finally { if (RBF.boxes) for (let i = n0; i < RBF.boxes.length; i++) RBF.boxes[i].w8 = w; } }; }); // F4: which widget drew each string (a string drawn outside every widget must not run under one) // only the top screen's text: an overlay's panel hides the screen under it
  await ev(() => { window.__textOverlaps = () => { const g = HH.game; RBF.boxes = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const raw = (RBF.boxes || []).filter(b => !b.under); RBF.boxes = null; const B = [];
    for (const b of raw) { if (!String(b.t).trim() || b.a < 0.35 || b.w < 1) continue; if (B.some(a => a.t === b.t && Math.abs(a.x - b.x) <= 4 * b.s && Math.abs(a.y - b.y) <= 4 * b.s)) continue; B.push(b); }
    const out = []; for (let i = 0; i < B.length; i++) for (let j = i + 1; j < B.length; j++) { const a = B[i], b = B[j]; if (a.t === b.t) continue; const px = Math.max(a.s, b.s), ix = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x), iy = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y); if (ix > px && iy > px) out.push('"' + String(a.t).slice(0, 28) + '" × "' + String(b.t).slice(0, 28) + '"'); }
    const ui = g.ui, s = ui.screen, dpr = g.dpr, ws = ((s && s.widgets) || []).filter(w => !w.hidden && w.w > 0 && w.h > 0); // a string drawn by the screen (not by a widget) under a widget's box
    for (const b of B) { if (b.w8) continue; for (const w of ws) { if (w.label && String(w.label).trim() === String(b.t).trim()) continue; /* a screen drawing a widget's own symbol */ const x0 = (ui.ox + w.x * ui.scale) * dpr, y0 = (ui.oy + w.y * ui.scale) * dpr, x1 = x0 + w.w * ui.scale * dpr, y1 = y0 + w.h * ui.scale * dpr, ix = Math.min(b.x + b.w, x1) - Math.max(b.x, x0), iy = Math.min(b.y + b.h, y1) - Math.max(b.y, y0); if (ix > 2 * b.s && iy > 2 * b.s) { out.push('"' + String(b.t).slice(0, 28) + '" under [' + String(w.label || w.kind).slice(0, 20) + ']'); break; } } }
    return out; }; });
  // F7: text cut short with '…' (a maxW, the screen edge or a line limit) hides what it says: the top screen's strings
  // from one synchronous UI draw that the font or a paragraph cut (faint text a<0.35 skipped).
  await ev(() => { window.__textCuts = () => { const g = HH.game; RBF.boxes = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const raw = RBF.boxes || []; RBF.boxes = null; const out = []; for (const b of raw) if (b.cut && !b.under && b.a >= 0.35 && !out.includes(String(b.cut).slice(0, 48))) out.push(String(b.cut).slice(0, 48)); return out; }; });
  // F10: a figure (a menu figure, a portrait, a trading card) drawn after a string and over at least a quarter of it hides
  // it: the top screen's strings from one synchronous UI draw against each figure's box (faint text a<0.35 skipped).
  await ev(() => { window.__artOverText = () => { const g = HH.game; RBF.boxes = []; RBF.art = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const raw = RBF.boxes || [], art = RBF.art || []; RBF.boxes = null; RBF.art = null; const out = [];
    for (const A of art) for (let i = 0; i < Math.min(A.n, raw.length); i++) { const b = raw[i]; if (b.under || !String(b.t).trim() || b.a < 0.35 || b.w < 1) continue; const ix = Math.min(b.x + b.w, A.x + A.w) - Math.max(b.x, A.x), iy = Math.min(b.y + b.h, A.y + A.h) - Math.max(b.y, A.y); if (ix > 0 && iy > 0 && ix * iy >= 0.25 * b.w * b.h) { const k = '"' + String(b.t).slice(0, 28) + '" under a ' + A.kind; if (!out.includes(k)) out.push(k); } }
    return out; }; });
  // V1 (§1.8): two screens' words at once: every string the screens under the top one draw (an overlay's underlay) that
  // shares more than a font pixel each way with a string of the top screen, from one synchronous UI draw.
  await ev(() => { window.__twoScreens = () => { const g = HH.game, ui = g.ui, top = ui.screen, wrapped = []; RBF.boxes = [];
    const drawn = []; for (const s of ui.stack) if (s !== top && typeof s.draw === 'function') { const d = s.draw; wrapped.push([s, d]); s.draw = function () { drawn.push(s.name || '?'); const n0 = RBF.boxes ? RBF.boxes.length : 0; try { return d.apply(this, arguments); } finally { if (RBF.boxes) for (let i = n0; i < RBF.boxes.length; i++) RBF.boxes[i].under = s.name || '?'; } }; }
    try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } finally { for (const [s, d] of wrapped) s.draw = d; }
    const raw = RBF.boxes || []; RBF.boxes = null; const U = raw.filter(b => b.under && String(b.t).trim() && b.a >= 0.05), Tp = raw.filter(b => !b.under && String(b.t).trim() && b.a >= 0.35), out = [];
    if (g.mode !== 'match' && top && top.overlay) for (const n of [...new Set(drawn)]) out.push('(' + n + ' drawn under the ' + (top.name || '?') + ' overlay)'); // a screen under an overlay shows its art and sprite text too
    for (const u of U) for (const b of Tp) { const px = Math.max(u.s, b.s), ix = Math.min(u.x + u.w, b.x + b.w) - Math.max(u.x, b.x), iy = Math.min(u.y + u.h, b.y + b.h) - Math.max(u.y, b.y); if (ix > px && iy > px) { const k = '"' + String(u.t).slice(0, 24) + '" (' + u.under + ') under "' + String(b.t).slice(0, 24) + '"'; if (!out.includes(k)) out.push(k); } }
    return out; }; });
  // V1 (§1.8): a push or pop never shows two screens at once (the old one is gone before the new one shows)
  { const tr = await ev(() => { if (typeof uiTransAlphas !== 'function') return { bad: ['0 to 1 (a cross-fade)'], end: [0, 1] }; const bad = []; for (let i = 0; i <= 100; i++) { const a = uiTransAlphas(i / 100); if (Math.min(a[0], a[1]) > 0) bad.push((i / 100).toFixed(2)); } const end = uiTransAlphas(1); return { bad, end }; });
    console.log((tr.bad.length || tr.end[0] !== 0 || tr.end[1] !== 1 ? 'FLAG  ' : 'ok    ') + 'transitions (push/pop: never two screens at once)' + (tr.bad.length ? ': TWO SCREENS at k = ' + tr.bad.slice(0, 6).join(', ') : '')); }
  if (big) await ev(() => { const D0 = defaultSave; window.defaultSave = () => { const d = D0(); d.settings.textSize = 1.25; return d; }; RBF.textScale = 1.25; });
  await ev(() => { localStorage.clear(); const g = HH.game; g.save = new SaveSystem(); const a = amCreate(g.save.data, { name: 'Phone Audit', look: PRESET_LOOKS[2], number: 5, style: 'slasher', seed: 31 }); a.events.length = 0; g.save.save(); });
  const audit = async (name, open, arg) => {
    await ev(open, arg); await ev(() => { if (typeof REC_TOASTS !== 'undefined') REC_TOASTS.length = 0; HH.game.ui.toastT = 0; }); /* V8: a toast is an overlay (a record broken in the scripted career would cover the next screens); story.js checks the record toast */ await wait(450); await ev(() => { const s = HH.game.ui.screen; if (s && s.finish) s.finish(); }); /* R9: a dialogue box's text typed out */ await wait(80); await ev(() => { window.__txt = []; window.__ovf.clear(); window.__txtOn = true; }); await wait(120); const ovf = await ev(() => [...window.__ovf]); const tx = await ev(() => { window.__txtOn = false; const L = window.__txt.filter(o => o.px > 0.5).sort((a, b) => a.px - b.px); const seen = new Set(), out = []; for (const o of L) { if (seen.has(o.t)) continue; seen.add(o.t); out.push(o); if (out.length >= 3) break; } return out; });
    const r = await ev(() => { const ui = HH.game.ui, s = ui.screen; if (!s) return { name: '(none)', bad: [] }; const ws = (s.widgets || []).filter(w => !w.hidden && w.enabled !== false && w.kind !== 'text'); const bad = [];
      for (const w of ws) { const hh = w.h * ui.scale, ww = w.w * ui.scale; if (ui.phone && (hh < 63.5 || ww < 63.5)) bad.push((w.label || w.kind) + ' ' + Math.round(ww) + '×' + Math.round(hh)); if (w.x < -1 || w.y < -1 || w.x + w.w > UI_W + 1 || w.y + w.h > UI_H + 1) bad.push('OFFSCREEN ' + (w.label || w.kind)); if (!(w.w >= 1 && w.h >= 1)) bad.push('ZERO-SIZE ' + (w.label || w.kind)); /* R9: a widget never laid out (it once threw inside its draw and leaked a zoom) */ }
      for (let i = 0; i < ws.length; i++) for (let j = i + 1; j < ws.length; j++) { const a = ws[i], b = ws[j]; if (a.x < b.x + b.w - 1 && b.x < a.x + a.w - 1 && a.y < b.y + b.h - 1 && b.y < a.y + a.h - 1) bad.push('OVERLAP ' + (a.label || a.kind) + ' / ' + (b.label || b.kind)); }
      return { name: s.name, n: ws.length, bad }; });
    if (dir) await P.shot(path.join(dir, name + '.jpg'));
    for (const o of ovf) r.bad.push('TEXT OVERFLOW ' + o);
    for (const o of await ev(() => window.__textOverlaps())) r.bad.push('TEXT OVERLAP ' + o); // F4
    for (const o of await ev(() => window.__textCuts())) r.bad.push('TEXT CUT "' + o + '"'); // F7
    for (const o of await ev(() => window.__twoScreens())) r.bad.push('TWO SCREENS ' + o); // V1 (§1.8)
    for (const o of await ev(() => window.__artOverText())) r.bad.push('ART OVER TEXT ' + o); // F10
    const minTxt = tx.length ? tx[0].px : 99; texts.push({ name, min: minTxt, tx });
    console.log((r.bad.length ? 'FLAG  ' : 'ok    ') + name + ' (' + r.name + ', ' + r.n + ' widgets, min text ' + minTxt.toFixed(1) + ' px)' + (r.bad.length ? ': ' + r.bad.slice(0, 12).join(' | ') + (r.bad.length > 12 ? ' …+' + (r.bad.length - 12) : '') : ''));
  };
  const texts = [];
  await audit('menu-new', () => { const g = HH.game; g.__c1 = g.save.data.c1; g.save.data.c1 = null; g.ui.clearTo(mainMenu(g)); }); await ev(() => { const g = HH.game; g.save.data.c1 = g.__c1; delete g.__c1; }); // F10: a new player's menu (no career yet: the league's pitch beside two players)
  await audit('title', () => HH.game.ui.clearTo(titleScreen(HH.game))); // R10: every screen
  await audit('menu', () => HH.game.ui.clearTo(mainMenu(HH.game)));
  for (let t = 0; t < 5; t++) await audit('settings-' + t, t => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(settingsScreen(g, t)); }, t); // R10: the five tabs
  if (desk) await audit('dev', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(devScreen(g)); }); // R10: the dev menu (a keyboard's ` key)
  if (desk) await audit('remap', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(remapScreen(g)); }); // R10: key remapping (keyboards only: a phone doesn't show it)
  await audit('slots', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.save.save(); g.ui.push(slotsScreen(g)); }); // R10: three save slots
  await audit('credits', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(creditsScreen(g)); });
  await audit('splash', () => { const g = HH.game; g.ui.clearTo(splashScreen(g)); }); await P.ev(() => HH.game.ui.clearTo(mainMenu(HH.game)));
  await audit('tip', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(tipScreen(g, 'ladder')); }); // R10: a first-time tip
  await audit('howto', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(howToScreen(HH.game)); });
  await audit('practice-hub', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(practiceHubScreen(HH.game)); }); // F1: Practice replaces Extras
  await audit('quickplay', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(quickPlayScreen(HH.game)); });
  await audit('threept', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(threePointScreen(HH.game)); });
  await audit('free-practice', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(practiceHubScreen(HH.game)); HH.game.ui.screen.widgets.find(w => w.label === 'Shooting practice').onPress(); });
  await audit('confirm', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(settingsScreen(g)); g.ui.push(confirmScreen(g, 'Erase everything, including your career and Hall of Fame?', () => {})); });
  await audit('keyboard', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(keyboardScreen(g, 'Rookie', () => {})); });
  await audit('halloffame', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(hallOfFameScreen(HH.game)); });
  await audit('create', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(createPlayerScreen(HH.game)); });
  await audit('customize-face', () => { const g = HH.game; const s = g.ui.screen; const w = (s.widgets || []).find(x => /face|Customize|Edit/i.test(x.label || '')); if (w) w.onPress(); });
  await audit('am-hub', () => { const g = HH.game; g.hubTab = 'play'; g.ui.clearTo(amHub(g)); });
  for (const tab of ['train', 'me', 'team', 'shop']) await audit('am-hub-' + tab, t => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.hubTab = t; g.ui.clearTo(amHub(g)); }, tab); // V5 (2.0 §5): the hub's five tabs
  await audit('am-road', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.hubTab = 'play'; g.ui.clearTo(amHub(g)); g.ui.push(roadScreen(g)); }); // V5 (2.0 §4.1)
  await audit('am-roadcard', () => { const g = HH.game, a = g.save.data.c1; g.hubTab = 'play'; g.ui.clearTo(amHub(g)); a.events = [{ kind: 'road', id: 'offer', title: 'A COLLEGE OFFER', reward: 'Basic court shoes, free: +0.5 Speed in games.', lines: ['Get a college scholarship offer.', 'Reward: Basic court shoes, free: +0.5 Speed in games.', 'Next on the road: start in college.'] }]; g.ui.push(amEventScreen(g)); });
  await audit('am-simsummary', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.hubTab = 'play'; g.ui.clearTo(amHub(g)); g.ui.push(simSummaryScreen(g, { mode: 'big', weeks: 3, w: 2, l: 1, pts: 37, games: 3, bench: 0, lines: ['Report card.', 'Level up: Clutch Gene (Silver).', 'Road to the League: a college offer. Basic court shoes, free: +0.5 Speed in games.'], stop: 'next: a game against your rival' }, () => g.ui.pop())); }); // V5 (2.0 §4.2)
  await audit('am-hub-play-again', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.hubTab = 'play'; g.ui.clearTo(amHub(g)); });
  for (const t of ['buzz', 'team', 'money']) await audit('am-guide-' + t, t => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(statsGuideScreen(g, t)); }, t); // F9: the stats guide (an amateur)
  await audit('am-gear', () => { const g = HH.game, a = g.save.data.c1; a.cash = 2600; a.gear = { sleeve: 1, shoes: 2 }; g.ui.clearTo(amHub(g)); g.ui.push(gearScreen(g)); }); // F8: the gear shop
  await audit('am-tryout', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(tryoutScreen(g)); }); // R5: tryouts, the shootout first
  await audit('am-tryout-1v1', () => { const g = HH.game, a = g.save.data.c1; if (a.tryout && a.tryout.step === 'drill') hsTryoutDrill(a, 12); g.ui.clearTo(amHub(g)); g.ui.push(tryoutScreen(g)); }); // R5: then the 1v1 against a senior
  await audit('am-tryout-post', () => { const g = HH.game; g.ui.push(tryoutPostScreen(g, { contest3: { score: 12 }, winner: 0, teams: [{ score: 7 }, { score: 5 }] }, { part: 'none' })); }); // R10: the tryout's result card
  await audit('am-team', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(teamScreen(g)); }); // R3
  await audit('am-genes-2', () => { const g = HH.game, a = g.save.data.c1; a.events.unshift({ kind: 'genes', title: 'YOUR GENES', lines: [] }); g.ui.clearTo(amHub(g)); g.ui.push(amEventScreen(g)); const s = g.ui.screen; s.widgets[0].onPress(); }); // R3: page 2
  await audit('am-trait-reveal', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.events.push({ kind: 'trait', title: 'HIDDEN TRAIT: ' + traitName(a.tr.hidden).toUpperCase(), trait: a.tr.hidden, lines: ['A story line about the trait.', traitUpText(a.tr.hidden, 1) + '.', 'The catch: ' + traitDownText(a.tr.hidden) + '.'] }); g.ui.clearTo(amHub(g)); g.ui.push(amEventScreen(g)); }); // R3
  await audit('am-trait-card', () => { const g = HH.game, a = g.save.data.c1; g.ui.clearTo(amHub(g)); g.ui.push(traitCardScreen(g, a.tr.sig, a)); }); // V3 (§2.3): a trait's card, from a chip
  await audit('trait-card-legendary', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(traitCardScreen(g, 'generational', null)); }); // V3: the longest card
  for (let part = 0; part < (desk ? 1 : 2); part++) await audit('codex-traits-' + part, part => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(statsGuideScreen(g, 'traits')); if (part) { const w = g.ui.screen.widgets.find(x => x.kind === 'select'); w.set(1); } }, part); // V3: the Codex's Traits page (a phone: two)
  await audit('trait-pick', () => { const g = HH.game, a = g.save.data.c1; g.ui.clearTo(amHub(g)); g.ui.push(traitPickScreen(g, a, { title: 'A THIRD TRAIT', offers: ['gymrat', 'ironman', 'paintprotector'], lines: ['1,000 career points! Pick a third trait. It starts at Bronze.'] }, () => {})); }); // V3 (§2.2): the third trait
  await audit('trait-levelup', () => { const g = HH.game, a = g.save.data.c1; g.ui.clearTo(amHub(g)); g.ui.push(traitEventScreen(g, a, { kind: 'traitlevel', trait: 'ironman', level: 2, title: 'LEVEL UP: IRON MAN', lines: ['Silver Iron Man!'].concat(traitLevelLines('ironman', 2)) }, () => {})); }); // V3: a level-up's card
  await audit('am-pregame', () => { const g = HH.game, a = g.save.data.c1; a.plan = 'practice'; g.ui.clearTo(amHub(g)); g.ui.push(amPregameScreen(g)); }); // V4 (2.0 §3): the scouting report before a game
  await audit('am-pregame-film', () => { const g = HH.game, a = g.save.data.c1; a.plan = 'film'; g.ui.clearTo(amHub(g)); g.ui.push(amPregameScreen(g)); }); await ev(() => { HH.game.save.data.c1.plan = 'practice'; }); // V4: all four tendencies
  await audit('am-film', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(filmRoomScreen(g)); }); // V4: the film room's scouting card
  for (let part = 0; part < (desk ? 1 : 3); part++) await audit('codex-moves-' + part, part => { const g = HH.game; if (!part) { g.ui.clearTo(amHub(g)); g.ui.push(statsGuideScreen(g, 'moves')); return; } const s = g.ui.screen, w = s.widgets.find(x => x.kind === 'select'); const opts = w.options || []; const i = opts.findIndex(o => /^Moves/.test(o)); if (i >= 0 && /^Moves/.test(opts[i + part] || '')) w.set(i + part); }, part); /* V6: paged on the drawn screen (the pages are measured as it draws; before, part 1 and 2 showed the next topic) */ // V4: the move list (a phone: in parts)
  await audit('touch-layout', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(touchLayoutScreen(g)); }); // V4: the layout editor
  await audit('am-story-event', () => { const g = HH.game, a = g.save.data.c1; a.events.push({ kind: 'story', from: 'Coach', title: 'FIRST DAY', lines: ['Line one of the story.', 'Line two.'] }); g.ui.clearTo(amHub(g)); });
  const sagaCase = ([arc, bi, setup]) => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; const S = sagaOf(a); delete S.arcs[arc]; S.order = S.order.filter(x => x !== arc); S.arcs[arc] = { st: 'on', b: bi, s0: a.season, stage: a.stage || 'hs', picks: [], inj: { name: 'Ankle sprain', games: 3 } }; S.order.push(arc); if (setup === 'took') S.flags.booster = 'took'; if (setup === 'last') { S.flags.mentorLast = a.season; S.cast.mentor.m = 40; } { const A = stFill(a); A.beats = 0; A.fired = {}; A.w = -99; } /* a fresh beat budget (R9's 3–5 a season) */ const e = sagaTell(a, arc, bi, { kind: 'camp' }); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(storyEventScreen(g, a, e, () => {}) || storyDialog(g, a, e, () => {})); const s = g.ui.screen; if (s.finish) s.finish(); for (let i = 0; i < 6; i++) { const nx = s.widgets.find(w => !w.hidden && w.label === '▼'); if (nx) { nx.onPress(); if (s.finish) s.finish(); } } }; /* (runs in the page: its arguments come in with it) */
  await audit('saga-kitchen', sagaCase, ['bills', 0, null]); // V7 (Part 2 §2.4): a cutscene with three answers (a phone: their own page)
  await audit('saga-press', sagaCase, ['booster', 1, 'took']); // the press room
  await audit('saga-finals', sagaCase, ['mentor', 3, 'last']); // the Finals court
  await audit('am-guide-story', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(statsGuideScreen(g, 'story')); }); // the Codex's story page
  await audit('am-story-sofar', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(storySoFarScreen(g, a)); }); // V8: the Story so far (the saga cases above left a few beats in it)
  await audit('am-story-people', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => w.label === 'People'); if (b) b.onPress(); }); // (a phone: the people view; a desktop shows both)
  await audit('am-records', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; recordsAfterGame(a, { pts: 18, reb: 7, stl: 2, blk: 1, tpm: 2 }, true); recordsAfterGame(a, { pts: CONFIG.records.levels.hs.pts[0] + 1, reb: 3 }, true); REC_TOASTS.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(recordsBookScreen(g, a)); }); // V8: the record book (a state record broken)
  await audit('am-records-book', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => w.label === 'Records'); if (b) b.onPress(); }); // (a phone: the records view)
  await audit('am-awards-night', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.events.push({ kind: 'ceremony', title: 'AWARDS NIGHT', sub: (a.school || 'Your school') + ' · season ' + a.season, rows: ['District MVP', 'All-District 1st team', 'District champion'].map(x => ({ award: x, name: a.name, mine: true })) }); g.ui.clearTo(amHub(g)); }); // V8 (2.0 §4.9): the awards ceremony
  await audit('am-awards-night-all', () => { const s = HH.game.ui.screen; if (s && s.onTap) s.onTap(); }); // (every award shown)
  await ev(() => { const a = HH.game.save.data.c1, S = sagaOf(a); for (const id of ['bills', 'booster', 'mentor']) { delete S.arcs[id]; } S.order = S.order.filter(x => !['bills', 'booster', 'mentor'].includes(x)); a.events.length = 0; });
  await audit('am-recap-bench', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.log.push({ season: a.season, age: a.age, stage: 'hs', label: 'Varsity', w: 4, l: 2, rank: 3, size: 6, ppg: 0, fg: 0, ovr: amOvr(a), awards: [], g: 0, ovr0: amOvr(a) - 2, chW: 1, chL: 2 }); a.events.push({ kind: 'recap', title: 'SEASON RECAP', lines: [] }); g.ui.clearTo(amHub(g)); }); await ev(() => { const a = HH.game.save.data.c1; a.log.pop(); a.events.length = 0; }); // V1 (§1.12): a season on the bench
  await audit('am-growth', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.events.push({ kind: 'growth', title: 'GROWTH SPURT!', grow: { from: a.height - 0.03, to: a.height }, lines: ['You grew 1″ this summer.', 'Height changes your game.'] }); g.ui.clearTo(amHub(g)); });
  await audit('am-practice', () => HH.game.ui.push(practiceScreen(HH.game)));
  await audit('am-standings', () => { HH.game.ui.clearTo(amHub(HH.game)); HH.game.ui.push(amStandingsScreen(HH.game)); });
  await audit('am-history', () => { HH.game.ui.clearTo(amHub(HH.game)); HH.game.ui.push(amHistoryScreen(HH.game)); });
  await audit('news', () => { HH.game.ui.clearTo(amHub(HH.game)); HH.game.ui.push(headlinesScreen(HH.game)); });
  await audit('trophies', () => { HH.game.ui.clearTo(amHub(HH.game)); HH.game.ui.push(trophyCaseScreen(HH.game)); });
  await audit('timeline', () => { HH.game.ui.clearTo(amHub(HH.game)); HH.game.ui.push(timelineScreen(HH.game)); });
  await audit('am-result', () => { const g = HH.game, a = g.save.data.c1; const r = amSimGame(a); a.events.length = 0; g.ui.clearTo(amResultScreen(g, r, null)); });
  await audit('am-result-tired', () => { const g = HH.game, a = g.save.data.c1; const r = amSimGame(a); a.events.length = 0; if (r.bench || !r.line || r.line.fga == null) Object.assign(r, { bench: false, gains: [], line: { pts: 4, fgm: 2, fga: 5, tpm: 0, tpa: 1, reb: 3, stl: 1, blk: 0 } }); g.__fat = a.fatigue; a.fatigue = 98; r.wk = Object.assign({}, r.wk || {}, { plan: 'practice', practiceXp: 9, injury: { name: 'Sprained ankle', games: 2 } }); g.ui.clearTo(amResultScreen(g, r, null)); }); await ev(() => { const g = HH.game; g.save.data.c1.fatigue = g.__fat || 0; delete g.__fat; }); // V1 (§1.7): a tired week with an injury
  await audit('am-result-slump', () => { const g = HH.game, a = g.save.data.c1; const r = amSimGame(a); a.events.length = 0; Object.assign(r, { slump: 'start', grade: r.grade || 'D', simmed: true }); r.wk = Object.assign({}, r.wk, { injury: { name: 'Knee sprain', games: 3, loss: { k: 'jmp', pts: 2, done: true } } }); g.ui.clearTo(amResultScreen(g, r, null)); }); // V6 (§1.2): a slump, the grade's XP, an injury that costs points for good
  await audit('am-train-slump', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.slump = { n: 3, on: true }; a.injury = { name: 'Knee sprain', games: 2, loss: { k: 'jmp', pts: 2, done: true } }; g.hubTab = 'train'; g.ui.clearTo(amHub(g)); }); await ev(() => { const a = HH.game.save.data.c1; delete a.slump; a.injury = null; }); // V6: the SLUMP chip
  await audit('am-practice-hard', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.intensity = 'hard'; a.wk = {}; g.hubTab = 'train'; g.ui.clearTo(amHub(g)); g.ui.push(practiceScreen(g)); }); // V6 (§1.2): the load cap's note
  await audit('am-practice-capped', () => { const g = HH.game, a = g.save.data.c1; a.wk = {}; a.fatigue = 10; const res = amPractice(a, a.focus, 'hard', amSessionXp(a, 'hard')); g.ui.clearTo(amHub(g)); g.ui.push(practiceResultScreen(g, res, a.focus, null)); }); await ev(() => { const a = HH.game.save.data.c1; a.intensity = 'normal'; }); // V6: XP past the cap turns into fatigue
  await audit('am-film', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(filmRoomScreen(g)); }); // F10: after the first game (before it there was no next opponent, and this opened the growth card)
  await audit('am-hub-jv', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; if (a.squad !== 'jv') { hsToJv(a); hsBuildLeague(a, amRng(a)); a.events.length = 0; } g.ui.clearTo(amHub(g)); }); // F11: the header says JV · 2ND TEAM
  await audit('am-team-jv', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(teamScreen(g)); }); // F11: JV → VARSITY on the Team page, and how to move up
  await audit('am-guide-team-jv', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(statsGuideScreen(g, 'team')); }); // F11: the guide's Your team entry
  await audit('am-hub-varsity', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; hsToVarsity(a, 'audit'); hsBuildLeague(a, amRng(a)); a.events.length = 0; g.ui.clearTo(amHub(g)); }); // F11: VARSITY · TOP TEAM
  const cardCase = ([kind, gpa]) => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; if (gpa != null) a.gpa = gpa; const e = kind === 'major' ? (schoolMajorCard(a, { name: a.college || 'Test State' }), a.events.pop()) : schoolExamCard(a, kind); a.events.length = 0; g.hubTab = 'play'; g.ui.clearTo(amHub(g)); g.ui.push(storyDialog(g, a, e, () => {})); const s = g.ui.screen; if (s.finish) s.finish(); for (let i = 0; i < 6; i++) { const nx = s.widgets.find(w => !w.hidden && w.label === '▼'); if (nx) { nx.onPress(); if (s.finish) s.finish(); } } }; /* V9: a school card, paged to its answers (runs in the page) */
  const answerCase = label => { const s = HH.game.ui.screen; if (s && s.name === 'dialog') { const b = s.widgets.find(w => !w.hidden && w.label === label); if (b) b.onPress(); if (s.finish) s.finish(); } };
  await audit('am-exam', cardCase, ['mid', 2.31]); // V9 (Part 2 §3): the exam week's three answers
  await audit('am-exam-answered', answerCase, 'Cram'); // (the outcome; the report card follows)
  await audit('press', () => { const g = HH.game, a = g.save.data.c1; g.ui.clearTo(amHub(g)); a.events.push({ kind: 'press', q: 'Test?', x: { name: a.name, won: true, us: 15, them: 9, opp: 'Some One' } }); });
  await audit('press-four', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; g.ui.clearTo(amHub(g)); const o = a.league.opps[0]; a.hype = 40; a.cash = 500; a.events.push({ kind: 'press', q: 'Nobody gave you a chance against ' + o.name.split(' ')[0] + '. What changed?', x: { name: a.name, won: true, us: 15, them: 11, opp: o.name, oppId: o.id, upsetWin: true, recs: [] } }); }); // R8: four answers
  await audit('press-trash-answered', () => { const g = HH.game, s = g.ui.screen; if (s && s.name === 'press') { const f0 = MD.trashFine; MD.trashFine = 1; try { s.widgets.find(w => w.ans === 'trash').onPress(); } finally { MD.trashFine = f0; } } }); // R8: the newspaper with a fine
  await audit('dialog-choice', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; stFill(a); a.arc.beats = 0; a.arc.w = -99; const m = stMentor(a); stBeat(a, 'mentor', 'mentor', 'A VETERAN', [(m ? stFirst(m.name) : 'Your teammate') + ' has been here longer than anyone: "You\'ve got it. Now let me show you what they don\'t teach."', '"Stay after practice this week. Or don\'t."'], { crit: true, choice: XP_CHOICE('mentor', 'Stay after with ' + (m ? stFirst(m.name) : 'them')) }); g.ui.clearTo(amHub(g)); }); // R9: a dialogue card with a choice
  await audit('dialog-answered', () => { const s = HH.game.ui.screen; if (s && s.name === 'dialog') { const b = s.widgets.find(w => !w.hidden && /^Stay after/.test(w.label || '')); if (b) b.onPress(); } }); // R9: what the choice did
  await audit('dialog-pages', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.events.push({ kind: 'story', who: 'coach', title: 'REPORT CARD', lines: ['First quarter: GPA 2.9. Eligible.', 'Math: B. English: B+. History: C.', 'Coach: "Grades first. Always. I don\'t play kids who don\'t go to class."', 'Next report card after game 6.'] }); g.ui.clearTo(amHub(g)); }); // R9: a card in pages
  await audit('news-social', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; stFill(a); for (let i = 0; i < 6; i++) socialPost(a, 'game', 'Post number ' + i + ': ' + stFirst(a.name) + ' handles business tonight, and the whole town saw it.', 1 + i); g.ui.clearTo(amHub(g)); g.ui.push(headlinesScreen(g)); const t = g.ui.screen.widgets.find(w => w.label === 'SOCIAL'); if (t) t.onPress(); }); // R9: the social feed
  await audit('news-buzz', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.hype = 74; a.sponsorCut = 3; a.quiet = true; g.ui.clearTo(amHub(g)); g.ui.push(headlinesScreen(g)); }); // R8: the BUZZ panel (phone: a line on the paper)
  await audit('news-buzz-tab', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => /^(SOCIAL|BUZZ|HEADLINES)$/.test(w.label || '')); b.onPress(); if (HH.game.ui.phone) b.onPress(); }); // F7: a phone's BUZZ tab (a desktop's feed)
  await audit('am-ladder', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; ladderInit(a, 3); g.ui.clearTo(amHub(g)); g.ui.push(ladderScreen(g)); }); // R4: the depth chart
  await audit('am-ladder-result', () => { const g = HH.game, a = g.save.data.c1; const res = ladderSimChallenge(a, ladderAboveId(a), 'you'); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(ladderResultScreen(g, res, { xp: 42 }, false, null)); }); // R4
  await audit('am-ladder-held', () => { const g = HH.game, a = g.save.data.c1; ladderInit(a, 2); a.events.length = 0; const st = ladderOf(a)[0], m = ladderMate(a, st), d = myChallengeOvr(a) + TM.takeGap + 3 - tmMateOvr(m); for (const k of RATING_KEYS) m.r[k] = clamp(m.r[k] + d, 1, 99); const res = ladderResolve(a, st, true, 'you'); g.ui.clearTo(amHub(g)); g.ui.push(ladderResultScreen(g, res, { xp: 42 }, false, null)); }); // V6: a won challenge that doesn't take the spot (NOT QUITE)
  await audit('am-ladder-event', () => { const g = HH.game, a = g.save.data.c1; ladderInit(a, 2); a.events.length = 0; const m = ladderMate(a, ladderBelowId(a)); a.events.push({ kind: 'ladder', mate: m.id, title: 'CHALLENGE!', lines: [m.name + ' wants your spot on the depth chart (#2).', 'A practice game to 7: win and you keep it; lose and you drop a rung.', 'Coach: "Settle it on the court."'] }); g.ui.clearTo(amHub(g)); }); // R4
  await audit('am-bench', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; ladderInit(a, 2); const r = amSimGame(a); a.events.length = 0; g.ui.clearTo(benchResultScreen(g, r)); }); // R4: a week on the bench
  await audit('am-summer', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; hsSummerStart(a); g.ui.clearTo(amHub(g)); g.ui.push(summerScreen(g)); }); // R5
  await audit('am-summer-hub', () => { const g = HH.game; g.ui.clearTo(amHub(g)); }); // R5: the hub waits for the summer
  await audit('am-reststudy', () => { const g = HH.game, a = g.save.data.c1; hsSummerChoose(a, 'rest'); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(restStudyScreen(g, careerKit(g))); }); // R5: the phone's Rest-or-Study chooser
  await audit('am-recruiting', () => { const g = HH.game, a = g.save.data.c1; hsUpdateRank(a, 'audit'); hsOfferCheck(a, amRng(a), 'final'); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(recruitingScreen(g)); }); // R5
  await audit('am-recruiting-gpa', () => { const g = HH.game, a = g.save.data.c1; a.gpa = 3.6; if (!a.offers.some(o => o.academic)) a.offers.push({ name: SCH.academic[0], tier: 2, academic: true, colors: ['#1B3A6B', '#E8E2D0'], coach: 'Coach Whitley', focus: 'shooting', fac: 3, visited: false, gpaReq: SCH.gpaReq.academic, when: 'final', season: a.season }); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(recruitingScreen(g)); }); // V9: the offers' GPA lines, an elite academic program
  await audit('am-state', () => { const g = HH.game, a = g.save.data.c1; if (!a.league || a.league.format !== 'district') { if (a.squad === 'jv') hsToVarsity(a, 'audit'); hsBuildLeague(a, amRng(a)); } a.league.playoffs = { round: 2, seeds: ['me'], pending: null, other: null, champion: null }; hsStartState(a, amRng(a)); a.events.length = 0; g.ui.clearTo(amHub(g)); }); // R5: the state tournament on the hub
  await audit('am-state-standings', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(amStandingsScreen(g)); }); // R5
  await audit('am-state-bracket', () => { const g = HH.game; g.ui.push(stateBracketScreen(g)); }); // R5
  await audit('recruit', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.stage = 'hs'; a.stageYear = 4; amStartRecruiting(a, amRng(a)); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(amDecisionScreen(g)); });
  await audit('visit', () => { const g = HH.game, a = g.save.data.c1; g.ui.push(visitScreen(g, a.decision.offers[0])); });
  await audit('recruit-power', () => { const g = HH.game, a = g.save.data.c1; const offs = a.decision.offers.filter(o => !o.draft); g.__tiers = offs.map(o => [o.tier, o.visited, o.fac, o.focus]); offs.forEach((o, i) => { o.tier = [1, 2, 3][i % 3]; }); offs[1].visited = true; offs[1].fac = 3; offs[1].focus = Object.keys(CR.trainFocus)[1]; g.ui.clearTo(amHub(g)); g.ui.push(recruitScreen(g)); }); await ev(() => { const g = HH.game, offs = g.save.data.c1.decision.offers.filter(o => !o.draft); offs.forEach((o, i) => { [o.tier, o.visited, o.fac, o.focus] = g.__tiers[i]; }); delete g.__tiers; }); // V1 (§1.9): a power conference and a blue blood
  await audit('commit-day', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.events.push({ kind: 'commit', offers: a.decision.offers.filter(o => !o.draft), chosen: 0 }); g.ui.clearTo(amHub(g)); });
  await audit('declare', () => { const g = HH.game, a = g.save.data.c1; amChooseCollege(a, a.decision.offers[0]); a.events.length = 0; a.decision = { kind: 'declare' }; g.ui.clearTo(amHub(g)); g.ui.push(amDecisionScreen(g)); });
  await audit('col-hub', () => { const g = HH.game, a = g.save.data.c1; a.decision = null; for (let i = 0; i < 3; i++) { a.events.length = 0; a.fatigue = 0; amSimGame(a); } a.events.length = 0; g.ui.clearTo(amHub(g)); }); // R6: the college hub (conference record, overall, the mock draft)
  await audit('col-major', cardCase, ['major', null]); // V9: the major (four answers)
  await audit('col-major-answered', answerCase, 'Kinesiology');
  await audit('col-hub-me', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; a.loan = 6000; g.hubTab = 'me'; g.ui.clearTo(amHub(g)); }); await ev(() => { HH.game.hubTab = 'play'; }); // V9: GPA, the scholarship and the degree
  await audit('col-exam', cardCase, ['end', 1.45]); // V9: finals week, probation's line
  await audit('col-probation', sagaCase, ['probation', 0, null]); // V9: the Academic Probation arc
  await audit('col-probation-hearing', sagaCase, ['probation', 1, null]); await ev(() => { const a = HH.game.save.data.c1; a.gpa = 3; a.scholarship = a.scholarship === 'lost' ? 'partial' : a.scholarship; a.ineligible = 0; a.events.length = 0; });
  await audit('col-team', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(teamScreen(g)); }); // F11: the four program levels, yours lit
  await audit('col-guide-team', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(statsGuideScreen(g, 'team')); }); // F11: the guide's Your program entry
  await audit('col-standings', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(amStandingsScreen(g)); }); // R6: marquee games
  await audit('col-draftstock', () => { const g = HH.game; g.ui.clearTo(amHub(g)); g.ui.push(draftStockScreen(g)); }); // R6
  await audit('col-nil', () => { const g = HH.game, a = g.save.data.c1; a.events.length = 0; const e = colNilOffer(a, { next: () => 0, int: () => 1, pick: x => x[0] }, 'game'); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(nilEventScreen(g, a, e, () => g.ui.pop())); }); // R6: an NIL offer
  await audit('col-conf-bracket', () => { const g = HH.game, a = g.save.data.c1; let n = 0; while (!a.league.playoffs && n++ < 20) { a.events.length = 0; a.fatigue = 0; amSimGame(a); } a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(collegeBracketScreen(g, 'conf')); }); // R6
  await audit('col-nat-bracket', () => { const g = HH.game, a = g.save.data.c1; const rng = amRng(a); for (let i = 0; i < 3 && a.league.playoffs.round < 31; i++) colAdvance(a, rng, true); colAdvance(a, rng, true); a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(collegeBracketScreen(g, 'nat')); }); // R6: the field of 64 after a round
  await audit('col-portal', () => { const g = HH.game, a = g.save.data.c1; a.decision = { kind: 'portal', offers: colPortalOffers(a, amRng(a)), bench: 8, games: 12 }; g.ui.clearTo(amHub(g)); g.ui.push(amDecisionScreen(g)); }); // R6: the transfer portal
  await audit('col-agent', () => { const g = HH.game, a = g.save.data.c1; a.decision = null; a.agent = undefined; a.events.length = 0; colAgentPitch(a); const e = a.events.pop(); g.ui.clearTo(amHub(g)); g.ui.push(agentEventScreen(g, a, e, () => g.ui.pop())); }); // R6: an agent calls
  await audit('combine', () => { const g = HH.game, a = g.save.data.c1; a.decision = null; a.stage = 'combine'; a.events.length = 0; g.ui.clearTo(amHub(g)); g.ui.push(amCombineScreen(g)); });
  await audit('pro-offers', () => { const g = HH.game, a = g.save.data.c1; g.save.data.career = null; a.stage = 'combine'; a.decision = null; a.proOffers = null; a.events.length = 0; g.ui.clearTo(proOffersScreen(g)); }); // F7: no draft
  await audit('signing', () => { const g = HH.game; const c = testProLeague(12, g.save.data); g.save.data.c1.handedOff = true; c.events.length = 0; const s = signingScreen(g); g.ui.clearTo(s); s.onTap(); s.onTap(); });
  await audit('pro-hub', () => { const g = HH.game; const c = testProLeague(12, g.save.data); g.save.data.c1.handedOff = true; c.events.length = 0; roadCheck(c); c.events.length = 0; g.save.save(); g.hubTab = 'play'; g.ui.clearTo(careerHub(g)); });
  for (const tab of ['train', 'me', 'team', 'shop']) await audit('pro-hub-' + tab, t => { const g = HH.game, c = g.save.data.career; c.events.length = 0; g.hubTab = t; g.ui.clearTo(careerHub(g)); }, tab); // V5 (2.0 §5)
  await audit('pro-road', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; g.hubTab = 'play'; g.ui.clearTo(careerHub(g)); g.ui.push(roadScreen(g)); });
  await audit('pro-hub-play-again', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; g.hubTab = 'play'; g.ui.clearTo(careerHub(g)); });
  await audit('pro-team', () => { const g = HH.game; g.ui.clearTo(careerHub(g)); g.ui.push(teamScreen(g)); }); // R3
  await audit('guide-you-p0', () => { const g = HH.game, c = g.save.data.career; c.me.slump = { n: 3, on: true }; g.ui.clearTo(careerHub(g)); g.ui.push(statsGuideScreen(g, 'you')); }); // V6: the Codex's climb entries (potential, the competition, XP) on its later pages...
  for (let part = 1; part < 3; part++) await audit('guide-you-' + part, part => { const s = HH.game.ui.screen, w = s.widgets.find(x => x.kind === 'select'), opts = (w && w.options) || [], i = opts.findIndex(o => /^OVR/.test(o)); if (i >= 0 && /^OVR/.test(opts[i + part] || '')) w.set(i + part); }, part); await ev(() => { delete HH.game.save.data.career.me.slump; }); // ...paged on the drawn screen (its pages are measured as it draws)
  await audit('career-menu', () => { const g = HH.game; g.ui.clearTo(careerHub(g)); g.ui.push(careerMenuScreen(g)); }); // F7
  await audit('league-franchises', () => { const g = HH.game; g.ui.clearTo(careerHub(g)); g.leagueTab = { tab: 1, player: 0 }; g.ui.push(leagueScreen(g)); }); // F7
  await audit('league-standings', () => { const g = HH.game; g.ui.clearTo(careerHub(g)); g.leagueTab = { tab: 0, player: 0 }; g.ui.push(leagueScreen(g)); });
  await audit('pregame', () => { const g = HH.game, c = g.save.data.career; g.ui.push(pregameScreen(g, userGame(c))); });
  await audit('pro-practice', () => { HH.game.ui.clearTo(careerHub(HH.game)); HH.game.ui.push(practiceScreen(HH.game)); });
  await audit('pro-film', () => { HH.game.ui.clearTo(careerHub(HH.game)); HH.game.ui.push(filmRoomScreen(HH.game)); }); // R10: every screen
  await audit('league', () => { HH.game.ui.clearTo(careerHub(HH.game)); HH.game.ui.push(leagueScreen(HH.game)); });
  await audit('player', () => { HH.game.ui.clearTo(careerHub(HH.game)); HH.game.ui.push(playerScreen(HH.game)); });
  for (const t of ['you', 'buzz', 'body', 'team', 'money']) await audit('guide-' + t, t => { const g = HH.game, c = g.save.data.career; c.me.hype = 66; c.me.fatigue = 57; c.me.gear = { sleeve: 2, braces: 1 }; g.ui.clearTo(careerHub(g)); g.ui.push(statsGuideScreen(g, t)); }, t); // F9: the stats guide (a pro)
  await audit('career-menu', () => { const g = HH.game; g.ui.clearTo(careerHub(g)); g.ui.push(careerMenuScreen(g)); }); // F7/F9: the Career menu's tiles
  for (let t = 0; t < 8; t++) await audit('management-tab' + t, t => { HH.game.ui.clearTo(careerHub(HH.game)); HH.game.mgmtTab = { tab: t }; const s = managementScreen(HH.game); HH.game.ui.push(s); }, t);
  for (const t of [1, 3, 5]) await audit('business-r7-tab' + t, t => { const g = HH.game, c = g.save.data.career; c.me.money = 3e7; c.me.hype = PR.shoeHype * MD.hypeMax; g.ui.clearTo(careerHub(g)); g.mgmtTab = { tab: t }; g.ui.push(managementScreen(g)); }, t); // R7: contract & money (agent, shoe line), training, lifestyle
  await audit('pro-trade-card', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.events.push({ kind: 'trade', title: 'UNHAPPY', why: 'bench', lines: ['You have watched 4 of the 6 games from the bench.', 'Your agent can ask for a trade: to a club that starts you, your contract comes with you.', 'Or stay and fight for it.'] }); g.ui.clearTo(careerHub(g)); }); // R7
  await audit('pro-shoe-card', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.me.shoePitched = false; c.me.shoe = null; c.me.hype = PR.shoeHype * MD.hypeMax; proShoePitch(c); g.ui.clearTo(careerHub(g)); }); // R7
  await audit('pro-fa-spots', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; g.__season = c.season; for (let k = 0; k < 40 && !Object.keys(frSpots5(c).open).length; k++) { c.season++; c.frSpots = null; } c.offseason = { step: 3, fa: { offers: proFreeAgency(c, careerRng(c), 6e6), value: 6e6 }, contractDone: false }; g.ui.clearTo(offseasonScreen(g)); }); await ev(() => { const g = HH.game, c = g.save.data.career; c.season = g.__season; c.frSpots = null; delete g.__season; }); // V6 (§1.3): the open 5★ spots, their rivals, your value
  await audit('pro-negotiate', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.offseason = { step: 3, fa: { offers: proFreeAgency(c, careerRng(c), 6e6), value: 6e6 }, contractDone: true }; g.ui.clearTo(offseasonScreen(g)); g.ui.push(negotiateScreen(g, 1)); }); // R7: the negotiation
  await audit('pro-negotiate-agent', () => { const g = HH.game, c = g.save.data.career; g.__agent = c.me.agent; c.me.agent = true; g.ui.clearTo(offseasonScreen(g)); g.ui.push(negotiateScreen(g, 1)); }); await ev(() => { const g = HH.game; g.save.data.career.me.agent = g.__agent; delete g.__agent; }); // V1 (§1.10): with an agent
  await audit('pro-result', () => { const g = HH.game, c = g.save.data.career; const rec = simUserGame(g.save.data); c.events.length = 0; g.ui.clearTo(careerResultScreen(g, rec, null)); });
  await audit('allstar', () => { const g = HH.game, c = g.save.data.career; for (const k of RATING_KEYS) meOf(c).r[k] = 99; let n = 0; while (!c.allStar && n++ < 30) { c.events.length = 0; simUserGame(g.save.data); } c.events = c.events.filter(e => e.kind === 'allstar'); g.ui.clearTo(careerHub(g)); });
  await audit('allstar-1v1-result', () => { const g = HH.game, c = g.save.data.career; if (c.allStar) g.ui.push(allStar1v1ResultScreen(g, { winner: 0, teams: [{ score: 21 }, { score: 17 }] }, { applied: true, opp: Object.keys(c.players).find(id => String(id) !== String(c.meId)) })); }); // R10: the All-Star 1v1's result
  await audit('allstar-result', () => { const g = HH.game, c = g.save.data.career; if (c.allStar) { if (!c.allStar.done) finishAllStar(c, 14); g.ui.clearTo(careerHub(g)); g.ui.push(allStarResultScreen(g)); } }); // R10: the contest's results
  await audit('offseason', () => { const g = HH.game, c = g.save.data.career; let n = 0; while (c.phase !== 'offseason' && n++ < 60) { c.events.length = 0; simUserGame(g.save.data); } c.events.length = 0; g.ui.clearTo(offseasonScreen(g)); });
  await audit('offseason-bench', () => { const g = HH.game, c = g.save.data.career, r = c.me.seasonLog[0]; g.__row = Object.assign({}, r); Object.assign(r, { g: 0, ppg: 0, rpg: 0, fg: 0, tp: 0, chW: 2, chL: 1, ovr0: r.ovr - 2 }); g.ui.clearTo(offseasonScreen(g)); }); await ev(() => { const g = HH.game; Object.assign(g.save.data.career.me.seasonLog[0], g.__row); delete g.__row; }); // V1 (§1.12): a season on the bench
  await audit('offseason-contract', () => { const g = HH.game, c = g.save.data.career; c.me.contract.years = 1; c.offseason.step = 3; c.offseason.fa = null; c.offseason.contractDone = false; g.ui.clearTo(offseasonScreen(g)); });
  await audit('offseason-next', () => { const g = HH.game, c = g.save.data.career; g.__step = c.offseason.step; c.offseason.step = 4; c.me.degree = { major: 'business', years: 2, academic: false }; c.me.money = Math.max(c.me.money, 1e6); g.ui.clearTo(offseasonScreen(g)); }); // V9: summer classes
  await audit('offseason-classes', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => /^Summer classes/.test(w.label || '')); if (b) b.onPress(); }); await ev(() => { const g = HH.game, c = g.save.data.career; c.offseason.step = g.__step; });
  await audit('rival-moment', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.events.push({ kind: 'rival', title: 'THE RIVAL', lines: ['They beat you last time.'], opp: c.rivalId || c.active.find(id => id !== c.meId) }); g.ui.clearTo(careerHub(g)); });
  await audit('pro-press', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.events.push({ kind: 'press', q: 'Big win tonight. Thoughts?', x: { name: meOf(c).name, won: true, us: 21, them: 12, opp: 'Some One' } }); g.ui.clearTo(careerHub(g)); });
  await audit('pro-dialog-tour', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; stFill(c); meOf(c).age = Math.max(meOf(c).age, SY.tourAge); c.me.arc.done = {}; c.me.tour = 0; stSeasonStart(c); g.ui.clearTo(careerHub(g)); }); // R9: is this the last one?
  await audit('pro-dialog-tour-last', () => { const s = HH.game.ui.screen; if (s && s.name === 'dialog') { for (let i = 0; i < 4; i++) { const nx = s.widgets.find(w => !w.hidden && w.label === '▼'); if (nx) nx.onPress(); } } }); // the choice page
  await audit('pro-awards-night', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; const ids = c.active; const aw = { mvp: c.meId, dpoy: ids[1], roy: ids[2], mip: ids[3], scoring: c.meId, finalsMvp: ids[4], allLeague: [c.meId, ids[5], ids[6]] }; c.events.push({ kind: 'ceremony', title: 'AWARDS NIGHT', sub: 'The PBL · season ' + c.season, rows: proCeremonyRows(c, aw) }); g.ui.clearTo(careerHub(g)); }); // V8: the league's awards, yours marked
  await audit('pro-awards-night-all', () => { const s = HH.game.ui.screen; if (s && s.onTap) s.onTap(); });
  await audit('pro-allstar-reveal', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; const four = [c.meId].concat(c.active.filter(id => id !== c.meId).slice(0, 3)); c.events.push({ kind: 'allstarpick', title: 'THE ALL-STARS', ids: four }); g.ui.clearTo(careerHub(g)); }); // V8: the All-Star reveal
  await audit('pro-allstar-reveal-all', () => { const s = HH.game.ui.screen; if (s && s.onTap) s.onTap(); });
  await audit('saga-trade', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; const S = sagaOf(c); delete S.arcs.trade; S.order = S.order.filter(x => x !== 'trade'); S.arcs.trade = { st: 'on', b: 0, s0: c.season, stage: 'pro', picks: [] }; S.order.push('trade'); { const A = stFill(c); A.beats = 0; A.fired = {}; A.w = -99; } const e = sagaTell(c, 'trade', 0, { why: 'bench' }); c.events.length = 0; g.ui.clearTo(careerHub(g)); g.ui.push(storyEventScreen(g, c, e, () => {}) || storyDialog(g, c, e, () => {})); const s = g.ui.screen; if (s.finish) s.finish(); for (let i = 0; i < 6; i++) { const nx = s.widgets.find(w => !w.hidden && w.label === '▼'); if (nx) { nx.onPress(); if (s.finish) s.finish(); } } }); // V8: the Trade Demand (three answers)
  await audit('pro-story-sofar', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; g.ui.clearTo(careerHub(g)); g.ui.push(storySoFarScreen(g, c)); });
  await audit('pro-records', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; recordsAfterGame(c, { pts: 24, reb: 9, stl: 3, blk: 1, tpm: 3 }, true); REC_TOASTS.length = 0; g.ui.clearTo(careerHub(g)); g.ui.push(recordsBookScreen(g, c)); });
  await audit('pro-news-buzz', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; storyFill(c); c.me.hype = 66; c.me.grudge[c.active.find(id => id !== c.meId)] = 1; c.me.sponsorCut = 2; g.ui.clearTo(careerHub(g)); g.ui.push(headlinesScreen(g)); }); // R8
  await audit('pro-news-buzz-tab', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => /^(SOCIAL|BUZZ|HEADLINES)$/.test(w.label || '')); b.onPress(); if (HH.game.ui.phone) b.onPress(); }); // F7
  await audit('pro-bench', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; if (c.phase === 'offseason') { offseasonProgression(c); offseasonMoves(c); const o = offseasonContract(c); if (o) acceptContract(c, 0); newSeason(c); } ladderInit(c, 2); const rec = simUserGame(g.save.data); c.events.length = 0; g.ui.clearTo(benchResultScreen(g, rec)); }); // R4
  await audit('hof-full', () => { const g = HH.game, H = g.save.data.hallOfFame; for (let i = 0; i < 7; i++) H.push({ name: 'Legend ' + i, look: PRESET_LOOKS[i % PRESET_LOOKS.length], h: 1.9, arch: 'slasher', score: 50 + i * 8, hof: i > 3, seasons: 10 + i, titles: i, ppg: 20 + i, mvps: i % 3, when: i + 1 }); g.ui.clearTo(mainMenu(g)); g.ui.push(hallOfFameScreen(g)); });
  await audit('epilogue', () => { const g = HH.game, sv = g.save.data; sv.career.me.money = 8e7; retireCareer(sv); g.save.save(); g.ui.clearTo(epilogueScreen(g)); }); // R7: what your money builds
  await audit('saga-epilogue', () => { const g = HH.game, c = g.save.data.career; const e = (c.events || []).find(x => x.epilogue) || { kind: 'dialog', title: 'HOME', who: 'family', lines: ['A line.'], bg: 'kitchen', mood: 'warm', epilogue: 'home' }; g.ui.clearTo(epilogueScreen(g)); g.ui.push(storyDialog(g, c, e, () => {})); const s = g.ui.screen; if (s.finish) s.finish(); for (let i = 0; i < 6; i++) { const nx = s.widgets.find(w => !w.hidden && w.label === '▼'); if (nx) { nx.onPress(); if (s.finish) s.finish(); } } }); // V8: the story's ending, at retirement
  await audit('epilogue-degree', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.me.degree = { major: 'kinesiology', years: 4, academic: false, school: 'Test State' }; g.ui.clearTo(epilogueScreen(g)); }); // V9: the head coach (the degree's version)
  await audit('hof-induction', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.legacy = Object.assign({}, c.legacy || legacyOf(c), { hof: true, titles: Math.max(1, (c.legacy || {}).titles || 0), mvps: 1 }); g.ui.clearTo(hofInductionScreen(g)); }); // V8 (2.0 §4.9): the induction
  await audit('legacy', () => { const g = HH.game, sv = g.save.data; proEpilogue(sv, { academy: true, foundation: 10, ending: 'booth' }); g.save.save(); g.ui.clearTo(legacyScreen(g)); }); // (R7: after the epilogue)
  await audit('money-built', () => { const g = HH.game; g.ui.push(moneyBuiltScreen(g)); }); // R7
  await audit('networth', () => { const g = HH.game, H = g.save.data.hallOfFame; H.forEach((e, i) => { if (e.netWorth == null) e.netWorth = 5e7 * (i + 1); }); g.ui.clearTo(mainMenu(g)); g.ui.push(netWorthScreen(g)); }); // R7: the leaderboard
  await audit('pause', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); const a = soloTeam(extrasPool(g)[0], false), b = soloTeam(extrasPool(g)[1], true); g.startMatch({ mode: '1v1', teams: [a, b], humanTeam: 0, humanPlayerIndex: 0, difficulty: 'pro', ruleset: 'arcade', format: { type: 'first', target: 11 }, court: 'blacktop', seed: 3, controlMode: 'lock' }, { kind: 'quick' }); g.pause(); });
  await audit('pause-practice', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); const a = soloTeam(extrasPool(g)[0], false), b2 = soloTeam(extrasPool(g)[1], true); g.startMatch({ mode: '1v1', teams: [a, b2], humanTeam: 0, humanPlayerIndex: 0, difficulty: 'rookie', ruleset: 'arcade', format: { type: 'first', target: 999 }, court: 'legends', seed: 11, controlMode: 'lock', practice: { noDefender: true, infiniteStamina: true, breakdown: true, chart: true } }, { kind: 'practice' }); const pr = g.match.practice; for (let i = 0; i < 12; i++) { const k = ['lay', 'mid', 'three', 'deep'][i % 4]; pr.shots++; pr.byZone[k][1]++; if (i % 3) { pr.makes++; pr.byZone[k][0]++; } pr.marks.push({ x: 0, d: [1.5, 5, 7.5, 9][i % 4], zone: k, make: !!(i % 3), type: k === 'lay' ? 'layup' : 'jumper', grade: k === 'lay' ? -1 : i % 2, id: 100 + i * 17 }); } g.pause(); }); // V4: practice's shot chart on the pause menu
  await audit('postgame-quick', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); const a = soloTeam(extrasPool(g)[0], false), b = soloTeam(extrasPool(g)[1], true); g.startMatch({ mode: '1v1', teams: [a, b], humanTeam: 0, humanPlayerIndex: 0, difficulty: 'pro', ruleset: 'arcade', format: { type: 'first', target: 3 }, court: 'blacktop', seed: 5, controlMode: 'lock' }, { kind: 'quick' }); for (const p of g.match.players) p.controlled = false; for (let i = 0; i < 120 * 240 && !g.match.ended; i++) simStep(g.match, STEP); });
  await wait(4000); await audit('postgame-quick-later', () => {});
  console.log('smallest text (CSS px): ' + texts.slice().sort((a, b) => a.min - b.min).slice(0, 25).map(o => o.name + ' ' + o.min.toFixed(1) + ' "' + (o.tx[0] ? o.tx[0].t : '') + '"').join(' | '));
  console.log('errors: ' + (P.errors.length ? P.errors.join(' | ') : 'none')); await browser.close();
})();
