// Phone audit (M9; 3.0): opens about 250 screens at 844×390 with touch (or at a desktop size) and lists every tap target
// under 64 CSS px (width or height), widgets off the screen, overlapping widgets, overlapping text (F4), text cut short
// with "…" (F7), text a figure covers (F10) and the smallest text each screen draws. It plays a scripted career (high
// school, college, the pros) to reach the later screens: 3.0's HOME and its five tabs (HOME, LEAGUE, EVENTS, CAREER,
// STORE), messages, the focus picker and the weekly drill's result, the Season review, LEAGUE's charts, tournaments and
// brackets, the recruiting board, the crew, the store and the Settings tabs, and every screen 3.0 kept (the menus, the
// Codex, the tryouts, recruiting, college, the Office, the franchises, the offseason, the endings, a match's pause).
// tests/screens30.js audits the 3.0 screens in every state, and this one goes wide. (3.0 removed the story's cutscenes,
// chapters and cards, the press room, rivals, picked and hidden traits, Film weeks, the practice screens, recruiting's
// film and filters, and the staff: CHANGES.md, X2.) Ends with a summary line: screens audited, how many flagged.
// Usage: node tests/phoneaudit.js [shotsDir] [--desktop] [--size=WxH@dpr] [--text125]
const path = require('path'), fs = require('fs');
const { launch, openPage } = require('./lib');
(async () => {
  const sizeArg = (process.argv.find(a => a.startsWith('--size=')) || '').slice(7), sz = /^(\d+)x(\d+)(?:@([\d.]+))?$/.exec(sizeArg); /* F4: --size=WxH[@dpr] runs the desktop audit in any window */
  const desk = process.argv.includes('--desktop') || !!sz, big = process.argv.includes('--text125'); /* R10: --text125 runs every screen at the 1.25× text size */ const dir = process.argv.slice(2).find(a => !a.startsWith('--')); if (dir) fs.mkdirSync(dir, { recursive: true });
  const browser = await launch(); const P = await openPage(browser, sz ? { viewport: { width: +sz[1], height: +sz[2] }, dpr: +(sz[3] || 1) } : { phone: !desk }); /* --desktop: the same screens at 1280×720 (overflow, overlap and off-screen only) */ const { page, ev } = P; const wait = ms => page.waitForTimeout(ms);
  await ev(() => { const F = CanvasRenderingContext2D.prototype.fillText; window.__txt = []; CanvasRenderingContext2D.prototype.fillText = function (t, x, y, mw) { try { const m = /(\d+(?:\.\d+)?)px/.exec(this.font); if (m && window.__txtOn && String(t).trim()) { const a = this.getTransform().a / (window.devicePixelRatio || 1); window.__txt.push({ px: +m[1] * a, t: String(t).slice(0, 40) }); } } catch (e) {} return F.call(this, t, x, y, mw); }; });
  // text wider than the widget it is drawn in (a label running off its button)
  await ev(() => { const U = UI.prototype, D = U.drawWidget; window.__ovf = new Set(); U.drawWidget = function (ctx, w, f) { const F = ctx.fillText; ctx.fillText = function (t, x, y, mw) { try { if (window.__txtOn && w.kind !== 'text') { const m = Math.min(ctx.measureText(String(t)).width, mw > 0 ? mw : 1e9), al = ctx.textAlign; /* a maxWidth draws the text truncated to fit (the bitmap font adds …) */ const x0 = al === 'center' ? x - m / 2 : al === 'right' || al === 'end' ? x - m : x; if (x0 < w.x - 3 || x0 + m > w.x + w.w + 3) window.__ovf.add((w.label || w.kind) + ': "' + String(t).slice(0, 34) + '"'); } } catch (e) {} return F.call(this, t, x, y, mw); }; try { return D.call(this, ctx, w, f); } finally { delete ctx.fillText; } }; });
  // F4 (the user: "text overlaps, so we can't read other stuff"): every string's ink box from one synchronous UI draw;
  // two different strings whose boxes share more than a font pixel each way are flagged.
  await ev(() => { const U = UI.prototype, DS = U.drawScreen; U.drawScreen = function (ctx, s) { const on = RBF.boxes; if (!on || s === this.screen) return DS.call(this, ctx, s); const n0 = on.length; try { return DS.call(this, ctx, s); } finally { for (let i = n0; i < on.length; i++) on[i].under = s.name || '?'; } }; }); // V1: a screen under the top one: its strings are tagged (the two-screens check), the other checks skip them
  await ev(() => { const U = UI.prototype, DW = U.drawWidget; U.drawWidget = function (ctx, w, f) { const n0 = RBF.boxes ? RBF.boxes.length : 0; try { return DW.call(this, ctx, w, f); } finally { if (RBF.boxes) for (let i = n0; i < RBF.boxes.length; i++) RBF.boxes[i].w8 = w; } }; }); // F4: which widget drew each string (a string drawn outside every widget must not run under one) // only the top screen's text: an overlay's panel hides the screen under it
  await ev(() => { window.__textOverlaps = () => { const g = HH.game; RBF.boxes = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const raw = (RBF.boxes || []).filter(b => !b.under); RBF.boxes = null; const B = [];
    for (const b of raw) { if (!String(b.t).trim() || b.a < 0.35 || b.w < 1) continue; if (B.some(a => a.t === b.t && Math.abs(a.x - b.x) <= 4 * b.s && Math.abs(a.y - b.y) <= 4 * b.s)) continue; B.push(b); }
    const out = []; for (let i = 0; i < B.length; i++) for (let j = i + 1; j < B.length; j++) { const a = B[i], b = B[j]; if (a.t === b.t) continue; const px = Math.max(a.s, b.s), ix = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x), iy = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y); if (ix > px && iy > px) out.push('"' + String(a.t).slice(0, 28) + '" × "' + String(b.t).slice(0, 28) + '"'); }
    const ui = g.ui, s = ui.screen, dpr = g.dpr, ws = ((s && s.widgets) || []).filter(w => !w.hidden && w.w > 0 && w.h > 0); // a string drawn by the screen (not by a widget) under a widget's box
    for (const b of B) { if (b.w8) continue; for (const w of ws) { if (w.label && String(w.label).trim() === String(b.t).trim()) continue; /* a screen drawing a widget's own symbol */ const x0 = (ui.ox + w.x * ui.scale) * dpr, y0 = (ui.oy + w.y * ui.scale) * dpr, x1 = x0 + w.w * ui.scale * dpr, y1 = y0 + w.h * ui.scale * dpr, ix = Math.min(b.x + b.w, x1) - Math.max(b.x, x0), iy = Math.min(b.y + b.h, y1) - Math.max(b.y, y0); if (ix > 2 * b.s && iy > 2 * b.s) { out.push('"' + String(b.t).slice(0, 28) + '" under [' + String(w.label || w.kind).slice(0, 20) + ']'); break; } } }
    return out; }; });
  // F7: text cut short with '…' (a maxW, the screen edge or a line limit) hides what it says: the top screen's strings
  // from one synchronous UI draw that the font or a paragraph cut (faint text a<0.35 skipped).
  await ev(() => { window.__textCuts = () => { const g = HH.game; RBF.boxes = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const raw = RBF.boxes || []; RBF.boxes = null; const out = []; for (const b of raw) if (b.cut && !b.under && b.a >= 0.35 && !out.includes(String(b.cut).slice(0, 48))) out.push(String(b.cut).slice(0, 48)); return out; }; });
  // F10: a figure (a menu figure, a portrait, a trading card) drawn after a string and over at least a quarter of it hides
  // it: the top screen's strings from one synchronous UI draw against each figure's box (faint text a<0.35 skipped).
  await ev(() => { window.__artOverText = () => { const g = HH.game; RBF.boxes = []; RBF.art = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const raw = RBF.boxes || [], art = RBF.art || []; RBF.boxes = null; RBF.art = null; const out = [];
    for (const A of art) for (let i = 0; i < Math.min(A.n, raw.length); i++) { const b = raw[i]; if (b.under || !String(b.t).trim() || b.a < 0.35 || b.w < 1) continue; const ix = Math.min(b.x + b.w, A.x + A.w) - Math.max(b.x, A.x), iy = Math.min(b.y + b.h, A.y + A.h) - Math.max(b.y, A.y); if (ix > 0 && iy > 0 && ix * iy >= 0.25 * b.w * b.h) { const k = '"' + String(b.t).slice(0, 28) + '" under a ' + A.kind; if (!out.includes(k)) out.push(k); } }
    return out; }; });
  // V1 (§1.8): two screens' words at once: every string the screens under the top one draw (an overlay's underlay) that
  // shares more than a font pixel each way with a string of the top screen, from one synchronous UI draw.
  await ev(() => { window.__twoScreens = () => { const g = HH.game, ui = g.ui, top = ui.screen, wrapped = []; RBF.boxes = [];
    const drawn = []; for (const s of ui.stack) if (s !== top && typeof s.draw === 'function') { const d = s.draw; wrapped.push([s, d]); s.draw = function () { drawn.push(s.name || '?'); const n0 = RBF.boxes ? RBF.boxes.length : 0; try { return d.apply(this, arguments); } finally { if (RBF.boxes) for (let i = n0; i < RBF.boxes.length; i++) RBF.boxes[i].under = s.name || '?'; } }; }
    try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } finally { for (const [s, d] of wrapped) s.draw = d; }
    const raw = RBF.boxes || []; RBF.boxes = null; const U = raw.filter(b => b.under && String(b.t).trim() && b.a >= 0.05), Tp = raw.filter(b => !b.under && String(b.t).trim() && b.a >= 0.35), out = [];
    if (g.mode !== 'match' && top && top.overlay) for (const n of [...new Set(drawn)]) out.push('(' + n + ' drawn under the ' + (top.name || '?') + ' overlay)'); // a screen under an overlay shows its art and sprite text too
    for (const u of U) for (const b of Tp) { const px = Math.max(u.s, b.s), ix = Math.min(u.x + u.w, b.x + b.w) - Math.max(u.x, b.x), iy = Math.min(u.y + u.h, b.y + b.h) - Math.max(u.y, b.y); if (ix > px && iy > px) { const k = '"' + String(u.t).slice(0, 24) + '" (' + u.under + ') under "' + String(b.t).slice(0, 24) + '"'; if (!out.includes(k)) out.push(k); } }
    return out; }; });
  // V13 (2.0 §5): legibility: every string a screen shows, the ones baked into its trading cards too (the card cache is
  // emptied first so they bake inside this draw), at the menus' pixel or bigger: a glyph 10 font pixels tall is then at
  // least 10 internal pixels (RBF.kUI device px each: the 360-row grid of the 1280×720 area, rounded the way the menus
  // round it).
  await ev(() => { window.__legib = () => { const g = HH.game; try { _cards.clear(); } catch (e) { /* no cards yet */ } RBF.audit = []; RBF.boxes = []; try { g.drawUI(g.ctx, g.W, g.H); } catch (e) { /* the audit's own draw */ } const sc = RBF.audit || [], bx = (RBF.boxes || []).filter(b => !b.under && String(b.t).trim()); RBF.audit = null; RBF.boxes = null; const k = RBF.kUI || 1, out = [];
    for (const b of bx) if (b.s < k) { const t = '"' + String(b.t).slice(0, 24) + '" at ' + b.s + ' < ' + k; if (!out.includes(t)) out.push(t); }
    const min = sc.length ? Math.min(...sc) : k; if (min < k && !out.length) out.push('baked text at ' + min + ' < ' + k); return { out, min, k }; }; });
  // V1 (§1.8): a push or pop never shows two screens at once (the old one is gone before the new one shows)
  { const tr = await ev(() => { if (typeof uiTransAlphas !== 'function') return { bad: ['0 to 1 (a cross-fade)'], end: [0, 1] }; const bad = []; for (let i = 0; i <= 100; i++) { const a = uiTransAlphas(i / 100); if (Math.min(a[0], a[1]) > 0) bad.push((i / 100).toFixed(2)); } const end = uiTransAlphas(1); return { bad, end }; });
    console.log((tr.bad.length || tr.end[0] !== 0 || tr.end[1] !== 1 ? 'FLAG  ' : 'ok    ') + 'transitions (push/pop: never two screens at once)' + (tr.bad.length ? ': TWO SCREENS at k = ' + tr.bad.slice(0, 6).join(', ') : '')); }
  if (big) await ev(() => { const D0 = defaultSave; window.defaultSave = () => { const d = D0(); d.settings.textSize = 1.25; return d; }; RBF.textScale = 1.25; });
  await ev(() => { localStorage.clear(); const g = HH.game; g.save = new SaveSystem(); const a = amCreate(g.save.data, { name: 'Phone Audit', look: PRESET_LOOKS[2], number: 5, style: 'slasher', seed: 31 }); a.events.length = 0; g.save.save(); });
  const audit = async (name, open, arg) => {
    await ev(open, arg); await ev(() => { if (typeof REC_TOASTS !== 'undefined') REC_TOASTS.length = 0; HH.game.ui.toastT = 0; }); /* V8: a toast is an overlay (a record broken in the scripted career would cover the next screens); story.js checks the record toast */ await wait(450); await ev(() => { const s = HH.game.ui.screen; if (s && s.finish && !s.auditCard) s.finish(); }); /* (2.1: a chapter's title card stays up for its own case) */ /* R9: a dialogue box's text typed out */ await wait(80); await ev(() => { window.__txt = []; window.__ovf.clear(); window.__txtOn = true; }); await wait(120); const ovf = await ev(() => [...window.__ovf]); const tx = await ev(() => { window.__txtOn = false; const L = window.__txt.filter(o => o.px > 0.5).sort((a, b) => a.px - b.px); const seen = new Set(), out = []; for (const o of L) { if (seen.has(o.t)) continue; seen.add(o.t); out.push(o); if (out.length >= 3) break; } return out; });
    const r = await ev(() => { const ui = HH.game.ui, s = ui.screen; if (!s) return { name: '(none)', bad: [] }; const ws = (s.widgets || []).filter(w => !w.hidden && w.enabled !== false && w.kind !== 'text'); const bad = [];
      for (const w of ws) { const hh = w.h * ui.scale, ww = w.w * ui.scale; if (ui.phone && (hh < 63.5 || ww < 63.5)) bad.push((w.label || w.kind) + ' ' + Math.round(ww) + '×' + Math.round(hh)); if (w.x < -1 || w.y < -1 || w.x + w.w > UI_W + 1 || w.y + w.h > UI_H + 1) bad.push('OFFSCREEN ' + (w.label || w.kind)); if (!(w.w >= 1 && w.h >= 1)) bad.push('ZERO-SIZE ' + (w.label || w.kind)); /* R9: a widget never laid out (it once threw inside its draw and leaked a zoom) */ }
      for (let i = 0; i < ws.length; i++) for (let j = i + 1; j < ws.length; j++) { const a = ws[i], b = ws[j]; if (a.x < b.x + b.w - 1 && b.x < a.x + a.w - 1 && a.y < b.y + b.h - 1 && b.y < a.y + a.h - 1) bad.push('OVERLAP ' + (a.label || a.kind) + ' / ' + (b.label || b.kind)); }
      return { name: s.name, n: ws.length, bad }; });
    if (dir) await P.shot(path.join(dir, name + '.jpg'));
    for (const o of ovf) r.bad.push('TEXT OVERFLOW ' + o);
    for (const o of await ev(() => window.__textOverlaps())) r.bad.push('TEXT OVERLAP ' + o); // F4
    for (const o of await ev(() => window.__textCuts())) r.bad.push('TEXT CUT "' + o + '"'); // F7
    for (const o of await ev(() => window.__twoScreens())) r.bad.push('TWO SCREENS ' + o); // V1 (§1.8)
    for (const o of await ev(() => window.__artOverText())) r.bad.push('ART OVER TEXT ' + o); // F10
    { const L = await ev(() => window.__legib()); for (const o of L.out) r.bad.push('SMALL TEXT ' + o); legib.push(L.min / L.k); } // V13 (2.0 §5)
    const minTxt = tx.length ? tx[0].px : 99; texts.push({ name, min: minTxt, tx });
    console.log((r.bad.length ? 'FLAG  ' : 'ok    ') + name + ' (' + r.name + ', ' + r.n + ' widgets, min text ' + minTxt.toFixed(1) + ' px)' + (r.bad.length ? ': ' + r.bad.slice(0, 12).join(' | ') + (r.bad.length > 12 ? ' …+' + (r.bad.length - 12) : '') : ''));
    screens++; if (r.bad.length) flagged++; // (the summary line at the end)
  };
  const texts = [], legib = []; // (V13: each screen's smallest glyph against the menus' pixel)
  let screens = 0, flagged = 0; // (3.0: how many screens were audited, how many flagged)
  // 3.0 (§2.1–2.3): the scripted careers' helpers (as tests/screens30.js opens the screens): a career's queue and inbox
  // emptied (HOME owes no message), and HOME on one of its five tabs (home, league, events, career, store)
  await ev(() => {
    window.__quiet = c => { if (!c) return; c.events = []; c.inbox = []; const B = holderOf(c); if (B) B.msgWk = null; if (typeof REC_TOASTS !== 'undefined') REC_TOASTS.length = 0; };
    window.__home = tab => { const g = HH.game, c = careerOf(g) || amateurOf(g); __quiet(c); g.hubTab = tab || 'home'; g.ui.clearTo(c && isPro(c) ? careerHub(g) : amHub(g)); };
    window.__tn = (key, o, sim) => { const g = HH.game, c = careerOf(g) || amateurOf(g); __quiet(c); const T = tnCreate(c, key, Object.assign({ mine: true }, o || {})); if (sim === 'all') tnSimAll(c, T); else { tnAdvance(c, T); for (let i = 0; i < (sim | 0); i++) tnSimMine(c, T); } __home('home'); g.ui.push(tnScreen(g, c, { kind: 'tourney', tid: T.id }, () => g.ui.pop())); return T; }; // 3.0 (§5): a tournament (sim: its games played, or 'all')
  });
  await audit('menu-new', () => { const g = HH.game; g.__c1 = g.save.data.c1; g.save.data.c1 = null; g.ui.clearTo(mainMenu(g)); }); await ev(() => { const g = HH.game; g.save.data.c1 = g.__c1; delete g.__c1; }); // F10: a new player's menu (no career yet: the league's pitch beside two players)
  await audit('title', () => HH.game.ui.clearTo(titleScreen(HH.game))); // R10: every screen
  await audit('menu', () => HH.game.ui.clearTo(mainMenu(HH.game)));
  const setTabs = await ev(() => SET_TABS.slice()); // 3.0: six tabs (Accessibility became Display; Save is new)
  for (let t = 0; t < setTabs.length; t++) await audit('settings-' + setTabs[t].toLowerCase(), t => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(settingsScreen(g, t)); }, t); // R10: every tab
  if (desk) await audit('dev', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(devScreen(g)); }); // R10: the dev menu (a keyboard's ` key)
  if (desk) await audit('remap', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(remapScreen(g)); }); // R10: key remapping (keyboards only: a phone doesn't show it)
  await audit('slots', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.save.save(); g.ui.push(slotsScreen(g)); }); // R10: three save slots
  await audit('credits', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(creditsScreen(g)); });
  await audit('tip', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(tipScreen(g, 'ladder')); }); // R10: a first-time tip
  await audit('howto', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(howToScreen(HH.game)); });
  await audit('practice-hub', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(practiceHubScreen(HH.game)); }); // F1: Practice replaces Extras
  await audit('quickplay', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(quickPlayScreen(HH.game)); });
  await audit('threept', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(threePointScreen(HH.game)); });
  await audit('free-practice', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(practiceHubScreen(HH.game)); HH.game.ui.screen.widgets.find(w => w.label === 'Shooting practice').onPress(); });
  await audit('confirm', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(settingsScreen(g)); g.ui.push(confirmScreen(g, 'Erase everything, including your career and Hall of Fame?', () => {})); });
  await audit('keyboard', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(keyboardScreen(g, 'Rookie', () => {})); });
  await audit('halloffame', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(hallOfFameScreen(HH.game)); });
  await audit('create', () => { HH.game.ui.clearTo(mainMenu(HH.game)); HH.game.ui.push(createPlayerScreen(HH.game)); });
  await audit('customize-face', () => { const g = HH.game; const s = g.ui.screen; const w = (s.widgets || []).find(x => /face|Customize|Edit/i.test(x.label || '')); if (w) w.onPress(); });
  // ---- high school: a new player before the tryouts ----
  // 3.0 (§2.1): HOME and its five tabs (2.x's hub: Play · Train · Me · Team · Shop / Recruit)
  for (const tab of ['home', 'league', 'events', 'career', 'store']) await audit('am-hub-' + tab, t => __home(t), tab);
  await audit('am-road', () => { __home('events'); HH.game.ui.push(roadScreen(HH.game)); }); // V5 (2.0 §4.1): the Road to the League (EVENTS)
  await audit('am-roadcard', () => { const g = HH.game, a = g.save.data.c1, r = ROAD.list.find(x => x.id === 'offer') || ROAD.list[0], no = window.HH_NO_ROAD_CARDS; __home('events'); window.HH_NO_ROAD_CARDS = false; try { roadReward(a, r); } finally { window.HH_NO_ROAD_CARDS = no; } a.events = a.events.filter(e => e.kind === 'road'); g.ui.push(amEventScreen(g)); }); // V5: a goal's card (3.0: when a queue plays out; HOME's results make it a reward line)
  for (const t of ['buzz', 'team', 'money', 'crew', 'shop']) await audit('am-guide-' + t, t => { const g = HH.game; __home('home'); g.ui.push(statsGuideScreen(g, t)); }, t); // F9: the stats guide (an amateur; 3.0: Fame & confidence, Your crew for the staff)
  await audit('am-shop-store', () => { const g = HH.game, a = g.save.data.c1; a.cash = 2600; a.gear = { sleeve: 1, shoes: 2 }; g.shopTab = null; __home('store'); g.ui.push(shopScreen(g, 'store')); }); // F8; V11; 3.0 (§6.1): the store's twelve items (F8's gear migrates to their levels)
  for (const v of ['locker', 'extras', 'celebs']) await audit('am-shop-' + v, v => { const g = HH.game; g.shopTab = { view: v, sel: null, page: 0, sub: null }; __home('store'); g.ui.push(shopScreen(g)); }, v); // V11: an amateur's locker (F8's gear, migrated) and extras (V13: and the celebrations)
  await audit('am-shop-celebs-item', () => { const g = HH.game; g.shopTab = { view: 'celebs', sel: 'earCup', page: 0, sub: 'celeb' }; __home('store'); g.ui.push(shopScreen(g)); }); // V13 (2.0 §6): one celebration (a phone: its own page)
  await audit('am-stattip', () => { const g = HH.game; __home('home'); g.ui.push(statTipScreen(g, 'fatigue')); }); // V13 (2.0 §5): a stat's card (a tap on a phone)
  await audit('whatsnew', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(whatsNewScreen(g)); }); // V13 (2.0 §5): What's new
  await audit('whatsnew-p3', () => { const s = HH.game.ui.screen, n = s.widgets.find(w => w.label === '▶' && !w.hidden); if (n) { n.onPress(); n.onPress(); } }); // (a phone's last page)
  await audit('am-tryout', () => { const g = HH.game; __home('home'); g.ui.push(tryoutScreen(g)); }); // R5: tryouts, the shootout first
  await audit('am-tryout-1v1', () => { const g = HH.game, a = g.save.data.c1; if (a.tryout && a.tryout.step === 'drill') hsTryoutDrill(a, 12); __home('home'); g.ui.push(tryoutScreen(g)); }); // R5: then the 1v1 against a senior
  await audit('am-tryout-post', () => { const g = HH.game; g.ui.push(tryoutPostScreen(g, { contest3: { score: 12 }, winner: 0, teams: [{ score: 7 }, { score: 5 }] }, { part: 'none' })); }); // R10: the tryout's result card
  await audit('am-team', () => { const g = HH.game; __home('league'); g.ui.push(teamScreen(g)); }); // R3 (3.0: LEAGUE's Your team → Roster)
  await audit('am-genes-2', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); a.events.unshift({ kind: 'genes', title: 'YOUR GENES', lines: [] }); g.ui.clearTo(amHub(g)); g.ui.push(amEventScreen(g)); const s = g.ui.screen; s.widgets[0].onPress(); }); // R3: page 2 (3.0: your body and the badges in reach)
  await audit('am-badge-card', () => { const g = HH.game, a = g.save.data.c1, n = badgeNextUp(a, 1)[0]; __home('career'); g.ui.push(traitCardScreen(g, n ? n.id : 'clutch', a)); }); // V3 (§2.3); 3.0 (§6.3): a badge's card, from a chip (its deed and your count)
  await audit('trait-card-legendary', () => { const g = HH.game; __home('career'); g.ui.push(traitCardScreen(g, 'generational', null)); }); // V3: the longest card
  await audit('codex-traits-0', () => { const g = HH.game; __home('career'); g.ui.push(statsGuideScreen(g, 'traits')); }); // V3; 3.0: the Codex's Badges page (CAREER's Badges)...
  if (!desk) await audit('codex-traits-1', () => { const s = HH.game.ui.screen, w = s.widgets.find(x => x.kind === 'select'), i = ((w && w.options) || []).findIndex(o => /^Badges 2/.test(o)); if (i >= 0) w.set(i); }); // ...a phone's second page (paged on the drawn screen: its pages are measured as it draws)
  await audit('trait-levelup', () => { const g = HH.game, a = g.save.data.c1, d = TR.list.ironman; __home('career'); g.ui.push(traitEventScreen(g, a, { kind: 'traitlevel', trait: 'ironman', level: 2, title: 'BADGE LEVEL UP: ' + d.name.toUpperCase(), lines: [d.name + ' ' + trLevelName(2) + '!'].concat(traitLevelLines('ironman', 2)) }, () => {})); }); // V3: a level-up's card (3.0: a badge's, when a queue plays out; HOME's results make it a reward line)
  for (let part = 0; part < (desk ? 1 : 3); part++) await audit('codex-moves-' + part, part => { const g = HH.game; if (!part) { __home('career'); g.ui.push(statsGuideScreen(g, 'moves')); return; } const s = g.ui.screen, w = s.widgets.find(x => x.kind === 'select'); const opts = w.options || []; const i = opts.findIndex(o => /^Moves/.test(o)); if (i >= 0 && /^Moves/.test(opts[i + part] || '')) w.set(i + part); }, part); /* V6: paged on the drawn screen (the pages are measured as it draws; before, part 1 and 2 showed the next topic) */ // V4: the move list (a phone: in parts)
  await audit('touch-layout', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); g.ui.push(touchLayoutScreen(g)); }); // V4: the layout editor
  // ---- high school: the season under way (the tryouts played, three weeks in, you start) ----
  await ev(() => { const a = HH.game.save.data.c1; if (a.tryout && a.tryout.step !== 'done') hsSimTryout(a); const L = ladderOf(a); if (L && L.indexOf('me') > 0) { L.splice(L.indexOf('me'), 1); L.unshift('me'); hsSquadSync(a); } a.ineligible = 0; for (let i = 0; i < 3; i++) { a.fatigue = 0; amSimGame(a); } __quiet(a); });
  await audit('am-hub-home-season', () => __home('home')); // 3.0 (§2.2): HOME's PLAY and SIM, the season line, the table, the next event, the plan
  if (!desk) for (const t of ['home', 'career']) await audit('am-' + t + '-more', t => { __home(t); const s = HH.game.ui.screen, b = (s.widgets || []).find(w => w.label === 'MORE…'); if (b) b.onPress(); }, t); // 3.0: a phone's MORE… (the sims, the scout report, the drill; CAREER's other doors)
  { // 3.0 (§2.2): SIM is a toast on HOME (2.x's sim summary screen); a toast isn't a screen: the text cut check alone
    const cuts = await ev(() => { const g = HH.game; __home('home'); g.ui.toastMsg(simRunToast({ weeks: 3, w: 2, l: 1, pts: 37, games: 3, lines: ['Badge level up: Clutch Lv2.', 'Road to the League: a college offer. Court shoes (Lv1), on you now: Speed +1.'], stop: 'next: a game against the #2 team in the district' })); return window.__textCuts(); });
    screens++; if (cuts.length) flagged++; console.log((cuts.length ? 'FLAG  ' : 'ok    ') + 'am-simtoast (the SIM toast on HOME)' + (cuts.length ? ': ' + cuts.map(t => 'TEXT CUT "' + t + '"').join(' | ') : '')); await ev(() => { HH.game.ui.toastT = 0; });
  }
  await audit('am-pregame', () => { const g = HH.game, a = g.save.data.c1; a.plan = 'auto'; __home('home'); g.ui.push(amPregameScreen(g)); }); // V4 (2.0 §3): the scouting report before a game (3.0: HOME's Scout report)
  await audit('am-pregame-film', () => { const g = HH.game, a = g.save.data.c1; a.cash = Math.max(a.cash || 0, 2000); gearConsume(a, 'film'); __home('home'); g.ui.push(amPregameScreen(g)); }); // V4: more of their tendencies (3.0: the store's film session for 2.x's Film plan)
  // 3.0 (§2.3): a message (2.x's dialogue cards, story cards and cutscenes): one icon, a line and its detail, three answers (the coaching carousel's, recCarouselFire's lines with the two longest program names)
  await audit('am-message', () => { const g = HH.game, a = g.save.data.c1, L = COLLEGES.slice().sort((p, q) => q.name.length - p.name.length); __quiet(a); a.events = [{ kind: 'dialog', offer: true, icon: 'swap', title: 'YOUR COACH IS LEAVING', rec: { pid: L[0].id, to: L[1].id, carousel: true }, lines: [colCoachTitle(colCoach(a, L[0].id)) + ' takes the job at ' + L[1].name + '.', L[0].name + ' will name a new coach; your commitment there still stands.'], choice: [{ label: 'Follow the coach', note: 'Their offer: no flip cost', rec: { car: 'follow' } }, { label: 'Stay committed', note: 'A new coach; your spot stands', rec: { car: 'stay' }, def: true }, { label: 'Reopen recruiting', note: 'No flip cost: the coach left, not you', rec: { car: 'reopen' } }] }]; g.hubTab = 'home'; g.ui.clearTo(amHub(g)); });
  await audit('am-records', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); recordsAfterGame(a, { pts: 18, reb: 7, stl: 2, blk: 1, tpm: 2 }, true); recordsAfterGame(a, { pts: CONFIG.records.levels.hs.pts[0] + 1, reb: 3 }, true); __home('career'); g.ui.push(recordsBookScreen(g, a)); }); // V8: the record book (a state record broken)
  await audit('am-records-book', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => w.label === 'Records'); if (b) b.onPress(); }); // (a phone: the records view)
  // 3.0 (§2.2): the season's end is one screen, the Season review (2.x's awards night, recap and growth cards); Awards night is its button
  await audit('am-review-awards', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); a.events = [{ kind: 'ceremony', title: 'AWARDS NIGHT', sub: (a.school || 'Your school') + ' · season ' + a.season, rows: ['District MVP', 'All-District 1st team', 'District champion'].map(x => ({ award: x, name: a.name, mine: true })) }, { kind: 'recap', title: 'SEASON ' + a.season + ' RECAP', lines: ['Record 9-1 · finished #1 of 6 · District champions', 'Awards: District MVP, All-District 1st team, District champion', 'Season: 21.4 points a game, 51% from the field.'] }]; g.hubTab = 'home'; g.ui.clearTo(amHub(g)); });
  await audit('am-awards-night', () => { const s = HH.game.ui.screen, b = (s.widgets || []).find(w => w.label === 'Awards night'); if (b) b.onPress(); }); // V8 (2.0 §4.9): the awards ceremony
  await audit('am-awards-night-all', () => { const s = HH.game.ui.screen; if (s && s.onTap) s.onTap(); }); // (every award shown)
  await audit('am-review-bench', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); a.log.push({ season: a.season, age: a.age, stage: 'hs', label: 'Varsity', w: 4, l: 2, rank: 3, size: 6, ppg: 0, fg: 0, ovr: amOvr(a), awards: [], g: 0, ovr0: amOvr(a) - 2, chW: 1, chL: 2 }); a.events = [{ kind: 'recap', title: 'SEASON ' + a.season + ' RECAP', lines: ['Record 4-2 · finished #3 of 6', 'No awards this season.', 'You didn\'t play a game: the bench all season.'] }]; g.hubTab = 'home'; g.ui.clearTo(amHub(g)); }); await ev(() => { const a = HH.game.save.data.c1; a.log.pop(); __quiet(a); }); // V1 (§1.12): a season on the bench
  await audit('am-review-growth', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); a.events = [{ kind: 'growth', title: 'GROWTH SPURT!', grow: { from: a.height - 0.03, to: a.height }, lines: ['You grew 1″ this summer.', 'Height changes your game.'] }]; g.hubTab = 'home'; g.ui.clearTo(amHub(g)); }); // a growth spurt
  // 3.0 (§3): the focus picker and the weekly drill (2.x's practice screens: the plan, the session, its result)
  await audit('am-focuspick', () => { const g = HH.game; __home('home'); g.ui.push(focusPickerScreen(g)); }); // every rating's "+1 in about N weeks"
  await audit('am-drillpost', () => { const g = HH.game, a = g.save.data.c1; __home('home'); holderOf(a).wk = {}; g.ui.push(drillPostScreen(g, { contest3: { score: 17 } }, { kind: 'drill', focus: 'handles' })); }); // the drill's result: the week's training +%
  // 3.0 (§4.2): LEAGUE's charts (2.x's standings): the standings, the rankings, the leaders, your team, your charts
  await audit('am-standings', () => { __home('league'); HH.game.ui.push(standingsChartScreen(HH.game)); });
  await audit('am-rankings', () => { __home('league'); HH.game.ui.push(rankingsChartScreen(HH.game)); });
  await audit('am-leaders', () => { __home('league'); HH.game.ui.push(leadersChartScreen(HH.game)); });
  await audit('am-teampage', () => { __home('league'); HH.game.ui.push(teamPageScreen(HH.game)); });
  await audit('am-mycharts', () => { __home('league'); HH.game.ui.push(myChartsScreen(HH.game)); });
  await audit('am-history', () => { __home('career'); HH.game.ui.push(amHistoryScreen(HH.game)); });
  await audit('news', () => { __home('career'); HH.game.ui.push(headlinesScreen(HH.game)); });
  await audit('trophies', () => { __home('career'); HH.game.ui.push(trophyCaseScreen(HH.game)); });
  await audit('timeline', () => { __home('career'); HH.game.ui.push(timelineScreen(HH.game)); });
  await audit('am-result', () => { const g = HH.game, a = g.save.data.c1; const r = amSimGame(a); __quiet(a); g.ui.clearTo(amResultScreen(g, r, null)); });
  await audit('am-result-tired', () => { const g = HH.game, a = g.save.data.c1; const r = amSimGame(a); __quiet(a); if (r.bench || !r.line || r.line.fga == null) Object.assign(r, { bench: false, gains: [], line: { pts: 4, fgm: 2, fga: 5, tpm: 0, tpa: 1, reb: 3, stl: 1, blk: 0 } }); g.__fat = a.fatigue; a.fatigue = 98; r.wk = Object.assign({}, r.wk || {}, { plan: 'focus', k: 'handles', practiceXp: 9, injury: { name: 'Sprained ankle', games: 2 } }); g.ui.clearTo(amResultScreen(g, r, null)); }); await ev(() => { const g = HH.game; g.save.data.c1.fatigue = g.__fat || 0; delete g.__fat; }); // V1 (§1.7): a tired week with an injury
  await audit('am-result-slump', () => { const g = HH.game, a = g.save.data.c1; const r = amSimGame(a); __quiet(a); Object.assign(r, { slump: 'start', grade: r.grade || 'D', simmed: true }); r.wk = Object.assign({}, r.wk, { injury: { name: 'Knee sprain', games: 3, loss: { k: 'jmp', pts: 2, done: true } } }); g.ui.clearTo(amResultScreen(g, r, null)); }); // V6 (§1.2): a slump, the grade's XP, an injury that costs points for good
  await audit('am-home-slump', () => { const g = HH.game, a = g.save.data.c1; a.slump = { n: 3, on: true }; a.injury = { name: 'Knee sprain', games: 2, loss: { k: 'jmp', pts: 2, done: true } }; __home('home'); }); await ev(() => { const a = HH.game.save.data.c1; delete a.slump; a.injury = null; }); // V6: slumping and hurt (2.x's Train tab: 3.0's HOME)
  await audit('am-hub-jv', () => { const g = HH.game, a = g.save.data.c1; if (isStarter(a)) { const L = ladderOf(a); L.splice(L.indexOf('me'), 1); L.splice(2, 0, 'me'); hsSquadSync(a); } __home('home'); }); // F11; 3.0 (§4.3): off the top rung, HOME's game is JV's
  await audit('am-team-jv', () => { const g = HH.game; __home('league'); g.ui.push(teamScreen(g)); }); // F11: JV → VARSITY on the Team page, and how to move up
  await audit('am-guide-team-jv', () => { const g = HH.game; __home('home'); g.ui.push(statsGuideScreen(g, 'team')); }); // F11: the guide's Your team entry
  await audit('am-hub-varsity', () => { const g = HH.game, a = g.save.data.c1; hsToVarsity(a, 'audit'); hsBuildLeague(a, amRng(a)); __home('home'); }); // F11: VARSITY · TOP TEAM
  await audit('news-fame', () => { const g = HH.game, a = g.save.data.c1; a.fame = 74; __home('career'); g.ui.push(headlinesScreen(g)); }); // R8: the BUZZ panel (3.0: one Fame meter; a phone: a line on the paper)
  if (!desk) await audit('news-fame-tab', () => { const s = HH.game.ui.screen, b = (s.widgets || []).find(w => w.label === 'FAME'); if (b) b.onPress(); }); // F7: a phone's FAME tab (a desktop shows it beside the headlines)
  await audit('am-ladder', () => { const g = HH.game, a = g.save.data.c1; ladderInit(a, 3); __home('league'); g.ui.push(ladderScreen(g)); }); // R4: the depth chart
  await audit('am-bench', () => { const g = HH.game, a = g.save.data.c1; ladderInit(a, 2); hsSquadSync(a); const r = amSimGame(a); __quiet(a); g.ui.clearTo(amResultScreen(g, r, null)); }); // 3.0 (§4.3): a week off the top rung is a JV game
  await audit('am-lowerleague', () => { const g = HH.game; __home('league'); g.ui.push(lowerLeagueScreen(g)); }); // 3.0 (§4.3): the league below
  // 3.0 (§5): tournaments: one under way, a game's result over it, a finished one's chart
  await audit('am-tn', () => __tn('aau1', null, 1));
  await audit('am-tn-result', () => { const g = HH.game, a = g.save.data.c1, T = __tn('aau2', null, 0), rec = tnSimMine(a, T); g.ui.replace(tnScreen(g, a, { kind: 'tourney', tid: T.id }, () => g.ui.pop())); g.ui.push(tnResultScreen(g, rec, null)); });
  await audit('am-tn-chart', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); const T = tnCreate(a, 'u17', { mine: true }); tnSimAll(a, T); __home('league'); g.ui.push(tnChartScreen(g, a, T)); });
  await audit('am-summer', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); hsSummerStart(a); g.sumPick = null; __home('home'); g.ui.push(summerScreen(g)); }); // R5
  await audit('am-summer-hub', () => __home('home')); // R5: HOME waits for the summer
  await audit('am-train-study', () => { const g = HH.game, a = g.save.data.c1; hsSummerChoose(a, 'rest'); a.gpa = 2.15; a.wk = {}; __home('home'); }); // 2.1 (§1.5); 3.0 (§3): HOME's plan row (AUTO: STUDY under 2.3)
  await audit('am-gpa-warn', () => { const g = HH.game, a = g.save.data.c1; a.gpa = 1.92; __home('home'); }); // 2.1 (§1.5): HOME's GPA warning
  await audit('am-recruiting', () => { const g = HH.game, a = g.save.data.c1; hsUpdateRank(a, 'audit'); hsOfferCheck(a, amRng(a), 'final'); __home('home'); g.ui.push(recBoardScreen(g)); g.ui.push(recruitingScreen(g)); }); // R5; 3.0 (§8): Offers & rank (the recruiting board's)
  await audit('am-recruiting-gpa', () => { const g = HH.game, a = g.save.data.c1; a.gpa = 3.6; if (!a.offers.some(o => o.academic)) a.offers.push(colOfferFrom(a, colProg('ashford'), 'final')); __home('home'); g.ui.push(recBoardScreen(g)); g.ui.push(recruitingScreen(g)); }); // V9: the offers' GPA lines, an elite academic program
  await audit('am-recboard', () => { const g = HH.game; __home('home'); g.ui.push(recBoardScreen(g)); }); // 2.1 (§2.1); 3.0 (§8): the recruiting board (HOME's Recruiting; 2.x's RECRUIT tab)
  await audit('colbrowser', () => { const g = HH.game; g.colBrowse = null; __home('league'); g.ui.push(collegeBrowserScreen(g)); }); // 2.1 (§2.1): the College Browser (3.0: all 64 programs ranked, no search or filters)
  await audit('colbrowser-page2', () => { const g = HH.game; colBrowseState(g).page = 1; __home('league'); g.ui.push(collegeBrowserScreen(g)); });
  await audit('colprogram', () => { const g = HH.game, a = g.save.data.c1, o = (a.offers || []).find(x => x.pid && !x.pulled); g.colBrowse = null; __home('league'); g.ui.push(collegeProgramScreen(g, o ? o.pid : 'royaloak')); }); // a program's page: your chances there
  if (!desk) for (const v of [1, 2]) await audit('colprogram-view' + v, k => { HH.game.ui.screen.widgets.find(w => w.label === 'View').set(k); }, v); // phones: Coach & school, Team & history
  await audit('colprogram-blueblood', () => { const g = HH.game; __home('league'); g.ui.push(collegeProgramScreen(g, 'kingsbridge')); });
  await audit('recactions', () => { const g = HH.game, a = g.save.data.c1, o = (a.offers || []).find(x => x.pid && !x.pulled); __home('league'); g.ui.push(recActionScreen(g, o ? o.pid : 'royaloak')); }); // 2.1 (§2.3): a program's actions (3.0: camps and visits)
  await audit('recactions-far', () => { const g = HH.game, a = g.save.data.c1, P = COLLEGES.slice().sort((p, q) => (colInterest(a, p.id) || 0) - (colInterest(a, q.id) || 0))[0]; __home('league'); g.ui.push(recActionScreen(g, P.id)); }); // ...one that isn't interested (every action's reason)
  await audit('reclog', () => { const g = HH.game; __home('home'); g.ui.push(recLogScreen(g)); }); // the recruiting log
  await audit('am-state', () => { const g = HH.game, a = g.save.data.c1; if (!a.league || a.league.format !== 'district') { if (a.squad === 'jv') hsToVarsity(a, 'audit'); hsBuildLeague(a, amRng(a)); } a.league.playoffs = { round: 2, seeds: ['me'], pending: null, other: null, champion: null }; hsStartState(a, amRng(a)); __home('home'); }); // R5: the state tournament on HOME
  await audit('am-state-standings', () => { __home('league'); HH.game.ui.push(standingsChartScreen(HH.game)); }); // R5 (3.0: LEAGUE's standings)
  await audit('am-state-bracket', () => { __home('events'); HH.game.ui.push(stateBracketScreen(HH.game)); }); // R5 (EVENTS: the State bracket)
  await audit('am-brackets', () => { __home('league'); HH.game.ui.push(bracketsScreen(HH.game)); }); // 3.0 (§4.2): LEAGUE's brackets
  await audit('signing-none', () => { const g = HH.game, a = g.save.data.c1, keep = a.offers; __quiet(a); a.stage = 'hs'; a.stageYear = 4; a.offers = []; amStartRecruiting(a, amRng(a)); a.offers = keep; __home('home'); g.ui.push(amDecisionScreen(g)); }); // 2.1 (§2.6): nobody offered
  await audit('recwalkon', () => { const g = HH.game; g.ui.push(recWalkOnScreen(g)); }); // ...a walk-on: the programs whose GPA line you meet
  await audit('recruit', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); a.stage = 'hs'; a.stageYear = 4; a.decision = null; for (const k of RATING_KEYS) a.r[k] = Math.max(a.r[k], 66); a.gpa = Math.max(a.gpa || 0, 3); hsOfferCheck(a, amRng(a), 'final'); amStartRecruiting(a, amRng(a)); __home('home'); g.ui.push(amDecisionScreen(g)); }); // 2.1 (§2.5): Signing Day
  await audit('visit', () => { const g = HH.game, a = g.save.data.c1; g.ui.push(visitScreen(g, a.decision.offers[0])); });
  await audit('recruit-power', () => { const g = HH.game, a = g.save.data.c1, d = a.decision, offs = d.offers.filter(o => !o.draft).slice(0, 4).map(o => Object.assign({}, o)), skip = d.offers.find(o => o.draft); g.__offers = d.offers; offs.forEach((o, i) => { o.tier = [1, 2, 3][i % 3]; }); if (offs[1]) { offs[1].visited = true; offs[1].fac = 3; offs[1].focus = Object.keys(CR.trainFocus)[1]; } d.offers = offs.concat(skip ? [skip] : []); __home('home'); g.ui.push(recruitScreen(g)); }); await ev(() => { const g = HH.game; g.save.data.c1.decision.offers = g.__offers; delete g.__offers; }); // V1 (§1.9): a power conference and a blue blood (2.0's offer board: a save from before 2.1 brings its best four offers)
  await audit('commit-day', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); a.events.push({ kind: 'commit', offers: a.decision.offers.filter(o => !o.draft), chosen: 0 }); g.hubTab = 'home'; g.ui.clearTo(amHub(g)); });
  await audit('signing-day-hats', () => { const g = HH.game, a = g.save.data.c1, hats = COLLEGES.slice(0, 15).map(q => ({ name: q.name, colors: q.colors, tier: q.tier, pid: q.id })); __quiet(a); a.events.push({ kind: 'commit', title: 'SIGNING DAY', signing: true, offers: hats, chosen: 4, lines: ['x signs.', 'Power conference · Coach X · facilities ★★★☆☆'] }); g.hubTab = 'home'; g.ui.clearTo(amHub(g)); }); // 2.1 (§2.5): fifteen hats, in two rows
  await audit('declare', () => { const g = HH.game, a = g.save.data.c1; amChooseCollege(a, a.decision.offers[0]); __quiet(a); a.decision = { kind: 'declare' }; g.hubTab = 'home'; g.ui.clearTo(amHub(g)); g.ui.push(amDecisionScreen(g)); });
  // ---- college ----
  await audit('col-hub-home', () => { const g = HH.game, a = g.save.data.c1; a.decision = null; for (let i = 0; i < 3; i++) { a.events.length = 0; a.fatigue = 0; amSimGame(a); } __home('home'); }); // R6: college HOME (conference record, overall, the mock draft)
  for (const tab of ['league', 'events', 'career', 'store']) await audit('col-hub-' + tab, t => { const a = HH.game.save.data.c1; if (t === 'career') a.loan = 6000; __home(t); }, tab); // 2.1: Pro stock and Colleges (LEAGUE); V9: GPA, the scholarship and the degree (CAREER)
  await audit('col-colleges', () => { const g = HH.game; g.colBrowse = null; __home('league'); g.ui.push(collegeBrowserScreen(g)); }); // 2.1 (§2.1): the browser in college (no interest; your program gold)
  await audit('col-program-mine', () => { const g = HH.game, a = g.save.data.c1; __home('league'); g.ui.push(collegeProgramScreen(g, a.program.pid || 'royaloak')); });
  await audit('col-team', () => { const g = HH.game; __home('league'); g.ui.push(teamScreen(g)); }); // F11: the four program levels, yours lit
  await audit('col-guide-team', () => { const g = HH.game; __home('home'); g.ui.push(statsGuideScreen(g, 'team')); }); // F11: the guide's Your program entry
  await audit('col-standings', () => { __home('league'); HH.game.ui.push(standingsChartScreen(HH.game)); }); // R6: marquee games (3.0: LEAGUE's standings)
  await audit('col-draftstock', () => { const g = HH.game; __home('league'); g.ui.push(draftStockScreen(g)); }); // R6
  await audit('col-nil', () => { const g = HH.game, a = g.save.data.c1; __quiet(a); colNilOffer(a, amRng(a), 'audit'); g.hubTab = 'home'; g.ui.clearTo(amHub(g)); }); // R6: an NIL offer (3.0: a message)
  await audit('col-conf-bracket', () => { const g = HH.game, a = g.save.data.c1; let n = 0; while (!a.league.playoffs && n++ < 20) { a.events.length = 0; a.fatigue = 0; amSimGame(a); } __home('events'); g.ui.push(collegeBracketScreen(g, 'conf')); }); // R6
  await audit('col-nat-bracket', () => { const g = HH.game, a = g.save.data.c1; const rng = amRng(a); for (let i = 0; i < 3 && a.league.playoffs.round < 31; i++) colAdvance(a, rng, true); colAdvance(a, rng, true); __home('events'); g.ui.push(collegeBracketScreen(g, 'nat')); }); // R6: the field of 64 after a round
  await audit('col-portal', () => { const g = HH.game, a = g.save.data.c1; a.decision = { kind: 'portal', offers: colPortalOffers(a, amRng(a)), bench: 8, games: 12 }; __home('home'); g.ui.push(amDecisionScreen(g)); }); // R6: the transfer portal
  await audit('col-agent', () => { const g = HH.game, a = g.save.data.c1; a.decision = null; a.agent = undefined; __quiet(a); colAgentPitch(a); g.hubTab = 'home'; g.ui.clearTo(amHub(g)); }); // R6: an agent calls (3.0: a message)
  await audit('combine', () => { const g = HH.game, a = g.save.data.c1; a.decision = null; a.stage = 'combine'; __home('home'); g.ui.push(amCombineScreen(g)); });
  await audit('pro-offers', () => { const g = HH.game, a = g.save.data.c1; g.save.data.career = null; a.stage = 'combine'; a.decision = null; a.proOffers = null; a.events.length = 0; g.ui.clearTo(proOffersScreen(g)); }); // F7: no draft
  await audit('signing', () => { const g = HH.game; const c = testProLeague(12, g.save.data); g.save.data.c1.handedOff = true; c.events.length = 0; const s = signingScreen(g); g.ui.clearTo(s); s.onTap(); s.onTap(); });
  // ---- the pros ----
  await audit('pro-hub-home', () => { const g = HH.game; const c = testProLeague(12, g.save.data); g.save.data.c1.handedOff = true; __quiet(c); roadCheck(c); __quiet(c); g.save.save(); __home('home'); });
  for (const tab of ['league', 'events', 'career', 'store']) await audit('pro-hub-' + tab, t => __home(t), tab); // V5 (2.0 §5); 3.0 (§2.1): the five tabs
  await audit('pro-road', () => { __home('events'); HH.game.ui.push(roadScreen(HH.game)); });
  await audit('pro-team', () => { __home('league'); HH.game.ui.push(teamPageScreen(HH.game)); }); // R3 (3.0: LEAGUE's Your team, the franchise behind it)
  await audit('guide-you-p0', () => { const g = HH.game, c = g.save.data.career; c.me.slump = { n: 3, on: true }; __home('career'); g.ui.push(statsGuideScreen(g, 'you')); }); // V6: the Codex's climb entries (potential, the competition, XP) on its later pages...
  for (let part = 1; part < 3; part++) await audit('guide-you-' + part, part => { const s = HH.game.ui.screen, w = s.widgets.find(x => x.kind === 'select'), opts = (w && w.options) || [], i = opts.findIndex(o => /^OVR/.test(o)); if (i >= 0 && /^OVR/.test(opts[i + part] || '')) w.set(i + part); }, part); await ev(() => { delete HH.game.save.data.career.me.slump; }); // ...paged on the drawn screen (its pages are measured as it draws)
  if (desk) await audit('career-menu', () => { const g = HH.game; __home('career'); g.ui.push(careerMenuScreen(g)); }); // F7/F9: the Career menu's tiles (3.0: CAREER's Career menu, a desktop's)
  await audit('league-franchises', () => { const g = HH.game; __home('league'); g.leagueTab = { tab: 1, player: 0 }; g.ui.push(leagueScreen(g)); }); // F7
  await audit('league-standings', () => { const g = HH.game; __home('league'); g.leagueTab = { tab: 0, player: 0 }; g.ui.push(leagueScreen(g)); });
  await audit('league-races', () => { const g = HH.game; __home('league'); g.leagueTab = { tab: 8, player: 0 }; g.ui.push(leagueScreen(g)); }); // 2.1 (§3.2): the award races
  await audit('league-schedule', () => { const g = HH.game; __home('league'); g.leagueTab = { tab: 3, player: 0 }; g.ui.push(leagueScreen(g)); }); // 2.1: fifteen weeks and the key weeks
  await audit('league-history', () => { const g = HH.game; __home('league'); g.leagueTab = { tab: 6, player: 0 }; g.ui.push(leagueScreen(g)); });
  await audit('pregame', () => { const g = HH.game, c = g.save.data.career; __home('home'); g.ui.push(pregameScreen(g, userGame(c))); }); // HOME's Scout report
  await audit('pro-focuspick', () => { __home('home'); HH.game.ui.push(focusPickerScreen(HH.game)); }); // 3.0 (§3): the focus picker (2.x's practice screen)
  await audit('league', () => { __home('league'); HH.game.ui.push(leagueScreen(HH.game)); });
  await audit('player', () => { __home('career'); HH.game.ui.push(playerScreen(HH.game)); });
  for (const t of ['you', 'buzz', 'body', 'shop', 'team', 'money', 'crew']) await audit('guide-' + t, t => { const g = HH.game, c = g.save.data.career; c.me.fame = 66; c.me.fatigue = 57; c.me.gear = { sleeve: 2, braces: 1 }; __home('career'); g.ui.push(statsGuideScreen(g, t)); }, t); // F9: the stats guide (a pro; 3.0: Your crew for the staff)
  for (const t of [0, 1, 2, 4, 5, 6, 7]) await audit('management-tab' + t, t => { __home('career'); HH.game.mgmtTab = { tab: t }; HH.game.ui.push(managementScreen(HH.game)); }, t); // the Office's tabs (3.0: no Staff tab; its id 3 is gone)
  await audit('management-tab8', () => { const g = HH.game, c = g.save.data.career, s0 = c.season; c.me.money = 6e7; c.season = Math.max(s0, BIG.stake.fromSeason); if (!bigOf(c).stake) bigBuy(c, 'stake'); if (!bigOf(c).sneaker) bigBuy(c, 'sneaker'); c.season = s0; __home('career'); g.mgmtTab = { tab: 8 }; g.ui.push(managementScreen(g)); }); // 2.1 (§1.4): the big buys (a stake and a share owned)
  await audit('big-sneaker', () => { const g = HH.game, c = g.save.data.career; __home('career'); g.mgmtTab = { tab: 8 }; g.ui.push(managementScreen(g)); g.ui.push(bigSneakerScreen(g, c, () => {})); }); // 2.1 (§1.4): buy another share or sell them
  // 3.0 (§2.3): the pros' messages (2.x's story cards): a franchise calls (urgent: at once), a trade request or a buyout, a shoe deal
  await audit('pro-tradeoffer', () => { const g = HH.game, c = g.save.data.career, me = meOf(c), T = frTable(c), mine = frMine(c), dest = frByStars(T, Math.min(5, mine + 1), [me.club])[0] || frByStars(T, mine, [me.club])[0] || frIds().find(k => k !== me.club); __quiet(c); c.events = [{ kind: 'tradeoffer', title: 'A TRADE OFFER', who: 'agent', dest, lines: ['Your agent: "The ' + frFullName(dest) + ' called. A ' + frStars(c, dest) + '★ franchise, and they want you now."', 'They trade for you: your contract comes with you, and you compete for the start there. No distraction: they asked.', 'Or stay with the ' + clubOf(me.club).name + ' (' + mine + '★) and finish the season.'] }]; g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); }); // 2.1 (§1.1): a franchise calls (proTradeOfferCheck's lines; ACCEPT, gold)
  for (const t of [1, 4, 5]) await audit('business-r7-tab' + t, t => { const g = HH.game, c = g.save.data.career; c.me.money = 3e7; c.me.fame = Math.round(PR.shoeFame * MD.fameMax); __home('career'); g.mgmtTab = { tab: t }; g.ui.push(managementScreen(g)); }, t); // R7: contract & money (the agent, the shoe line at the fame it opens at), the home gym, lifestyle
  await audit('pro-trade-card', () => { const g = HH.game, c = g.save.data.career, nm = clubOf(meOf(c).club).name; __quiet(c); c.inbox = [{ kind: 'trade', title: 'UNHAPPY', why: 'bench', inS: c.season, lines: ['You have watched 4 of the ' + nm + (/s$/.test(nm) ? '’' : '’s') + ' games from the bench.', 'Your agent can ask for a trade: to the best franchise that takes you (at most a star up), your contract comes with you. It’s a distraction: fame −' + Math.round(PR.tradeFame * MD.fameMax * 10) / 10 + '.', 'Or stay and fight for it.'] }]; g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); }); // R7; 3.0 (§4.4): a trade request, a buyout or stay (proTradeCheck's lines)
  await audit('pro-shoe-card', () => { const g = HH.game, c = g.save.data.career; __quiet(c); c.me.shoePitched = false; c.me.shoe = null; c.me.fame = MD.fameMax; proShoePitch(c); g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); }); // R7: a shoe of your own
  await audit('pro-fa-spots', () => { const g = HH.game, c = g.save.data.career; __quiet(c); g.__season = c.season; for (let k = 0; k < 40 && !Object.keys(frSpots5(c).open).length; k++) { c.season++; c.frSpots = null; } c.offseason = { step: 3, fa: { offers: proFreeAgency(c, careerRng(c), 6e6), value: 6e6 }, contractDone: false }; g.ui.clearTo(offseasonScreen(g)); }); await ev(() => { const g = HH.game, c = g.save.data.career; c.season = g.__season; c.frSpots = null; delete g.__season; }); // V6 (§1.3): the open 5★ spots, their rivals, your value (an offseason from before 2.1)
  await audit('pro-negotiate', () => { const g = HH.game, c = g.save.data.career; __quiet(c); c.offseason = { step: 3, fa: { offers: proFreeAgency(c, careerRng(c), 6e6), value: 6e6 }, contractDone: true }; g.ui.clearTo(offseasonScreen(g)); g.ui.push(negotiateScreen(g, 1)); }); // R7: the negotiation
  await audit('pro-negotiate-agent', () => { const g = HH.game, c = g.save.data.career; g.__agent = [c.me.agent, JSON.stringify(c.me.crew || null)]; proHireAgent(c); g.ui.clearTo(offseasonScreen(g)); g.ui.push(negotiateScreen(g, 1)); }); await ev(() => { const g = HH.game, c = g.save.data.career, k = JSON.parse(g.__agent[1]); c.me.agent = g.__agent[0]; if (k) c.me.crew = k; else delete c.me.crew; delete g.__agent; }); /* 3.0 (§7): the agent is on your crew */ // V1 (§1.10): with an agent
  // X8 (3.0 §7): the crew (2.x's staff): nobody hired, the candidates, all six, a phone's role, the agent (the Office's), the season's grades, a rival calling
  await ev(() => { const g = HH.game, c = g.save.data.career; g.__crew = [JSON.stringify(c.me.crew || null), c.me.agent, c.me.money, c.me.credits]; delete c.me.crew; c.me.agent = null; crewSync(c); c.me.money = 6e6; c.me.credits = 12; g.crewTab = null;
    window.__crewFull = c => { c.me.money = Math.max(c.me.money || 0, 5e7); c.me.credits = Math.max(c.me.credits || 0, 40); for (const role of CREW_ROLES) { const L = crewCandidates(c, role); if (L.length) crewHireForce(c, L[L.length - 1]); } crewSync(c); }; });
  await audit('pro-crew-empty', () => { const g = HH.game; __home('career'); g.ui.push(crewScreen(g, 'skills')); });
  if (!desk) await audit('pro-crewrole-empty', () => { const g = HH.game; __home('career'); g.ui.push(crewScreen(g)); g.ui.push(crewRoleScreen(g, 'skills')); }); // (a phone: a role on its own page)
  await audit('pro-crewhire', () => { const g = HH.game; __home('career'); g.ui.push(crewScreen(g)); g.ui.push(crewHireScreen(g, 'skills')); }); // the candidates
  await audit('pro-crew-full', () => { const g = HH.game, c = g.save.data.career; __crewFull(c); __home('career'); g.ui.push(crewScreen(g, 'physio')); });
  if (!desk) await audit('pro-crewrole', () => { const g = HH.game; __home('career'); g.ui.push(crewScreen(g)); g.ui.push(crewRoleScreen(g, 'physio')); });
  await audit('pro-crew-agent', () => { const g = HH.game; __home('career'); g.mgmtTab = { tab: 1 }; g.ui.push(managementScreen(g)); g.ui.push(crewScreen(g, 'agent')); }); // the Office's "Your agent"
  await audit('pro-crewrecap', () => { const g = HH.game, c = g.save.data.career; __quiet(c); crewSeasonEnd(c, 10); const e = c.events.find(x => x.kind === 'crewrecap'); __home('home'); if (e) g.ui.push(crewRecapScreen(g, c, e, () => g.ui.pop())); }); // the season's grades
  await audit('pro-msg-crewpoach', () => { const g = HH.game, c = g.save.data.career, B = c.me, keep = Object.assign({}, CREW.msg), ph = c.phase; __quiet(c); __crewFull(c); try { CREW.msg.poach = 1; c.phase = 'regular'; for (let k = 0; k < 80 && !c.events.some(e => e.kind === 'crewpoach'); k++) { B.crew.poachS = null; crewPoachCheck(c, B, careerRng(c)); } } finally { Object.assign(CREW.msg, keep); c.phase = ph; } const e = c.events.find(x => x.kind === 'crewpoach'); c.events = []; g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); if (e) g.ui.push(eventScreen(g, c, e, () => g.ui.pop())); }); // a rival calls for one of them (2.x's poaching card)
  await ev(() => { const g = HH.game, c = g.save.data.career, [k, ag, m, cr] = g.__crew, K = JSON.parse(k); if (K) c.me.crew = K; else delete c.me.crew; c.me.agent = ag; c.me.money = m; c.me.credits = cr; __quiet(c); delete g.__crew; g.crewTab = null; });
  // V11 (Part 2 §5); 3.0 (§6.1): the store: the shelves, a card's try-on, the locker and one item, the extras, the celebrations (a pro with eight items at levels 1–4)
  await ev(() => { const g = HH.game, c = g.save.data.career; g.__gear = [JSON.stringify(c.me.gear || null), c.me.money]; c.me.money = 2e7; const G = gearOf(c.me); for (const [id, lv] of [['courtShoes', 3], ['gripSocks', 2], ['shooterSleeve', 4], ['sweatband', 1], ['gripBands', 2], ['shootingMachine', 2], ['recoveryBoots', 3], ['kneeBrace', 1]]) { G.owned[id] = lv; gearEquip(c.me, id); } });
  const shopCase = st => { const g = HH.game; g.shopTab = Object.assign({ view: 'store', sel: null, page: 0, sub: null }, st); if (st.sub === 'try') g.shopTab.sel = GEAR_IDS[1]; __home('store'); g.ui.push(shopScreen(g)); };
  await audit('pro-shop-store', shopCase, {});
  await audit('pro-shop-try', shopCase, { sub: 'try' });
  await audit('pro-shop-locker', shopCase, { view: 'locker' });
  await audit('pro-shop-locker-item', shopCase, { view: 'locker', sel: 'shooterSleeve', sub: 'item' });
  await audit('pro-shop-extras', shopCase, { view: 'extras' });
  await audit('pro-shop-celebs', shopCase, { view: 'celebs', sel: 'raiseRoof' }); // V13 (2.0 §6)
  await audit('pro-shop-celebs-item', shopCase, { view: 'celebs', sel: 'iceVeins', sub: 'celeb' });
  await ev(() => { const g = HH.game, c = g.save.data.career, [gr, m] = g.__gear; c.me.gear = JSON.parse(gr); c.me.money = m; delete g.__gear; g.shopTab = null; });
  // V12 (Part 2 §6, 2.0 §4.4/4.5): the franchises, the bracket, a title's season review and scenes, the owners' moves, free agency's cards, a trade side by side (a second career, swapped back after)
  await ev(() => { const g = HH.game; g.__v12 = [g.save.data.career, g.save.data.c1]; const c = testProLeague(36, g.save.data); g.save.data.career = c; g.save.data.c1.handedOff = true; __quiet(c); });
  await audit('v12-franchise', () => { const g = HH.game, c = g.save.data.career; __home('league'); g.ui.push(franchiseScreen(g, meOf(c).club)); });
  await audit('v12-franchise-other', () => { const g = HH.game, c = g.save.data.career; __home('league'); g.ui.push(franchiseScreen(g, frIds().find(k => k !== meOf(c).club))); });
  await audit('v12-trade', () => { const g = HH.game, c = g.save.data.career; __home('career'); g.ui.push(tradeCompareScreen(g, frIds().find(k => k !== meOf(c).club))); });
  const titleCase = kinds => { const g = HH.game, c = g.save.data.career, me = meOf(c); __quiet(c); c.events = kinds.map(k => ({ kind: k, club: me.club, season: 2, year: frYear(2), run: 2, frRun: 2, rings: 2, fans: frFans(c, me.club), oppName: 'Sam Ray', score: '2-1', fmvp: k === 'ring', fmvpName: me.name })); g.ui.clearTo(careerHub(g)); if (kinds.length === 1) eventChain(g, c); g.ui.update(0.1, g.input); const s = g.ui.screen; if (s && s.onTap) s.onTap(0, 0); g.ui.update(0.1, g.input); };
  await audit('v12-champions', titleCase, ['parade', 'ring', 'banner']); // 3.0 (§2.2): a title's Season review (CHAMPIONS)
  await audit('v12-parade', () => { const g = HH.game, s = g.ui.screen, b = ((s && s.widgets) || []).find(w => w.label === 'The parade'); if (b) b.onPress(); g.ui.update(0.1, g.input); const s2 = g.ui.screen; if (s2 && s2.onTap) s2.onTap(0, 0); g.ui.update(0.1, g.input); }); // the parade (the review's button)
  for (const kind of ['ring', 'banner']) await audit('v12-' + kind, titleCase, [kind]); // the ring and the banner (an offseason's queue plays them)
  await audit('v12-rebuild', () => { const g = HH.game, c = g.save.data.career, me = meOf(c), T = c.fr, O = frx(c, me.club).owner, dest = frIds().filter(id => id !== me.club && T[id].stars > frMine(c)).sort((a, b) => (T[b].mode === 'contend') - (T[a].mode === 'contend') || T[b].stars - T[a].stars)[0] || frIds().find(k => k !== me.club); __quiet(c); c.events = [{ kind: 'rebuild', icon: 'swap', title: 'THE REBUILD', dest, lines: [O.name + ', who owns the ' + clubOf(me.club).name + ', calls: "We are starting over. Kids, cap space, a few lean years."', '"You deserve better than a rebuild. The ' + clubOf(dest).name + ' (' + T[dest].stars + '★, ' + (T[dest].mode === 'contend' ? 'going for a title' : 'on the rise') + ') want you. Your contract goes with you."', 'Go to a winner, or stay and lead the young players through it.'] }]; g.ui.clearTo(careerHub(g)); g.ui.update(0.1, g.input); }); // a rebuilding owner's offer (frRebuildOffer's lines; 3.0: an urgent message)
  await ev(() => { const g = HH.game, c = g.save.data.career; __quiet(c); for (const id of c.active) c.standings[id] = { w: 3, l: 3, pf: 0, pa: 0, strk: 0 }; c.standings[c.meId].w = 9; c.week = c.schedule.length; startPlayoffs(c); __quiet(c); });
  await audit('v12-bracket', () => { const g = HH.game; __home('events'); g.ui.push(bracketScreen(g)); }); // EVENTS: the playoff bracket
  await audit('v12-brackets', () => { const g = HH.game; __home('league'); g.ui.push(bracketsScreen(g)); }); // 3.0 (§4.2): LEAGUE's brackets
  await audit('w5-franchise-history', () => { const g = HH.game, c = g.save.data.career; g.frTab = { tab: 1 }; __home('league'); g.ui.push(franchiseScreen(g, meOf(c).club)); g.frTab = { tab: 0 }; }); // 2.1 (§3.1): titles, jerseys, legends
  await audit('w5-franchise-new', () => { const g = HH.game; g.frTab = { tab: 0 }; __home('league'); g.ui.push(franchiseScreen(g, 'foxes')); }); // a new franchise (a meddler owner)
  for (const t of ['home', 'league', 'events']) await audit('v12-hub-' + t + '-playoffs', t => __home(t), t); // HOME, LEAGUE and EVENTS in the playoffs
  await ev(() => { const g = HH.game, c = testProLeague(37, g.save.data); g.save.data.career = c; g.save.data.c1.handedOff = true; __quiet(c); c.me.contract.years = 1; for (const id of c.active) c.stats[id].g = 10; endSeason(c); c.offseason.step = 1; offseasonProgression(c); c.offseason.step = 2; offseasonMoves(c); __quiet(c); });
  await audit('v12-owners-moves', () => { const g = HH.game; g.ui.clearTo(offseasonScreen(g)); });
  await audit('v12-free-agency', () => { const g = HH.game; g.save.data.career.offseason.step = 3; g.ui.clearTo(offseasonScreen(g)); });
  await audit('v12-free-agency-wait', () => { const g = HH.game, c = g.save.data.career; off2Day(c); off2Day(c); g.ui.clearTo(offseasonScreen(g)); }); // two days in: the offers that came
  await audit('v12-negotiate', () => { const s = HH.game.ui.screen, b = ((s && s.widgets) || []).find(w => w.label === 'Counter'); if (b) b.onPress(); }); // 2.1 (§3.3): a counter-offer (the offseason's negotiation)
  await ev(() => { const g = HH.game; [g.save.data.career, g.save.data.c1] = g.__v12; delete g.__v12; __home('home'); });
  await audit('pro-result', () => { const g = HH.game, c = g.save.data.career; const rec = simUserGame(g.save.data); __quiet(c); g.ui.clearTo(careerResultScreen(g, rec, null)); });
  await audit('allstar', () => { const g = HH.game, c = g.save.data.career; for (const k of RATING_KEYS) meOf(c).r[k] = 99; let n = 0; while (!c.allStar && n++ < 30) { c.events.length = 0; simUserGame(g.save.data); } const keep = c.events.filter(e => e.kind === 'allstar'); __quiet(c); c.events = keep; g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); }); // All-Star weekend (3.0: a moment, its own screen)
  await audit('allstar-1v1-result', () => { const g = HH.game, c = g.save.data.career; if (c.allStar) g.ui.push(allStar1v1ResultScreen(g, { winner: 0, teams: [{ score: 21 }, { score: 17 }] }, { applied: true, opp: Object.keys(c.players).find(id => String(id) !== String(c.meId)) })); }); // R10: the All-Star 1v1's result
  await audit('allstar-result', () => { const g = HH.game, c = g.save.data.career; if (c.allStar) { if (!c.allStar.done) finishAllStar(c, 14); __home('home'); g.ui.push(allStarResultScreen(g)); } }); // R10: the contest's results
  await audit('offseason', () => { const g = HH.game, c = g.save.data.career; let n = 0; while (c.phase !== 'offseason' && n++ < 200) { c.events = []; if (!simUserGame(g.save.data) && c.phase === 'playoffs') simPlayoffsToEnd(c); } __quiet(c); g.ui.clearTo(offseasonScreen(g)); });
  await audit('offseason-bench', () => { const g = HH.game, c = g.save.data.career, r = c.me.seasonLog[0]; g.__row = Object.assign({}, r); Object.assign(r, { g: 0, ppg: 0, rpg: 0, fg: 0, tp: 0, chW: 2, chL: 1, ovr0: r.ovr - 2 }); g.ui.clearTo(offseasonScreen(g)); }); await ev(() => { const g = HH.game; Object.assign(g.save.data.career.me.seasonLog[0], g.__row); delete g.__row; }); // V1 (§1.12): a season on the bench
  await audit('offseason-contract', () => { const g = HH.game, c = g.save.data.career; c.me.contract.years = 1; c.offseason.step = 3; c.offseason.fa = null; c.offseason.contractDone = false; g.ui.clearTo(offseasonScreen(g)); });
  await audit('offseason-next', () => { const g = HH.game, c = g.save.data.career; g.__step = c.offseason.step; c.offseason.step = 4; c.me.degree = { major: 'business', years: 2, academic: false }; c.me.money = Math.max(c.me.money, 1e6); g.ui.clearTo(offseasonScreen(g)); }); // V9: summer classes
  await audit('offseason-classes', () => { const s = HH.game.ui.screen, b = s.widgets.find(w => /^Summer classes/.test(w.label || '')); if (b) b.onPress(); }); await ev(() => { const g = HH.game, c = g.save.data.career; c.offseason.step = g.__step; });
  // 3.0 (§2.2): the pros' Season review, awards night from its button (2.x's awards night card)
  await audit('pro-review-awards', () => { const g = HH.game, c = g.save.data.career; __quiet(c); const ids = c.active; const aw = { mvp: c.meId, dpoy: ids[1], roy: ids[2], mip: ids[3], scoring: c.meId, finalsMvp: ids[4], allLeague: [c.meId, ids[5], ids[6]] }; c.events = [{ kind: 'ceremony', title: 'AWARDS NIGHT', sub: 'The PBL · season ' + c.season, rows: proCeremonyRows(c, aw) }]; g.hubTab = 'home'; g.ui.clearTo(careerHub(g)); });
  await audit('pro-awards-night', () => { const s = HH.game.ui.screen, b = (s.widgets || []).find(w => w.label === 'Awards night'); if (b) b.onPress(); }); // V8: the league's awards, yours marked
  await audit('pro-awards-night-all', () => { const s = HH.game.ui.screen; if (s && s.onTap) s.onTap(); });
  await audit('pro-records', () => { const g = HH.game, c = g.save.data.career; __quiet(c); recordsAfterGame(c, { pts: 24, reb: 9, stl: 3, blk: 1, tpm: 3 }, true); __home('career'); g.ui.push(recordsBookScreen(g, c)); });
  await audit('pro-news-fame', () => { const g = HH.game, c = g.save.data.career; c.me.fame = 66; __home('career'); g.ui.push(headlinesScreen(g)); }); // R8 (3.0: FAME)
  if (!desk) await audit('pro-news-fame-tab', () => { const s = HH.game.ui.screen, b = (s.widgets || []).find(w => w.label === 'FAME'); if (b) b.onPress(); }); // F7
  await audit('pro-bench', () => { const g = HH.game, c = g.save.data.career; __quiet(c); if (c.phase === 'offseason') { offseasonProgression(c); offseasonMoves(c); const o = offseasonContract(c); if (o) acceptContract(c, 0); newSeason(c); } ladderInit(c, 2); const rec = simUserGame(g.save.data); __quiet(c); g.ui.clearTo(careerResultScreen(g, rec, null)); }); // R4; 3.0 (§4.3): the Development League's game
  await audit('pro-tn', () => { const c = HH.game.save.data.career; __tn('wc', { field: c.active.filter(id => id !== c.meId).slice(0, 3).concat([c.meId]) }, 1); }); // 3.0 (§5): the World Cup, a group game played
  await audit('hof-full', () => { const g = HH.game, H = g.save.data.hallOfFame; for (let i = 0; i < 7; i++) H.push({ name: 'Legend ' + i, look: PRESET_LOOKS[i % PRESET_LOOKS.length], h: 1.9, arch: 'slasher', score: 50 + i * 8, hof: i > 3, seasons: 10 + i, titles: i, ppg: 20 + i, mvps: i % 3, when: i + 1 }); g.ui.clearTo(mainMenu(g)); g.ui.push(hallOfFameScreen(g)); });
  await audit('epilogue', () => { const g = HH.game, sv = g.save.data; __quiet(sv.career); sv.career.me.money = 8e7; retireCareer(sv); g.save.save(); g.ui.clearTo(epilogueScreen(g)); }); // R7: what your money builds
  await audit('epilogue-degree', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.me.degree = { major: 'kinesiology', years: 4, academic: false, school: 'Test State' }; g.ui.clearTo(epilogueScreen(g)); }); // V9: the head coach (the degree's version)
  await audit('hof-induction', () => { const g = HH.game, c = g.save.data.career; c.events.length = 0; c.legacy = Object.assign({}, c.legacy || legacyOf(c), { hof: true, titles: Math.max(1, (c.legacy || {}).titles || 0), mvps: 1 }); g.ui.clearTo(hofInductionScreen(g)); }); // V8 (2.0 §4.9): the induction
  await audit('legacy', () => { const g = HH.game, sv = g.save.data; proEpilogue(sv, { academy: true, foundation: 10 }); g.save.save(); g.ui.clearTo(legacyScreen(g)); }); // (R7: after the epilogue)
  await audit('money-built', () => { const g = HH.game; g.ui.push(moneyBuiltScreen(g)); }); // R7
  await audit('networth', () => { const g = HH.game, H = g.save.data.hallOfFame; H.forEach((e, i) => { if (e.netWorth == null) e.netWorth = 5e7 * (i + 1); }); g.ui.clearTo(mainMenu(g)); g.ui.push(netWorthScreen(g)); }); // R7: the leaderboard
  await audit('pause', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); const a = soloTeam(extrasPool(g)[0], false), b = soloTeam(extrasPool(g)[1], true); g.startMatch({ mode: '1v1', teams: [a, b], humanTeam: 0, humanPlayerIndex: 0, difficulty: 'pro', ruleset: 'arcade', format: { type: 'first', target: 11 }, court: 'blacktop', seed: 3, controlMode: 'lock' }, { kind: 'quick' }); g.pause(); });
  await audit('pause-practice', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); const a = soloTeam(extrasPool(g)[0], false), b2 = soloTeam(extrasPool(g)[1], true); g.startMatch({ mode: '1v1', teams: [a, b2], humanTeam: 0, humanPlayerIndex: 0, difficulty: 'rookie', ruleset: 'arcade', format: { type: 'first', target: 999 }, court: 'legends', seed: 11, controlMode: 'lock', practice: { noDefender: true, infiniteStamina: true, breakdown: true, chart: true } }, { kind: 'practice' }); const pr = g.match.practice; for (let i = 0; i < 12; i++) { const k = ['lay', 'mid', 'three', 'deep'][i % 4]; pr.shots++; pr.byZone[k][1]++; if (i % 3) { pr.makes++; pr.byZone[k][0]++; } pr.marks.push({ x: 0, d: [1.5, 5, 7.5, 9][i % 4], zone: k, make: !!(i % 3), type: k === 'lay' ? 'layup' : 'jumper', grade: k === 'lay' ? -1 : i % 2, id: 100 + i * 17 }); } g.pause(); }); // V4: practice's shot chart on the pause menu
  await audit('postgame-quick', () => { const g = HH.game; g.ui.clearTo(mainMenu(g)); const a = soloTeam(extrasPool(g)[0], false), b = soloTeam(extrasPool(g)[1], true); g.startMatch({ mode: '1v1', teams: [a, b], humanTeam: 0, humanPlayerIndex: 0, difficulty: 'pro', ruleset: 'arcade', format: { type: 'first', target: 3 }, court: 'blacktop', seed: 5, controlMode: 'lock' }, { kind: 'quick' }); for (const p of g.match.players) p.controlled = false; for (let i = 0; i < 120 * 240 && !g.match.ended; i++) simStep(g.match, STEP); });
  await wait(4000); await audit('postgame-quick-later', () => {});
  console.log('legibility: the smallest glyph is ' + (legib.length ? Math.min(...legib).toFixed(2) : '?') + '× the menus\' pixel over ' + legib.length + ' screens (1.00 or more: every string at least 10 internal pixels tall)');
  console.log('smallest text (CSS px): ' + texts.slice().sort((a, b) => a.min - b.min).slice(0, 25).map(o => o.name + ' ' + o.min.toFixed(1) + ' "' + (o.tx[0] ? o.tx[0].t : '') + '"').join(' | '));
  console.log('phoneaudit (' + (sz ? sizeArg : desk ? '1280×720' : '844×390 touch') + (big ? ', 1.25× text' : '') + '): ' + screens + ' screens audited, ' + flagged + ' flagged');
  console.log('errors: ' + (P.errors.length ? P.errors.join(' | ') : 'none')); await browser.close();
})();
