// 3.0 (§4.1, §11): rankings come from how people play. Simulated seasons at each level (high school's nation, college's
// 64 programs, the PBL), read at the regular season's end: the season's top scorer (PPG) is in the top 10 in 95% of
// seasons; teams follow their record (the best record in the top 5); ranks aren't OVR's order; ▲▼ is last week's
// rank; the PBL's stars follow its team ranking; JV players aren't ranked nationally; a save from before 3.0's
// rankings gets its season so far. Usage: node tests/rankings.js [careers per level, default 40]
const { launch, openPage, runner } = require('./lib');
(async () => {
  const N = +process.argv[2] || 40; const browser = await launch(); const P = await openPage(browser); const R = runner('rankings'); const { ev } = P;
  await ev(() => {
    window.__adv = (a, n, until) => { let k = 0, g = 0; while (k++ < 2000 && g < n) { if (until && until(a)) break; a.events = []; a.inbox = []; if (a.summer && a.summer.pending) hsSummerChoose(a, 'rest'); else if (a.tryout && a.tryout.step !== 'done') hsSimTryout(a); else if (a.decision) { const d = a.decision; if (d.kind === 'portal') colPortalChoose(a, null); else if (d.kind === 'college' && d.signing) recSimSign(a); else if (d.kind === 'college') amChooseCollege(a, d.offers[0]); else amDeclare(a, false); } else { amSimGame(a); g++; } } };
    // A level's season at its regular season's end: { ppgTop (its rank), bestRec (the best record's team rank), rho (rank vs OVR, rank vs PPG) }
    window.__read = c => { const pl = rkPlayers(c).concat(rkUnranked(c)), R = c.rk, minG = Math.max(3, Math.floor(R.wk * 0.6)), el = pl.filter(p => p.g >= minG); if (el.length < 10) return null; const top = el.slice().sort((a, b) => b.ppg - a.ppg)[0], tm = rkTeams(c).filter(t => t.g >= minG);
      const best = tm.length ? tm.slice().sort((a, b) => (b.w / Math.max(1, b.g)) - (a.w / Math.max(1, a.g)) || b.diff - a.diff)[0] : null;
      const ovrOfRow = p => { if (R.lv === 'pro') return recOvr(c.players[p.id]); const q = R.P[p.id]; return q.k === 'n' ? q.o : q.k === 'me' ? amOvr(c) : (amOppById(c, p.id) ? ovrOf(amOppById(c, p.id).r, amOppById(c, p.id).height) : null); };
      const ranked = el.filter(p => p.r <= 100), spear = (xs, ys) => { const rk = a => { const s = a.map((v, i) => [v, i]).sort((p, q) => p[0] - q[0]), r = new Array(a.length); s.forEach((p, i) => { r[p[1]] = i; }); return r; }, rx = rk(xs), ry = rk(ys), n = xs.length, mx = (n - 1) / 2; let num = 0, dx = 0, dy = 0; for (let i = 0; i < n; i++) { num += (rx[i] - mx) * (ry[i] - mx); dx += (rx[i] - mx) ** 2; dy += (ry[i] - mx) ** 2; } return num / Math.sqrt(dx * dy || 1); };
      const ov = ranked.map(ovrOfRow), ok = ov.every(v => v != null);
      const tr = tm.filter(t => t.r <= 100), one = tr.find(t => t.r === 1), bestL = tm.length ? Math.min(...tm.map(t => t.l)) : null;
      return { lv: R.lv, ppgTop: top.r > 100 ? 999 : top.r, ppg: +top.ppg.toFixed(1), bestRec: best ? best.r : null, rhoWin: tr.length > 4 ? -spear(tr.map(t => t.r), tr.map(t => t.w / Math.max(1, t.g))) : null, oneOff: one && bestL != null ? one.l <= bestL + 1 : null, rhoOvr: ok ? -spear(ranked.map(p => p.r), ov) : null, rhoPpg: -spear(ranked.map(p => p.r), ranked.map(p => p.ppg)), n: el.length }; };
  });
  const seasons = { hs: [], college: [], pro: [] };
  await R.step('simulated seasons: ' + N + ' high school careers to the draft, ' + N + ' PBL seasons', async () => {
    for (let i = 0; i < N; i++) { const out = await ev(i => { const res = []; const sv = defaultSave(); const a = amCreate(sv, { name: 'Rank Test', look: PRESET_LOOKS[i % PRESET_LOOKS.length], number: 5, style: ['slasher', 'sharpshooter', 'postscorer', 'playmaker'][i % 4], seed: 1000 + i }); sv.c1 = a;
        let last = -1, guard = 0; while (guard++ < 3000 && a.stage !== 'combine' && !a.draft) { const L = a.league; if (L && (L.playoffs || L.done) && L.format !== 'jv' && a.rk && a.rk.season === a.season && a.season !== last) { last = a.season; const r = __read(a); if (r) res.push(r); } __adv(a, 1); }
        return res; }, i); for (const r of out) seasons[r.lv].push(r); }
    for (let i = 0; i < N; i++) { const r = await ev(i => { const sv = defaultSave(); const c = testProLeague(200 + i, sv); sv.career = c; sv.c1.handedOff = true; let k = 0; while (c.phase === 'regular' && k++ < 40) simUserGame(sv); return __read(c); }, i); if (r) seasons.pro.push(r); }
    return 'seasons read: high school ' + seasons.hs.length + ', college ' + seasons.college.length + ', PBL ' + seasons.pro.length;
  }, P);
  const share = (a, f) => a.length ? a.filter(f).length / a.length : 0, pct = v => Math.round(100 * v) + '%', mean = (a, f) => a.length ? a.reduce((s, x) => s + f(x), 0) / a.length : 0;
  for (const lv of ['hs', 'college', 'pro']) {
    const S = seasons[lv], name = { hs: 'high school (the nation)', college: 'college (64 programs)', pro: 'the PBL' }[lv];
    await R.step('the top scorer is in the top 10, ' + name + ' (95% of seasons)', async () => { const s = share(S, x => x.ppgTop <= 10); const line = pct(s) + ' of ' + S.length + ' seasons · their rank: ' + S.map(x => x.ppgTop).sort((a, b) => a - b).slice(-6).join(', ') + ' (the worst six)'; if (S.length < 10 || s < 0.95) throw new Error(line); return line; });
    await R.step('teams follow their record, ' + name + ' (rank vs win share ρ ≥ 0.75; the #1 within a loss of the best record)', async () => { const ro = mean(S.filter(x => x.rhoWin != null), x => x.rhoWin), s = share(S.filter(x => x.oneOff != null), x => x.oneOff); const line = 'ρ ' + ro.toFixed(2) + ' · the #1 within a loss of the best: ' + pct(s); if (ro < 0.75 || s < 0.9) throw new Error(line); return line; });
    await R.step('players follow how they play, not OVR, ' + name, async () => { const ro = mean(S.filter(x => x.rhoOvr != null), x => x.rhoOvr), rp = mean(S, x => x.rhoPpg); const line = 'rank vs PPG ρ ' + rp.toFixed(2) + ' · rank vs OVR ρ ' + ro.toFixed(2); if (!(rp > ro) || rp < 0.6) throw new Error(line); return line; });
  }
  await R.step('▲▼: a week later each rank remembers the last; JV players are not ranked nationally', () => ev(() => { const sv = defaultSave(); const a = amCreate(sv, { name: 'Move Test', look: PRESET_LOOKS[1], number: 5, style: 'slasher', seed: 4242 }); sv.c1 = a; __adv(a, 3); const before = {}; for (const id in a.rk.P) before[id] = a.rk.P[id].r; __adv(a, 1); const bad = Object.keys(before).filter(id => a.rk.P[id] && a.rk.P[id].pv !== before[id]); if (bad.length) throw new Error('pv ≠ last week: ' + bad.slice(0, 4).join(', '));
    const jv = Object.keys(a.rk.P).filter(id => a.rk.P[id].jv && a.rk.P[id].r > 0); if (jv.length) throw new Error('JV players ranked: ' + jv.join(', ')); const mv = rkMoveText(5, 9) + ' ' + rkMoveText(9, 5) + ' ' + rkMoveText(5, 5) + ' ' + rkMoveText(5, 0); if (mv !== '▲4 ▼4 – NEW') throw new Error('move text ' + mv); return 'ok · ' + mv; }), P);
  await R.step('the PBL\'s stars follow its team ranking at the season\'s end', () => ev(() => { const sv = defaultSave(); const c = testProLeague(77, sv); sv.career = c; sv.c1.handedOff = true; let k = 0; while (c.phase === 'regular' && k++ < 40) simUserGame(sv); const ord = rkProTeamOrder(c).map(id => c.players[id].club), tr = rkTeams(c).map(t => t.id); if (ord.slice(0, tr.length).join() !== tr.join()) throw new Error('order ' + ord.join() + ' vs ' + tr.join()); return 'ok · #1 ' + clubOf(tr[0]).name; }), P);
  await R.step('a save from before 3.0\'s rankings gets its season so far (your line, your league, the nation\'s weeks)', () => ev(() => { const sv = defaultSave(); const a = amCreate(sv, { name: 'Old Save', look: PRESET_LOOKS[3], number: 5, style: 'slasher', seed: 5151 }); sv.c1 = a; __adv(a, 400, a => a.league && a.league.format === 'district' && a.league.week >= 4); delete a.rk; const R0 = rkFill(a), me = R0.P.me, L = a.league;
    if (R0.wk !== L.week) throw new Error('weeks ' + R0.wk + ' vs ' + L.week); if (me.g !== a.seasonStats.g || me.pts !== a.seasonStats.pts) throw new Error('your line ' + me.g + '/' + me.pts + ' vs ' + a.seasonStats.g + '/' + a.seasonStats.pts); const nat = Object.values(R0.P).filter(p => p.k === 'n'); if (!nat.every(p => p.g === L.week)) throw new Error('the nation\'s games'); const d = L.opps.map(o => R0.P[o.id]); if (!d.every(p => p && p.g === o_g(p))) throw new Error('the league'); function o_g(p) { const o = L.opps.find(x => R0.P[x.id] === p); return o.rec.w + o.rec.l; }
    __adv(a, 1); return 'ok · week ' + a.rk.wk + ', you ' + rkText(rkMeRow(a).r); }), P);
  console.log('errors: ' + (P.errors.length ? P.errors.slice(0, 5).join(' | ') : 'none')); const fail = R.done(); await browser.close(); process.exit(fail ? 1 : 0);
})();
