// Smoke test: the whole game through the real UI at desktop size (1280×720), plus the phone layout with touch (844×390),
// old-save migrations and the regression checks. Zero page errors, console errors or recovered frame exceptions allowed.
// Usage: node tests/smoke.js [--shots <dir>]
const fs = require('fs'), path = require('path');
const { ROOT, launch, openPage, runner } = require('./lib');
const FIX = path.join(__dirname, 'fixtures');
(async () => {
  const shotsDir = process.argv.includes('--shots') ? process.argv[process.argv.indexOf('--shots') + 1] : null; if (shotsDir) fs.mkdirSync(shotsDir, { recursive: true });
  const browser = await launch(); const R = runner('smoke');
  const D = await openPage(browser); const { page, ev } = D; const step = (n, f) => R.step(n, f, D);
  const shot = async n => { if (shotsDir) { await page.waitForTimeout(250); await D.shot(path.join(shotsDir, n + '.jpg')); } };
  const wait = ms => page.waitForTimeout(ms);
  // bots play both sides until the match ends (a full game, fast-forwarded through the real simulation)
  const finishMatch = () => ev(() => { const m = HH.game.match; if (!m) throw new Error('no match'); for (const p of m.players) if (p.controlled) { p.controlled = false; p.input.reset(); } let n = 0; while (!m.ended && n < 120 * 60 * 30) { simStep(m, STEP); n++; } if (!m.ended) throw new Error('match did not end'); return n; });
  const clearEvents = () => ev(() => { const a = HH.game.save.data.c1; if (a) a.events.length = 0; });
  const drainEvents = async () => { for (let i = 0; i < 8; i++) { const s = await D.screen(); if (s !== 'amevent') return; await D.press(/^(Continue|CONTINUE)$/); } };

  await step('fresh save, title screen', async () => { await ev(() => { localStorage.clear(); HH.game.save = new SaveSystem(); HH.game.ui.clearTo(titleScreen(HH.game)); }); await wait(300); await D.expectScreen('title'); await shot('01-title'); });
  await step('title → main menu (Enter)', async () => { await page.keyboard.press('Enter'); await wait(300); await D.expectScreen('menu'); await shot('02-menu'); });
  await step('create your player', async () => { await D.press(/START YOUR CAREER/); await D.expectScreen('create'); await shot('03-create'); });
  await step('no height slider on create', () => ev(() => { const bad = HH.game.ui.screen.widgets.find(w => /height/i.test(w.label || '') && w.kind === 'slider'); if (bad) throw new Error('height slider: ' + bad.label); }));
  await step('start high school → genes reveal', async () => { await D.press(/START HIGH SCHOOL/); await wait(1500); await D.expectScreen('amevent'); await shot('04-genes'); });
  await step('genes → hub', async () => { await drainEvents(); await D.expectScreen('amhub'); await shot('05-hub'); });
  await step('play the first game (full match)', async () => { await D.press(/^PLAY( GAME)?$/); await wait(1500); await ev(() => { if (!HH.game.match || HH.game.match.perSide !== 1) throw new Error('no 1v1 match'); }); await shot('06-match'); const n = await finishMatch(); if (n < 120 * 20) throw new Error('suspiciously short match: ' + n + ' steps'); await wait(2500); });
  await step('postgame → result', async () => { const s = await D.screen(); if (s !== 'amresult' && s !== 'postgame') throw new Error('screen ' + s); await shot('07-result'); });
  await step('result → hub', async () => { await D.press(/CONTINUE/); await wait(400); await drainEvents(); await D.expectScreen('amhub'); });
  await step('the week advanced', () => ev(() => { const a = HH.game.save.data.c1; if (!a.league || a.league.games.length < 1) throw new Error('no game recorded'); }));
  await step('standings', async () => { await D.press(/Standings/); await shot('08-standings'); await ev(() => HH.game.ui.pop()); });
  await step('stats & history', async () => { await D.press(/^Stats/); await shot('09-history'); await ev(() => HH.game.ui.pop()); });
  await step('sim to the season recap', async () => { for (let i = 0; i < 30; i++) { const s = await D.screen(); if (s === 'amevent') break; if (s === 'amresult') { await D.press(/CONTINUE/); continue; } await D.press(/^SIM$/); } await wait(1200); await D.expectScreen('amevent'); await shot('10-recap'); await drainEvents(); });
  await step('grew between seasons (model height changes)', () => ev(() => { const a = HH.game.save.data.c1; const log = a.log || []; if (!log.length) throw new Error('no season log'); }));
  await step('sim to college offers', async () => { await ev(() => { const g = HH.game, a = g.save.data.c1; let guard = 0; while (!a.decision && a.stage === 'hs' && guard++ < 200) { a.events.length = 0; if (!amSimGame(a)) break; } a.events.length = 0; g.ui.clearTo(amHub(g)); if (!a.decision) throw new Error('no decision'); }); await D.press(/CHOOSE YOUR COLLEGE/); await D.expectScreen('amdecision'); await shot('11-offers'); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); await wait(400); await drainEvents(); await D.expectScreen('amhub'); });
  await step('sim to the draft combine', async () => { await ev(() => { const g = HH.game, a = g.save.data.c1; let guard = 0; while (a.stage !== 'combine' && guard++ < 300) { a.events.length = 0; if (a.decision) { if (a.decision.kind === 'declare') amDeclare(a, true); else amChooseCollege(a, a.decision.offers[0]); continue; } if (!amSimGame(a)) break; } a.events.length = 0; g.ui.clearTo(amHub(g)); if (a.stage !== 'combine') throw new Error('stage ' + a.stage); }); });
  await step('combine measures you', async () => { await D.press(/DRAFT COMBINE/); await wait(6500); await D.expectScreen('combine'); await shot('12-combine'); });
  await step('draft night', async () => { await D.press(/DRAFT NIGHT/); await wait(7000); await D.expectScreen('draft'); await shot('13-draft'); });
  await step('pro hub', async () => { await D.press(/START YOUR PRO CAREER/); await wait(400); await D.expectScreen('career'); await shot('14-pro-hub'); });
  await step('pregame → tip off → full pro match', async () => { await D.press(/^PLAY( GAME)?$/); await D.expectScreen('pregame'); await shot('15-pregame'); await D.press(/TIP OFF/); await wait(1500); await shot('16-pro-match'); await finishMatch(); await wait(2500); const s = await D.screen(); if (s !== 'result' && s !== 'postgame') throw new Error('screen ' + s); await shot('17-pro-result'); });
  await step('back to the pro hub', async () => { for (let i = 0; i < 3; i++) { const s = await D.screen(); if (s === 'career') break; await D.press(/CONTINUE/); } await D.expectScreen('career'); });
  await step('pause menu in a match', async () => { await D.press(/^PLAY( GAME)?$/); await D.press(/TIP OFF/); await wait(1200); await page.keyboard.press('Escape'); await wait(300); await D.expectScreen('pause'); await shot('18-pause'); await D.press(/Sim the rest/); await wait(1500); for (let i = 0; i < 3; i++) { const s = await D.screen(); if (s === 'career') break; try { await D.press(/CONTINUE/); } catch (e) { break; } } });
  // other modes
  const toMenu = () => ev(() => { const g = HH.game; if (g.mode === 'match') g.quitToMenu(); g.ui.clearTo(mainMenu(g)); });
  const runMode = async (label, open, secs) => step(label, async () => { await toMenu(); await wait(200); await open(); await wait(1500); await ev(() => { if (!HH.game.match) throw new Error('no match started'); }); await wait((secs || 1.5) * 1000); await ev(() => { const g = HH.game; if (g.match && !g.match.ended) { for (const p of g.match.players) p.controlled = false; for (let i = 0; i < 120 * 3; i++) simStep(g.match, STEP); } }); await wait(300); await toMenu(); });
  await runMode('quick 1v1 starts and runs', async () => { await D.press(/Quick 1v1/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); });
  await runMode('extras → street tournament', async () => { await D.press(/Extras/); await D.press(/Street tournament/); await D.press(/START TOURNAMENT/); await ev(() => { const w = HH.game.ui.screen.widgets.find(w => w.primary); if (w) w.onPress(); }); });
  await runMode('extras → 3-point contest', async () => { await D.press(/Extras/); await D.press(/3-Point Contest/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); });
  await runMode('extras → practice', async () => { await D.press(/Extras/); await D.press(/^Practice$/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); });
  await runMode('extras → tutorial', async () => { await D.press(/Extras/); await D.press(/Tutorial/); });
  await step('extras → team league (classic) is reachable', async () => { await toMenu(); await D.press(/Extras/); await D.press(/Team league/); const s = await D.screen(); if (!/create|teamhub|chooseTeam/.test(s)) throw new Error('screen ' + s); await shot('19-team-league'); await toMenu(); });
  await step('extras → art lab (every view)', async () => { await toMenu(); await D.press(/Extras/); await D.press(/Art Lab/); await D.expectScreen('artlab'); const n = await ev(() => LAB_VIEWS.length); for (let v = 0; v < n; v++) { await ev(v => HH.game.ui.screen.setView(v), v); await wait(250); } await shot('20-artlab'); await toMenu(); });
  await step('settings and how to play', async () => { await toMenu(); await D.press(/Settings/); await D.expectScreen('settings'); await ev(() => HH.game.ui.pop()); await D.press(/How to play/); await D.expectScreen('howto'); await ev(() => HH.game.ui.pop()); });
  // regressions that were fixed before and must stay fixed
  await step('regression: odd look values never crash drawing', () => ev(() => { const odd = [{}, { skin: NaN, hair: -3, hairColor: 99 }, { skin: 1e9, hair: 'x', beard: 42, eyes: -1, face: null }, { skin: 2.5, facialHair: 17, iris: 'q', acc: null }]; const cv = document.createElement('canvas'); cv.width = cv.height = 300; const g = cv.getContext('2d'); for (const look of odd) { drawHead(g, 150, 150, 60, look, 'hyped', 1, ['#123456', '#FFFFFF'], 2); portraitOf({ name: 'Odd', look }, ['#123456', '#FFFFFF'], 96); drawMannequin(g, { name: 'Odd', look, height: 1.9, attrs: {} }, { colors: ['#123456', '#FFFFFF'], pattern: 'solid' }, 150, 280, 200, 'focused', 1, 0); } }));
  await step('regression: dunks respect the contest', () => ev(() => { const m = new Match({ mode: '1v1', teams: [teamWithRoster(TEAMS[0]), teamWithRoster(TEAMS[1])], seed: 3, headless: true, humanTeam: -1 }); const p = m.players[0]; const open = makeProbability(p, 'dunk', 'mid', 0, 0).P, smothered = makeProbability(p, 'dunk', 'mid', 0, 0.9).P; if (!(smothered < open - 0.1)) throw new Error('dunk P open ' + open + ' vs contested ' + smothered); }));
  await step('regression: the camera keeps your player in view', async () => { await toMenu(); await D.press(/Quick 1v1/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); await wait(1200); await ev(() => { const g = HH.game, m = g.match, me = m.controlledPlayer; me.controlled = false; let worst = 0; for (let i = 0; i < 120 * 60; i++) { simStep(m, STEP); if (i % 4 === 3) { g.cam.update(m, 4 * STEP); const x = g.cam.sx(me.x); worst = Math.max(worst, x < 0 ? -x : x > g.W ? x - g.W : 0); } if (m.ended) break; } me.controlled = true; if (worst > 40) throw new Error('player left the frame by ' + worst.toFixed(0) + ' px'); }); await toMenu(); });
  // the animation rig (M4): every clip, every game state, replays and faces
  await step('rig: every clip gives a valid pose over its whole length', () => ev(() => { const cv = document.createElement('canvas'); cv.width = cv.height = 200; const g = cv.getContext('2d'); const cam = { scale: () => 40, sx: x => 100 + x * 40, sy: y => 190 - y * 40, ppm: 40, W: 0, H: 0 }; let n = 0;
    for (const [clip, dur] of LAB_CLIPS) for (const ci of [0, 5, 11]) for (let k = 0; k <= 12; k++) { const t = dur * 1.4 * k / 12; const { p, ball } = labClipStandIn(LAB_CAST[ci], ci, clip, t); const P = rigPoseFor(p, 1, ball); if (!rigPoseOk(P)) throw new Error(clip + ' bad pose at t=' + t.toFixed(2)); if (P.clip !== p.rigForce) throw new Error(clip + ' fell back to ' + P.clip); drawPlayer(g, cam, p, 1, ball, { colors: LAB_CAST[ci].colors, pattern: 'solid' }, { replay: true }); n++; }
    if (n < LAB_CLIPS.length * 39) throw new Error('only ' + n + ' poses'); }));
  await step('rig: every game state maps to a clip', () => ev(() => { const def = labDef(LAB_CAST[3], 3); for (const st of STATE_LIST) for (const grounded of [true, false]) for (const hasBall of [true, false]) { const p = { name: 'x', def, look: def.look, height: 1.9, facing: -1, state: st, stateT: 0.2, sd: {}, grounded, vx: 3, vy: 1, x: 5, y: grounded ? 0 : 0.8, z: 0.5, px: 5, py: grounded ? 0 : 0.8, pz: 0.5, reach: 2.5, anim: {}, stamina: 50, hand: { x: 0, y: 0 } }; const ball = hasBall ? { owner: p, x: 5.2, y: 1, px: 5.2, py: 1, z: 0.5, pz: 0.5 } : null; const P = rigPoseFor(p, 1, ball); if (!rigPoseOk(P) || !RIG_CLIPS[P.clip]) throw new Error(st + ' → ' + P.clip); } }));
  await step('rig: replay ghosts animate from the recorded clip', () => ev(() => { const m = new Match({ mode: '1v1', teams: [teamWithRoster(TEAMS[0]), teamWithRoster(TEAMS[1])], seed: 21, headless: true, humanTeam: -1 }); const rec = new ReplayRecorder(m); for (let i = 0; i < 120 * 12; i++) { simStep(m, STEP); if (i % 4 === 0) rec.record(); }
    const clip = rec.snapshotClip(1, 'test', m.players[0]); const seen = new Set(); for (let f = 0; f < clip.count - 1; f += 0.5) { rec.applyFrame(clip, f); for (const gh of rec.ghosts) { const P = rigPoseFor(gh, 1, rec.ghostBall); if (!rigPoseOk(P)) throw new Error('bad ghost pose at frame ' + f); seen.add(P.clip); } }
    if (seen.size < 3) throw new Error('ghosts used only ' + [...seen].join(', ')); }));
  await step('rig: faces follow the expression triggers', () => ev(() => { const m = { ball: { owner: null } }, p = { team: 0, state: 'move', sd: {}, grounded: true, hasBall: false, stamina: 80, anim: { expr: 'neutral', exprT: 0 } }; const run = (n) => { for (let i = 0; i < n; i++) rigExpression(p, m, STEP); return p.anim.expr; };
    setExpr(p, 'hyped', 1.5); if (run(60) !== 'hyped') throw new Error('hyped ended early'); if (run(150) !== 'neutral') throw new Error('hyped never ended: ' + p.anim.expr);
    p.stamina = 10; if (run(1) !== 'tired') throw new Error('low stamina shows ' + p.anim.expr); p.stamina = 80; m.ball.owner = { team: 1 }; if (run(1) !== 'focused') throw new Error('defense shows ' + p.anim.expr);
    p.state = 'jumpshot'; setExpr(p, 'shocked', 1.2); if (run(1) !== 'effort') throw new Error('a shot shows ' + p.anim.expr); p.sd.released = true; m.ball.owner = null; if (run(1) !== 'neutral') throw new Error('after the release: ' + p.anim.expr); }));
  // venues (M5): every court, every guard level, crowd reactions, the career venue by level
  await step('venues: every court draws at every guard level, with crowd reactions', () => ev(() => { const W_ = 640, H_ = 360, cv = document.createElement('canvas'); cv.width = W_; cv.height = H_; const ctx = cv.getContext('2d'); const before = (window.HH_ERRORS || []).length; let drawn = 0;
    for (const id of COURT_ORDER) { const m = new Match({ mode: '1v1', teams: [teamWithRoster(TEAMS[0]), teamWithRoster(TEAMS[1])], humanTeam: -1, headless: true, court: id, seed: 5, format: { type: 'first', target: 21 } }); const cam = new Camera(); cam.resize(W_, H_); cam.snapTo(COURT_L / 2); const world = new WorldRenderer();
      for (let i = 0; i < 120; i++) { simStep(m, STEP); cam.update(m, STEP); world.update(STEP, m); if (i % 30 === 29) for (const guard of [0, 1, 2, 3]) { drawMatchScene(ctx, { cam, world, fx: null, W: W_, H: H_, guard }, m, 1); drawn++; } }
      const V = world.venueFor(m); if (!!V !== !!venueKind(id)) throw new Error(id + ': venue missing'); if (V) { V.crowd.react('big', 6, m.time); V.crowd.react('oooh', 18, m.time); V.crowd.score(0, 6, 12, m.time, true); V.crowd.flash(m.time, 12, 0, 24, Math.random); for (let i = 0; i < 20; i++) { m.time += 0.05; world.update(0.05, m); drawMatchScene(ctx, { cam, world, fx: null, W: W_, H: H_, guard: 0 }, m, 1); drawn++; } } }
    const errs = (window.HH_ERRORS || []).slice(before); if (errs.length) throw new Error(errs.slice(0, 3).join(' | ')); if (drawn < COURT_ORDER.length * 16) throw new Error('only ' + drawn + ' frames'); }));
  await step('venues: career games use the venue for their level', () => ev(() => { const S = CONFIG.amateur.stages; if (S.hs.court !== 'gym' || S.college.court !== 'college') throw new Error('stage courts ' + S.hs.court + ', ' + S.college.court); if (venueKind('gym') !== 'hs' || venueKind('college') !== 'college' || venueKind('arena') !== 'pro' || venueKind('blacktop') !== 'street') throw new Error('venue map'); if (!/const court = 'arena'/.test(careerMatchOpts.toString())) throw new Error('pro games are not in the pro arena'); }));
  // UI kit, effects and key screens (M6)
  await step('ui: screen transitions settle, Reduce Motion skips them', async () => { await ev(() => { const g = HH.game; g.save.data.settings.reduceMotion = false; g.ui.push(howToScreen(g)); if (!g.ui.trans) throw new Error('no transition started'); }); await wait(350); await ev(() => { const g = HH.game; if (g.ui.trans) throw new Error('transition still running after 350 ms'); g.ui.pop(); g.save.data.settings.reduceMotion = true; g.ui.push(howToScreen(g)); const tr = g.ui.trans; g.ui.pop(); g.save.data.settings.reduceMotion = false; if (tr) throw new Error('Reduce Motion still animates'); }); });
  await step('effects: every §5 effect draws', () => ev(() => { const fx = new FXSystem(), cam = new Camera(), cv = document.createElement('canvas'); cv.width = 640; cv.height = 360; const ctx = cv.getContext('2d'); cam.resize(640, 360); cam.snapTo(12); const before = (window.HH_ERRORS || []).length;
    for (const k of ['puff', 'spark', 'sweat', 'shock', 'impact', 'confetti', 'dust', 'ring', 'flame', 'star']) fx.spawn(k, 12, 1.5, 0.5, k === 'confetti' ? CONFIG.fx.confettiCount : 8, ['#FFD23F', '#F3F0FF'], { dir: 1 });
    if (fx.pool.count < 100) throw new Error('only ' + fx.pool.count + ' particles'); for (let i = 0; i < 90; i++) { fx.update(1 / 60, null); fx.draw(ctx, cam); } if (fx.pool.count > 130) throw new Error('particles did not expire: ' + fx.pool.count);
    const k0 = calloutScale(0), kp = calloutScale(CONFIG.fx.calloutPopS * 0.6), k1 = calloutScale(CONFIG.fx.calloutPopS); if (k0 !== 0 || Math.abs(kp - 1.2) > 0.01 || Math.abs(k1 - 1) > 0.01) throw new Error('callout pop ' + k0 + ' ' + kp + ' ' + k1);
    const errs = (window.HH_ERRORS || []).slice(before); if (errs.length) throw new Error(errs.join(' | ')); }));
  await step('ui: trading cards draw at every tier', () => ev(() => { const cv = document.createElement('canvas'); cv.width = 400; cv.height = 400; const ctx = cv.getContext('2d'); const tiers = [];
    for (const ovr of [48, 66, 80, 91]) { const P = { key: 't' + ovr, name: 'Test Player', look: randomLook(artRng(ovr), {}), height: 1.9, colors: ['#2E6FD8', '#F3F0FF'], ovr, style: 'Slasher', number: 7, age: 20 }; drawTradingCard(ctx, 10, 10, 180, 252, P, { t: 1.2 }); tiers.push(cardTierOf(ovr)); }
    if (tiers.join() !== 'bronze,silver,gold,diamond') throw new Error('tiers ' + tiers.join()); }));
  // old saves migrate and continue
  const migrate = async (file, expectFn) => step('migration: ' + file, async () => { const raw = fs.readFileSync(path.join(FIX, file), 'utf8'); await ev(raw => { localStorage.setItem(CONFIG.save.key, raw); HH.game.save = new SaveSystem(); if (HH.game.save.corrupted) throw new Error('flagged corrupt'); if (HH.game.save.data.version !== CONFIG.save.version) throw new Error('version ' + HH.game.save.data.version); HH.game.ui.clearTo(mainMenu(HH.game)); }, raw); await wait(250); await expectFn(); });
  const continues = async () => { const has = await ev(() => HH.game.ui.screen.widgets.some(w => /CONTINUE CAREER/.test(w.label || ''))); if (!has) throw new Error('no CONTINUE CAREER'); await D.press(/CONTINUE CAREER/); await wait(500); const s = await D.screen(); if (!/amhub|amevent|career|combine/.test(s)) throw new Error('continue went to ' + s); };
  await migrate('save_v2_highschool.json', continues);
  await migrate('save_v2_pro_stage.json', continues);
  await migrate('save_v2_team_career.json', async () => { const ok = await ev(() => HH.game.save.data.settings.difficulty === 'allstar' && HH.game.save.data.records.threePoint === 21); if (!ok) throw new Error('settings or records lost'); });
  await migrate('save_v3_pro_only.json', async () => { await ev(() => { if (HH.game.save.data.career && HH.game.save.data.career.v === 3) throw new Error('v3 career kept as is'); }); });
  await migrate('save_v4_highschool.json', continues);
  await migrate('save_v4_pro.json', continues);
  await step('migrated looks use the painted-face model (v2)', () => ev(() => { const d = HH.game.save.data; const bad = []; const walk = (o, path, depth) => { if (!o || typeof o !== 'object' || depth > 7) return; for (const k in o) { const v = o[k]; if (k === 'look' && v && typeof v === 'object') { if (v.v !== 2 || !v.face) bad.push(path + '.look'); } else if (v && typeof v === 'object') walk(v, path + '.' + k, depth + 1); } }; walk(d.c1, 'c1', 0); walk(d.career, 'career', 0); if (bad.length) throw new Error('old looks left: ' + bad.slice(0, 5).join(', ')); }));
  await step('retirement: the jersey banner and the verdict', async () => { await ev(() => { const g = HH.game, sv = g.save.data; if (!sv.career) { const a = HH.amCreate(sv, { name: 'Test Retiree', look: randomLook(artRng(9), { teen: true }), number: 9, style: 'shooter', seasonLength: 11, gameLength: 120 }); a.events.length = 0; a.stage = 'combine'; HH.createCareerFromAmateur(sv, a); } retireCareer(sv); g.ui.clearTo(legacyScreen(g)); }); await wait(4600); await D.expectScreen('legacy'); await shot('20-retirement'); await ev(() => { const g = HH.game; g.save.data.career = null; g.ui.clearTo(mainMenu(g)); }); });
  await step('no recovered frame exceptions (desktop)', async () => { const fe = await D.frameErrors(); if (fe.length) throw new Error(fe.join(' | ')); });

  // phone: tap to start, the touch buttons show in a match and tapping them is safe
  const M = await openPage(browser, { phone: true, wait: 800 }); const pstep = (n, f) => R.step('phone: ' + n, f, M);
  await pstep('tap to start', async () => { await M.ev(() => { localStorage.clear(); HH.game.save = new SaveSystem(); HH.game.ui.clearTo(titleScreen(HH.game)); }); await M.page.waitForTimeout(300); await M.page.touchscreen.tap(422, 300); await M.page.waitForTimeout(400); await M.expectScreen('menu'); if (shotsDir) await M.shot(path.join(shotsDir, 'p1-menu.jpg')); });
  await pstep('touch buttons appear in a match', async () => { await M.ev(() => HH.game.ui.screen.widgets.find(w => /Quick 1v1/.test(w.label)).onPress()); await M.page.waitForTimeout(200); await M.ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); await M.page.waitForTimeout(1500); const vis = await M.ev(() => HH.game.input.touch.visible && !!HH.game.input.touch.layout && HH.game.input.touch.layout.buttons.length); if (!vis) throw new Error('touch controls not visible'); if (shotsDir) await M.shot(path.join(shotsDir, 'p2-match.jpg')); });
  await pstep('tapping every touch button is safe (regression: down() shadowing)', async () => { const L = await M.ev(() => { const l = HH.game.input.touch.layout; return l.buttons.map(b => ({ x: b.x, y: b.y })).concat([{ x: l.stick.x, y: l.stick.y }]); }); for (const b of L) { await M.page.touchscreen.tap(b.x, b.y); await M.page.waitForTimeout(120); } await M.page.waitForTimeout(300); });
  await pstep('stick drag moves the player', async () => { const s = await M.ev(() => { const l = HH.game.input.touch.layout.stick; return { x: l.x, y: l.y, x0: HH.game.match.controlledPlayer.x }; }); const cdp = await M.context.newCDPSession(M.page); await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: s.x, y: s.y }] }); for (let i = 1; i <= 6; i++) { await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: s.x + i * 10, y: s.y }] }); await M.page.waitForTimeout(40); } await M.page.waitForTimeout(600); await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); const x1 = await M.ev(() => HH.game.match.controlledPlayer.x); if (Math.abs(x1 - s.x0) < 0.3) throw new Error('player did not move: ' + s.x0.toFixed(2) + ' → ' + x1.toFixed(2)); });
  // phone: the key screens keep every tap target at least 64 CSS px tall
  const tapCheck = (label) => M.ev(label => { const ui = HH.game.ui, s = ui.screen; const small = (s.widgets || []).filter(w => !w.hidden && w.enabled !== false && w.kind !== 'text' && w.kind !== 'custom' && w.h * ui.scale < 63.5).map(w => (w.label || w.kind) + ' ' + Math.round(w.h * ui.scale) + 'px'); if (small.length) throw new Error(label + ': ' + small.join(', ')); return (s.widgets || []).length; }, label);
  await pstep('64 px tap targets: pause menu', async () => { await M.ev(() => HH.game.pause()); await M.page.waitForTimeout(300); await tapCheck('pause'); await M.ev(() => HH.game.quitToMenu()); await M.page.waitForTimeout(300); });
  await pstep('64 px tap targets: main menu', async () => { await M.ev(() => HH.game.ui.clearTo(mainMenu(HH.game))); await M.page.waitForTimeout(300); await tapCheck('menu'); });
  await pstep('64 px tap targets: create (every tab)', async () => { await M.ev(() => HH.game.ui.push(createPlayerScreen(HH.game))); await M.page.waitForTimeout(300); for (let tab = 0; tab < 3; tab++) { await M.ev(tab => { const s = HH.game.ui.screen; s.widgets[tab].onPress(); }, tab); await tapCheck('create tab ' + tab); } });
  await pstep('64 px tap targets: genes, hub, recap', async () => { await M.ev(() => { const g = HH.game; const b = g.ui.screen.widgets.find(w => /START HIGH SCHOOL/.test(w.label || '')); b.onPress(); }); await M.page.waitForTimeout(700); if (await M.screen() !== 'amevent') throw new Error('no genes reveal'); await tapCheck('genes');
    await M.ev(() => { const g = HH.game; const s = g.ui.screen; s.onBack(); }); await M.page.waitForTimeout(400); if (await M.screen() !== 'amhub') throw new Error('not the hub'); await tapCheck('hub');
    await M.ev(() => { const g = HH.game, c = g.save.data.c1; let n = 0; while (n++ < 60 && !c.events.length) { if (c.decision) break; HH.amSimGame(c); } g.ui.clearTo(amHub(g)); }); await M.page.waitForTimeout(600); if (await M.screen() !== 'amevent') throw new Error('no recap'); await tapCheck('recap'); });
  await pstep('no recovered frame exceptions (phone)', async () => { const fe = await M.frameErrors(); if (fe.length) throw new Error(fe.join(' | ')); });

  const notes = new Set([...D.notes, ...M.notes]); if (notes.size) console.log('notes: ' + [...notes].join('; '));
  const fails = R.done(); await browser.close(); process.exitCode = fails ? 1 : 0;
})();
