// Smoke test: the whole game through the real UI at desktop size (1280×720), plus the phone layout with touch (844×390),
// old-save migrations and the regression checks. Zero page errors, console errors or recovered frame exceptions allowed.
// Usage: node tests/smoke.js [--shots <dir>]
const fs = require('fs'), path = require('path');
const { ROOT, launch, openPage, runner } = require('./lib');
const FIX = path.join(__dirname, 'fixtures');
(async () => {
  const shotsDir = process.argv.includes('--shots') ? process.argv[process.argv.indexOf('--shots') + 1] : null; if (shotsDir) fs.mkdirSync(shotsDir, { recursive: true });
  const browser = await launch(); const R = runner('smoke');
  const D = await openPage(browser); const { page, ev } = D; const step = (n, f) => R.step(n, f, D);
  const shot = async n => { if (shotsDir) { await page.waitForTimeout(250); await D.shot(path.join(shotsDir, n + '.jpg')); } };
  const wait = ms => page.waitForTimeout(ms);
  // bots play both sides until the match ends (a full game, fast-forwarded through the real simulation)
  const finishMatch = () => ev(() => { const m = HH.game.match; if (!m) throw new Error('no match'); for (const p of m.players) if (p.controlled) { p.controlled = false; p.input.reset(); } let n = 0; while (!m.ended && n < 120 * 60 * 30) { simStep(m, STEP); n++; } if (!m.ended) throw new Error('match did not end'); return n; });
  const clearEvents = () => ev(() => { const a = HH.game.save.data.c1; if (a) a.events.length = 0; });
  const drainEvents = async () => { for (let i = 0; i < 8; i++) { const s = await D.screen(); if (s !== 'amevent') return; await D.press(/^Continue$/); } };

  await step('fresh save, title screen', async () => { await ev(() => { localStorage.clear(); HH.game.save = new SaveSystem(); HH.game.ui.clearTo(titleScreen(HH.game)); }); await wait(300); await D.expectScreen('title'); await shot('01-title'); });
  await step('title → main menu (Enter)', async () => { await page.keyboard.press('Enter'); await wait(300); await D.expectScreen('menu'); await shot('02-menu'); });
  await step('create your player', async () => { await D.press(/START YOUR CAREER/); await D.expectScreen('create'); await shot('03-create'); });
  await step('no height slider on create', () => ev(() => { const bad = HH.game.ui.screen.widgets.find(w => /height/i.test(w.label || '') && w.kind === 'slider'); if (bad) throw new Error('height slider: ' + bad.label); }));
  await step('start high school → genes reveal', async () => { await D.press(/START HIGH SCHOOL/); await wait(1500); await D.expectScreen('amevent'); await shot('04-genes'); });
  await step('genes → hub', async () => { await drainEvents(); await D.expectScreen('amhub'); await shot('05-hub'); });
  await step('play the first game (full match)', async () => { await D.press(/^PLAY GAME$/); await wait(1500); await ev(() => { if (!HH.game.match || HH.game.match.perSide !== 1) throw new Error('no 1v1 match'); }); await shot('06-match'); const n = await finishMatch(); if (n < 120 * 20) throw new Error('suspiciously short match: ' + n + ' steps'); await wait(2500); });
  await step('postgame → result', async () => { const s = await D.screen(); if (s !== 'amresult' && s !== 'postgame') throw new Error('screen ' + s); await shot('07-result'); });
  await step('result → hub', async () => { await D.press(/CONTINUE/); await wait(400); await drainEvents(); await D.expectScreen('amhub'); });
  await step('the week advanced', () => ev(() => { const a = HH.game.save.data.c1; if (!a.league || a.league.games.length < 1) throw new Error('no game recorded'); }));
  await step('standings', async () => { await D.press(/Standings/); await shot('08-standings'); await ev(() => HH.game.ui.pop()); });
  await step('stats & history', async () => { await D.press(/Stats & history/); await shot('09-history'); await ev(() => HH.game.ui.pop()); });
  await step('sim to the season recap', async () => { for (let i = 0; i < 30; i++) { const s = await D.screen(); if (s === 'amevent') break; if (s === 'amresult') { await D.press(/CONTINUE/); continue; } await D.press(/^SIM$/); } await wait(1200); await D.expectScreen('amevent'); await shot('10-recap'); await drainEvents(); });
  await step('grew between seasons (model height changes)', () => ev(() => { const a = HH.game.save.data.c1; const log = a.log || []; if (!log.length) throw new Error('no season log'); }));
  await step('sim to college offers', async () => { await ev(() => { const g = HH.game, a = g.save.data.c1; let guard = 0; while (!a.decision && a.stage === 'hs' && guard++ < 200) { a.events.length = 0; if (!amSimGame(a)) break; } a.events.length = 0; g.ui.clearTo(amHub(g)); if (!a.decision) throw new Error('no decision'); }); await D.press(/CHOOSE YOUR COLLEGE/); await D.expectScreen('amdecision'); await shot('11-offers'); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); await wait(400); await drainEvents(); await D.expectScreen('amhub'); });
  await step('sim to the draft combine', async () => { await ev(() => { const g = HH.game, a = g.save.data.c1; let guard = 0; while (a.stage !== 'combine' && guard++ < 300) { a.events.length = 0; if (a.decision) { if (a.decision.kind === 'declare') amDeclare(a, true); else amChooseCollege(a, a.decision.offers[0]); continue; } if (!amSimGame(a)) break; } a.events.length = 0; g.ui.clearTo(amHub(g)); if (a.stage !== 'combine') throw new Error('stage ' + a.stage); }); });
  await step('combine measures you', async () => { await D.press(/DRAFT COMBINE/); await wait(6500); await D.expectScreen('combine'); await shot('12-combine'); });
  await step('draft night', async () => { await D.press(/DRAFT NIGHT/); await wait(7000); await D.expectScreen('draft'); await shot('13-draft'); });
  await step('pro hub', async () => { await D.press(/START YOUR PRO CAREER/); await wait(400); await D.expectScreen('career'); await shot('14-pro-hub'); });
  await step('pregame → tip off → full pro match', async () => { await D.press(/PLAY GAME/); await D.expectScreen('pregame'); await shot('15-pregame'); await D.press(/TIP OFF/); await wait(1500); await shot('16-pro-match'); await finishMatch(); await wait(2500); const s = await D.screen(); if (s !== 'result' && s !== 'postgame') throw new Error('screen ' + s); await shot('17-pro-result'); });
  await step('back to the pro hub', async () => { for (let i = 0; i < 3; i++) { const s = await D.screen(); if (s === 'career') break; await D.press(/CONTINUE/); } await D.expectScreen('career'); });
  await step('pause menu in a match', async () => { await D.press(/PLAY GAME/); await D.press(/TIP OFF/); await wait(1200); await page.keyboard.press('Escape'); await wait(300); await D.expectScreen('pause'); await shot('18-pause'); await D.press(/Sim the rest/); await wait(1500); for (let i = 0; i < 3; i++) { const s = await D.screen(); if (s === 'career') break; try { await D.press(/CONTINUE/); } catch (e) { break; } } });
  // other modes
  const toMenu = () => ev(() => { const g = HH.game; if (g.mode === 'match') g.quitToMenu(); g.ui.clearTo(mainMenu(g)); });
  const runMode = async (label, open, secs) => step(label, async () => { await toMenu(); await wait(200); await open(); await wait(1500); await ev(() => { if (!HH.game.match) throw new Error('no match started'); }); await wait((secs || 1.5) * 1000); await ev(() => { const g = HH.game; if (g.match && !g.match.ended) { for (const p of g.match.players) p.controlled = false; for (let i = 0; i < 120 * 3; i++) simStep(g.match, STEP); } }); await wait(300); await toMenu(); });
  await runMode('quick 1v1 starts and runs', async () => { await D.press(/Quick 1v1/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); });
  await runMode('extras → street tournament', async () => { await D.press(/Extras/); await D.press(/Street tournament/); await D.press(/START TOURNAMENT/); await ev(() => { const w = HH.game.ui.screen.widgets.find(w => w.primary); if (w) w.onPress(); }); });
  await runMode('extras → 3-point contest', async () => { await D.press(/Extras/); await D.press(/3-Point Contest/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); });
  await runMode('extras → practice', async () => { await D.press(/Extras/); await D.press(/^Practice$/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); });
  await runMode('extras → tutorial', async () => { await D.press(/Extras/); await D.press(/Tutorial/); });
  await step('extras → team league (classic) is reachable', async () => { await toMenu(); await D.press(/Extras/); await D.press(/Team league/); const s = await D.screen(); if (!/create|teamhub|chooseTeam/.test(s)) throw new Error('screen ' + s); await shot('19-team-league'); await toMenu(); });
  await step('extras → art lab (every view)', async () => { await toMenu(); await D.press(/Extras/); await D.press(/Art Lab/); await D.expectScreen('artlab'); const n = await ev(() => LAB_VIEWS.length); for (let v = 0; v < n; v++) { await ev(v => HH.game.ui.screen.setView(v), v); await wait(250); } await shot('20-artlab'); await toMenu(); });
  await step('settings and how to play', async () => { await toMenu(); await D.press(/Settings/); await D.expectScreen('settings'); await ev(() => HH.game.ui.pop()); await D.press(/How to play/); await D.expectScreen('howto'); await ev(() => HH.game.ui.pop()); });
  // regressions that were fixed before and must stay fixed
  await step('regression: odd look values never crash drawing', () => ev(() => { const odd = [{}, { skin: NaN, hair: -3, hairColor: 99 }, { skin: 1e9, hair: 'x', beard: 42, eyes: -1, face: null }, { skin: 2.5, facialHair: 17, iris: 'q', acc: null }]; const cv = document.createElement('canvas'); cv.width = cv.height = 300; const g = cv.getContext('2d'); for (const look of odd) { drawHead(g, 150, 150, 60, look, 'hyped', 1, ['#123456', '#FFFFFF'], 2); portraitOf({ name: 'Odd', look }, ['#123456', '#FFFFFF'], 96); drawMannequin(g, { name: 'Odd', look, height: 1.9, attrs: {} }, { colors: ['#123456', '#FFFFFF'], pattern: 'solid' }, 150, 280, 200, 'focused', 1, 0); } }));
  await step('regression: dunks respect the contest', () => ev(() => { const m = new Match({ mode: '1v1', teams: [teamWithRoster(TEAMS[0]), teamWithRoster(TEAMS[1])], seed: 3, headless: true, humanTeam: -1 }); const p = m.players[0]; const open = makeProbability(p, 'dunk', 'mid', 0, 0).P, smothered = makeProbability(p, 'dunk', 'mid', 0, 0.9).P; if (!(smothered < open - 0.1)) throw new Error('dunk P open ' + open + ' vs contested ' + smothered); }));
  await step('regression: the camera keeps your player in view', async () => { await toMenu(); await D.press(/Quick 1v1/); await ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); await wait(1200); await ev(() => { const g = HH.game, m = g.match, me = m.controlledPlayer; me.controlled = false; let worst = 0; for (let i = 0; i < 120 * 60; i++) { simStep(m, STEP); if (i % 4 === 3) { g.cam.update(m, 4 * STEP); const x = g.cam.sx(me.x); worst = Math.max(worst, x < 0 ? -x : x > g.W ? x - g.W : 0); } if (m.ended) break; } me.controlled = true; if (worst > 40) throw new Error('player left the frame by ' + worst.toFixed(0) + ' px'); }); await toMenu(); });
  // old saves migrate and continue
  const migrate = async (file, expectFn) => step('migration: ' + file, async () => { const raw = fs.readFileSync(path.join(FIX, file), 'utf8'); await ev(raw => { localStorage.setItem(CONFIG.save.key, raw); HH.game.save = new SaveSystem(); if (HH.game.save.corrupted) throw new Error('flagged corrupt'); if (HH.game.save.data.version !== CONFIG.save.version) throw new Error('version ' + HH.game.save.data.version); HH.game.ui.clearTo(mainMenu(HH.game)); }, raw); await wait(250); await expectFn(); });
  const continues = async () => { const has = await ev(() => HH.game.ui.screen.widgets.some(w => /CONTINUE CAREER/.test(w.label || ''))); if (!has) throw new Error('no CONTINUE CAREER'); await D.press(/CONTINUE CAREER/); await wait(500); const s = await D.screen(); if (!/amhub|amevent|career|combine/.test(s)) throw new Error('continue went to ' + s); };
  await migrate('save_v2_highschool.json', continues);
  await migrate('save_v2_pro_stage.json', continues);
  await migrate('save_v2_team_career.json', async () => { const ok = await ev(() => HH.game.save.data.settings.difficulty === 'allstar' && HH.game.save.data.records.threePoint === 21); if (!ok) throw new Error('settings or records lost'); });
  await migrate('save_v3_pro_only.json', async () => { await ev(() => { if (HH.game.save.data.career && HH.game.save.data.career.v === 3) throw new Error('v3 career kept as is'); }); });
  await migrate('save_v4_highschool.json', continues);
  await migrate('save_v4_pro.json', continues);
  await step('migrated looks use the painted-face model (v2)', () => ev(() => { const d = HH.game.save.data; const bad = []; const walk = (o, path, depth) => { if (!o || typeof o !== 'object' || depth > 7) return; for (const k in o) { const v = o[k]; if (k === 'look' && v && typeof v === 'object') { if (v.v !== 2 || !v.face) bad.push(path + '.look'); } else if (v && typeof v === 'object') walk(v, path + '.' + k, depth + 1); } }; walk(d.c1, 'c1', 0); walk(d.career, 'career', 0); if (bad.length) throw new Error('old looks left: ' + bad.slice(0, 5).join(', ')); }));
  await step('no recovered frame exceptions (desktop)', async () => { const fe = await D.frameErrors(); if (fe.length) throw new Error(fe.join(' | ')); });

  // phone: tap to start, the touch buttons show in a match and tapping them is safe
  const M = await openPage(browser, { phone: true, wait: 800 }); const pstep = (n, f) => R.step('phone: ' + n, f, M);
  await pstep('tap to start', async () => { await M.ev(() => { localStorage.clear(); HH.game.save = new SaveSystem(); HH.game.ui.clearTo(titleScreen(HH.game)); }); await M.page.waitForTimeout(300); await M.page.touchscreen.tap(422, 300); await M.page.waitForTimeout(400); await M.expectScreen('menu'); if (shotsDir) await M.shot(path.join(shotsDir, 'p1-menu.jpg')); });
  await pstep('touch buttons appear in a match', async () => { await M.ev(() => HH.game.ui.screen.widgets.find(w => /Quick 1v1/.test(w.label)).onPress()); await M.page.waitForTimeout(200); await M.ev(() => HH.game.ui.screen.widgets.find(w => w.primary).onPress()); await M.page.waitForTimeout(1500); const vis = await M.ev(() => HH.game.input.touch.visible && !!HH.game.input.touch.layout && HH.game.input.touch.layout.buttons.length); if (!vis) throw new Error('touch controls not visible'); if (shotsDir) await M.shot(path.join(shotsDir, 'p2-match.jpg')); });
  await pstep('tapping every touch button is safe (regression: down() shadowing)', async () => { const L = await M.ev(() => { const l = HH.game.input.touch.layout; return l.buttons.map(b => ({ x: b.x, y: b.y })).concat([{ x: l.stick.x, y: l.stick.y }]); }); for (const b of L) { await M.page.touchscreen.tap(b.x, b.y); await M.page.waitForTimeout(120); } await M.page.waitForTimeout(300); });
  await pstep('stick drag moves the player', async () => { const s = await M.ev(() => { const l = HH.game.input.touch.layout.stick; return { x: l.x, y: l.y, x0: HH.game.match.controlledPlayer.x }; }); const cdp = await M.context.newCDPSession(M.page); await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: s.x, y: s.y }] }); for (let i = 1; i <= 6; i++) { await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: s.x + i * 10, y: s.y }] }); await M.page.waitForTimeout(40); } await M.page.waitForTimeout(600); await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); const x1 = await M.ev(() => HH.game.match.controlledPlayer.x); if (Math.abs(x1 - s.x0) < 0.3) throw new Error('player did not move: ' + s.x0.toFixed(2) + ' → ' + x1.toFixed(2)); });
  await pstep('no recovered frame exceptions (phone)', async () => { const fe = await M.frameErrors(); if (fe.length) throw new Error(fe.join(' | ')); });

  const notes = new Set([...D.notes, ...M.notes]); if (notes.size) console.log('notes: ' + [...notes].join('; '));
  const fails = R.done(); await browser.close(); process.exitCode = fails ? 1 : 0;
})();
