// 3.0 (§5, §11): tournaments, all 1v1 and harder at each level. Every tournament runs and has a bracket chart; the NPCs'
// strength rises each round and each tier (local → state → national → international → the Olympics; the best
// international players 85–95 OVR); the rewards are granted (cash, ranking points, credits, a tournament item, a trophy
// or a medal; the legacy score); the Olympics and the World Cup alternate (two years apart); tournament items are won,
// never bought, a level stronger, and gear still adds at most +4 to a rating; your game is played or simmed from the
// tournament's screen; the calendar brings each one at its time across a whole career. Prints the §11 tables.
// Usage: node tests/tourney.js
const { launch, openPage, runner } = require('./lib');
(async () => {
  const browser = await launch(); const P = await openPage(browser); const R = runner('tourney'); const { ev, page } = P;
  await ev(() => {
    window.__hs = (seed, boost) => { const sv = defaultSave(); const a = amCreate(sv, { name: 'Bracket Kid', look: PRESET_LOOKS[seed % 6], number: 5, style: 'slasher', seed }); sv.c1 = a; HH.game.save.data = sv; a.events = []; if (boost) for (const k of RATING_KEYS) a.r[k] = clamp(a.r[k] + boost, 20, 99); return a; };
    window.__adv = (a, n, until) => { let k = 0, g = 0; while (k++ < 3000 && g < n) { if (until && until(a)) break; a.inbox = []; if (a.summer && a.summer.pending) hsSummerGo(a, 'rest', hsSummerEvents(a).filter(e => e.ok).map(e => e.key)); /* every event you can enter: the circuit, the camp if invited, the U17 if picked */ else if (a.tryout && a.tryout.step !== 'done') hsSimTryout(a); else if (a.decision) { const d = a.decision; if (d.kind === 'portal') colPortalChoose(a, null); else if (d.kind === 'college' && d.signing) recSimSign(a); else if (d.kind === 'college') amChooseCollege(a, d.offers[0]); else amDeclare(a, a.stageYear >= 4); } else if (a.stage === 'combine' || a.stage === 'overseas') break; else { amSimGame(a); g++; } tnAutoResolve(a); a.events = (a.events || []).filter(e => e && e.kind === 'tourney'); } return a; };
    window.__pro = (seed) => { const sv = defaultSave(), c = testProLeague(seed, sv); sv.career = c; sv.c1.handedOff = true; HH.game.save.data = sv; return c; };
    window.__proSeason = (c) => { const sv = HH.game.save.data; let g = 0; while (c.phase !== 'offseason' && g++ < 160) { c.events = []; if (!simUserGame(sv)) { if (c.phase === 'playoffs') simPlayoffsToEnd(c); else if (c.phase === 'regular') { const gm = userGame(c); if (!gm) break; } } } c.events = []; lgOffseasonAuto(c); const keys = tnState(c).list.filter(T => T.s === c.season).map(T => T.key); newSeason(c); return keys; };
  });
  // every tournament the engine runs, at its level
  const KEYS = ['hsnat', 'aau1', 'aau2', 'aau3', 'camp', 'allam', 'u17', 'inv', 'u21', 'cup', 'blacktop', 'wc', 'oly'];
  await R.step('§11: every tournament runs and has a bracket chart (HS Nationals, the AAU circuit, the Elite Camp, the All-American Game, the U17 and U21 World Cups, the Preseason Invitational, the PBL Cup, Blacktop Kings, the World Cup, the Olympics; and the state, conference, national, All-Star and playoff brackets)', () => ev(KEYS => {
    const out = [], g = HH.game, mk = key => { const ev = TNE[key]; if (ev.lvl === 'pro') { const c = __pro(300 + key.length); if (key === 'cup') { let k = 0; while (c.week < TNE.cup.ko && k++ < 30) { c.events = []; simUserGame(HH.game.save.data); } return [c, tnOfSeason(c, 'cup', c.season)]; } const field = key === 'blacktop' ? null : c.active.slice(0, 3).concat([c.meId]); const T = tnCreate(c, key, { mine: true, field }); tnSimAll(c, T); return [c, T]; }
      const a = __hs(400 + key.length, 14); if (ev.lvl === 'college') { a.stage = 'college'; a.stageYear = 2; a.college = COLLEGES[5].name; } const T = tnCreate(a, key, { mine: true }); tnSimAll(a, T); return [a, T]; };
    for (const key of KEYS) { const [c, T] = mk(key); if (!T || !T.done) throw new Error(key + ': not played out (' + (T ? 'wait ' + T.wait : 'none') + ')'); if (!T.champ || !T.E[T.champ]) throw new Error(key + ': no champion');
      const n = T.ids.length, games = T.G.length, want = { ko: n - 1, groups: 24 + 8, skills: 3, showcase: 12, cup: 7 }[T.fmt]; if (games !== want) throw new Error(key + ': ' + games + ' games (want ' + want + ')'); if (T.ids.some(id => !(T.place[id] >= 1))) throw new Error(key + ': a player without a place');
      if (T.my.in && !(T.my.place >= 1)) throw new Error(key + ': your place'); const L = bracketList(g, c); if (!L.some(b => b.label.indexOf(tnTitle(T)) === 0)) throw new Error(key + ': not in Brackets: ' + L.map(b => b.label).join(', '));
      g.ui.push(tnChartScreen(g, c, T)); g.drawUI(g.ctx, g.W, g.H); g.ui.pop(); out.push(key + ' ' + T.fmt + ' ' + n); }
    // the ones that were here before: their brackets are in the list when they're on
    const a = __hs(77, 18); __adv(a, 400, a => a.league && a.league.playoffs && a.league.playoffs.state); const hasState = bracketList(g, a).some(b => /State/.test(b.label)); if (a.league && a.league.playoffs && a.league.playoffs.state && !hasState) throw new Error('no state bracket');
    const c = __pro(88); let k = 0; while (c.week < 8 && k++ < 30) { c.events = []; simUserGame(HH.game.save.data); } if (c.allStar && c.allStar.one && !bracketList(g, c).some(b => b.label === 'All-Star 1v1')) throw new Error('no All-Star chart'); while (c.phase !== 'offseason' && k++ < 120) { c.events = []; if (!simUserGame(HH.game.save.data) && c.phase === 'playoffs') simPlayoffsToEnd(c); } if (!bracketList(g, c).some(b => b.label === 'The playoffs')) throw new Error('no playoffs bracket');
    return out.length + ' new tournaments: ' + out.join(' · ') + ' · and state, All-Star, playoffs'; }, KEYS), P);
  await R.step('§11: NPC strength rises each round and each tier: the field\'s level by tier (local → state → national → international → the Olympics), every round + tourney.round, the best international players 85–95 OVR', () => ev(() => {
    const a = __hs(500, 0), lv = key => { const T = tnCreate(a, key, { mine: false, mean: amStageMean(a) + TN.tier[TNE[key].tier] }); return T.ids.reduce((s, id) => s + T.E[id].o, 0) / T.ids.length; };
    const hsTiers = ['aau1', 'aau2', 'hsnat', 'u17'].map(k => lv(k)); for (let i = 1; i < hsTiers.length; i++) if (!(hsTiers[i] > hsTiers[i - 1])) throw new Error('high school tiers: ' + hsTiers.map(v => v.toFixed(1)).join(' '));
    const c = __pro(501), pl = key => { const T = tnCreate(c, key, { mine: false, field: c.active.slice(0, 4) }); const intl = T.ids.filter(id => !T.E[id].pid).map(id => T.E[id].o); return { mean: intl.reduce((s, v) => s + v, 0) / intl.length, best: Math.max(...intl), top: intl.sort((x, y) => y - x).slice(0, TN.intl.top) }; };
    const W = pl('wc'), O = pl('oly'), bt = (() => { const T = tnCreate(c, 'blacktop', { mine: false }); return T.ids.filter(id => !T.E[id].pid).reduce((s, id) => s + T.E[id].o, 0) / T.ids.filter(id => !T.E[id].pid).length; })();
    if (!(O.mean > W.mean && W.mean > bt)) throw new Error('pro tiers: blacktop ' + bt.toFixed(1) + ' · World Cup ' + W.mean.toFixed(1) + ' · Olympics ' + O.mean.toFixed(1)); if (W.top.concat(O.top).some(v => v < 84 || v > 96)) throw new Error('the best internationals ' + W.top.concat(O.top).join(' '));
    // each round: the opponents a top seed meets, on average, and the same player's rating a round later
    const run = (key, n) => { const b = __hs(510 + n, 20), by = {}; for (let i = 0; i < n; i++) { const T = tnCreate(b, key, { mine: true, mean: amStageMean(b) + TN.tier[TNE[key].tier] }); let gg = 0; while (!T.done && gg++ < 12) { const g = tnAdvance(b, T); if (!g) break; const s = g.s; (by[s] || (by[s] = [])).push(tnGameOvr(b, T, tnOppIdOf(T, g), g)); tnSimMine(b, T); } } return Object.keys(by).map(Number).sort((x, y) => x - y).map(s => [s, by[s].reduce((x, y) => x + y, 0) / by[s].length, by[s].length]); };
    const out = []; for (const [key, n] of [['hsnat', 60], ['u17', 40]]) { const L = run(key, n); for (let i = 1; i < L.length; i++) if (!(L[i][1] > L[i - 1][1])) throw new Error(key + ' rounds: ' + L.map(x => x[1].toFixed(1)).join(' ')); out.push(key + ' ' + L.map(x => x[1].toFixed(1)).join(' → ')); }
    const T = tnCreate(a, 'hsnat', { mine: false }), id = T.ids[0], g0 = { s: 0 }, g3 = { s: 3 }; if (tnGameOvr(a, T, id, g3) - tnGameOvr(a, T, id, g0) !== 3 * TN.round) throw new Error('the step');
    return 'HS tiers ' + hsTiers.map(v => v.toFixed(1)).join(' < ') + ' · pros: Blacktop ' + bt.toFixed(1) + ' < World Cup ' + W.mean.toFixed(1) + ' < Olympics ' + O.mean.toFixed(1) + ' (best ' + W.best + '/' + O.best + ') · ' + out.join(' · '); }), P);
  await R.step('§11: the rewards are granted: cash, ranking points, credits, fame and exposure by your place; the champion\'s tournament item; trophies and medals in the trophy room; the legacy score; once a season for the brackets that were here before; the games count for the badges, but not for Unbreakable\'s and Iron Man\'s games', () => ev(() => {
    const a = __hs(600, 0), c0 = a.cash, cr0 = a.credits || 0, x0 = a.exposure || 0, lines = tnGrant(a, 'hsnat', 1); const row = TNE.hsnat.rw[0];
    if (a.cash !== c0 + row[1] || (a.credits || 0) !== cr0 + row[3] || a.exposure !== x0 + row[5] || tnRkBonus(a) !== row[2] || !gearOf(a).owned['tn:hsnat']) throw new Error('HS Nationals: ' + lines.join(' · '));
    tnGrant(a, 'hsnat', 1); if (gearOf(a).owned['tn:hsnat'] !== 2) throw new Error('won again: a level up'); const r16 = tnGrant(a, 'hsnat', 16); if (r16.some(l => /^Won/.test(l))) throw new Error('an item for the round of 16');
    if (tnAward(a, 'state', 1).length === 0 || tnAward(a, 'state', 1).length) throw new Error('state: once a season');
    const c = __pro(601), m0 = c.me.money, f0 = c.me.fame; tnGrant(c, 'oly', 1); if (c.me.money < m0 + TNE.oly.rw[0][1] * 0.9 || c.me.fame <= f0 || !gearOf(c.me).owned['tn:oly']) throw new Error('Olympic gold');
    const T = tnCreate(c, 'oly', { mine: true, field: c.active.slice(0, 3).concat([c.meId]) }), D = () => Object.assign({}, trDeeds(c.me) || {}), d0 = D(); tnSimAll(c, T); const M = T.my, d1 = D(); if (!M.rw || !M.rw.length) throw new Error('no reward lines');
    if ((d1.games || 0) !== (d0.games || 0) || (d1.healthy || 0) !== (d0.healthy || 0) || !((d1.pts || 0) > (d0.pts || 0))) throw new Error('the badges\' deeds: a tournament game counts, but not for the seasons\' games and healthy games ' + JSON.stringify([d0, d1])); /* X6: counted, they stretched careers */ const tr = tnTrophies(c), L = legacyOf(c);
    const fake = { k: 'oly', s: c.season, y: 2032, n: 'Olympics 2032', f: 1, m: 1, lv: 'pro' }; tnState(c).rows.push(fake, Object.assign({}, fake, { k: 'wc', n: 'World Cup 2034', f: 2, m: 2 }), Object.assign({}, fake, { k: 'cup', n: 'PBL Cup', f: 1, m: 0 }));
    const L2 = legacyOf(c), want = TNE.oly.legacy[0] + TNE.wc.legacy[1] + TNE.cup.legacy[0]; if (Math.abs((L2.tour - L.tour) - want) > 0.01 || L2.medals < 2 || L2.cups < 1) throw new Error('legacy ' + L.tour + ' → ' + L2.tour + ' (want +' + want + ')');
    const kinds = tnTrophies(c).map(t => t.kind); if (!kinds.includes('gold') || !kinds.includes('silver') || !kinds.includes('cup')) throw new Error('trophy room: ' + kinds.join(','));
    return 'HS Nationals champion: ' + lines.join(' · ') + ' · Olympics: you ' + tnPlaceText(T, M.place, true) + ' (' + M.rw.join(' · ') + ') · legacy +' + want + ' for gold, silver and a Cup'; }), P);
  await R.step('§11: the Olympics and the World Cup alternate: the World Cup in years ≡ 2 (mod 4), the Olympics two years later; over six pro seasons each summer brings the right one', () => ev(() => {
    const ys = []; for (let y = 2031; y <= 2060; y++) { const k = tnProIntlKey(y); if (k) ys.push([y, k]); } for (let i = 1; i < ys.length; i++) { if (ys[i][0] - ys[i - 1][0] !== 2 || ys[i][1] === ys[i - 1][1]) throw new Error('years ' + ys.map(x => x.join(':')).join(' ')); } if (ys[0][1] !== 'oly' || tnProIntlKey(2034) !== 'wc') throw new Error('the calendar');
    const c = __pro(700), got = []; for (let s = 0; s < 6; s++) { const yr = frYear(c.season), keys = __proSeason(c); const want = tnProIntlKey(yr); if (!keys.includes('cup') || !keys.includes('blacktop')) throw new Error(yr + ': ' + keys.join(',')); if (want && !keys.includes(want)) throw new Error(yr + ': no ' + want); if (keys.includes(want === 'wc' ? 'oly' : 'wc')) throw new Error(yr + ': both'); got.push(yr + (want ? ' ' + want : '')); }
    return got.join(' · '); }), P);
  await R.step('tournament items (§6.2): won, never bought, a level stronger than the store\'s at the same level; gear never adds more than +4 to a rating (a property test over random lockers)', () => ev(() => {
    const a = __hs(800, 0); if (gearBuy(a, 'tn:oly') || gearBuy(a, 'tn:hsnat')) throw new Error('bought a tournament item'); if (GEAR_IDS.some(id => /^tn:/.test(id))) throw new Error('in the store');
    const it = gearItem('tn:hsnat'), base = gearItem(it.fam); if (!it.won || gearRatingAt(it, 1).main !== gearRatingAt(base, 2).main) throw new Error('a level stronger'); if (gearRatingAt(it, 5).also !== gearRatingAt(base, 5).also + 1) throw new Error('Lv5');
    const ids = GEAR_IDS.concat(Object.keys(TNE).filter(k => TNE[k].item).map(k => 'tn:' + tnItemKey(k))), rng = new RNG(9); let worst = 0;
    for (let t = 0; t < 300; t++) { a.gear = { v: 3, owned: {}, eq: {} }; const G = gearOf(a); for (const id of ids) if (rng.next() < 0.5) G.owned[id] = 1 + rng.int(5); for (const id of Object.keys(G.owned)) if (rng.next() < 0.7) gearEquip(a, id); const b = gearBonus(a); for (const k in b) worst = Math.max(worst, b[k]); if (Object.values(b).some(v => v > GEAR.cap)) throw new Error('over the cap: ' + JSON.stringify(b)); }
    return 'never sold · Lv1 = the store\'s Lv2 · 300 random lockers: the most +' + worst; }), P);
  await R.step('your game from the tournament\'s screen: PLAY (the real 1v1 at the tournament\'s floor, the opponent at their round\'s rating), the result over the match, back to the tournament; SIM; Sim the rest; DONE shows the rewards', async () => {
    await ev(() => { localStorage.clear(); const g = HH.game; g.save = new SaveSystem(); const sv = g.save.data; const a = amCreate(sv, { name: 'Bracket Kid', look: PRESET_LOOKS[0], number: 5, style: 'slasher', seed: 4321 }); sv.c1 = a; a.events = []; for (const k of RATING_KEYS) a.r[k] = clamp(a.r[k] + 16, 20, 99); tnQueue(a, tnCreate(a, 'hsnat', { mine: true })); g.ui.clearTo(amHub(g)); });
    await page.waitForTimeout(800); await P.expectScreen('tourney'); const before = await ev(() => { const T = tnLive(HH.game.save.data.c1); return { court: T.court, g: tnNextMine(HH.game.save.data.c1, T) }; });
    await P.press(/^PLAY$/); await page.waitForTimeout(1200); const mo = await ev(() => ({ mode: HH.game.mode, court: HH.game.match && HH.game.match.courtId, kind: HH.game.after && HH.game.after.kind })); if (mo.mode !== 'match' || mo.kind !== 'tourney' || mo.court !== before.court) throw new Error('the match: ' + JSON.stringify(mo));
    await ev(() => { const m = HH.game.match; for (const p of m.players) if (p.controlled) { p.controlled = false; p.input.reset(); } let n = 0; while (!m.ended && n < 120 * 60 * 30) { simStep(m, STEP); n++; } }); let s = null; for (let i = 0; i < 20 && s !== 'tnresult'; i++) { await page.waitForTimeout(400); s = await P.screen(); } if (s !== 'tnresult') throw new Error('result: ' + s);
    await P.press(/^BACK TO THE/); await page.waitForTimeout(700); await P.expectScreen('tourney'); const g1 = await ev(() => { const T = tnLive(HH.game.save.data.c1); return T ? T.my.g : -1; }); if (g1 < 1 && g1 !== -1) throw new Error('the game didn\'t count');
    const live = await ev(() => !!tnLive(HH.game.save.data.c1)); if (live) { await P.press(/^SIM$/); await page.waitForTimeout(200); const still = await ev(() => !!tnLive(HH.game.save.data.c1)); if (still) await P.press(/^Sim the rest$/); await page.waitForTimeout(200); }
    const fin = await ev(() => { const s = HH.game.ui.screen; return s && s.name === 'tourney' && s.widgets.some(w => w.label === 'DONE' && !w.hidden); }); if (!fin) throw new Error('no DONE'); await P.press(/^DONE$/); await page.waitForTimeout(400); await P.expectScreen('amhub');
    const r = await ev(() => { const a = HH.game.save.data.c1, row = tnState(a).rows.slice(-1)[0]; return row.k + ' ' + row.f; }); return 'played the ' + r + ' · ' + P.errors.length + ' errors'; });
  await R.step('the calendar across careers: high school\'s Nationals (after State), the AAU circuit and the Elite Camp (summers), the All-American Game (seniors), the U17 World Cup (one summer in two); college\'s Invitational (before the first game) and the U21 World Cup', () => ev(() => {
    const seen = {}, mine = {}; let careers = 0;
    for (let i = 0; i < 6; i++) { const a = __hs(900 + i, 6 + 2 * (i % 3)); __adv(a, 3000, a => a.stage === 'combine' || a.stage === 'overseas'); careers++; for (const r of tnState(a).rows) { seen[r.k] = (seen[r.k] || 0) + 1; if (r.f) mine[r.k] = (mine[r.k] || 0) + 1; } }
    for (const k of ['hsnat', 'aau1', 'aau2', 'aau3', 'camp', 'state', 'inv', 'u17']) if (!seen[k]) throw new Error('never: ' + k + ' (' + JSON.stringify(seen) + ')');
    return careers + ' careers · ' + Object.keys(seen).sort().map(k => k + ' ' + (mine[k] || 0) + '/' + seen[k]).join(' · ') + ' (yours/all)'; }), P);
  // §11's table: each tournament's field, the rounds a top seed meets, how often the top seed wins it, the champion's rewards
  await R.step('the table (§11): every tournament, its field and its ladder', () => ev(KEYS => {
    const rows = [], col = (s, n) => String(s).padEnd(n);
    for (const key of KEYS) { const E = TNE[key]; let Tm = null, wins = 0, n = 0, by = {}; const N = key === 'cup' ? 0 : 30;
      for (let i = 0; i < N; i++) { let c, T; if (E.lvl === 'pro') { c = __pro(1000 + i); const field = /^(wc|oly)$/.test(key) ? c.active.slice(0, 3).concat([c.meId]) : null; const me = meOf(c); for (let q = 0; q < 4; q++) { const d = 88 - recOvr(me); if (!d) break; for (const k of RATING_KEYS) me.r[k] = clamp(me.r[k] + d, 20, 99); } T = tnCreate(c, key, { mine: true, field }); } else { c = __hs(1000 + i, E.lvl === 'college' ? 36 : 16); if (E.lvl === 'college') { c.stage = 'college'; c.stageYear = 2; c.college = COLLEGES[5].name; } T = tnCreate(c, key, { mine: true }); }
        let gg = 0; while (!T.done && gg++ < 12) { const g = tnAdvance(c, T); if (!g) break; (by[g.s] || (by[g.s] = [])).push(tnGameOvr(c, T, tnOppIdOf(T, g), g)); tnSimMine(c, T); } n++; if (T.my.place === 1) wins++; Tm = T; }
      const lad = Object.keys(by).map(Number).sort((x, y) => x - y).map(s => (by[s].reduce((x, y) => x + y, 0) / by[s].length).toFixed(0)).join('→'), rw = E.rw[0];
      rows.push(col(E.name, 24) + col(E.fmt + ' ' + (E.n || 16), 12) + col(['local', 'state', 'national', 'intl', 'Olympic'][E.tier] || 'league', 10) + col(lad || '(the league\'s)', 18) + col(n ? Math.round(100 * wins / n) + '%' : '—', 8) + (rw[1] ? '$' + rw[1].toLocaleString() + ' · ' : '') + rw[2] + ' rk · ' + rw[3] + ' cr' + (E.item ? ' · ' + E.item[1] : '')); }
    return '\n     ' + 'TOURNAMENT'.padEnd(24) + 'FORMAT'.padEnd(12) + 'TIER'.padEnd(10) + 'OPP BY ROUND'.padEnd(18) + 'WIN%'.padEnd(8) + 'THE CHAMPION\'S REWARD\n     ' + rows.join('\n     ') + '\n     (a high school player 16 over a freshman (about OVR 57), a college one 36 (about 77), a pro at OVR 88; 30 runs each)'; }, KEYS), P);
  console.log('errors: ' + (P.errors.length ? P.errors.slice(0, 5).join(' | ') : 'none')); const fail = R.done(); await browser.close(); process.exit(fail ? 1 : 0);
})();
